In [165]:
import os
import sys
import pandas as pd
import mygene
import numpy as np

In [166]:
datasets_dir = '../1_inputs/datasets'

# Sahni

## load variants

In [167]:
sahni_vars = pd.read_csv(f'{datasets_dir}/Sahni/Sahni_variants.tsv', sep='\t')
sahni_vars.mutation_id_rc4 = sahni_vars.mutation_id_rc4.astype('str')
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0
1,A2M,18119,10256,2998G>A,Val1000Ile,other,0,0,0
2,A4GALT,1850,777,287G>A,Cys96Tyr,Pathogenic,0,1,0
3,A4GALT,1852,777,299C>T,Ser100Leu,Pathogenic,0,1,0
4,A4GALT,1854,777,548T>A,Met183Lys,Pathogenic,0,1,0
...,...,...,...,...,...,...,...,...,...
2944,ZNF350,10887,5946,1570G>A,Val524Ile,NaN,0,0,0
2945,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0
2946,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0
2947,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0
2948,ZNF624,24413,52828,27G>T,Lys9Asn,other,1,1,0

In [168]:
# Map mutation_id_rc4 to ccsb_mutation_id

mapping_df = pd.read_csv('../1_inputs/RC4_CCSB_mutation_id_map.tsv', sep='\t')

map_dict = dict(zip(mapping_df.mutation_id_rc4.astype('str'), mapping_df.ccsb_mutation_id.astype('str')))
sahni_vars['ccsb_mutation_id'] = sahni_vars.mutation_id_rc4.map(map_dict)
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589
1,A2M,18119,10256,2998G>A,Val1000Ile,other,0,0,0,CCSBVarC001590
2,A4GALT,1850,777,287G>A,Cys96Tyr,Pathogenic,0,1,0,CCSBVarC000076
3,A4GALT,1852,777,299C>T,Ser100Leu,Pathogenic,0,1,0,CCSBVarC000077
4,A4GALT,1854,777,548T>A,Met183Lys,Pathogenic,0,1,0,CCSBVarC000078
...,...,...,...,...,...,...,...,...,...,...
2944,ZNF350,10887,5946,1570G>A,Val524Ile,NaN,0,0,0,CCSBVarC000938
2945,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275
2946,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907
2947,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909
2948,ZNF624,24413,52828,27G>T,Lys9Asn,other,1,1,0,CCSBVarC002177

In [169]:
# Harmonize Sahni clinical_significance casing to match clinvar_clnsig_clean
sahni_vars['clinical_significance'] = sahni_vars['clinical_significance'].str.capitalize().replace({
    'Other': 'Others',
    'Vus': 'VUS',
})

sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589
1,A2M,18119,10256,2998G>A,Val1000Ile,Others,0,0,0,CCSBVarC001590
2,A4GALT,1850,777,287G>A,Cys96Tyr,Pathogenic,0,1,0,CCSBVarC000076
3,A4GALT,1852,777,299C>T,Ser100Leu,Pathogenic,0,1,0,CCSBVarC000077
4,A4GALT,1854,777,548T>A,Met183Lys,Pathogenic,0,1,0,CCSBVarC000078
...,...,...,...,...,...,...,...,...,...,...
2944,ZNF350,10887,5946,1570G>A,Val524Ile,NaN,0,0,0,CCSBVarC000938
2945,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275
2946,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907
2947,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909
2948,ZNF624,24413,52828,27G>T,Lys9Asn,Others,1,1,0,CCSBVarC002177

In [170]:
# Loading allele collection dataset

allele_col = pd.read_csv('../../1_allele_collection/3_outputs/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI_SpliceAI_AM.tsv', sep='\t')
allele_col

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/2083065048.py:3: DtypeWarning: Columns (24,25,26,27,102,104,134,137,140,155,156,157,159,160,162,164,188,189,191,192,194,195,198,208,209,212,216,217,218,219,229,230,240,241,242,253,254,257,258,479,481,483,485,487,489,499,501,503,505,507,509,515,517,521,523,527,529,531,535,543,553,555,557,563,565,567,569,571,579,581,583,585,593,595,647,649,651,653,655,657,659,663,667,699,701,703,713,715,717,725,727,729,731,733,735,737,755,823,845,851,875,877,879,881,883,891,897,909,911,913,915,917,919,921,923,925,937,938,944,946,947,948,949,951,952,955,959,960,967,968,972,977,978,979,983,989,996,997,999,1002) have mixed types. Specify dtype option on import or set low_memory=False.
  allele_col = pd.read_csv('../../1_allele_collection/3_outputs/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI_SpliceAI_AM.tsv', sep='\t')

,symbol,aa_change,gene_variant,spdi,nt_change,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,...,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant,am_pathogenicity
0,GBA1,Val54Leu,GBA1_Val54Leu,NC_000001.11:155240032:C:G,160G>C,1,155240033,C,G,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False,0.8423
1,GBA1,Leu224Phe,GBA1_Leu224Phe,NC_000001.11:155238224:G:A,670C>T,1,155238225,G,A,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False,0.6676
2,GBA1,Arg296Gln,GBA1_Arg296Gln,NC_000001.11:155237452:C:T,887G>A,1,155237453,C,T,1,...,>90,10-90,608013;230800;230900;231000;230800;231005;168600,multiple,OMIM,NaN,0,"GAUCHER DISEASE, PERINATAL LETHAL; GAUCHER DIS...",False,0.3545
3,GBA1,Leu483Pro,GBA1_Leu483Pro,NC_000001.11:155235251:A:G,1448T>C,1,155235252,A,G,1,...,>90,<10,230900;230800;231000;168600;608013;230900;2310...,multiple,OMIM,NaN,0,"GAUCHER DISEASE, TYPE II; GAUCHER DISEASE, TYP...",False,0.6022
4,NHERF1,Leu110Val,NHERF1_Leu110Val,NC_000017.11:74749173:C:G,328C>G,17,74749174,C,G,17,...,50-70,10-90,612287,autosomal dominant,OMIM,NaN,0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False,0.0954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9645,BRIP1,Thr266Lys,BRIP1_Thr266Lys,NC_000017.11:61808587:G:T,797C>A,17,61808588,G,T,17,...,>90,<10,167000,somatic mutation,OMIM,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER,False,0.9582
9646,BRIP1,Ser520Thr,BRIP1_Ser520Thr,NC_000017.11:61784338:C:G,1559G>C,17,61784339,C,G,17,...,70-90,10-90,NaN,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,NaN,False,0.1002
9647,BRIP1,Leu537His,BRIP1_Leu537His,NC_000017.11:61784287:A:T,1610T>A,17,61784288,A,T,17,...,>90,<10,167000,NaN,NaN,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER,False,0.8302
9648,BRIP1,His587Arg,BRIP1_His587Arg,NC_000017.11:61780873:T:C,1760A>G,17,61780874,T,C,17,...,>90,10-90,114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,BREAST CANCER,False,0.0704
9649,BRIP1,Arg848His,BRIP1_Arg848His,NC_000017.11:61693461:C:T,2543G>A,17,61693462,C,T,17,...,>90,10-90,609054;114480;609054;609054;114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,"FANCONI ANEMIA, COMPLEMENTATION GROUP J; BREAS...",True,0.8672

In [171]:
# Check if all Sahni variants are in the allele collection
missing_in_allele_col = sahni_vars[~sahni_vars.ccsb_mutation_id.isin(allele_col.ccsb_mutation_id)]
print(f"Number of Sahni variants missing in allele collection: {len(missing_in_allele_col)}")
missing_in_allele_col

Number of Sahni variants missing in allele collection: 1

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id
1307,HCP5,31345,56027,335T>G,Val112Gly,NaN,0,1,0,CCSBVarC002524

In [172]:
# Mapping ClinVar clinical significance from allele_col (clinvar_clnsig_clean) to Sahni variants using ccsb_mutation_id

allele_col_dedup = allele_col.drop_duplicates(subset=['gene_variant'])

sahni_vars = sahni_vars.merge(
    allele_col_dedup[['ccsb_mutation_id', 'symbol', 'clinvar_clnsig_clean']],
    on='ccsb_mutation_id',
    how='left',
    suffixes=('', '_allele_col')
)
# sahni_vars.drop_duplicates(subset=['mutation_id_rc4'], inplace=True)
sahni_vars['symbol'] = sahni_vars['symbol_allele_col']
sahni_vars.drop(columns=['symbol_allele_col'], inplace=True)
sahni_vars['gene_variant'] = sahni_vars['symbol'] + '_' + sahni_vars['aa_change']
sahni_vars = sahni_vars[sahni_vars.gene_variant.notna()]
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id,clinvar_clnsig_clean,gene_variant
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589,Benign,A2M_Cys972Tyr
1,A2M,18119,10256,2998G>A,Val1000Ile,Others,0,0,0,CCSBVarC001590,Others,A2M_Val1000Ile
2,A4GALT,1850,777,287G>A,Cys96Tyr,Pathogenic,0,1,0,CCSBVarC000076,Others,A4GALT_Cys96Tyr
3,A4GALT,1852,777,299C>T,Ser100Leu,Pathogenic,0,1,0,CCSBVarC000077,VUS,A4GALT_Ser100Leu
4,A4GALT,1854,777,548T>A,Met183Lys,Pathogenic,0,1,0,CCSBVarC000078,Others,A4GALT_Met183Lys
...,...,...,...,...,...,...,...,...,...,...,...,...
2944,ZNF350,10887,5946,1570G>A,Val524Ile,NaN,0,0,0,CCSBVarC000938,Benign,ZNF350_Val524Ile
2945,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275,Benign,ZNF41_Pro111Leu
2946,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907,Benign,ZNF41_Ile125Arg
2947,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909,Benign,ZNF41_Cys301Arg
2948,ZNF624,24413,52828,27G>T,Lys9Asn,Others,1,1,0,CCSBVarC002177,Others,ZNF624_Lys9Asn

In [173]:
# Compare clinical_significance and clinvar_clnsig_clean in sahni_vars
print("=== clinical_significance unique values ===")
print(sahni_vars['clinical_significance'].value_counts(dropna=False))

print("\n=== clinvar_clnsig_clean unique values ===")
print(sahni_vars['clinvar_clnsig_clean'].value_counts(dropna=False))

# Cross-tab
both_have = sahni_vars[
    sahni_vars['clinical_significance'].notna() & 
    sahni_vars['clinvar_clnsig_clean'].notna()
].copy()

print(f"\nVariants with both annotations: {len(both_have)}")

if len(both_have) > 0:
    ct = pd.crosstab(
        both_have['clinical_significance'], 
        both_have['clinvar_clnsig_clean'],
        margins=True
    )
    print("\n--- Cross-tab: clinical_significance (rows) vs clinvar_clnsig_clean (columns) ---")
    print(ct.to_string())
    
    concordant = (both_have['clinical_significance'] == both_have['clinvar_clnsig_clean']).sum()
    discordant = (both_have['clinical_significance'] != both_have['clinvar_clnsig_clean']).sum()
    print(f"\n  Concordant: {concordant} ({100*concordant/len(both_have):.1f}%)")
    print(f"  Discordant: {discordant} ({100*discordant/len(both_have):.1f}%)")
    
    if discordant > 0:
        disc = both_have[both_have['clinical_significance'] != both_have['clinvar_clnsig_clean']]
        print(f"\n--- Discordant transitions ---")
        print(pd.crosstab(disc['clinical_significance'], disc['clinvar_clnsig_clean']).to_string())
        print(f"\n--- Example discordant variants ---")
        print(disc[['gene_variant', 'clinical_significance', 'clinvar_clnsig_clean']].head(20).to_string(index=False))

# Coverage comparison
only_clinsig = sahni_vars[
    sahni_vars['clinical_significance'].notna() & 
    sahni_vars['clinvar_clnsig_clean'].isna()
]
only_clean = sahni_vars[
    sahni_vars['clinical_significance'].isna() & 
    sahni_vars['clinvar_clnsig_clean'].notna()
]
print(f"\n  Only clinical_significance:  {len(only_clinsig)}")
print(f"  Only clinvar_clnsig_clean:   {len(only_clean)}")
print(f"  Neither:                     {sahni_vars['clinical_significance'].isna().sum() - len(only_clean)}")

=== clinical_significance unique values ===
clinical_significance
Pathogenic     1883
Others          422
Benign          240
VUS             191
Conflicting     177
NaN              33
Name: count, dtype: int64

=== clinvar_clnsig_clean unique values ===
clinvar_clnsig_clean
Pathogenic     1165
Others          932
Benign          320
VUS             274
Conflicting     255
Name: count, dtype: int64

Variants with both annotations: 2913

--- Cross-tab: clinical_significance (rows) vs clinvar_clnsig_clean (columns) ---
clinvar_clnsig_clean   Benign  Conflicting  Others  Pathogenic  VUS   All
clinical_significance
Benign                    226            9       3           0    2   240
Conflicting                11          121       3          39    3   177
Others                     54            3     354           1   10   422
Pathogenic                 19           66     549        1114  135  1883
VUS                         0           56       2          11  122   191
All                       310          255     911        1165  272  2913

  Concordant: 1937 (66.5%)
  Discordant: 976 (33.5%)

--- Discordant transitions ---
clinvar_clnsig_clean   Benign  Conflicting  Others  Pathogenic  VUS
clinical_significance
Benign                      0            9       3           0    2
Conflicting                11            0       3          39    3
Others                     54            3       0           1   10
Pathogenic                 19           66     549           0  135
VUS                         0           56       2          11    0

--- Example discordant variants ---
    gene_variant clinical_significance clinvar_clnsig_clean
 A4GALT_Cys96Tyr            Pathogenic               Others
A4GALT_Ser100Leu            Pathogenic                  VUS
A4GALT_Met183Lys            Pathogenic               Others
A4GALT_Ala219Val            Pathogenic                  VUS
  AAAS_Leu381Arg            Pathogenic               Others
   ABHD5_Glu7Lys            Pathogenic               Benign
  ABHD5_His82Arg            Pathogenic               Others
 ABHD5_Ser115Gly            Pathogenic               Others
  ACADM_Ala52Val            Pathogenic               Others
 ACADM_Lys329Glu           Conflicting           Pathogenic
ACADSB_Glu387Lys           Conflicting           Pathogenic
  ACTA2_Arg39His           Conflicting           Pathogenic
 ACTA2_Arg292Gly            Pathogenic               Others
 ACTC1_Pro166Ala            Pathogenic                  VUS
 ACTC1_Ser273Phe            Pathogenic               Others
 ACTG1_Ile122Val            Pathogenic               Others
 ACVR1_Gln207Glu            Pathogenic               Others
ACVR2B_Val494Ile            Pathogenic                  VUS
ACVRL1_Glu215Lys            Pathogenic          Conflicting
  ACY1_Arg393His           Conflicting               Benign

  Only clinical_significance:  0
  Only clinvar_clnsig_clean:   33
  Neither:                     0

In [174]:
# Update deprecated clinical_significance values in Sahni for the newly updated annotations

sahni_vars['clinical_significance'] = sahni_vars['clinvar_clnsig_clean']
sahni_vars.drop(columns=['clinvar_clnsig_clean'], inplace=True)
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id,gene_variant
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589,A2M_Cys972Tyr
1,A2M,18119,10256,2998G>A,Val1000Ile,Others,0,0,0,CCSBVarC001590,A2M_Val1000Ile
2,A4GALT,1850,777,287G>A,Cys96Tyr,Others,0,1,0,CCSBVarC000076,A4GALT_Cys96Tyr
3,A4GALT,1852,777,299C>T,Ser100Leu,VUS,0,1,0,CCSBVarC000077,A4GALT_Ser100Leu
4,A4GALT,1854,777,548T>A,Met183Lys,Others,0,1,0,CCSBVarC000078,A4GALT_Met183Lys
...,...,...,...,...,...,...,...,...,...,...,...
2944,ZNF350,10887,5946,1570G>A,Val524Ile,Benign,0,0,0,CCSBVarC000938,ZNF350_Val524Ile
2945,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275,ZNF41_Pro111Leu
2946,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907,ZNF41_Ile125Arg
2947,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909,ZNF41_Cys301Arg
2948,ZNF624,24413,52828,27G>T,Lys9Asn,Others,1,1,0,CCSBVarC002177,ZNF624_Lys9Asn

## Edgotyping

In [175]:
edgotype_df = pd.read_excel(f'{datasets_dir}/Sahni/Table S3.xlsx', sheet_name='Table S3C')
edgotype_df['mutation_id_rc4'] = [var.split('_')[-1] for var in edgotype_df.Allele_ID]
edgotype_df

/Users/user_42/.pyenv/versions/3.9.17/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Category,Symbol,Entrez_Gene_ID,Allele_ID,Mutation_RefSeq_NT,Mutation_RefSeq_AA,Edgotype_class,mutation_id_rc4
0,Disease mutation,AANAT,15,15_22963,NM_001088:c.385G>A,NP_001079:p.A129T,Edgetic,22963
1,Non-disease variant,AANAT,15,15_900207,NM_001088:c.8C>T,NP_001079:p.T3M,Quasi-wild-type,900207
2,Disease mutation,ACTB,60,60_12760,NM_001101:c.547C>T,NP_001092:p.R183W,Quasi-wild-type,12760
3,Disease mutation,ACTB,60,60_12761,NM_001101:c.1090G>A,NP_001092:p.E364K,Edgetic,12761
4,Disease mutation,ACTG1,71,71_20917,NM_001614:c.266C>T,NP_001605:p.T89I,Quasi-wild-type,20917
...,...,...,...,...,...,...,...,...
522,Disease mutation,ZDHHC9,51114,51114_6217,NM_016032:c.448C>T,NP_057116:p.P150S,Perturbed-degree-1,6217
523,Disease mutation,ZNF41,7592,7592_3854,NM_153380:c.332C>T,NP_700359:p.P111L,Perturbed-degree-1,3854
524,Non-disease variant,ZNF41,7592,7592_900185,NM_153380:c.374T>G,NP_700359:p.I125R,Unperturbed-degree-1,900185
525,Non-disease variant,ZNF41,7592,7592_900188,NM_153380:c.901T>C,NP_700359:p.C301R,Unperturbed-degree-1,900188
526,Disease mutation,ZNF624,57547,57547_24413,NM_020787:c.405G>T,NP_065838:p.K135N,Unperturbed-degree-1,24413

In [176]:
sahni_vars = sahni_vars.merge(edgotype_df, how='left', on='mutation_id_rc4')
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id,gene_variant,Category,Symbol,Entrez_Gene_ID,Allele_ID,Mutation_RefSeq_NT,Mutation_RefSeq_AA,Edgotype_class
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A2M,18119,10256,2998G>A,Val1000Ile,Others,0,0,0,CCSBVarC001590,A2M_Val1000Ile,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A4GALT,1850,777,287G>A,Cys96Tyr,Others,0,1,0,CCSBVarC000076,A4GALT_Cys96Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT,1852,777,299C>T,Ser100Leu,VUS,0,1,0,CCSBVarC000077,A4GALT_Ser100Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,1854,777,548T>A,Met183Lys,Others,0,1,0,CCSBVarC000078,A4GALT_Met183Lys,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2941,ZNF350,10887,5946,1570G>A,Val524Ile,Benign,0,0,0,CCSBVarC000938,ZNF350_Val524Ile,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275,ZNF41_Pro111Leu,Disease mutation,ZNF41,7592.0,7592_3854,NM_153380:c.332C>T,NP_700359:p.P111L,Perturbed-degree-1
2943,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907,ZNF41_Ile125Arg,Non-disease variant,ZNF41,7592.0,7592_900185,NM_153380:c.374T>G,NP_700359:p.I125R,Unperturbed-degree-1
2944,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909,ZNF41_Cys301Arg,Non-disease variant,ZNF41,7592.0,7592_900188,NM_153380:c.901T>C,NP_700359:p.C301R,Unperturbed-degree-1
2945,ZNF624,24413,52828,27G>T,Lys9Asn,Others,1,1,0,CCSBVarC002177,ZNF624_Lys9Asn,Disease mutation,ZNF624,57547.0,57547_24413,NM_020787:c.405G>T,NP_065838:p.K135N,Unperturbed-degree-1

## Chaperones

In [177]:
chap_df = pd.read_excel(f'{datasets_dir}/Sahni/Chaperone data.xlsx', sheet_name='Sheet3')
chap_df['mutation_id_rc4'] = [var.split('_')[-1] for var in chap_df.Allele_ID]
chap_df

,Symbol,Allele_ID,BAG2,CHIP,GRP78,GRP94,HSC70,HSP90,PSMD2,Number of datasets,Number of Yes,Number of 0,Number of N/A,Chaperone Responsive (Y/N),mutation_id_rc4
0,A4GALT,53947_1850,yes,yes,0,0,0,0,0,7,2,5,0,Y,1850
1,A4GALT,53947_1852,yes,yes,0,0,0,0,0,7,2,5,0,Y,1852
2,A4GALT,53947_1854,0,yes,0,0,0,0,0,7,1,6,0,Y,1854
3,A4GALT,53947_1856,yes,yes,0,0,0,0,0,7,2,5,0,Y,1856
4,AAAS,8086_5606,0,0,0,0,0,0,0,7,0,7,0,N,5606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,ZFYVE27,118813_2819,0,0,0,0,0,0,0,7,0,7,0,N,2819
2398,ZNF24,7572_6801,0,0,0,0,0,0,0,7,0,7,0,N,6801
2399,ZNF41,7592_900185,NaN,NaN,NaN,NaN,0,0,NaN,2,0,2,5,N,900185
2400,ZNF41,7592_900188,NaN,NaN,NaN,NaN,0,0,NaN,2,0,2,5,N,900188
2401,ZNF624,57547_24413,0,0,0,0,0,0,0,7,0,7,0,N,24413

In [178]:
sahni_vars = sahni_vars.merge(chap_df, how='left', on='mutation_id_rc4')
sahni_vars

,symbol,mutation_id_rc4,orf_id_wt,nt_change,aa_change,clinical_significance,edgotyping_sahni,chaperone_binding_sahni,tf_binding_sahni,ccsb_mutation_id,...,GRP78,GRP94,HSC70,HSP90,PSMD2,Number of datasets,Number of Yes,Number of 0,Number of N/A,Chaperone Responsive (Y/N)
0,A2M,18118,10256,2915G>A,Cys972Tyr,Benign,0,0,0,CCSBVarC001589,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A2M,18119,10256,2998G>A,Val1000Ile,Others,0,0,0,CCSBVarC001590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A4GALT,1850,777,287G>A,Cys96Tyr,Others,0,1,0,CCSBVarC000076,...,0,0,0,0,0,7.0,2.0,5.0,0.0,Y
3,A4GALT,1852,777,299C>T,Ser100Leu,VUS,0,1,0,CCSBVarC000077,...,0,0,0,0,0,7.0,2.0,5.0,0.0,Y
4,A4GALT,1854,777,548T>A,Met183Lys,Others,0,1,0,CCSBVarC000078,...,0,0,0,0,0,7.0,1.0,6.0,0.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2941,ZNF350,10887,5946,1570G>A,Val524Ile,Benign,0,0,0,CCSBVarC000938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,ZNF41,3854,2496,332C>T,Pro111Leu,Benign,1,0,0,CCSBVarC000275,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2943,ZNF41,900185,2496,374T>G,Ile125Arg,Benign,0,1,0,CCSBVarC002907,...,NaN,NaN,0,0,NaN,2.0,0.0,2.0,5.0,N
2944,ZNF41,900188,2496,901T>C,Cys301Arg,Benign,0,1,0,CCSBVarC002909,...,NaN,NaN,0,0,NaN,2.0,0.0,2.0,5.0,N
2945,ZNF624,24413,52828,27G>T,Lys9Asn,Others,1,1,0,CCSBVarC002177,...,0,0,0,0,0,7.0,0.0,7.0,0.0,N

In [179]:
sahni_vars.columns

Index(['symbol', 'mutation_id_rc4', 'orf_id_wt', 'nt_change', 'aa_change',
       'clinical_significance', 'edgotyping_sahni', 'chaperone_binding_sahni',
       'tf_binding_sahni', 'ccsb_mutation_id', 'gene_variant', 'Category',
       'Symbol_x', 'Entrez_Gene_ID', 'Allele_ID_x', 'Mutation_RefSeq_NT',
       'Mutation_RefSeq_AA', 'Edgotype_class', 'Symbol_y', 'Allele_ID_y',
       'BAG2', 'CHIP', 'GRP78', 'GRP94', 'HSC70', 'HSP90', 'PSMD2',
       'Number of datasets', 'Number of Yes', 'Number of 0', 'Number of N/A',
       'Chaperone Responsive (Y/N)'],
      dtype='object')

In [180]:
cols_to_keep = ['symbol', 'nt_change', 'aa_change',
                'clinical_significance', 'Category', 'Edgotype_class',
                'Chaperone Responsive (Y/N)']

sahni_vars = sahni_vars[cols_to_keep]
sahni_vars.rename({'Chaperone Responsive (Y/N)':'Sahni_Chaperone_binding'}, axis=1, errors='raise', inplace=True)
sahni_vars['gene_variant'] = sahni_vars.symbol + '_' + sahni_vars.aa_change

# Keep variants with either edgotype or chaperone binding data
sahni_vars = sahni_vars[(sahni_vars.Edgotype_class == sahni_vars.Edgotype_class) | (sahni_vars.Sahni_Chaperone_binding == sahni_vars.Sahni_Chaperone_binding)]
sahni_vars

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/3036903136.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sahni_vars.rename({'Chaperone Responsive (Y/N)':'Sahni_Chaperone_binding'}, axis=1, errors='raise', inplace=True)
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/3036903136.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sahni_vars['gene_variant'] = sahni_vars.symbol + '_' + sahni_vars.aa_change

,symbol,nt_change,aa_change,clinical_significance,Category,Edgotype_class,Sahni_Chaperone_binding,gene_variant
2,A4GALT,287G>A,Cys96Tyr,Others,NaN,NaN,Y,A4GALT_Cys96Tyr
3,A4GALT,299C>T,Ser100Leu,VUS,NaN,NaN,Y,A4GALT_Ser100Leu
4,A4GALT,548T>A,Met183Lys,Others,NaN,NaN,Y,A4GALT_Met183Lys
5,A4GALT,656C>T,Ala219Val,VUS,NaN,NaN,Y,A4GALT_Ala219Val
6,AAAS,43C>A,Gln15Lys,Pathogenic,NaN,NaN,N,AAAS_Gln15Lys
...,...,...,...,...,...,...,...,...
2938,ZNF24,659G>A,Ser220Asn,Others,NaN,NaN,N,ZNF24_Ser220Asn
2942,ZNF41,332C>T,Pro111Leu,Benign,Disease mutation,Perturbed-degree-1,NaN,ZNF41_Pro111Leu
2943,ZNF41,374T>G,Ile125Arg,Benign,Non-disease variant,Unperturbed-degree-1,N,ZNF41_Ile125Arg
2944,ZNF41,901T>C,Cys301Arg,Benign,Non-disease variant,Unperturbed-degree-1,N,ZNF41_Cys301Arg
2945,ZNF624,27G>T,Lys9Asn,Others,Disease mutation,Unperturbed-degree-1,N,ZNF624_Lys9Asn

In [181]:
sahni_vars.Edgotype_class.unique()

array([nan, 'Edgetic', 'Quasi-wild-type', 'Quasi-null',
       'Unperturbed-degree-1', 'Perturbed-degree-1',
       'Gain-and-loss-of-interaction', 'Gain-of-interaction'],
      dtype=object)

# Rolland

In [182]:
rol_df = pd.read_excel(f'{datasets_dir}/Rolland/1-s2.0-S0092867414014226-mmc4.xlsx')
rol_df.rename({'aa-change':'aa_change'}, axis=1 ,inplace=True)

# No Clinvar mut? what does disease mutation/common variant means? gnomad frequent/rare?

from Bio.SeqUtils import seq3

rol_df['aa_change'] = [f'{seq3(aa_change[0])}{aa_change[1:-1]}{seq3(aa_change[-1])}' for aa_change in rol_df.aa_change]
rol_df.columns

/Users/user_42/.pyenv/versions/3.9.17/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Index(['category', 'entrez_gene_id', 'gene_symbol', 'aa_change',
       'Interactor_entrez_gene_id', 'Interactor_gene_symbol', 'Y2H_score',
       'Phenotype'],
      dtype='object')

In [183]:
cols_to_keep = ['category', 'gene_symbol', 'aa_change',
       'Interactor_gene_symbol', 'Y2H_score',
       'Phenotype']

rol_df = rol_df[cols_to_keep]

# Update symbol ADCK3 to COQ8A to match allele collection
rol_df['gene_symbol'] = rol_df['gene_symbol'].replace({'ADCK3': 'COQ8A'})

rol_df['gene_variant'] = rol_df.gene_symbol + '_' + rol_df.aa_change
rol_df

,category,gene_symbol,aa_change,Interactor_gene_symbol,Y2H_score,Phenotype,gene_variant
0,Disease mutation,COQ8A,Arg213Trp,AGTRAP,0,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp
1,Disease mutation,COQ8A,Arg213Trp,TMEM239,0,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp
2,Disease mutation,COQ8A,Arg213Trp,TFIP11,0,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp
3,Disease mutation,COQ8A,Arg213Trp,RABAC1,0,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp
4,Disease mutation,COQ8A,Arg213Trp,TMEM159,0,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp
...,...,...,...,...,...,...,...
400,Disease mutation,GFAP,Glu374Gly,TRIM27,1,Alexander disease,GFAP_Glu374Gly
401,Disease mutation,GFAP,Glu374Gly,GOLGA2,1,Alexander disease,GFAP_Glu374Gly
402,Disease mutation,GFAP,Glu374Gly,KRT13,1,Alexander disease,GFAP_Glu374Gly
403,Disease mutation,GFAP,Glu374Gly,PIAS2,1,Alexander disease,GFAP_Glu374Gly
404,Disease mutation,GFAP,Glu374Gly,KRT15,1,Alexander disease,GFAP_Glu374Gly

In [184]:
def edgotype_status(score_list):
    score_list = score_list.to_list()
    if len(score_list) == 1:
        if pd.isnull(score_list[0]):
            return np.nan
        elif score_list[0] == 1:
            return 'Unperturbed-degree-1'
        elif score_list[0] == 0:
            return 'Perturbed-degree-1'
        else:
            return np.nan
    if pd.isnull(score_list).all():
        return np.nan
    if 0 in score_list and 1 in score_list:
        return 'Edgetic'
    elif score_list.count(0) >= 2:
        return 'Quasi-null'
    elif score_list.count(1) >= 2:
        return 'Quasi-wild-type'
    else:
        return np.nan

# Group by variant (gene + aa_change) and assign edgotype
rol_df['Edgotype_class'] = rol_df.groupby('gene_variant')['Y2H_score'].transform(edgotype_status)

rol_df.drop_duplicates(subset=['gene_variant'], inplace=True)
rol_df.drop(columns=['Interactor_gene_symbol', 'Y2H_score'], inplace=True)
rol_df

,category,gene_symbol,aa_change,Phenotype,gene_variant,Edgotype_class
0,Disease mutation,COQ8A,Arg213Trp,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Arg213Trp,Quasi-null
6,Disease mutation,COQ8A,Tyr514Cys,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Tyr514Cys,Quasi-wild-type
12,Disease mutation,COQ8A,Gly272Val,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Gly272Val,Edgetic
18,Disease mutation,COQ8A,Glu551Lys,Ubiquinone deficiency with cerebellar ataxia,COQ8A_Glu551Lys,Edgetic
24,Disease mutation,RPGR,Thr255Ile,Retinitis pigmentosa,RPGR_Thr255Ile,Perturbed-degree-1
...,...,...,...,...,...,...
382,Disease mutation,TNFRSF13B,Val200Phe,Antibody deficiency,TNFRSF13B_Val200Phe,Unperturbed-degree-1
383,Disease mutation,PGBD1,Gly244Glu,"Alzheimer disease, late-onset, association with",PGBD1_Gly244Glu,Quasi-wild-type
390,Disease mutation,GFAP,Pro47Leu,Alexander disease?,GFAP_Pro47Leu,Quasi-wild-type
395,Disease mutation,GFAP,Arg258Pro,Alexander disease,GFAP_Arg258Pro,Quasi-wild-type
400,Disease mutation,GFAP,Glu374Gly,Alexander disease,GFAP_Glu374Gly,Quasi-wild-type

# Luck

In [185]:
luck_df = pd.read_csv(f'{datasets_dir}/Luck/Supplementary Table 27.txt', sep='\t')
luck_df.columns

Index(['causal_gene_id', 'CG_symbol', 'causal_orf_id', 'causal_mut_id',
       'interactor_gene_id', 'interactor_symbol', 'interactor_orf_id',
       'assay_id', 'GS_WT', 'GS_allele', 'GS_diff', 'perturbed', 'final_score',
       'mutation', 'pathogenecity', 'omim_ids', 'TiP_tissue', 'CG_tis_expr',
       'CG_TiP_expr', 'interactor_tis_expr', 'interactor_TiP_expr'],
      dtype='object')

In [186]:
luck_df

,causal_gene_id,CG_symbol,causal_orf_id,causal_mut_id,interactor_gene_id,interactor_symbol,interactor_orf_id,assay_id,GS_WT,GS_allele,...,perturbed,final_score,mutation,pathogenecity,omim_ids,TiP_tissue,CG_tis_expr,CG_TiP_expr,interactor_tis_expr,interactor_TiP_expr
0,ENSG00000136143,SUCLA2,1598,0,ENSG00000100934,SEC23A,100008515,1,3.0,NaN,...,NaN,1,NaN,WT,612073,brain_basal_ganglia,11.4304,0.576914,10.669700,-0.514763
1,ENSG00000136143,SUCLA2,1598,0,ENSG00000170540,ARL6IP1,2374,1,4.0,NaN,...,NaN,1,NaN,WT,612073,brain_basal_ganglia,11.4304,0.576914,14.090000,2.172370
2,ENSG00000136143,SUCLA2,1598,0,ENSG00000185247,MAGEA11,4361,1,2.0,NaN,...,NaN,1,NaN,WT,612073,brain_basal_ganglia,11.4304,0.576914,NaN,NaN
3,ENSG00000136143,SUCLA2,1598,0,ENSG00000177674,AGTRAP,7845,1,4.0,NaN,...,NaN,1,NaN,WT,612073,brain_basal_ganglia,11.4304,0.576914,9.164670,-1.045780
4,ENSG00000136143,SUCLA2,1598,0,ENSG00000147676,MAL2,581,1,2.0,NaN,...,NaN,1,NaN,WT,612073,brain_basal_ganglia,11.4304,0.576914,5.756710,0.087044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,ENSG00000183230,CTNNA3,71258,220347,ENSG00000186654,PRR5,14223,3,2.0,0.0,...,1.0,0,Val94Asp,Pathogenic,615616,heart_left_ventricle,11.3306,0.864220,6.366930,-1.374010
675,ENSG00000183230,CTNNA3,71258,220347,ENSG00000213213,CCDC183,12198,3,3.0,0.0,...,1.0,0,Val94Asp,Pathogenic,615616,heart_left_ventricle,11.3306,0.864220,8.042830,0.655210
676,ENSG00000183230,CTNNA3,71258,220347,ENSG00000159173,TNNI1,6326,3,4.0,2.0,...,1.0,1,Val94Asp,Pathogenic,615616,heart_left_ventricle,11.3306,0.864220,7.955300,0.865447
677,ENSG00000183230,CTNNA3,71258,220347,ENSG00000104435,STMN2,4907,3,3.0,3.0,...,0.0,1,Val94Asp,Pathogenic,615616,heart_left_ventricle,11.3306,0.864220,3.463880,-0.477047
678,ENSG00000183230,CTNNA3,71258,220347,ENSG00000170948,MBD3L1,71963,3,3.0,2.0,...,0.0,1,Val94Asp,Pathogenic,615616,heart_left_ventricle,11.3306,0.864220,0.126823,0.298931

In [187]:

cols_to_keep = ['CG_symbol',
                'interactor_symbol', 'assay_id', 'final_score',
       'mutation', 'pathogenecity', 'omim_ids']

luck_df = luck_df[cols_to_keep]
luck_df['final_score'] = pd.to_numeric(luck_df['final_score'], errors='coerce')
luck_df['gene_variant'] = luck_df.CG_symbol + '_' + luck_df.mutation
luck_df = luck_df[luck_df.gene_variant == luck_df.gene_variant]
luck_df

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/2236254554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  luck_df['final_score'] = pd.to_numeric(luck_df['final_score'], errors='coerce')
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/2236254554.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  luck_df['gene_variant'] = luck_df.CG_symbol + '_' + luck_df.mutation

,CG_symbol,interactor_symbol,assay_id,final_score,mutation,pathogenecity,omim_ids,gene_variant
7,SUCLA2,MAL2,1,0.0,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg
8,SUCLA2,CMTM5,1,0.0,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg
9,SUCLA2,AGTRAP,1,0.0,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg
10,SUCLA2,MAGEA11,1,0.0,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg
11,SUCLA2,ARL6IP1,1,0.0,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg
...,...,...,...,...,...,...,...,...
674,CTNNA3,PRR5,3,0.0,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp
675,CTNNA3,CCDC183,3,0.0,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp
676,CTNNA3,TNNI1,3,1.0,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp
677,CTNNA3,STMN2,3,1.0,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp
678,CTNNA3,MBD3L1,3,1.0,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp

In [188]:
def edgotype_status(score_list):
    score_list = score_list.to_list()
    if len(score_list) == 1:
        if pd.isnull(score_list[0]):
            return np.nan
        elif score_list[0] == 1:
            return 'Unperturbed-degree-1'
        elif score_list[0] == 0:
            return 'Perturbed-degree-1'
        else:
            return np.nan
    if pd.isnull(score_list).all():
        return np.nan
    if 0 in score_list and 1 in score_list:
        return 'Edgetic'
    elif score_list.count(0) >= 2:
        return 'Quasi-null'
    elif score_list.count(1) >= 2:
        return 'Quasi-wild-type'
    else:
        return np.nan

# Group by variant (gene + aa_change) and assign edgotype
luck_df['Edgotype_class'] = luck_df.groupby('gene_variant')['final_score'].transform(edgotype_status)

luck_df.drop_duplicates(subset=['gene_variant'], inplace=True)
luck_df.drop(columns=['interactor_symbol', 'final_score'], inplace=True)
luck_df = luck_df[luck_df.Edgotype_class == luck_df.Edgotype_class]
luck_df

,CG_symbol,assay_id,mutation,pathogenecity,omim_ids,gene_variant,Edgotype_class
7,SUCLA2,1,Gly118Arg,Pathogenic,612073,SUCLA2_Gly118Arg,Quasi-null
14,SUCLA2,1,Asp251Asn,Pathogenic,612073,SUCLA2_Asp251Asn,Quasi-null
38,CLN6,1,Arg6Thr,Pathogenic,204300,CLN6_Arg6Thr,Edgetic
55,CLN6,1,Leu47Phe,Pathogenic,204300,CLN6_Leu47Phe,Edgetic
72,CLN6,1,Gly123Asp,Pathogenic,601780,CLN6_Gly123Asp,Edgetic
146,GOSR2,1,Gly144Trp,Pathogenic,614018,GOSR2_Gly144Trp,Edgetic
194,TMEM43,1,Arg28Trp,Benign/Likely benign,604400,TMEM43_Arg28Trp,Edgetic
202,TMEM43,1,Glu85Lys,Pathogenic,614302,TMEM43_Glu85Lys,Edgetic
210,TMEM43,1,Ile91Val,Uncertain significance,604400|614302,TMEM43_Ile91Val,Quasi-wild-type
218,TMEM43,1,Glu142Lys,Conflicting interpretations of pathogenicity,604400,TMEM43_Glu142Lys,Edgetic
226,TMEM43,1,Tyr371His,Conflicting interpretations of pathogenicity,604400,TMEM43_Tyr371His,Quasi-wild-type
272,BAG3,1,Arg218Trp,Uncertain significance,613881|612954,BAG3_Arg218Trp,Quasi-wild-type
310,BAG3,1,Arg258Trp,Conflicting interpretations of pathogenicity,613881|612954,BAG3_Arg258Trp,Edgetic
348,BAG3,1,Leu462Pro,Likely pathogenic,613881,BAG3_Leu462Pro,Edgetic
407,TECR,1,Pro182Leu,Pathogenic,614020,TECR_Pro182Leu,Edgetic
450,PGAP2,1,Thr160Ile,Pathogenic,614207,PGAP2_Thr160Ile,Edgetic
488,DOLK,1,Tyr441Ser,Pathogenic,610768,DOLK_Tyr441Ser,Edgetic
537,PNKP,1,Pro20Ser,Benign/Likely benign,613402,PNKP_Pro20Ser,Quasi-wild-type
570,PNKP,1,Glu326Lys,Pathogenic,613402,PNKP_Glu326Lys,Edgetic
641,CTNNA3,1,Val94Asp,Pathogenic,615616,CTNNA3_Val94Asp,Edgetic

# Lacoste

In [189]:
lacoste_df = pd.read_excel(f'{datasets_dir}/Lacoste/Lacoste revision Table S1.xlsx', sheet_name='Variant annotation')

# Remove variants with no amino acid change (e.g. splicing, non-coding) and those with complex indels or gene fusions, as well as those in genes with ambiguous names (e.g. containing '-')
lacoste_df = lacoste_df[lacoste_df.Variant.str.contains(' ')]
lacoste_df = lacoste_df[~lacoste_df.Variant.str.contains('ins|del|dup')]
lacoste_df = lacoste_df[~lacoste_df.Gene.str.contains('-')]

# Remove variants where the column Variant doesn't have the P570H format


lacoste_df['aa_change_temp'] = [aa_c.split(' ')[1] for aa_c in lacoste_df.Variant]
lacoste_df['aa_change'] = [f'{seq3(aa_change[0])}{aa_change[1:-1]}{seq3(aa_change[-1])}' for aa_change in lacoste_df.aa_change_temp]
lacoste_df.drop(['aa_change_temp', 'Variant'], axis=1, inplace=True)

# Keep only variants with standard missense aa_change format: e.g., Ser100Leu
import re
lacoste_df = lacoste_df[lacoste_df['aa_change'].str.match(r'^[A-Z][a-z]{2}\d+[A-Z][a-z]{2}$', na=False)]

lacoste_df

,Gene,Variant (alternative),Collection,Phenotype annotation,dbSNP_ID,Uniprot,Mislocalized,Mislocalization phenotype,Impact score,AlphaMissense score,AlphaMissense class,GnomAD VEP frequency,Inheritance,ClinVar class,PPI phenotype,PTM residue,PTM type,Disulfide bond,HeLa expression (TPM),aa_change
0,A2M,NaN,hmORFeome 1.1,Chronic obstructive pulmonary disease,rs1800433,P01023,0.0,NaN,0.638561,0.9488,pathogenic,0.000000,unclear phenotype,Benign/Likely benign,NaN,NaN,NaN,NaN,17.7,Cys972Tyr
1,A2M,NaN,hmORFeome 1.1,"Alzheimer disease, association with",rs669,P01023,NaN,NaN,NaN,NaN,NaN,NaN,association,No data,NaN,NaN,NaN,NaN,17.7,Val1000Ile
2,A4GALT,NaN,hmORFeome 1.1,Pk synthase deficiency (p phenotype),NaN,Q9NPC4,0.0,NaN,0.396055,0.9612,pathogenic,0.000004,autosomal dominant,No data,NaN,NaN,NaN,NaN,19.8,Ala219Val
3,A4GALT,NaN,Target Accelerator Pan-Cancer Mutant Collection,NaN,NaN,Q9NPC4,0.0,NaN,0.066536,0.0944,benign,0.000000,somatic,No data,NaN,NaN,NaN,NaN,19.8,Ala272Val
4,A4GALT,NaN,hmORFeome 1.1,Pk synthase deficiency (p phenotype),NaN,Q9NPC4,0.0,NaN,NaN,0.9898,pathogenic,0.000004,autosomal dominant,No data,NaN,NaN,NaN,NaN,19.8,Cys96Tyr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3443,ZNF41,NaN,hmORFeome 1.1 common variant,NaN,rs17147624,P51814,NaN,NaN,NaN,0.0932,benign,0.027420,common variant,Benign/Likely benign,Unperturbed-degree-1,NaN,NaN,NaN,7.1,Ile125Arg
3444,ZNF41,NaN,hmORFeome 1.1,Mental retardation,rs104894955,P51814,NaN,NaN,NaN,0.0878,benign,0.000519,x-linked recessive,Benign/Likely benign,Perturbed-degree-1,NaN,NaN,NaN,7.1,Pro111Leu
3445,ZNF454,NaN,Target Accelerator Pan-Cancer Mutant Collection,NaN,NaN,Q8N9F8,0.0,NaN,0.234768,0.9742,pathogenic,0.000000,somatic,No data,NaN,NaN,NaN,NaN,0.0,His462Tyr
3446,ZNF454,NaN,Target Accelerator Pan-Cancer Mutant Collection,NaN,NaN,Q8N9F8,0.0,NaN,0.059484,0.9722,pathogenic,0.000000,somatic,No data,NaN,NaN,NaN,NaN,0.0,Pro299Leu
3447,ZNF624,NaN,hmORFeome 1.1,"Lung cancer, susceptibility to, association with",rs8065506,Q9P2J8,0.0,NaN,NaN,0.0773,benign,0.360000,association,No data,Unperturbed-degree-1,NaN,NaN,NaN,0.6,Lys135Asn

In [190]:
lacoste_df.columns

Index(['Gene', 'Variant (alternative)', 'Collection', 'Phenotype annotation',
       'dbSNP_ID', 'Uniprot', 'Mislocalized', 'Mislocalization phenotype',
       'Impact score', 'AlphaMissense score', 'AlphaMissense class',
       'GnomAD VEP frequency', 'Inheritance', 'ClinVar class', 'PPI phenotype',
       'PTM residue', 'PTM type', 'Disulfide bond', 'HeLa expression (TPM)',
       'aa_change'],
      dtype='object')

In [191]:
lacoste_vars = pd.read_csv('../1_inputs/Lacoste_variants.tsv', sep='\t')
lacoste_vars

,mutation_id,orf_id,nt_change,aa_change,cloned,ensembl_protein_id,orf_class,aa_change_hgvs,nt_change_cnt,cloned_project,obsolete,note
0,CCSBVarC009367,3581,771C>A,Ser257Arg,1,ENSP00000264079.5,class1m,ENSP00000264079.5:p.Ser257Arg,1,varchamp_lacoste,0,NaN
1,CCSBVarC009375,3581,625C>T,Leu209Phe,1,ENSP00000264079.5,class1m,ENSP00000264079.5:p.Leu209Phe,1,varchamp_lacoste,0,NaN
2,CCSBVarC009378,3581,707G>A,Arg236Gln,1,ENSP00000264079.5,class1m,ENSP00000264079.5:p.Arg236Gln,1,varchamp_lacoste,0,NaN
3,CCSBVarC009565,4870,1003G>A,Ala335Thr,1,ENSP00000369317.3,class1m,ENSP00000369317.3:p.Ala335Thr,1,varchamp_lacoste,0,NaN
4,CCSBVarC009567,4870,628C>A,Leu210Met,1,ENSP00000369317.3,class1m,ENSP00000369317.3:p.Leu210Met,1,varchamp_lacoste,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1156,CCSBVarC017302,9352,815A>G,Asn272Ser,1,ENSP00000324246.6,class1,ENSP00000324246.6:p.Asn272Ser,1,varchamp_lacoste,0,NaN
1157,CCSBVarC017305,9352,857C>T,Ala286Val,1,ENSP00000324246.6,class1,ENSP00000324246.6:p.Ala286Val,1,varchamp_lacoste,0,NaN
1158,CCSBVarC017309,9352,905C>T,Pro302Leu,1,ENSP00000324246.6,class1,ENSP00000324246.6:p.Pro302Leu,1,varchamp_lacoste,0,NaN
1159,CCSBVarC017310,9352,94G>A,Val32Ile,1,ENSP00000324246.6,class1,ENSP00000324246.6:p.Val32Ile,1,varchamp_lacoste,0,NaN
1160,CCSBVarC017311,9352,997A>G,Thr333Ala,1,ENSP00000324246.6,class1,ENSP00000324246.6:p.Thr333Ala,1,varchamp_lacoste,0,NaN

In [192]:
# TODO clean clinvar annontation better

# Harmonize Lacoste ClinVar class to match clinvar_clnsig_clean categories
lacoste_df['ClinVar class'] = lacoste_df['ClinVar class'].replace({
    'Benign/Likely benign': 'Benign',
    'Pathogenic/Likely pathogenic': 'Pathogenic',
    'No data': np.nan,
    'Conflicting': 'VUS',
    'Affects': 'Others',
    'Risk factor': 'Others',
    'Drug response': 'Others',
    'Association': 'Others',
    'Other': 'Others',
})

print("Harmonized Lacoste ClinVar class:")
print(lacoste_df['ClinVar class'].value_counts(dropna=False))

Harmonized Lacoste ClinVar class:
ClinVar class
NaN           1280
Pathogenic    1271
VUS            481
Benign         252
Others          90
Name: count, dtype: int64

In [193]:

cols_to_keep = ['Gene','aa_change','ClinVar class', 'Phenotype annotation',
       'dbSNP_ID', 'Uniprot', 'Mislocalized',
       'Impact score']

lacoste_df = lacoste_df[cols_to_keep]
lacoste_df = lacoste_df[lacoste_df.Mislocalized == lacoste_df.Mislocalized]

# Remove Met1Xxx (start-loss) variants
met1_pattern = r'Met1[A-Z][a-z][a-z]$'
n_met1 = lacoste_df.aa_change.str.match(met1_pattern, na=False).sum()
print(f"Removing {n_met1} Met1Xxx variants from Lacoste")
lacoste_df = lacoste_df[~lacoste_df.aa_change.str.match(met1_pattern, na=False)]

lacoste_df['gene_variant'] = lacoste_df.Gene + '_' + lacoste_df.aa_change
lacoste_df

Removing 4 Met1Xxx variants from Lacoste

,Gene,aa_change,ClinVar class,Phenotype annotation,dbSNP_ID,Uniprot,Mislocalized,Impact score,gene_variant
0,A2M,Cys972Tyr,Benign,Chronic obstructive pulmonary disease,rs1800433,P01023,0.0,0.638561,A2M_Cys972Tyr
2,A4GALT,Ala219Val,NaN,Pk synthase deficiency (p phenotype),NaN,Q9NPC4,0.0,0.396055,A4GALT_Ala219Val
3,A4GALT,Ala272Val,NaN,NaN,NaN,Q9NPC4,0.0,0.066536,A4GALT_Ala272Val
4,A4GALT,Cys96Tyr,NaN,Pk synthase deficiency (p phenotype),NaN,Q9NPC4,0.0,NaN,A4GALT_Cys96Tyr
5,A4GALT,Met183Lys,Others,Pk synthase deficiency (p phenotype),rs74315453,Q9NPC4,0.0,0.352201,A4GALT_Met183Lys
...,...,...,...,...,...,...,...,...,...
3437,ZFYVE27,Gly191Val,VUS,Spastic paraplegia ?,rs35077384,Q5T4F4,0.0,0.513286,ZFYVE27_Gly191Val
3438,ZNF24,Ser220Asn,NaN,"Leukemia, risk, association with",rs2032729,P17028,0.0,NaN,ZNF24_Ser220Asn
3445,ZNF454,His462Tyr,NaN,NaN,NaN,Q8N9F8,0.0,0.234768,ZNF454_His462Tyr
3446,ZNF454,Pro299Leu,NaN,NaN,NaN,Q8N9F8,0.0,0.059484,ZNF454_Pro299Leu
3447,ZNF624,Lys135Asn,NaN,"Lung cancer, susceptibility to, association with",rs8065506,Q9P2J8,0.0,NaN,ZNF624_Lys135Asn

# Fragoza

## Edgotyping

In [194]:
mg = mygene.MyGeneInfo()

In [195]:
frag_exac_df = pd.read_excel(f'{datasets_dir}/Fragoza/41467_2019_11959_MOESM6_ESM.xlsx')
frag_exac_df['aa_change'] = [f'{seq3(UniProt.split(",")[-1][0])}{UniProt.split(",")[-1][1:-1]}{seq3(UniProt.split(",")[-1][-1])}' for UniProt in frag_exac_df.UniProt]

missing_updated = {285733:100507203,440321:100132565}
frag_exac_df['Interactor Entrez GeneID'] = frag_exac_df['Target Entrez GeneID'].replace(missing_updated)
entrez_ids = frag_exac_df['Target Entrez GeneID'].tolist() + frag_exac_df['Interactor Entrez GeneID'].tolist()
entrez_ids = list(set(entrez_ids))
mg_res = mg.querymany(entrez_ids, scopes='entrezgene', fields='symbol', species='human')
entrez_to_symbol = {int(res['query']): res['symbol'] for res in mg_res if 'symbol' in res}

frag_exac_df['target_symbol'] = frag_exac_df['Target Entrez GeneID'].map(entrez_to_symbol)
frag_exac_df['interactor_symbol'] = frag_exac_df['Interactor Entrez GeneID'].map(entrez_to_symbol)

cdna_to_aa = {cdna: uni for cdna, uni in zip(frag_exac_df['HGVS_cDNA'], frag_exac_df['aa_change'])}

frag_exac_df.columns

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

Index(['Chrom', 'Pos', 'dbSNP_id', 'Mutation', 'AF_all',
       'Target Entrez GeneID', 'HGVS_cDNA', 'UniProt',
       'Interactor Entrez GeneID', 'Disruption', 'aa_change', 'target_symbol',
       'interactor_symbol'],
      dtype='object')

In [196]:
frag_exac_df

,Chrom,Pos,dbSNP_id,Mutation,AF_all,Target Entrez GeneID,HGVS_cDNA,UniProt,Interactor Entrez GeneID,Disruption,aa_change,target_symbol,interactor_symbol
0,1,909238,rs3829740,G>C,0.668550,84069,NM_001160184.1:c.1355G>C,"Q494U1,R539P",84069,0,Arg539Pro,PLEKHN1,PLEKHN1
1,1,909238,rs3829740,G>C,0.668550,84069,NM_001160184.1:c.1355G>C,"Q494U1,R539P",84069,0,Arg539Pro,PLEKHN1,PLEKHN1
2,1,909238,rs3829740,G>C,0.668550,84069,NM_001160184.1:c.1355G>C,"Q494U1,R539P",84069,0,Arg539Pro,PLEKHN1,PLEKHN1
3,1,909238,rs3829740,G>C,0.668550,84069,NM_001160184.1:c.1355G>C,"Q494U1,R539P",84069,0,Arg539Pro,PLEKHN1,PLEKHN1
4,1,1686081,rs75816936,G>A,0.025416,65220,NM_023018.4:c.745C>T,"O95544,R249W",65220,0,Arg249Trp,NADK,NADK
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4104,X,153609400,rs144842093,G>A,0.000046,2010,NM_000117.2:c.608G>A,"P50402,R203H",2010,0,Arg203His,EMD,EMD
4105,X,153881552,rs61731293,C>T,0.002954,30848,NM_172377.3:c.238G>A,"O75638,A80T",30848,0,Ala80Thr,CTAG2,CTAG2
4106,X,153881552,rs61731293,C>T,0.002954,30848,NM_172377.3:c.238G>A,"O75638,A80T",30848,0,Ala80Thr,CTAG2,CTAG2
4107,X,154490199,rs146900062,C>A,0.000091,116442,NM_171998.2:c.531G>T,"Q96DA2,R177S",116442,0,Arg177Ser,RAB39B,RAB39B
4108,X,154490199,rs146900062,C>A,0.000091,116442,NM_171998.2:c.531G>T,"Q96DA2,R177S",116442,1,Arg177Ser,RAB39B,RAB39B

In [197]:
cols_to_keep = ['dbSNP_id', 'Mutation', 'AF_all',
              'target_symbol', 'aa_change', 'interactor_symbol',
              'Disruption']

frag_exac_df = frag_exac_df[cols_to_keep]
frag_exac_df

,dbSNP_id,Mutation,AF_all,target_symbol,aa_change,interactor_symbol,Disruption
0,rs3829740,G>C,0.668550,PLEKHN1,Arg539Pro,PLEKHN1,0
1,rs3829740,G>C,0.668550,PLEKHN1,Arg539Pro,PLEKHN1,0
2,rs3829740,G>C,0.668550,PLEKHN1,Arg539Pro,PLEKHN1,0
3,rs3829740,G>C,0.668550,PLEKHN1,Arg539Pro,PLEKHN1,0
4,rs75816936,G>A,0.025416,NADK,Arg249Trp,NADK,0
...,...,...,...,...,...,...,...
4104,rs144842093,G>A,0.000046,EMD,Arg203His,EMD,0
4105,rs61731293,C>T,0.002954,CTAG2,Ala80Thr,CTAG2,0
4106,rs61731293,C>T,0.002954,CTAG2,Ala80Thr,CTAG2,0
4107,rs146900062,C>A,0.000091,RAB39B,Arg177Ser,RAB39B,0
4108,rs146900062,C>A,0.000091,RAB39B,Arg177Ser,RAB39B,1

In [198]:
frag_cosmic = pd.read_excel(f'{datasets_dir}/Fragoza/41467_2019_11959_MOESM7_ESM.xlsx')


frag_cosmic['aa_change'] = [f'{seq3(UniProt.split(",")[-1][0])}{UniProt.split(",")[-1][1:-1]}{seq3(UniProt.split(",")[-1][-1])}' for UniProt in frag_cosmic.UniProt]

entrez_ids = frag_cosmic['Target Entrez GeneID'].tolist() + frag_cosmic['Interactor Entrez GeneID'].tolist()
entrez_ids = list(set(entrez_ids))
mg_res = mg.querymany(entrez_ids, scopes='entrezgene', fields='symbol', species='human')
entrez_to_symbol = {int(res['query']): res['symbol'] for res in mg_res if 'symbol' in res}

frag_cosmic['target_symbol'] = frag_cosmic['Target Entrez GeneID'].map(entrez_to_symbol)
frag_cosmic['interactor_symbol'] = frag_cosmic['Interactor Entrez GeneID'].map(entrez_to_symbol)

cdna_to_aa.update(frag_cosmic.set_index('HGVS_cDNA')['aa_change'].to_dict())


frag_cosmic.columns

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

Index(['Chrom', 'Pos', 'dbSNP_id', 'Mutation', 'Target Entrez GeneID',
       'HGVS_cDNA', 'UniProt', 'Interactor Entrez GeneID', 'Disruption',
       'aa_change', 'target_symbol', 'interactor_symbol'],
      dtype='object')

In [199]:
cols_to_keep = ['dbSNP_id', 'Mutation',
              'target_symbol', 'aa_change', 'interactor_symbol',
              'Disruption']

frag_cosmic = frag_cosmic[cols_to_keep]
frag_cosmic

    dbSNP_id Mutation target_symbol  aa_change interactor_symbol  Disruption
0          -      C>G         STX12   Pro88Arg              DTX2           0
1          -      C>G         STX12   Pro88Arg              STX4           0
2          -      C>T         HOOK1  Ser433Leu              CDK4           0
3          -      C>T         HOOK1  Ser433Leu            TFIP11           0
4          -      C>T         HOOK1  Ser433Leu            TBC1D7           0
..       ...      ...           ...        ...               ...         ...
379        -      G>T          NXF3    Thr9Lys              NXT2           0
380        -      G>C         PRPS1  Asp203His           GORASP2           0
381        -      G>C         PRPS1  Asp203His             PRPS2           1
382        -      G>C         PRPS1  Asp203His           PRPSAP1           0
383        -      G>A         PDZD4   Arg39Cys              APIP           0

[384 rows x 6 columns]

In [200]:
frag_hgmd = pd.read_excel(f'{datasets_dir}/Fragoza/41467_2019_11959_MOESM8_ESM.xlsx')

frag_hgmd['aa_change'] = [f'{seq3(UniProt.split(",")[-1][0])}{UniProt.split(",")[-1][1:-1]}{seq3(UniProt.split(",")[-1][-1])}' for UniProt in frag_hgmd.UniProt]

entrez_ids = frag_hgmd['Target Entrez GeneID'].tolist() + frag_hgmd['Interactor Entrez GeneID'].tolist()
entrez_ids = list(set(entrez_ids))
mg_res = mg.querymany(entrez_ids, scopes='entrezgene', fields='symbol', species='human')
entrez_to_symbol = {int(res['query']): res['symbol'] for res in mg_res if 'symbol' in res}

frag_hgmd['target_symbol'] = frag_hgmd['Target Entrez GeneID'].map(entrez_to_symbol)
frag_hgmd['interactor_symbol'] = frag_hgmd['Interactor Entrez GeneID'].map(entrez_to_symbol)

cdna_to_aa.update(frag_hgmd.set_index('HGVS_cDNA')['aa_change'].to_dict())

frag_hgmd.columns

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

Index(['Chrom', 'Pos', 'Mutation', 'Target Entrez GeneID', 'HGVS_cDNA',
       'UniProt', 'Interactor Entrez GeneID', 'Disruption', 'aa_change',
       'target_symbol', 'interactor_symbol'],
      dtype='object')

In [201]:
cols_to_keep = ['Mutation',
              'target_symbol', 'aa_change', 'interactor_symbol',
              'Disruption']

frag_hgmd = frag_hgmd[cols_to_keep]
frag_hgmd

    Mutation target_symbol  aa_change interactor_symbol  Disruption
0        G>A        NMNAT1    Val9Met            NMNAT1           0
1        G>A        NMNAT1   Ala13Thr            NMNAT1           0
2        C>T        NMNAT1   Arg66Trp              CCNC           1
3        C>T        NMNAT1   Arg66Trp             KPNA2           1
4        C>T        NMNAT1   Arg66Trp            NMNAT1           1
..       ...           ...        ...               ...         ...
347      G>A         HPRT1  Cys206Tyr             NTAQ1           1
348      G>A         HPRT1  Cys206Tyr           PRTFDC1           0
349      C>T           EMD   Ser54Phe             BANF1           0
350      A>T           EMD   Asp72Val             BANF1           0
351      C>A           EMD  Pro183Thr             BANF1           0

[352 rows x 5 columns]

In [202]:
def edgotype_status_fragoza(score_list):
    score_list = score_list.to_list()
    if len(score_list) == 1:
        if pd.isnull(score_list[0]):
            return np.nan
        elif score_list[0] == 0:
            return 'Unperturbed-degree-1'
        elif score_list[0] == 1:
            return 'Perturbed-degree-1'
        else:
            return np.nan
    if pd.isnull(score_list).all():
        return np.nan
    if 0 in score_list and 1 in score_list:
        return 'Edgetic'
    elif score_list.count(1) >= 2:
        return 'Quasi-null'
    elif score_list.count(0) >= 2:
        return 'Quasi-wild-type'
    else:
        return np.nan
    
# Fragoza ExAC
frag_exac_df['Disruption'] = pd.to_numeric(frag_exac_df['Disruption'], errors='coerce')
frag_exac_df['gene_variant'] = frag_exac_df.target_symbol + '_' + frag_exac_df.aa_change
frag_exac_df['Edgotype_class'] = frag_exac_df.groupby('gene_variant')['Disruption'].transform(edgotype_status_fragoza)
frag_exac_df.drop_duplicates(subset=['gene_variant'], inplace=True)
frag_exac_df.drop(columns=['interactor_symbol', 'Disruption'], inplace=True)

# Fragoza COSMIC
frag_cosmic['Disruption'] = pd.to_numeric(frag_cosmic['Disruption'], errors='coerce')
frag_cosmic['gene_variant'] = frag_cosmic.target_symbol + '_' + frag_cosmic.aa_change
frag_cosmic['Edgotype_class'] = frag_cosmic.groupby('gene_variant')['Disruption'].transform(edgotype_status_fragoza)
frag_cosmic.drop_duplicates(subset=['gene_variant'], inplace=True)
frag_cosmic.drop(columns=['interactor_symbol', 'Disruption'], inplace=True)

# Fragoza HGMD
frag_hgmd['Disruption'] = pd.to_numeric(frag_hgmd['Disruption'], errors='coerce')
frag_hgmd['gene_variant'] = frag_hgmd.target_symbol + '_' + frag_hgmd.aa_change
frag_hgmd['Edgotype_class'] = frag_hgmd.groupby('gene_variant')['Disruption'].transform(edgotype_status_fragoza)
frag_hgmd.drop_duplicates(subset=['gene_variant'], inplace=True)
frag_hgmd.drop(columns=['interactor_symbol', 'Disruption'], inplace=True)

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1568599443.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frag_exac_df['Disruption'] = pd.to_numeric(frag_exac_df['Disruption'], errors='coerce')
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1568599443.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frag_exac_df['gene_variant'] = frag_exac_df.target_symbol + '_' + frag_exac_df.aa_change
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1568599443.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frag_exac_df['Edgotype_class'] = frag_exac_df.groupby('gene_variant')['Disruption'].transform(edgotype_status_fragoza)
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1568599443.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frag_exac_df.drop_duplicates(subset=['gene_variant'], inplace=True)
/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1568599443.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frag_exac_df.drop(columns=['interactor_symbol', 'Disruption'], inplace=True)

## Abundance

In [203]:
frag_abun = pd.read_excel(f'{datasets_dir}/Fragoza/41467_2019_11959_MOESM9_ESM.xlsx')

frag_abun['aa_change'] = [cdna_to_aa.get(cdna, None) for cdna in frag_abun['HGVS_cDNA']]
frag_abun

entrez_ids = frag_abun['Target Entrez GeneID'].tolist()
entrez_ids = list(set(entrez_ids))
mg_res = mg.querymany(entrez_ids, scopes='entrezgene', fields='symbol', species='human')
entrez_to_symbol = {int(res['query']): res['symbol'] for res in mg_res if 'symbol' in res}

frag_abun['target_symbol'] = frag_abun['Target Entrez GeneID'].map(entrez_to_symbol)

frag_abun.columns

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

Index(['Target Entrez GeneID', 'HGVS_cDNA', 'Fold Change', 'Fold Z',
       'WT_Activation', 'Local_Activation', 'Status', 'aa_change',
       'target_symbol'],
      dtype='object')

In [204]:
cols_to_keep = ['HGVS_cDNA',
              'target_symbol', 'aa_change',
              'Status']

frag_abun = frag_abun[cols_to_keep]
frag_abun['gene_variant'] = frag_abun.target_symbol + '_' + frag_abun.aa_change
frag_abun

,HGVS_cDNA,target_symbol,aa_change,Status,gene_variant
0,NM_015458.3:c.377C>G,MTMR9,Ser126Cys,stable,MTMR9_Ser126Cys
1,NM_182679.2:c.313C>G,GPATCH4,Leu105Val,stable,GPATCH4_Leu105Val
2,NM_003702.3:c.598C>T,RGS20,His347Tyr,stable,RGS20_His347Tyr
3,NM_139276.2:c.429G>A,STAT3,Met143Ile,stable,STAT3_Met143Ile
4,NM_024041.3:c.617G>C,SCNM1,Arg206Pro,stable,SCNM1_Arg206Pro
...,...,...,...,...,...
273,NM_000554.4:c.472G>A,CRX,Ala158Thr,unstable,CRX_Ala158Thr
274,NM_000270.3:c.553C>T,PNP,Arg185Cys,unstable,PNP_Arg185Cys
275,NM_023112.3:c.437G>C,OTUB2,Arg146Pro,unstable,OTUB2_Arg146Pro
276,NM_014328.3:c.587T>C,RUSC1,Phe665Ser,unstable,RUSC1_Phe665Ser
277,NM_024041.3:c.521C>T,SCNM1,Ala174Val,unstable,SCNM1_Ala174Val

# Merging datasets

In [205]:
dataset_names = ['1% dataset',
                'Sahni PPI',
                'Sahni Chaperone',
                'Lacoste Imaging',
                'Luck PPI',
                'Rolland PPI',
                'Fragoza-ExAC PPI',
                'Fragoza-COSMIC PPI',
                'Fragoza-HGMD PPI',
                'Fragoza Abundance',
                'Union (all)']

## Check Overlap of variants across datasets

In [206]:
# Check for overlapping gene_variants across edgotyping datasets
edgotype_datasets = {
    'Sahni': set(sahni_vars[sahni_vars.Edgotype_class.notna()].gene_variant),
    'Rolland': set(rol_df[rol_df.Edgotype_class.notna()].gene_variant),
    'Luck': set(luck_df[luck_df.Edgotype_class.notna()].gene_variant),
    'Fragoza_ExAC': set(frag_exac_df[frag_exac_df.Edgotype_class.notna()].gene_variant),
    'Fragoza_COSMIC': set(frag_cosmic[frag_cosmic.Edgotype_class.notna()].gene_variant),
    'Fragoza_HGMD': set(frag_hgmd[frag_hgmd.Edgotype_class.notna()].gene_variant),
}

from itertools import combinations

for (name_a, set_a), (name_b, set_b) in combinations(edgotype_datasets.items(), 2):
    overlap = set_a & set_b
    if overlap:
        print(f"{name_a} ∩ {name_b}: {len(overlap)} overlapping variants")
        print(f"  Examples: {list(overlap)[:5]}")
    else:
        print(f"{name_a} ∩ {name_b}: no overlap")

Sahni ∩ Rolland: 115 overlapping variants
  Examples: ['EFHC1_Met448Thr', 'RPGR_Thr255Ile', 'SMAD3_Asn197Ile', 'COQ8A_Gly272Val', 'TNFRSF13B_Ala103Thr']
Sahni ∩ Luck: no overlap
Sahni ∩ Fragoza_ExAC: 30 overlapping variants
  Examples: ['FTH1_Lys54Arg', 'FMO3_Gly180Val', 'PGBD1_Gly244Glu', 'RPGR_Arg425Lys', 'CBR3_Val244Met']
Sahni ∩ Fragoza_COSMIC: no overlap
Sahni ∩ Fragoza_HGMD: 23 overlapping variants
  Examples: ['TAT_Arg119Trp', 'SMAD3_Asn197Ile', 'CDK4_Asn41Ser', 'FBP1_Gly260Arg', 'FBP1_Gly164Ser']
Rolland ∩ Luck: no overlap
Rolland ∩ Fragoza_ExAC: 18 overlapping variants
  Examples: ['SMAD3_Ile170Val', 'LITAF_Ile92Val', 'FBP1_Gly260Arg', 'ACTN2_Gln9Arg', 'ACTN2_Met604Val']
Rolland ∩ Fragoza_COSMIC: no overlap
Rolland ∩ Fragoza_HGMD: 6 overlapping variants
  Examples: ['FBP1_Gly164Ser', 'FBP1_Phe194Ser', 'SMAD3_Asn197Ile', 'ACTN2_Gln9Arg', 'FBP1_Asn213Lys']
Luck ∩ Fragoza_ExAC: no overlap
Luck ∩ Fragoza_COSMIC: no overlap
Luck ∩ Fragoza_HGMD: no overlap
Fragoza_ExAC ∩ Fragoza_COSMIC: 7 overlapping variants
  Examples: ['BLK_Ala71Thr', 'PBX4_Thr283Met', 'PKNOX1_Val265Ile', 'ELOA2_Arg498Gln', 'BIRC7_His164Arg']
Fragoza_ExAC ∩ Fragoza_HGMD: 25 overlapping variants
  Examples: ['ACY1_Arg378Trp', 'ACY1_Arg393His', 'ACTN2_His775Tyr', 'ACTN2_Thr495Met', 'FBP1_Gly260Arg']
Fragoza_COSMIC ∩ Fragoza_HGMD: no overlap

In [207]:
# For overlapping variants, compare their Edgotype_class across datasets
edgotype_dfs = {
    'Sahni': sahni_vars[sahni_vars.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
    'Rolland': rol_df[rol_df.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
    'Luck': luck_df[luck_df.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
    'Fragoza_ExAC': frag_exac_df[frag_exac_df.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
    'Fragoza_COSMIC': frag_cosmic[frag_cosmic.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
    'Fragoza_HGMD': frag_hgmd[frag_hgmd.Edgotype_class.notna()][['gene_variant', 'Edgotype_class']],
}

from itertools import combinations

for (name_a, df_a), (name_b, df_b) in combinations(edgotype_dfs.items(), 2):
    merged = df_a.merge(df_b, on='gene_variant', suffixes=(f'_{name_a}', f'_{name_b}'))
    if len(merged) == 0:
        continue
    
    col_a = f'Edgotype_class_{name_a}'
    col_b = f'Edgotype_class_{name_b}'
    
    concordant = (merged[col_a] == merged[col_b]).sum()
    discordant = (merged[col_a] != merged[col_b]).sum()
    
    print(f"\n{name_a} ∩ {name_b}: {len(merged)} overlapping variants")
    print(f"  Concordant: {concordant}, Discordant: {discordant}")
    
    if discordant > 0:
        disc_df = merged[merged[col_a] != merged[col_b]]
        print(f"  Discordant cases:")
        print(disc_df[['gene_variant', col_a, col_b]].to_string(index=False))

Sahni ∩ Rolland: 115 overlapping variants
  Concordant: 103, Discordant: 12
  Discordant cases:
   gene_variant Edgotype_class_Sahni Edgotype_class_Rolland
CRYBA4_Leu69Pro           Quasi-null     Perturbed-degree-1
CRYBA4_Phe94Ser           Quasi-null     Perturbed-degree-1
CRYBA4_Val36Met           Quasi-null     Perturbed-degree-1
 EFHC1_Pro77Thr              Edgetic             Quasi-null
 FBP1_Gly164Ser      Quasi-wild-type   Unperturbed-degree-1
 FBP1_Phe194Ser              Edgetic     Perturbed-degree-1
 FBP1_Asn213Lys      Quasi-wild-type   Unperturbed-degree-1
 FBP1_Gly260Arg           Quasi-null     Perturbed-degree-1
 FBP1_Arg218Lys      Quasi-wild-type   Unperturbed-degree-1
 FBP1_Phe233Ile      Quasi-wild-type   Unperturbed-degree-1
  GYPA_Arg50Trp              Edgetic             Quasi-null
  GYPA_Glu24Gly              Edgetic             Quasi-null

Sahni ∩ Fragoza_ExAC: 30 overlapping variants
  Concordant: 15, Discordant: 15
  Discordant cases:
     gene_variant Edgotype_class_Sahni Edgotype_class_Fragoza_ExAC
    ACTN2_Gln9Arg              Edgetic        Unperturbed-degree-1
 ADIPOQ_Tyr111His      Quasi-wild-type        Unperturbed-degree-1
   BLMH_Ile443Val Unperturbed-degree-1             Quasi-wild-type
   CBR3_Val244Met   Perturbed-degree-1        Unperturbed-degree-1
   DMC1_Met200Val           Quasi-null        Unperturbed-degree-1
   FBP1_Arg218Lys      Quasi-wild-type        Unperturbed-degree-1
    FTH1_Lys54Arg Unperturbed-degree-1             Quasi-wild-type
   LITAF_Ile92Val      Quasi-wild-type        Unperturbed-degree-1
     LTA_Thr60Asn      Quasi-wild-type        Unperturbed-degree-1
NEUROG3_Phe199Ser   Perturbed-degree-1        Unperturbed-degree-1
  PGBD1_Gly244Glu      Quasi-wild-type                     Edgetic
  PGBD1_Gln248Glu      Quasi-wild-type                     Edgetic
  PGBD1_Pro256Leu      Quasi-wild-type                     Edgetic
  PITX1_Gly299Ala      Quasi-wild-type        Unperturbed-degree-1
   PKP2_Ala264Val      Quasi-wild-type        Unperturbed-degree-1

Sahni ∩ Fragoza_HGMD: 23 overlapping variants
  Concordant: 3, Discordant: 20
  Discordant cases:
   gene_variant Edgotype_class_Sahni Edgotype_class_Fragoza_HGMD
 ACTB_Arg183Trp      Quasi-wild-type          Perturbed-degree-1
  ACTN2_Gln9Arg              Edgetic        Unperturbed-degree-1
  CDK4_Arg24His              Edgetic        Unperturbed-degree-1
  CDK4_Asn41Ser      Quasi-wild-type        Unperturbed-degree-1
 DMC1_Met200Val           Quasi-null                     Edgetic
   EMD_Ser54Phe      Quasi-wild-type        Unperturbed-degree-1
   EMD_Asp72Val      Quasi-wild-type        Unperturbed-degree-1
  EMD_Pro183Thr      Quasi-wild-type        Unperturbed-degree-1
 FBP1_Gly164Ser      Quasi-wild-type          Perturbed-degree-1
 FBP1_Phe194Ser              Edgetic          Perturbed-degree-1
 FBP1_Asn213Lys      Quasi-wild-type          Perturbed-degree-1
 FBP1_Gly260Arg           Quasi-null          Perturbed-degree-1
   FTL_Ala96Thr           Quasi-null          Perturbed-degree-1
MYD88_Arg196Cys              Edgetic          Perturbed-degree-1
 NME1_Ser120Gly   Perturbed-degree-1                     Edgetic
PRPS1_Asp183His      Quasi-wild-type                     Edgetic
SMAD3_Asn197Ile      Quasi-wild-type        Unperturbed-degree-1
  TAT_Arg119Trp      Quasi-wild-type                  Quasi-null
  TAT_Pro220Ser              Edgetic        Unperturbed-degree-1
  TAT_Leu273Pro           Quasi-null          Perturbed-degree-1

Rolland ∩ Fragoza_ExAC: 18 overlapping variants
  Concordant: 11, Discordant: 7
  Discordant cases:
   gene_variant Edgotype_class_Rolland Edgotype_class_Fragoza_ExAC
PGBD1_Pro256Leu        Quasi-wild-type                     Edgetic
PGBD1_Gln248Glu        Quasi-wild-type                     Edgetic
 LITAF_Ile92Val        Quasi-wild-type        Unperturbed-degree-1
 PKP2_Ala264Val        Quasi-wild-type        Unperturbed-degree-1
 FBP1_Gly260Arg     Perturbed-degree-1                  Quasi-null
  ACTN2_Gln9Arg                Edgetic        Unperturbed-degree-1
PGBD1_Gly244Glu        Quasi-wild-type                     Edgetic

Rolland ∩ Fragoza_HGMD: 6 overlapping variants
  Concordant: 2, Discordant: 4
  Discordant cases:
   gene_variant Edgotype_class_Rolland Edgotype_class_Fragoza_HGMD
SMAD3_Asn197Ile        Quasi-wild-type        Unperturbed-degree-1
 FBP1_Gly164Ser   Unperturbed-degree-1          Perturbed-degree-1
 FBP1_Asn213Lys   Unperturbed-degree-1          Perturbed-degree-1
  ACTN2_Gln9Arg                Edgetic        Unperturbed-degree-1

Fragoza_ExAC ∩ Fragoza_COSMIC: 7 overlapping variants
  Concordant: 7, Discordant: 0

Fragoza_ExAC ∩ Fragoza_HGMD: 25 overlapping variants
  Concordant: 16, Discordant: 9
  Discordant cases:
   gene_variant Edgotype_class_Fragoza_ExAC Edgotype_class_Fragoza_HGMD
ACTN2_Thr495Met        Unperturbed-degree-1             Quasi-wild-type
 ACY1_Arg197Trp          Perturbed-degree-1                     Edgetic
CDKN1A_Arg67Leu        Unperturbed-degree-1                     Edgetic
CDKN1A_Arg84Gln             Quasi-wild-type        Unperturbed-degree-1
 GNMT_His177Asn        Unperturbed-degree-1          Perturbed-degree-1
   ASL_Arg12Gln        Unperturbed-degree-1             Quasi-wild-type
 FBP1_Gly260Arg                  Quasi-null          Perturbed-degree-1
  PTS_Thr106Met                  Quasi-null          Perturbed-degree-1
 DMC1_Met200Val        Unperturbed-degree-1                     Edgetic

In [208]:
# Check which variants appear in multiple edgotyping datasets
from collections import Counter

variant_to_datasets = {}
for name, variant_set in edgotype_datasets.items():
    for v in variant_set:
        variant_to_datasets.setdefault(v, []).append(name)

# Variants in 3+ datasets
multi_overlap = {v: ds for v, ds in variant_to_datasets.items() if len(ds) >= 3}
print(f"Variants in 3+ edgotyping datasets: {len(multi_overlap)}")
for v, ds in sorted(multi_overlap.items()):
    print(f"  {v}: {ds}")

# Also show the edgotype class for each
print("\nDetailed edgotype classes:")
for v, ds in sorted(multi_overlap.items()):
    classes = {}
    for name, df in edgotype_dfs.items():
        match = df[df.gene_variant == v]
        if len(match) > 0:
            classes[name] = match.Edgotype_class.values[0]
    print(f"  {v}: {classes}")

Variants in 3+ edgotyping datasets: 23
  ACTN2_Gln9Arg: ['Sahni', 'Rolland', 'Fragoza_ExAC', 'Fragoza_HGMD']
  ACTN2_Met604Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  DMC1_Met200Val: ['Sahni', 'Fragoza_ExAC', 'Fragoza_HGMD']
  EFHC1_Arg159Trp: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  FBP1_Arg218Lys: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  FBP1_Asn213Lys: ['Sahni', 'Rolland', 'Fragoza_HGMD']
  FBP1_Gly164Ser: ['Sahni', 'Rolland', 'Fragoza_HGMD']
  FBP1_Gly260Arg: ['Sahni', 'Rolland', 'Fragoza_ExAC', 'Fragoza_HGMD']
  FBP1_Phe194Ser: ['Sahni', 'Rolland', 'Fragoza_HGMD']
  KRT6A_Thr552Ser: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  KRT6A_Val523Phe: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  LITAF_Ile92Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  MCEE_Ala76Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  MCEE_Arg143His: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  PGBD1_Gln248Glu: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  PGBD1_Gly244Glu: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  PGBD1_Ile678Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  PGBD1_Pro256Leu: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  PKP2_Ala264Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  RPGR_Arg425Lys: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  RPGR_Gln184His: ['Sahni', 'Rolland', 'Fragoza_ExAC']
  SMAD3_Asn197Ile: ['Sahni', 'Rolland', 'Fragoza_HGMD']
  SMAD3_Ile170Val: ['Sahni', 'Rolland', 'Fragoza_ExAC']

Detailed edgotype classes:
  ACTN2_Gln9Arg: {'Sahni': 'Edgetic', 'Rolland': 'Edgetic', 'Fragoza_ExAC': 'Unperturbed-degree-1', 'Fragoza_HGMD': 'Unperturbed-degree-1'}
  ACTN2_Met604Val: {'Sahni': 'Edgetic', 'Rolland': 'Edgetic', 'Fragoza_ExAC': 'Edgetic'}
  DMC1_Met200Val: {'Sahni': 'Quasi-null', 'Fragoza_ExAC': 'Unperturbed-degree-1', 'Fragoza_HGMD': 'Edgetic'}
  EFHC1_Arg159Trp: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  FBP1_Arg218Lys: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Unperturbed-degree-1', 'Fragoza_ExAC': 'Unperturbed-degree-1'}
  FBP1_Asn213Lys: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Unperturbed-degree-1', 'Fragoza_HGMD': 'Perturbed-degree-1'}
  FBP1_Gly164Ser: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Unperturbed-degree-1', 'Fragoza_HGMD': 'Perturbed-degree-1'}
  FBP1_Gly260Arg: {'Sahni': 'Quasi-null', 'Rolland': 'Perturbed-degree-1', 'Fragoza_ExAC': 'Quasi-null', 'Fragoza_HGMD': 'Perturbed-degree-1'}
  FBP1_Phe194Ser: {'Sahni': 'Edgetic', 'Rolland': 'Perturbed-degree-1', 'Fragoza_HGMD': 'Perturbed-degree-1'}
  KRT6A_Thr552Ser: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  KRT6A_Val523Phe: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  LITAF_Ile92Val: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Unperturbed-degree-1'}
  MCEE_Ala76Val: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  MCEE_Arg143His: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  PGBD1_Gln248Glu: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Edgetic'}
  PGBD1_Gly244Glu: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Edgetic'}
  PGBD1_Ile678Val: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}
  PGBD1_Pro256Leu: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Edgetic'}
  PKP2_Ala264Val: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Unperturbed-degree-1'}
  RPGR_Arg425Lys: {'Sahni': 'Unperturbed-degree-1', 'Rolland': 'Unperturbed-degree-1', 'Fragoza_ExAC': 'Unperturbed-degree-1'}
  RPGR_Gln184His: {'Sahni': 'Unperturbed-degree-1', 'Rolland': 'Unperturbed-degree-1', 'Fragoza_ExAC': 'Unperturbed-degree-1'}
  SMAD3_Asn197Ile: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_HGMD': 'Unperturbed-degree-1'}
  SMAD3_Ile170Val: {'Sahni': 'Quasi-wild-type', 'Rolland': 'Quasi-wild-type', 'Fragoza_ExAC': 'Quasi-wild-type'}

In [209]:
# Identify variants ONLY in Fragoza datasets (not in Sahni, Rolland, or Luck)
sahni_rolland_luck = edgotype_datasets['Sahni'] | edgotype_datasets['Rolland'] | edgotype_datasets['Luck']
fragoza_only = {}
for name in ['Fragoza_ExAC', 'Fragoza_COSMIC', 'Fragoza_HGMD']:
    fragoza_only[name] = edgotype_datasets[name] - sahni_rolland_luck

# Check discordance among Fragoza-only variants that appear in multiple Fragoza datasets
fragoza_names = ['Fragoza_ExAC', 'Fragoza_COSMIC', 'Fragoza_HGMD']
for (name_a, name_b) in combinations(fragoza_names, 2):
    overlap = fragoza_only[name_a] & fragoza_only[name_b]
    if not overlap:
        print(f"{name_a} ∩ {name_b} (Fragoza-only): no overlap")
        continue
    
    df_a = edgotype_dfs[name_a]
    df_b = edgotype_dfs[name_b]
    merged = df_a[df_a.gene_variant.isin(overlap)].merge(
        df_b[df_b.gene_variant.isin(overlap)], on='gene_variant', suffixes=(f'_{name_a}', f'_{name_b}')
    )
    col_a = f'Edgotype_class_{name_a}'
    col_b = f'Edgotype_class_{name_b}'
    
    concordant = (merged[col_a] == merged[col_b]).sum()
    discordant = (merged[col_a] != merged[col_b]).sum()
    
    print(f"\n{name_a} ∩ {name_b} (Fragoza-only): {len(merged)} variants")
    print(f"  Concordant: {concordant}, Discordant: {discordant}")
    if discordant > 0:
        disc_df = merged[merged[col_a] != merged[col_b]]
        print(f"  -> These will be DISCARDED:")
        print(disc_df[['gene_variant', col_a, col_b]].to_string(index=False))

Fragoza_ExAC ∩ Fragoza_COSMIC (Fragoza-only): 7 variants
  Concordant: 7, Discordant: 0

Fragoza_ExAC ∩ Fragoza_HGMD (Fragoza-only): 22 variants
  Concordant: 15, Discordant: 7
  -> These will be DISCARDED:
   gene_variant Edgotype_class_Fragoza_ExAC Edgotype_class_Fragoza_HGMD
ACTN2_Thr495Met        Unperturbed-degree-1             Quasi-wild-type
 ACY1_Arg197Trp          Perturbed-degree-1                     Edgetic
CDKN1A_Arg67Leu        Unperturbed-degree-1                     Edgetic
CDKN1A_Arg84Gln             Quasi-wild-type        Unperturbed-degree-1
 GNMT_His177Asn        Unperturbed-degree-1          Perturbed-degree-1
   ASL_Arg12Gln        Unperturbed-degree-1             Quasi-wild-type
  PTS_Thr106Met                  Quasi-null          Perturbed-degree-1
Fragoza_COSMIC ∩ Fragoza_HGMD (Fragoza-only): no overlap

## Merging step

In [210]:
# Build unified Edgotype_class with priority: Sahni > Rolland > Luck > Fragoza
# For Fragoza-only variants in multiple Fragoza sub-datasets: concordant -> keep, discordant -> discard

# Step 1: Identify Fragoza-only discordant variants to discard
sahni_rolland_luck = edgotype_datasets['Sahni'] | edgotype_datasets['Rolland'] | edgotype_datasets['Luck']
fragoza_only = {}
for name in ['Fragoza_ExAC', 'Fragoza_COSMIC', 'Fragoza_HGMD']:
    fragoza_only[name] = edgotype_datasets[name] - sahni_rolland_luck

discard_variants = set()
fragoza_names = ['Fragoza_ExAC', 'Fragoza_COSMIC', 'Fragoza_HGMD']
for (name_a, name_b) in combinations(fragoza_names, 2):
    overlap = fragoza_only[name_a] & fragoza_only[name_b]
    if not overlap:
        continue
    df_a = edgotype_dfs[name_a].set_index('gene_variant')
    df_b = edgotype_dfs[name_b].set_index('gene_variant')
    for v in overlap:
        if df_a.loc[v, 'Edgotype_class'] != df_b.loc[v, 'Edgotype_class']:
            discard_variants.add(v)

print(f"Discarding {len(discard_variants)} Fragoza-only discordant variants:")
for v in sorted(discard_variants):
    print(f"  {v}")

# Step 2: Build priority-based Edgotype_class lookup
# Priority order: Sahni, Rolland, Luck, Fragoza_ExAC, Fragoza_COSMIC, Fragoza_HGMD
priority_order = ['Sahni', 'Rolland', 'Luck', 'Fragoza_ExAC', 'Fragoza_COSMIC', 'Fragoza_HGMD']

edgotype_lookup = {}
# Go in reverse priority so higher priority overwrites
for name in reversed(priority_order):
    df = edgotype_dfs[name]
    for _, row in df.iterrows():
        v = row['gene_variant']
        if v in discard_variants and name.startswith('Fragoza'):
            continue
        edgotype_lookup[v] = row['Edgotype_class']

print(f"\nTotal variants with Edgotype_class: {len(edgotype_lookup)}")

# Step 3: Also track which dataset the edgotype came from
edgotype_source = {}
for name in reversed(priority_order):
    df = edgotype_dfs[name]
    for _, row in df.iterrows():
        v = row['gene_variant']
        if v in discard_variants and name.startswith('Fragoza'):
            continue
        edgotype_source[v] = name

# Step 4: Merge all datasets (outer join) keeping dataset-specific metadata
# but using a single Edgotype_class column

# --- Sahni (combined PPI + Chaperone) ---
sahni_combined = sahni_vars[['symbol', 'aa_change', 'gene_variant', 'clinical_significance', 'Category', 'Sahni_Chaperone_binding']].copy()
sahni_combined = sahni_combined.drop_duplicates('gene_variant')
sahni_combined.rename(columns={
    'symbol': 'gene_symbol',
    'clinical_significance': 'Sahni_clinical_significance',
    'Category': 'Sahni_Category',
}, inplace=True)


# --- Rolland metadata ---
rol_harmonized = rol_df[['gene_symbol', 'aa_change', 'gene_variant', 'category', 'Phenotype']].copy()
rol_harmonized.rename(columns={
    'category': 'Rolland_category',
    'Phenotype': 'Rolland_Phenotype',
}, inplace=True)

# --- Luck metadata ---
luck_harmonized = luck_df[['CG_symbol', 'mutation', 'gene_variant', 'assay_id', 'pathogenecity', 'omim_ids']].copy()
luck_harmonized.rename(columns={
    'CG_symbol': 'gene_symbol',
    'mutation': 'aa_change',
    'assay_id': 'Luck_assay_id',
    'pathogenecity': 'Luck_pathogenecity',
    'omim_ids': 'Luck_omim_ids',
}, inplace=True)

# --- Lacoste Imaging ---
lacoste_harmonized = lacoste_df[['Gene', 'aa_change', 'ClinVar class', 'Phenotype annotation',
                                  'dbSNP_ID', 'Uniprot', 'Mislocalized', 'Impact score']].copy()
lacoste_harmonized.rename(columns={
    'Gene': 'gene_symbol',
    'ClinVar class': 'Lacoste_ClinVar_class',
    'Phenotype annotation': 'Lacoste_Phenotype_annotation',
    'dbSNP_ID': 'Lacoste_dbSNP_ID',
    'Uniprot': 'Lacoste_Uniprot',
    'Mislocalized': 'Lacoste_Mislocalized',
    'Impact score': 'Lacoste_Impact_score',
}, inplace=True)
lacoste_harmonized['gene_variant'] = lacoste_harmonized.gene_symbol + '_' + lacoste_harmonized.aa_change

# --- Fragoza ExAC metadata ---
frag_exac_harmonized = frag_exac_df[['target_symbol', 'aa_change', 'gene_variant', 'dbSNP_id', 'Mutation', 'AF_all']].copy()
frag_exac_harmonized.rename(columns={
    'target_symbol': 'gene_symbol',
    'dbSNP_id': 'Fragoza_ExAC_dbSNP_id',
    'Mutation': 'Fragoza_ExAC_Mutation',
    'AF_all': 'Fragoza_ExAC_AF_all',
}, inplace=True)

# --- Fragoza COSMIC metadata ---
frag_cosmic_harmonized = frag_cosmic[['target_symbol', 'aa_change', 'gene_variant', 'dbSNP_id', 'Mutation']].copy()
frag_cosmic_harmonized.rename(columns={
    'target_symbol': 'gene_symbol',
    'dbSNP_id': 'Fragoza_COSMIC_dbSNP_id',
    'Mutation': 'Fragoza_COSMIC_Mutation',
}, inplace=True)

# --- Fragoza HGMD metadata ---
frag_hgmd_harmonized = frag_hgmd[['target_symbol', 'aa_change', 'gene_variant', 'Mutation']].copy()
frag_hgmd_harmonized.rename(columns={
    'target_symbol': 'gene_symbol',
    'Mutation': 'Fragoza_HGMD_Mutation',
}, inplace=True)

# --- Fragoza Abundance ---
frag_abun_harmonized = frag_abun[['target_symbol', 'aa_change', 'HGVS_cDNA', 'Status']].copy()
frag_abun_harmonized.rename(columns={
    'target_symbol': 'gene_symbol',
    'Status': 'Fragoza_Abundance_Status',
    'HGVS_cDNA': 'Fragoza_Abundance_HGVS_cDNA',
}, inplace=True)
frag_abun_harmonized['gene_variant'] = frag_abun_harmonized.gene_symbol + '_' + frag_abun_harmonized.aa_change

# --- Merge all on gene_variant (outer joins) ---
all_datasets = [
    sahni_combined,
    rol_harmonized,
    luck_harmonized,
    lacoste_harmonized,
    frag_exac_harmonized,
    frag_cosmic_harmonized,
    frag_hgmd_harmonized,
    frag_abun_harmonized,
]

from functools import reduce

merged_df = reduce(
    lambda left, right: left.merge(
        right.drop(columns=['gene_symbol', 'aa_change'], errors='ignore'),
        on='gene_variant',
        how='outer'
    ),
    all_datasets
)

# Fill gene_symbol and aa_change from gene_variant for rows that came from right-only joins
merged_df['gene_symbol'] = merged_df['gene_symbol'].fillna(merged_df['gene_variant'].str.rsplit('_', n=1).str[0])
merged_df['aa_change'] = merged_df['aa_change'].fillna(merged_df['gene_variant'].str.rsplit('_', n=1).str[1])

# Step 5: Add unified Edgotype_class and source columns
merged_df['Edgotype_class'] = merged_df['gene_variant'].map(edgotype_lookup)
merged_df['Edgotype_source'] = merged_df['gene_variant'].map(edgotype_source)

print(f"Merged table: {merged_df.shape}")
print(f"Unique variants: {merged_df.gene_variant.nunique()}")
print(f"Variants with Edgotype_class: {merged_df.Edgotype_class.notna().sum()}")
print(f"\nEdgotype source breakdown:")
print(merged_df.Edgotype_source.value_counts())
merged_df

Discarding 7 Fragoza-only discordant variants:
  ACTN2_Thr495Met
  ACY1_Arg197Trp
  ASL_Arg12Gln
  CDKN1A_Arg67Leu
  CDKN1A_Arg84Gln
  GNMT_His177Asn
  PTS_Thr106Met

Total variants with Edgotype_class: 2500
Merged table: (5336, 27)
Unique variants: 5335
Variants with Edgotype_class: 2500

Edgotype source breakdown:
Edgotype_source
Fragoza_ExAC      1639
Sahni              527
Fragoza_HGMD       159
Fragoza_COSMIC     155
Luck                20
Name: count, dtype: int64

,gene_symbol,aa_change,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,...,Fragoza_ExAC_dbSNP_id,Fragoza_ExAC_Mutation,Fragoza_ExAC_AF_all,Fragoza_COSMIC_dbSNP_id,Fragoza_COSMIC_Mutation,Fragoza_HGMD_Mutation,Fragoza_Abundance_HGVS_cDNA,Fragoza_Abundance_Status,Edgotype_class,Edgotype_source
0,A2M,Cys972Tyr,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A4GALT,Ala219Val,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A4GALT,Ala272Val,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT,Cys96Tyr,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,Met183Lys,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5331,ZSCAN22,Ala321Val,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rs60710360,C>T,0.002568,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC
5332,ZSCAN9,Gln34Arg,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rs62638671,A>G,0.000634,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC
5333,ZYX,Arg489Trp,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rs73154206,C>T,0.014218,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC
5334,ZYX,Arg563Gln,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rs149835123,G>A,0.000801,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC
5335,ZYX,His223Leu,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rs11978404,A>T,0.060885,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC

## Clinical significance

In [211]:
# Check different Clinical and Category annotations to unify later
print("Sahni clinical_significance:")
print(merged_df['Sahni_clinical_significance'].value_counts(dropna=False))
print("\nSahni Category:")
print(merged_df['Sahni_Category'].value_counts(dropna=False))
print("\nRolland category:")
print(merged_df['Rolland_category'].value_counts(dropna=False))
print("\nLuck pathogenecity:")
print(merged_df['Luck_pathogenecity'].value_counts(dropna=False))
print("\nLacoste ClinVar class:")
print(merged_df['Lacoste_ClinVar_class'].value_counts(dropna=False))

Sahni clinical_significance:
Sahni_clinical_significance
NaN            2874
Pathogenic      964
Others          787
Benign          281
VUS             216
Conflicting     214
Name: count, dtype: int64

Sahni Category:
Sahni_Category
NaN                    4809
Disease mutation        460
Non-disease variant      67
Name: count, dtype: int64

Rolland category:
Rolland_category
NaN                 5221
Disease mutation      67
Common variant        48
Name: count, dtype: int64

Luck pathogenecity:
Luck_pathogenecity
NaN                                             5316
Pathogenic                                        12
Conflicting interpretations of pathogenicity       3
Uncertain significance                             2
Benign/Likely benign                               2
Likely pathogenic                                  1
Name: count, dtype: int64

Lacoste ClinVar class:
Lacoste_ClinVar_class
NaN           3995
Pathogenic     817
VUS            303
Benign         162
Others          59
Name: count, dtype: int64

### Adding ClinVar from 2025-01

In [212]:
# Map clinical significance for ExAC variants using ClinVar annontations
import polars as pl


processed_clinvar_parq = "../../1_allele_collection/3_outputs/processed_data/clinvar/clinvar_processed.parquet"
clinvar = pl.scan_parquet(processed_clinvar_parq)
clinvar_snv = clinvar.filter(pl.col("Type")=='single nucleotide variant') ##.select(pl.col("Type")).unique().collect().to_numpy()
clinvar_snv.collect().shape
clinvar_snv.schema

# Collect to pandas for easier merging
clinvar_pd = clinvar_snv.collect().to_pandas()

# Check columns
print(clinvar_pd.columns.tolist())
print(clinvar_pd.head())
# Build a gene_variant key in ClinVar to match your format
clinvar_pd['gene_variant'] = clinvar_pd['GeneSymbol'] + '_' + clinvar_pd['clinvar_aa_change']

# Create a lookup for clinical significance
clinvar_lookup = clinvar_pd.drop_duplicates('gene_variant').set_index('gene_variant')['clinvar_clnsig_clean']

# Map to merged_df
merged_df['ClinVar_significance'] = merged_df['gene_variant'].map(clinvar_lookup)
merged_df['ClinVar_significance'] = merged_df['ClinVar_significance'].astype('object')
print(f"Variants with ClinVar annotation: {merged_df.ClinVar_significance.notna().sum()}")

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/4077264327.py:9: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  clinvar_snv.schema

['#AlleleID', 'Type', 'Name', 'GeneID', 'GeneSymbol', 'HGNC_ID', 'ClinicalSignificance', 'ClinSigSimple', 'LastEvaluated', 'RS# (dbSNP)', 'nsv/esv (dbVar)', 'RCVaccession', 'PhenotypeIDS', 'PhenotypeList', 'Origin', 'OriginSimple', 'Assembly', 'ChromosomeAccession', 'Chromosome', 'Start', 'Stop', 'Cytogenetic', 'ReviewStatus', 'NumberSubmitters', 'Guidelines', 'TestedInGTR', 'OtherIDs', 'SubmitterCategories', 'VariationID', 'PositionVCF', 'ReferenceAlleleVCF', 'AlternateAlleleVCF', 'SomaticClinicalImpact', 'SomaticClinicalImpactLastEvaluated', 'ReviewStatusClinicalImpact', 'Oncogenicity', 'OncogenicityLastEvaluated', 'ReviewStatusOncogenicity', 'clinvar_nt_change', 'clinvar_aa_change', 'SPDI', 'RefSeq_mRNA', 'StarStatus', 'clinvar_clnsig_clean', 'clinvar_clnsig_clean_pp_strict']
   #AlleleID                       Type  \
0      15043  single nucleotide variant
1      15044  single nucleotide variant
2      15045  single nucleotide variant
3      15046  single nucleotide variant
4      15048  single nucleotide variant

                                           Name  GeneID GeneSymbol  \
0  NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg)    9640     ZNF592
1   NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter)   55572    FOXRED1
2  NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser)   55572    FOXRED1
3      NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg)   80224      NUBPL
4       NM_000410.4(HFE):c.845G>A (p.Cys282Tyr)    3077        HFE

      HGNC_ID                               ClinicalSignificance  \
0  HGNC:28986                             Uncertain significance
1  HGNC:26927                                         Pathogenic
2  HGNC:26927                                         Pathogenic
3  HGNC:20278       Conflicting classifications of pathogenicity
4   HGNC:4886  Pathogenic/Pathogenic, low penetrance; other; ...

   ClinSigSimple LastEvaluated  RS# (dbSNP)  ... Oncogenicity  \
0              0  Jun 29, 2015    150829393  ...            -
1              1  Dec 01, 2023    267606829  ...            -
2              1  Oct 01, 2010    267606830  ...            -
3              1  Jul 05, 2022    200401432  ...            -
4              1  Nov 01, 2024      1800562  ...            -

  OncogenicityLastEvaluated ReviewStatusOncogenicity clinvar_nt_change  \
0                         -                        -          3136G>A
1                         -                        -           694C>T
2                         -                        -          1289A>G
3                         -                        -           166G>A
4                         -                        -           845G>A

  clinvar_aa_change                        SPDI  RefSeq_mRNA StarStatus  \
0        Gly1046Arg   NC_000015.10:84799208:G:A  NM_014630.3        NaN
1         Gln232Ter  NC_000011.10:126275388:C:T  NM_017547.4        2.0
2         Asn430Ser  NC_000011.10:126277516:A:G  NM_017547.4        NaN
3          Gly56Arg    NC_000014.9:31562124:G:A  NM_025152.3        1.0
4         Cys282Tyr   NC_000006.12:26092912:G:A  NM_000410.4        2.0

  clinvar_clnsig_clean  clinvar_clnsig_clean_pp_strict
0                  VUS                             VUS
1           Pathogenic                      Pathogenic
2           Pathogenic                      Pathogenic
3          Conflicting                     Conflicting
4               Others                          Others

[5 rows x 45 columns]
Variants with ClinVar annotation: 2433

In [213]:
merged_df

,gene_symbol,aa_change,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,...,Fragoza_ExAC_Mutation,Fragoza_ExAC_AF_all,Fragoza_COSMIC_dbSNP_id,Fragoza_COSMIC_Mutation,Fragoza_HGMD_Mutation,Fragoza_Abundance_HGVS_cDNA,Fragoza_Abundance_Status,Edgotype_class,Edgotype_source,ClinVar_significance
0,A2M,Cys972Tyr,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benign
1,A4GALT,Ala219Val,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VUS
2,A4GALT,Ala272Val,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT,Cys96Tyr,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,Met183Lys,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5331,ZSCAN22,Ala321Val,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>T,0.002568,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5332,ZSCAN9,Gln34Arg,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A>G,0.000634,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN
5333,ZYX,Arg489Trp,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>T,0.014218,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5334,ZYX,Arg563Gln,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,G>A,0.000801,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5335,ZYX,His223Leu,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A>T,0.060885,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN

In [214]:
merged_df[merged_df.Edgotype_source.str.contains('Fragoza', na=False)]

,gene_symbol,aa_change,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,...,Fragoza_ExAC_Mutation,Fragoza_ExAC_AF_all,Fragoza_COSMIC_dbSNP_id,Fragoza_COSMIC_Mutation,Fragoza_HGMD_Mutation,Fragoza_Abundance_HGVS_cDNA,Fragoza_Abundance_Status,Edgotype_class,Edgotype_source,ClinVar_significance
14,ABCF3,Arg340Trp,ABCF3_Arg340Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>T,0.001403,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN
15,ABCF3,Arg510His,ABCF3_Arg510His,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,G>A,0.004250,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN
19,ABHD16A,Arg184Leu,ABHD16A_Arg184Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>A,0.001516,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,Benign
24,ABTB1,Arg386His,ABTB1_Arg386His,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,G>A,0.001445,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
45,ACAT2,Gly161Ser,ACAT2_Gly161Ser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-,G>A,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_COSMIC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5331,ZSCAN22,Ala321Val,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>T,0.002568,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5332,ZSCAN9,Gln34Arg,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A>G,0.000634,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN
5333,ZYX,Arg489Trp,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C>T,0.014218,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5334,ZYX,Arg563Gln,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,G>A,0.000801,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN
5335,ZYX,His223Leu,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A>T,0.060885,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN

In [215]:
# Count number of ClinVar annotations (NaN included) for each Edgotype_source
print("\nClinVar annotation counts by Edgotype_source:")
merged_df.groupby('Edgotype_source')['ClinVar_significance'].value_counts(dropna=False)

ClinVar annotation counts by Edgotype_source:

Edgotype_source  ClinVar_significance
Fragoza_COSMIC   NaN                      125
                 VUS                       17
                 Conflicting                6
                 Pathogenic                 6
                 Benign                     1
Fragoza_ExAC     NaN                     1197
                 Benign                   269
                 VUS                      103
                 Conflicting               59
                 Pathogenic                 8
                 Others                     3
Fragoza_HGMD     Pathogenic                67
                 NaN                       44
                 VUS                       25
                 Conflicting               14
                 Others                     8
                 Benign                     1
Luck             Pathogenic                 7
                 Conflicting                6
                 Benign                     3
                 VUS                        2
                 Others                     1
                 NaN                        1
Sahni            Pathogenic               172
                 NaN                      166
                 Benign                   100
                 VUS                       38
                 Conflicting               29
                 Others                    22
Name: count, dtype: int64

In [216]:
# Count number of ClinVar annotations (NaN included) for each Edgotype_source
for source in merged_df.Edgotype_source.dropna().unique():
    subset = merged_df[merged_df.Edgotype_source == source]
    print(f"\n--- {source} ({len(subset)} variants) ---")
    print(subset.ClinVar_significance.value_counts(dropna=False))

--- Sahni (527 variants) ---
ClinVar_significance
Pathogenic     172
NaN            166
Benign         100
VUS             38
Conflicting     29
Others          22
Name: count, dtype: int64

--- Fragoza_ExAC (1639 variants) ---
ClinVar_significance
NaN            1197
Benign          269
VUS             103
Conflicting      59
Pathogenic        8
Others            3
Name: count, dtype: int64

--- Fragoza_COSMIC (155 variants) ---
ClinVar_significance
NaN            125
VUS             17
Pathogenic       6
Conflicting      6
Benign           1
Name: count, dtype: int64

--- Fragoza_HGMD (159 variants) ---
ClinVar_significance
Pathogenic     67
NaN            44
VUS            25
Conflicting    14
Others          8
Benign          1
Name: count, dtype: int64

--- Luck (20 variants) ---
ClinVar_significance
Pathogenic     7
Conflicting    6
Benign         3
VUS            2
NaN            1
Others         1
Name: count, dtype: int64

In [217]:
len(merged_df) - 2986

2350

In [218]:
merged_df.ClinVar_significance.value_counts(dropna=False)

ClinVar_significance
NaN            2903
Pathogenic     1089
Benign          520
VUS             402
Conflicting     296
Others          126
Name: count, dtype: int64

In [219]:
merged_df[~merged_df.Edgotype_source.str.contains('Fragoza', na=False)].ClinVar_significance.value_counts(dropna=False)

ClinVar_significance
NaN            1537
Pathogenic     1008
VUS             257
Benign          249
Conflicting     217
Others          115
Name: count, dtype: int64

In [220]:
merged_df[~merged_df.Edgotype_source.str.contains('Fragoza', na=False)]

,gene_symbol,aa_change,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,...,Fragoza_ExAC_Mutation,Fragoza_ExAC_AF_all,Fragoza_COSMIC_dbSNP_id,Fragoza_COSMIC_Mutation,Fragoza_HGMD_Mutation,Fragoza_Abundance_HGVS_cDNA,Fragoza_Abundance_Status,Edgotype_class,Edgotype_source,ClinVar_significance
0,A2M,Cys972Tyr,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benign
1,A4GALT,Ala219Val,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VUS
2,A4GALT,Ala272Val,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT,Cys96Tyr,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A4GALT,Met183Lys,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5292,ZNF41,Pro111Leu,ZNF41_Pro111Leu,Benign,Disease mutation,NaN,Disease mutation,Mental retardation,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Perturbed-degree-1,Sahni,Benign
5293,ZNF454,His462Tyr,ZNF454_His462Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5294,ZNF454,Pro299Leu,ZNF454_Pro299Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5319,ZNF624,Lys135Asn,ZNF624_Lys135Asn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5320,ZNF624,Lys9Asn,ZNF624_Lys9Asn,Others,Disease mutation,N,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Sahni,NaN

In [221]:
# Compare Sahni's original clinical_significance vs ClinVar parquet lookup
sahni_subset = merged_df[merged_df.Sahni_clinical_significance.notna()].copy()

# Harmonize Sahni's original to match ClinVar categories (case fix)
sahni_subset['Sahni_clinsig_harmonized'] = sahni_subset['Sahni_clinical_significance'].str.capitalize()
sahni_subset['Sahni_clinsig_harmonized'] = sahni_subset['Sahni_clinsig_harmonized'].replace({
    'Other': 'Others',
    'Vus': 'VUS',
})

print(f"Sahni variants with original clinsig: {len(sahni_subset)}")
print(f"  of which also have ClinVar lookup: {sahni_subset.ClinVar_significance.notna().sum()}")
print(f"  of which missing ClinVar lookup:   {sahni_subset.ClinVar_significance.isna().sum()}")

# Cross-tab: old vs new
ct = pd.crosstab(
    sahni_subset['Sahni_clinsig_harmonized'], 
    sahni_subset['ClinVar_significance'].fillna('No ClinVar match'),
    margins=True
)
print("\n--- Cross-tabulation: Sahni original (rows) vs ClinVar parquet (columns) ---")
print(ct.to_string())

# Concordance for variants that have both
both = sahni_subset[sahni_subset.ClinVar_significance.notna()].copy()
concordant = (both['Sahni_clinsig_harmonized'] == both['ClinVar_significance']).sum()
discordant = (both['Sahni_clinsig_harmonized'] != both['ClinVar_significance']).sum()
print(f"\nVariants with both annotations: {len(both)}")
print(f"  Concordant: {concordant} ({100*concordant/len(both):.1f}%)")
print(f"  Discordant: {discordant} ({100*discordant/len(both):.1f}%)")

# Show discordant cases breakdown
if discordant > 0:
    disc = both[both['Sahni_clinsig_harmonized'] != both['ClinVar_significance']]
    print("\n--- Discordant transitions ---")
    print(pd.crosstab(disc['Sahni_clinsig_harmonized'], disc['ClinVar_significance']).to_string())

Sahni variants with original clinsig: 2462
  of which also have ClinVar lookup: 1527
  of which missing ClinVar lookup:   935

--- Cross-tabulation: Sahni original (rows) vs ClinVar parquet (columns) ---
ClinVar_significance      Benign  Conflicting  No ClinVar match  Others  Pathogenic  VUS   All
Sahni_clinsig_harmonized
Benign                       232            0                49       0           0    0   281
Conflicting                    0          176                37       1           0    0   214
Others                         0            0               686      92           8    1   787
Pathogenic                     0            1               128       0         835    0   964
VUS                            0            0                35       0           0  181   216
All                          232          177               935      93         843  182  2462

Variants with both annotations: 1527
  Concordant: 1516 (99.3%)
  Discordant: 11 (0.7%)

--- Discordant transitions ---
ClinVar_significance      Conflicting  Others  Pathogenic  VUS
Sahni_clinsig_harmonized
Conflicting                         0       1           0    0
Others                              0       0           8    1
Pathogenic                          1       0           0    0

### Mapping ClinVar from Allele_col

In [222]:
len(merged_df)

5336

In [223]:
# Map gene_variant to clinvar_clnsig_clean for all merged_df from allele_col

merged_df = merged_df.merge(
    allele_col_dedup[['gene_variant', 'clinvar_clnsig_clean']],
    on='gene_variant',
    how='left',
    suffixes=('', '_allele_col')
)

merged_df

,gene_symbol,aa_change,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,...,Fragoza_ExAC_AF_all,Fragoza_COSMIC_dbSNP_id,Fragoza_COSMIC_Mutation,Fragoza_HGMD_Mutation,Fragoza_Abundance_HGVS_cDNA,Fragoza_Abundance_Status,Edgotype_class,Edgotype_source,ClinVar_significance,clinvar_clnsig_clean
0,A2M,Cys972Tyr,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benign,Benign
1,A4GALT,Ala219Val,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VUS,VUS
2,A4GALT,Ala272Val,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT,Cys96Tyr,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Others
4,A4GALT,Met183Lys,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Others,Others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5331,ZSCAN22,Ala321Val,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.002568,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN,NaN
5332,ZSCAN9,Gln34Arg,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000634,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN,NaN
5333,ZYX,Arg489Trp,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.014218,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN,NaN
5334,ZYX,Arg563Gln,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000801,NaN,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,NaN,NaN
5335,ZYX,His223Leu,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.060885,NaN,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,NaN,NaN

In [224]:
# save merged table
merged_df.to_csv('../3_outputs/Unified_Previous_Edgotype_Abundance_Dataset.csv', index=False)

# Add 1% data

In [225]:
oneperc_df = pd.read_csv('../3_outputs/0_all_gene_variants_assayed_summary.tsv', sep='\t')
oneperc_df

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/799331618.py:1: DtypeWarning: Columns (164,185,186,198,208,214,215,253,254,257,258,479,481,523,553,555,557,569,571,583,585,593,595,647,649,651,657,663,667,699,701,703,823,875,877,879,881,883,938,947,949,952,959,960,967,972,977,978,979,983,986,995,996,997) have mixed types. Specify dtype option on import or set low_memory=False.
  oneperc_df = pd.read_csv('../3_outputs/0_all_gene_variants_assayed_summary.tsv', sep='\t')

,symbol,aa_change,gene_variant,spdi,nt_change,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,...,img_U2OS_prot_abun_t_stat,img_U2OS_prot_abun_t_pval,img_U2OS_prot_abun_t_adj_pval,img_Metadata_Bio_Batch,imaging_score,img_misloc_score,img_pheno_hit,img_misloc_hit,img_pheno_hit_strict,imaging_hit
0,ABCD1,Arg389Gly,ABCD1_Arg389Gly,NC_000023.11:153736194:C:G,1165C>G,23,153736195,C,G,X,...,2.001570,0.101735,0.134305,2025_01_Batch_13-14,0.693378,0.573403,False,False,False,False
1,ABCD1,Arg518Gln,ABCD1_Arg518Gln,NC_000023.11:153740155:G:A,1553G>A,23,153740156,G,A,X,...,-0.564297,0.596924,0.645086,2025_01_Batch_13-14,0.784993,0.691867,False,False,False,False
2,ACSF3,Ala17Pro,ACSF3_Ala17Pro,NC_000016.10:89100729:G:C,49G>C,16,89100730,G,C,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACSF3,Ala197Thr,ACSF3_Ala197Thr,NC_000016.10:89101269:G:A,589G>A,16,89101270,G,A,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACSF3,Arg10Trp,ACSF3_Arg10Trp,NC_000016.10:89100708:C:T,28C>T,16,89100709,C,T,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402,ZC4H2,Pro201Ser,ZC4H2_Pro201Ser,NC_000023.11:64917856:G:A,601C>T,23,64917857,G,A,X,...,3.412556,0.058483,0.076827,2025_01_Batch_13-14,0.802143,0.776184,False,False,False,False
1403,ZC4H2,Val63Leu,ZC4H2_Val63Leu,NC_000023.11:64921854:C:G,187G>C,23,64921855,C,G,X,...,-3.575493,1.000000,1.000000,2025_01_Batch_13-14,0.921160,0.805641,False,False,False,False
1404,ZMYND10,Arg243Cys,ZMYND10_Arg243Cys,NC_000003.12:50342542:G:A,727C>T,3,50342543,G,A,3,...,1.676036,0.144748,0.183814,2024_01_Batch_7-8,0.904041,0.842055,False,False,False,False
1405,ZMYND10,Leu266Pro,ZMYND10_Leu266Pro,NC_000003.12:50342472:A:G,797T>C,3,50342473,A,G,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1406,ZMYND10,Val16Gly,ZMYND10_Val16Gly,NC_000003.12:50345532:A:C,47T>G,3,50345533,A,C,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
# Check overlap between 1% dataset and merged_df
oneperc_variants = set(oneperc_df['gene_variant'].dropna())
merged_variants = set(merged_df['gene_variant'].dropna())

overlap = oneperc_variants & merged_variants
only_oneperc = oneperc_variants - merged_variants
only_merged = merged_variants - oneperc_variants

print(f"1% dataset variants:     {len(oneperc_variants)}")
print(f"Merged dataset variants: {len(merged_variants)}")
print(f"Overlap:                 {len(overlap)}")
print(f"Only in 1%:              {len(only_oneperc)}")
print(f"Only in merged:          {len(only_merged)}")
print(f"\nOverlap rate (of 1%):    {100*len(overlap)/len(oneperc_variants):.1f}%")
print(f"Overlap rate (of merged): {100*len(overlap)/len(merged_variants):.1f}%")

# Show which merged datasets the overlapping variants come from
if overlap:
    overlap_df = merged_df[merged_df.gene_variant.isin(overlap)]
    print(f"\n--- Overlapping variants: Edgotype_source breakdown ---")
    print(overlap_df['Edgotype_source'].value_counts(dropna=False))
    
    print(f"\n--- Overlapping variants: dataset-specific column coverage ---")
    for col in ['Sahni_clinical_significance', 'Sahni_Chaperone_binding', 
                'Rolland_category', 'Luck_pathogenecity', 
                'Lacoste_Mislocalized', 'Edgotype_class',
                'Fragoza_Abundance_Status', 'ClinVar_significance']:
        n = overlap_df[col].notna().sum()
        if n > 0:
            print(f"  {col}: {n} variants")
    
    print(f"\n--- Examples of overlapping variants ---")
    print(overlap_df[['gene_variant', 'Edgotype_class', 'Edgotype_source']].head(10).to_string(index=False))

    # Compare Edgotype_class between 1% dataset and merged_df for overlapping variants
    oneperc_overlap = oneperc_df[oneperc_df.gene_variant.isin(overlap)][['gene_variant', 'Edgotype_class']].copy()
    merged_overlap = merged_df[merged_df.gene_variant.isin(overlap)][['gene_variant', 'Edgotype_class', 'Edgotype_source']].copy()
    
    edgotype_compare = oneperc_overlap.merge(
        merged_overlap, on='gene_variant', suffixes=('_1pct', '_literature')
    )
    
    # Only compare where both have an edgotype
    both_have = edgotype_compare[
        edgotype_compare.Edgotype_class_1pct.notna() & 
        edgotype_compare.Edgotype_class_literature.notna()
    ].copy()
    
    print(f"\n--- Edgotype_class comparison (overlap with both annotations) ---")
    print(f"Variants with edgotype in both: {len(both_have)}")
    
    if len(both_have) > 0:
        concordant = (both_have['Edgotype_class_1pct'] == both_have['Edgotype_class_literature']).sum()
        discordant = (both_have['Edgotype_class_1pct'] != both_have['Edgotype_class_literature']).sum()
        print(f"  Concordant: {concordant} ({100*concordant/len(both_have):.1f}%)")
        print(f"  Discordant: {discordant} ({100*discordant/len(both_have):.1f}%)")
        
        # Cross-tab
        ct = pd.crosstab(
            both_have['Edgotype_class_1pct'], 
            both_have['Edgotype_class_literature'],
            margins=True
        )
        print(f"\n--- Cross-tab: 1% (rows) vs Literature (columns) ---")
        print(ct.to_string())
        
        # Show discordant cases
        if discordant > 0:
            disc = both_have[both_have['Edgotype_class_1pct'] != both_have['Edgotype_class_literature']]
            print(f"\n--- Discordant variants ---")
            print(disc[['gene_variant', 'Edgotype_class_1pct', 'Edgotype_class_literature', 'Edgotype_source']].to_string(index=False))
    
    # Also show coverage: how many in overlap have edgotype in one but not the other
    only_1pct = edgotype_compare[
        edgotype_compare.Edgotype_class_1pct.notna() & 
        edgotype_compare.Edgotype_class_literature.isna()
    ]
    only_lit = edgotype_compare[
        edgotype_compare.Edgotype_class_1pct.isna() & 
        edgotype_compare.Edgotype_class_literature.notna()
    ]
    print(f"\n  Edgotype only in 1%:        {len(only_1pct)}")
    print(f"  Edgotype only in literature: {len(only_lit)}")
    print(f"  Edgotype in neither:         {len(edgotype_compare) - len(both_have) - len(only_1pct) - len(only_lit)}")

1% dataset variants:     1407
Merged dataset variants: 5335
Overlap:                 251
Only in 1%:              1156
Only in merged:          5084

Overlap rate (of 1%):    17.8%
Overlap rate (of merged): 4.7%

--- Overlapping variants: Edgotype_source breakdown ---
Edgotype_source
Sahni             127
NaN                79
Fragoza_HGMD       21
Luck               12
Fragoza_ExAC       11
Fragoza_COSMIC      1
Name: count, dtype: int64

--- Overlapping variants: dataset-specific column coverage ---
  Sahni_clinical_significance: 199 variants
  Sahni_Chaperone_binding: 187 variants
  Rolland_category: 51 variants
  Luck_pathogenecity: 12 variants
  Lacoste_Mislocalized: 129 variants
  Edgotype_class: 172 variants
  Fragoza_Abundance_Status: 3 variants
  ClinVar_significance: 211 variants

--- Examples of overlapping variants ---
   gene_variant       Edgotype_class Edgotype_source
 AGXT_Arg233Leu                  NaN             NaN
  AGXT_Pro11Leu                  NaN             NaN
 AGXT_Ser187Phe                  NaN             NaN
 AGXT_Val336Asp                  NaN             NaN
AIPL1_Arg270His                  NaN             NaN
AIPL1_Arg302Leu                  NaN             NaN
 AIPL1_Met79Thr                  NaN             NaN
AIPL1_Thr114Ile                  NaN             NaN
ALAS2_Arg133His Unperturbed-degree-1           Sahni
ALAS2_Ile439Asn   Perturbed-degree-1           Sahni

--- Edgotype_class comparison (overlap with both annotations) ---
Variants with edgotype in both: 39
  Concordant: 18 (46.2%)
  Discordant: 21 (53.8%)

--- Cross-tab: 1% (rows) vs Literature (columns) ---
Edgotype_class_literature  Edgetic  Perturbed-degree-1  Quasi-null  Quasi-wild-type  Unperturbed-degree-1  All
Edgotype_class_1pct
Edgetic                          6                   1           1                4                     0   12
Perturbed-degree-1               2                   2           0                0                     1    5
Quasi-null                       0                   0           3                0                     1    4
Quasi-wild-type                  3                   1           1                7                     4   16
Uncertain                        0                   0           0                0                     1    1
Uncertain-degree-1               0                   1           0                0                     0    1
All                             11                   5           5               11                     7   39

--- Discordant variants ---
    gene_variant Edgotype_class_1pct Edgotype_class_literature Edgotype_source
  CLN6_Gly123Asp  Perturbed-degree-1                   Edgetic            Luck
    EMD_Asp72Val             Edgetic           Quasi-wild-type           Sahni
   EMD_Pro183Thr             Edgetic           Quasi-wild-type           Sahni
    EMD_Ser54Phe             Edgetic           Quasi-wild-type           Sahni
  GALE_Asp103Gly  Uncertain-degree-1        Perturbed-degree-1    Fragoza_HGMD
 HPRT1_Thr168Ile             Edgetic        Perturbed-degree-1    Fragoza_HGMD
 LITAF_Ala111Gly             Edgetic                Quasi-null           Sahni
 LITAF_Gly112Ser     Quasi-wild-type                Quasi-null           Sahni
   MVK_Asn301Thr  Perturbed-degree-1                   Edgetic    Fragoza_HGMD
NMNAT1_Glu257Lys     Quasi-wild-type      Unperturbed-degree-1    Fragoza_HGMD
NMNAT1_Leu153Val     Quasi-wild-type        Perturbed-degree-1    Fragoza_HGMD
 SMAD3_Arg279Lys           Uncertain      Unperturbed-degree-1    Fragoza_HGMD
 SMAD3_Arg287Trp     Quasi-wild-type      Unperturbed-degree-1    Fragoza_HGMD
 SMAD3_Glu239Lys          Quasi-null      Unperturbed-degree-1    Fragoza_HGMD
 SMAD3_Pro263Leu     Quasi-wild-type      Unperturbed-degree-1    Fragoza_HGMD
 SMAD3_Thr261Ile     Quasi-wild-type      Unperturbed-degree-1    Fragoza_HGMD
 TMEM43_Arg28Trp     Quasi-wild-type                   Edgetic            Luck
TMEM43_Tyr371His             Edgetic           Quasi-wild-type            Luck
   TPM1_Glu40Lys     Quasi-wild-type                   Edgetic           Sahni
   TPM1_Val95Ala     Quasi-wild-type                   Edgetic           Sahni
    VHL_Pro81Ser  Perturbed-degree-1      Unperturbed-degree-1    Fragoza_ExAC

  Edgotype only in 1%:        10
  Edgotype only in literature: 133
  Edgotype in neither:         69

In [227]:
for col in oneperc_df.columns:
    print(col)

symbol
aa_change
gene_variant
spdi
nt_change
chr_num
nuc_loc
ref_allele
alt_allele
Chrom
ensembl_gene_id
orf_id
mut_id
ccsb_mutation_id
ccsb_allele_id
seq
seq_aa
ensembl_protein_id
collection
entry_plate_orig
entry_well_orig
entry_plate_conso
entry_well_conso
entry_seq_pool
db_plate
db_well
n2h_plate
n2h_well
dualip_plate
dualip_well
mislocalization_plate
mislocalization_well
entry_sequenced
entry_sequence_confirmation_class
db_sequenced
db_sequence_confirmation_class
n2h_sequenced
n2h_sequence_confirmation_class
n2h_ref_sequence_confirmation_class
dualip_sequenced
dualip_sequence_confirmation_class
dualip_ref_sequence_confirmation_class
mislocalization_sequenced
mislocalization_sequence_confirmation_class
mislocalization_ref_sequence_confirmation_class
entry_seq_final
db_seq_final
n2h_seq_final
dualip_seq_final
mislocalization_seq_final
#AlleleID
Type
Name
GeneID
GeneSymbol
HGNC_ID
ClinicalSignificance
ClinSigSimple
LastEvaluated
RS# (dbSNP)
nsv/esv (dbVar)
RCVaccession
PhenotypeIDS
PhenotypeList
Origin
OriginSimple
Assembly
ChromosomeAccession
Chromosome
Start
Stop
Cytogenetic
ReviewStatus
NumberSubmitters
Guidelines
TestedInGTR
OtherIDs
SubmitterCategories
VariationID
PositionVCF
ReferenceAlleleVCF
AlternateAlleleVCF
SomaticClinicalImpact
SomaticClinicalImpactLastEvaluated
ReviewStatusClinicalImpact
Oncogenicity
OncogenicityLastEvaluated
ReviewStatusOncogenicity
clinvar_nt_change
clinvar_aa_change
RefSeq_mRNA
StarStatus
clinvar_clnsig_clean
clinvar_clnsig_clean_pp_strict
#chr
pos(1-based)
ref
alt
aaref
aaalt
rs_dbSNP
hg19_chr
hg19_pos(1-based)
hg18_chr
hg18_pos(1-based)
aapos
genename
Ensembl_geneid
Ensembl_transcriptid
Ensembl_proteinid
Uniprot_acc
Uniprot_entry
HGVSc_snpEff
HGVSp_snpEff
HGVSc_VEP
HGVSp_VEP
APPRIS
GENCODE_basic
TSL
VEP_canonical
MANE
cds_strand
refcodon
codonpos
codon_degeneracy
Ancestral_allele
AltaiNeandertal
Denisova
VindijiaNeandertal
ChagyrskayaNeandertal
SIFT_score
SIFT_converted_rankscore
SIFT_pred
SIFT4G_score
SIFT4G_converted_rankscore
SIFT4G_pred
Polyphen2_HDIV_score
Polyphen2_HDIV_rankscore
Polyphen2_HDIV_pred
Polyphen2_HVAR_score
Polyphen2_HVAR_rankscore
Polyphen2_HVAR_pred
MutationTaster_score
MutationTaster_converted_rankscore
MutationTaster_pred
MutationTaster_model
MutationTaster_trees_benign
MutationTaster_trees_deleterious
MutationAssessor_score
MutationAssessor_rankscore
MutationAssessor_pred
PROVEAN_score
PROVEAN_converted_rankscore
PROVEAN_pred
VEST4_score
VEST4_rankscore
MetaSVM_score
MetaSVM_rankscore
MetaSVM_pred
MetaLR_score
MetaLR_rankscore
MetaLR_pred
Reliability_index
MetaRNN_score
MetaRNN_rankscore
MetaRNN_pred
M-CAP_score
M-CAP_rankscore
M-CAP_pred
REVEL_score
REVEL_rankscore
MutPred_score
MutPred_rankscore
MutPred_protID
MutPred_AAchange
MutPred_Top5features
MVP_score
MVP_rankscore
gMVP_score
gMVP_rankscore
MPC_score
MPC_rankscore
PrimateAI_score
PrimateAI_rankscore
PrimateAI_pred
DEOGEN2_score
DEOGEN2_rankscore
DEOGEN2_pred
BayesDel_addAF_score
BayesDel_addAF_rankscore
BayesDel_addAF_pred
BayesDel_noAF_score
BayesDel_noAF_rankscore
BayesDel_noAF_pred
ClinPred_score
ClinPred_rankscore
ClinPred_pred
LIST-S2_score
LIST-S2_rankscore
LIST-S2_pred
VARITY_R_score
VARITY_R_rankscore
VARITY_ER_score
VARITY_ER_rankscore
VARITY_R_LOO_score
VARITY_R_LOO_rankscore
VARITY_ER_LOO_score
VARITY_ER_LOO_rankscore
ESM1b_score
ESM1b_rankscore
ESM1b_pred
AlphaMissense_score
AlphaMissense_rankscore
AlphaMissense_pred
PHACTboost_score
PHACTboost_rankscore
MutFormer_score
MutFormer_rankscore
MutScore_score
MutScore_rankscore
Aloft_Fraction_transcripts_affected
Aloft_prob_Tolerant
Aloft_prob_Recessive
Aloft_prob_Dominant
Aloft_pred
Aloft_Confidence
CADD_raw
CADD_raw_rankscore
CADD_phred
DANN_score
DANN_rankscore
fathmm-XF_coding_score
fathmm-XF_coding_rankscore
fathmm-XF_coding_pred
Eigen-raw_coding
Eigen-raw_coding_rankscore
Eigen-phred_coding
Eigen-PC-raw_coding
Eigen-PC-raw_coding_rankscore
Eigen-PC-phred_coding
GERP++_NR
GERP++_RS
GERP++_RS_rankscore
GERP_91_mammals
GERP_91_mammals_rankscore
phyloP100way_vertebrate
phyloP100way_vertebrate_rankscore
phyloP470way_mammalian
phyloP470way_mammalian_rankscore
phyloP17way_primate
phyloP17way_primate_rankscore
phastCons100way_vertebrate
phastCons100way_vertebrate_rankscore
phastCons470way_mammalian
phastCons470way_mammalian_rankscore
phastCons17way_primate
phastCons17way_primate_rankscore
bStatistic
bStatistic_converted_rankscore
1000Gp3_AC
1000Gp3_AF
1000Gp3_AFR_AC
1000Gp3_AFR_AF
1000Gp3_EUR_AC
1000Gp3_EUR_AF
1000Gp3_AMR_AC
1000Gp3_AMR_AF
1000Gp3_EAS_AC
1000Gp3_EAS_AF
1000Gp3_SAS_AC
1000Gp3_SAS_AF
TOPMed_frz8_AC
TOPMed_frz8_AN
TOPMed_frz8_AF
gnomAD2.1.1_exomes_flag
gnomAD2.1.1_exomes_controls_AC
gnomAD2.1.1_exomes_controls_AN
gnomAD2.1.1_exomes_controls_AF
gnomAD2.1.1_exomes_controls_nhomalt
gnomAD2.1.1_exomes_non_neuro_AC
gnomAD2.1.1_exomes_non_neuro_AN
gnomAD2.1.1_exomes_non_neuro_AF
gnomAD2.1.1_exomes_non_neuro_nhomalt
gnomAD2.1.1_exomes_non_cancer_AC
gnomAD2.1.1_exomes_non_cancer_AN
gnomAD2.1.1_exomes_non_cancer_AF
gnomAD2.1.1_exomes_non_cancer_nhomalt
gnomAD2.1.1_exomes_controls_AFR_AC
gnomAD2.1.1_exomes_controls_AFR_AN
gnomAD2.1.1_exomes_controls_AFR_AF
gnomAD2.1.1_exomes_controls_AFR_nhomalt
gnomAD2.1.1_exomes_controls_AMR_AC
gnomAD2.1.1_exomes_controls_AMR_AN
gnomAD2.1.1_exomes_controls_AMR_AF
gnomAD2.1.1_exomes_controls_AMR_nhomalt
gnomAD2.1.1_exomes_controls_ASJ_AC
gnomAD2.1.1_exomes_controls_ASJ_AN
gnomAD2.1.1_exomes_controls_ASJ_AF
gnomAD2.1.1_exomes_controls_ASJ_nhomalt
gnomAD2.1.1_exomes_controls_EAS_AC
gnomAD2.1.1_exomes_controls_EAS_AN
gnomAD2.1.1_exomes_controls_EAS_AF
gnomAD2.1.1_exomes_controls_EAS_nhomalt
gnomAD2.1.1_exomes_controls_FIN_AC
gnomAD2.1.1_exomes_controls_FIN_AN
gnomAD2.1.1_exomes_controls_FIN_AF
gnomAD2.1.1_exomes_controls_FIN_nhomalt
gnomAD2.1.1_exomes_controls_NFE_AC
gnomAD2.1.1_exomes_controls_NFE_AN
gnomAD2.1.1_exomes_controls_NFE_AF
gnomAD2.1.1_exomes_controls_NFE_nhomalt
gnomAD2.1.1_exomes_controls_SAS_AC
gnomAD2.1.1_exomes_controls_SAS_AN
gnomAD2.1.1_exomes_controls_SAS_AF
gnomAD2.1.1_exomes_controls_SAS_nhomalt
gnomAD2.1.1_exomes_controls_POPMAX_AC
gnomAD2.1.1_exomes_controls_POPMAX_AN
gnomAD2.1.1_exomes_controls_POPMAX_AF
gnomAD2.1.1_exomes_controls_POPMAX_nhomalt
gnomAD2.1.1_exomes_non_neuro_AFR_AC
gnomAD2.1.1_exomes_non_neuro_AFR_AN
gnomAD2.1.1_exomes_non_neuro_AFR_AF
gnomAD2.1.1_exomes_non_neuro_AFR_nhomalt
gnomAD2.1.1_exomes_non_neuro_AMR_AC
gnomAD2.1.1_exomes_non_neuro_AMR_AN
gnomAD2.1.1_exomes_non_neuro_AMR_AF
gnomAD2.1.1_exomes_non_neuro_AMR_nhomalt
gnomAD2.1.1_exomes_non_neuro_ASJ_AC
gnomAD2.1.1_exomes_non_neuro_ASJ_AN
gnomAD2.1.1_exomes_non_neuro_ASJ_AF
gnomAD2.1.1_exomes_non_neuro_ASJ_nhomalt
gnomAD2.1.1_exomes_non_neuro_EAS_AC
gnomAD2.1.1_exomes_non_neuro_EAS_AN
gnomAD2.1.1_exomes_non_neuro_EAS_AF
gnomAD2.1.1_exomes_non_neuro_EAS_nhomalt
gnomAD2.1.1_exomes_non_neuro_FIN_AC
gnomAD2.1.1_exomes_non_neuro_FIN_AN
gnomAD2.1.1_exomes_non_neuro_FIN_AF
gnomAD2.1.1_exomes_non_neuro_FIN_nhomalt
gnomAD2.1.1_exomes_non_neuro_NFE_AC
gnomAD2.1.1_exomes_non_neuro_NFE_AN
gnomAD2.1.1_exomes_non_neuro_NFE_AF
gnomAD2.1.1_exomes_non_neuro_NFE_nhomalt
gnomAD2.1.1_exomes_non_neuro_SAS_AC
gnomAD2.1.1_exomes_non_neuro_SAS_AN
gnomAD2.1.1_exomes_non_neuro_SAS_AF
gnomAD2.1.1_exomes_non_neuro_SAS_nhomalt
gnomAD2.1.1_exomes_non_neuro_POPMAX_AC
gnomAD2.1.1_exomes_non_neuro_POPMAX_AN
gnomAD2.1.1_exomes_non_neuro_POPMAX_AF
gnomAD2.1.1_exomes_non_neuro_POPMAX_nhomalt
gnomAD2.1.1_exomes_non_cancer_AFR_AC
gnomAD2.1.1_exomes_non_cancer_AFR_AN
gnomAD2.1.1_exomes_non_cancer_AFR_AF
gnomAD2.1.1_exomes_non_cancer_AFR_nhomalt
gnomAD2.1.1_exomes_non_cancer_AMR_AC
gnomAD2.1.1_exomes_non_cancer_AMR_AN
gnomAD2.1.1_exomes_non_cancer_AMR_AF
gnomAD2.1.1_exomes_non_cancer_AMR_nhomalt
gnomAD2.1.1_exomes_non_cancer_ASJ_AC
gnomAD2.1.1_exomes_non_cancer_ASJ_AN
gnomAD2.1.1_exomes_non_cancer_ASJ_AF
gnomAD2.1.1_exomes_non_cancer_ASJ_nhomalt
gnomAD2.1.1_exomes_non_cancer_EAS_AC
gnomAD2.1.1_exomes_non_cancer_EAS_AN
gnomAD2.1.1_exomes_non_cancer_EAS_AF
gnomAD2.1.1_exomes_non_cancer_EAS_nhomalt
gnomAD2.1.1_exomes_non_cancer_FIN_AC
gnomAD2.1.1_exomes_non_cancer_FIN_AN
gnomAD2.1.1_exomes_non_cancer_FIN_AF
gnomAD2.1.1_exomes_non_cancer_FIN_nhomalt
gnomAD2.1.1_exomes_non_cancer_NFE_AC
gnomAD2.1.1_exomes_non_cancer_NFE_AN
gnomAD2.1.1_exomes_non_cancer_NFE_AF
gnomAD2.1.1_exomes_non_cancer_NFE_nhomalt
gnomAD2.1.1_exomes_non_cancer_SAS_AC
gnomAD2.1.1_exomes_non_cancer_SAS_AN
gnomAD2.1.1_exomes_non_cancer_SAS_AF
gnomAD2.1.1_exomes_non_cancer_SAS_nhomalt
gnomAD2.1.1_exomes_non_cancer_POPMAX_AC
gnomAD2.1.1_exomes_non_cancer_POPMAX_AN
gnomAD2.1.1_exomes_non_cancer_POPMAX_AF
gnomAD2.1.1_exomes_non_cancer_POPMAX_nhomalt
gnomAD4.1_joint_flag
gnomAD4.1_joint_AC
gnomAD4.1_joint_AN
gnomAD4.1_joint_AF
gnomAD4.1_joint_nhomalt
gnomAD4.1_joint_POPMAX_AC
gnomAD4.1_joint_POPMAX_AN
gnomAD4.1_joint_POPMAX_AF
gnomAD4.1_joint_POPMAX_nhomalt
gnomAD4.1_joint_AFR_AC
gnomAD4.1_joint_AFR_AN
gnomAD4.1_joint_AFR_AF
gnomAD4.1_joint_AFR_nhomalt
gnomAD4.1_joint_AMI_AC
gnomAD4.1_joint_AMI_AN
gnomAD4.1_joint_AMI_AF
gnomAD4.1_joint_AMI_nhomalt
gnomAD4.1_joint_AMR_AC
gnomAD4.1_joint_AMR_AN
gnomAD4.1_joint_AMR_AF
gnomAD4.1_joint_AMR_nhomalt
gnomAD4.1_joint_ASJ_AC
gnomAD4.1_joint_ASJ_AN
gnomAD4.1_joint_ASJ_AF
gnomAD4.1_joint_ASJ_nhomalt
gnomAD4.1_joint_EAS_AC
gnomAD4.1_joint_EAS_AN
gnomAD4.1_joint_EAS_AF
gnomAD4.1_joint_EAS_nhomalt
gnomAD4.1_joint_FIN_AC
gnomAD4.1_joint_FIN_AN
gnomAD4.1_joint_FIN_AF
gnomAD4.1_joint_FIN_nhomalt
gnomAD4.1_joint_MID_AC
gnomAD4.1_joint_MID_AN
gnomAD4.1_joint_MID_AF
gnomAD4.1_joint_MID_nhomalt
gnomAD4.1_joint_NFE_AC
gnomAD4.1_joint_NFE_AN
gnomAD4.1_joint_NFE_AF
gnomAD4.1_joint_NFE_nhomalt
gnomAD4.1_joint_SAS_AC
gnomAD4.1_joint_SAS_AN
gnomAD4.1_joint_SAS_AF
gnomAD4.1_joint_SAS_nhomalt
ALFA_European_AC
ALFA_European_AN
ALFA_European_AF
ALFA_African_Others_AC
ALFA_African_Others_AN
ALFA_African_Others_AF
ALFA_East_Asian_AC
ALFA_East_Asian_AN
ALFA_East_Asian_AF
ALFA_African_American_AC
ALFA_African_American_AN
ALFA_African_American_AF
ALFA_Latin_American_1_AC
ALFA_Latin_American_1_AN
ALFA_Latin_American_1_AF
ALFA_Latin_American_2_AC
ALFA_Latin_American_2_AN
ALFA_Latin_American_2_AF
ALFA_Other_Asian_AC
ALFA_Other_Asian_AN
ALFA_Other_Asian_AF
ALFA_South_Asian_AC
ALFA_South_Asian_AN
ALFA_South_Asian_AF
ALFA_Other_AC
ALFA_Other_AN
ALFA_Other_AF
ALFA_African_AC
ALFA_African_AN
ALFA_African_AF
ALFA_Asian_AC
ALFA_Asian_AN
ALFA_Asian_AF
ALFA_Total_AC
ALFA_Total_AN
ALFA_Total_AF
clinvar_trait
clinvar_review
clinvar_hgvs
clinvar_var_source
clinvar_MedGen_id
clinvar_OMIM_id
clinvar_Orphanet_id
Interpro_domain
aaref_3
aaalt_3
plddt
rsa
g2p_00000001-d-2 avg
g2p_00000001-d-2 outliers⁺⁺
g2p_00000003-a-2 avg
g2p_00000003-a-2 outliers⁺⁺
g2p_00000003-b-2 avg
g2p_00000003-b-2 outliers⁺⁺
g2p_00000005-a-1 avg
g2p_00000005-a-1 outliers⁺⁺
g2p_00000005-a-2 avg
g2p_00000005-a-2 outliers⁺⁺
g2p_00000005-a-3 avg
g2p_00000005-a-3 outliers⁺⁺
g2p_00000005-a-4 avg
g2p_00000005-a-4 outliers⁺⁺
g2p_00000013-a-1 avg
g2p_00000013-a-1 outliers⁺⁺
g2p_00000013-b-1 avg
g2p_00000013-b-1 outliers⁺⁺
g2p_00000036-a-1 avg
g2p_00000036-a-1 outliers⁺⁺
g2p_00000036-a-2 avg
g2p_00000036-a-2 outliers⁺⁺
g2p_00000045-a-1 avg
g2p_00000045-a-1 outliers⁺⁺
g2p_00000045-b-1 avg
g2p_00000045-b-1 outliers⁺⁺
g2p_00000045-c-1 avg
g2p_00000045-c-1 outliers⁺⁺
g2p_00000045-d-1 avg
g2p_00000045-d-1 outliers⁺⁺
g2p_00000045-e-1 avg
g2p_00000045-e-1 outliers⁺⁺
g2p_00000045-f-1 avg
g2p_00000045-f-1 outliers⁺⁺
g2p_00000045-g-1 avg
g2p_00000045-g-1 outliers⁺⁺
g2p_00000045-h-1 avg
g2p_00000045-h-1 outliers⁺⁺
g2p_00000045-i-1 avg
g2p_00000045-i-1 outliers⁺⁺
g2p_00000045-j-1 avg
g2p_00000045-j-1 outliers⁺⁺
g2p_00000045-k-1 avg
g2p_00000045-k-1 outliers⁺⁺
g2p_00000045-l-1 avg
g2p_00000045-l-1 outliers⁺⁺
g2p_00000050-a-1 avg
g2p_00000050-a-1 outliers⁺⁺
g2p_00000051-c-1 avg
g2p_00000051-c-1 outliers⁺⁺
g2p_00000057-a-1 avg
g2p_00000057-a-1 outliers⁺⁺
g2p_00000057-b-1 avg
g2p_00000057-b-1 outliers⁺⁺
g2p_00000057-c-1 avg
g2p_00000057-c-1 outliers⁺⁺
g2p_00000057-d-1 avg
g2p_00000057-d-1 outliers⁺⁺
g2p_00000059-a-1 avg
g2p_00000059-a-1 outliers⁺⁺
g2p_00000060-a-1 avg
g2p_00000060-a-1 outliers⁺⁺
g2p_00000060-a-2 avg
g2p_00000060-a-2 outliers⁺⁺
g2p_00000061-a-1 avg
g2p_00000061-a-1 outliers⁺⁺
g2p_00000061-b-1 avg
g2p_00000061-b-1 outliers⁺⁺
g2p_00000061-c-1 avg
g2p_00000061-c-1 outliers⁺⁺
g2p_00000061-d-1 avg
g2p_00000061-d-1 outliers⁺⁺
g2p_00000061-e-1 avg
g2p_00000061-e-1 outliers⁺⁺
g2p_00000061-f-1 avg
g2p_00000061-f-1 outliers⁺⁺
g2p_00000061-g-1 avg
g2p_00000061-g-1 outliers⁺⁺
g2p_00000061-h-1 avg
g2p_00000061-h-1 outliers⁺⁺
g2p_00000061-i-1 avg
g2p_00000061-i-1 outliers⁺⁺
g2p_00000066-a-1 avg
g2p_00000066-a-1 outliers⁺⁺
g2p_00000067-a-1 avg
g2p_00000067-a-1 outliers⁺⁺
g2p_00000068-a-1 avg
g2p_00000068-a-1 outliers⁺⁺
g2p_00000068-b-1 avg
g2p_00000068-b-1 outliers⁺⁺
g2p_00000068-c-1 avg
g2p_00000068-c-1 outliers⁺⁺
g2p_00000081-a-1 avg
g2p_00000081-a-1 outliers⁺⁺
g2p_00000081-a-2 avg
g2p_00000081-a-2 outliers⁺⁺
g2p_00000091-a-1 avg
g2p_00000091-a-1 outliers⁺⁺
g2p_00000094-a-14 avg
g2p_00000094-a-14 outliers⁺⁺
g2p_00000094-a-15 avg
g2p_00000094-a-15 outliers⁺⁺
g2p_00000095-a-1 avg
g2p_00000095-a-1 outliers⁺⁺
g2p_00000095-b-1 avg
g2p_00000095-b-1 outliers⁺⁺
g2p_00000096-a-1 avg
g2p_00000096-a-1 outliers⁺⁺
g2p_00000096-b-1 avg
g2p_00000096-b-1 outliers⁺⁺
g2p_00000097-a-1 avg
g2p_00000097-a-1 outliers⁺⁺
g2p_00000097-b-1 avg
g2p_00000097-b-1 outliers⁺⁺
g2p_00000097-c-1 avg
g2p_00000097-c-1 outliers⁺⁺
g2p_00000097-d-1 avg
g2p_00000097-d-1 outliers⁺⁺
g2p_00000097-e-1 avg
g2p_00000097-e-1 outliers⁺⁺
g2p_00000097-f-1 avg
g2p_00000097-f-1 outliers⁺⁺
g2p_00000097-g-1 avg
g2p_00000097-g-1 outliers⁺⁺
g2p_00000097-h-1 avg
g2p_00000097-h-1 outliers⁺⁺
g2p_00000097-i-1 avg
g2p_00000097-i-1 outliers⁺⁺
g2p_00000097-j-1 avg
g2p_00000097-j-1 outliers⁺⁺
g2p_00000097-k-1 avg
g2p_00000097-k-1 outliers⁺⁺
g2p_00000097-l-1 avg
g2p_00000097-l-1 outliers⁺⁺
g2p_00000097-m-1 avg
g2p_00000097-m-1 outliers⁺⁺
g2p_00000097-n-1 avg
g2p_00000097-n-1 outliers⁺⁺
g2p_00000097-o-1 avg
g2p_00000097-o-1 outliers⁺⁺
g2p_00000097-p-1 avg
g2p_00000097-p-1 outliers⁺⁺
g2p_00000097-q-1 avg
g2p_00000097-q-1 outliers⁺⁺
g2p_00000097-r-1 avg
g2p_00000097-r-1 outliers⁺⁺
g2p_00000097-s-1 avg
g2p_00000097-s-1 outliers⁺⁺
g2p_00000097-t-1 avg
g2p_00000097-t-1 outliers⁺⁺
g2p_00000097-u-1 avg
g2p_00000097-u-1 outliers⁺⁺
g2p_00000097-v-1 avg
g2p_00000097-v-1 outliers⁺⁺
g2p_00000097-w-1 avg
g2p_00000097-w-1 outliers⁺⁺
g2p_00000097-x-1 avg
g2p_00000097-x-1 outliers⁺⁺
g2p_00000097-y-1 avg
g2p_00000097-y-1 outliers⁺⁺
g2p_00000097-z-1 avg
g2p_00000097-z-1 outliers⁺⁺
g2p_00000101-a-1 avg
g2p_00000101-a-1 outliers⁺⁺
g2p_00000102-0-1 avg
g2p_00000102-0-1 outliers⁺⁺
g2p_00000107-a-1 avg
g2p_00000107-a-1 outliers⁺⁺
g2p_00000107-b-1 avg
g2p_00000107-b-1 outliers⁺⁺
g2p_00000108-a-1 avg
g2p_00000108-a-1 outliers⁺⁺
g2p_00000108-a-2 avg
g2p_00000108-a-2 outliers⁺⁺
g2p_00000108-a-3 avg
g2p_00000108-a-3 outliers⁺⁺
g2p_00000112-a-1 avg
g2p_00000112-a-1 outliers⁺⁺
g2p_00000114-a-1 avg
g2p_00000114-a-1 outliers⁺⁺
g2p_00000115-a-1 avg
g2p_00000115-a-1 outliers⁺⁺
g2p_00000115-a-10 avg
g2p_00000115-a-10 outliers⁺⁺
g2p_00000115-a-11 avg
g2p_00000115-a-11 outliers⁺⁺
g2p_00000115-a-12 avg
g2p_00000115-a-12 outliers⁺⁺
g2p_00000115-a-13 avg
g2p_00000115-a-13 outliers⁺⁺
g2p_00000115-a-14 avg
g2p_00000115-a-14 outliers⁺⁺
g2p_00000115-a-15 avg
g2p_00000115-a-15 outliers⁺⁺
g2p_00000115-a-16 avg
g2p_00000115-a-16 outliers⁺⁺
g2p_00000115-a-17 avg
g2p_00000115-a-17 outliers⁺⁺
g2p_00000115-a-18 avg
g2p_00000115-a-18 outliers⁺⁺
g2p_00000115-a-19 avg
g2p_00000115-a-19 outliers⁺⁺
g2p_00000115-a-2 avg
g2p_00000115-a-2 outliers⁺⁺
g2p_00000115-a-20 avg
g2p_00000115-a-20 outliers⁺⁺
g2p_00000115-a-21 avg
g2p_00000115-a-21 outliers⁺⁺
g2p_00000115-a-22 avg
g2p_00000115-a-22 outliers⁺⁺
g2p_00000115-a-23 avg
g2p_00000115-a-23 outliers⁺⁺
g2p_00000115-a-24 avg
g2p_00000115-a-24 outliers⁺⁺
g2p_00000115-a-25 avg
g2p_00000115-a-25 outliers⁺⁺
g2p_00000115-a-26 avg
g2p_00000115-a-26 outliers⁺⁺
g2p_00000115-a-27 avg
g2p_00000115-a-27 outliers⁺⁺
g2p_00000115-a-28 avg
g2p_00000115-a-28 outliers⁺⁺
g2p_00000115-a-3 avg
g2p_00000115-a-3 outliers⁺⁺
g2p_00000115-a-4 avg
g2p_00000115-a-4 outliers⁺⁺
g2p_00000115-a-5 avg
g2p_00000115-a-5 outliers⁺⁺
g2p_00000115-a-6 avg
g2p_00000115-a-6 outliers⁺⁺
g2p_00000115-a-7 avg
g2p_00000115-a-7 outliers⁺⁺
g2p_00000115-a-8 avg
g2p_00000115-a-8 outliers⁺⁺
g2p_00000115-a-9 avg
g2p_00000115-a-9 outliers⁺⁺
g2p_00000657-a-1 avg
g2p_00000657-a-1 outliers⁺⁺
g2p_00000657-a-2 avg
g2p_00000657-a-2 outliers⁺⁺
g2p_00000659-a-1 avg
g2p_00000659-a-1 outliers⁺⁺
g2p_00000664-a-1 avg
g2p_00000664-a-1 outliers⁺⁺
g2p_00000664-a-2 avg
g2p_00000664-a-2 outliers⁺⁺
g2p_00000664-a-3 avg
g2p_00000664-a-3 outliers⁺⁺
g2p_00000664-a-4 avg
g2p_00000664-a-4 outliers⁺⁺
g2p_00000664-a-6 avg
g2p_00000664-a-6 outliers⁺⁺
g2p_00000674-a-1 avg
g2p_00000674-a-1 outliers⁺⁺
g2p_00000674-a-2 avg
g2p_00000674-a-2 outliers⁺⁺
g2p_00000674-a-3 avg
g2p_00000674-a-3 outliers⁺⁺
g2p_00000674-a-4 avg
g2p_00000674-a-4 outliers⁺⁺
g2p_00000685-a-1 avg
g2p_00000685-a-1 outliers⁺⁺
g2p_00000686-a-1 avg
g2p_00000686-a-1 outliers⁺⁺
g2p_00000691-a-1 avg
g2p_00000691-a-1 outliers⁺⁺
g2p_00000697-a-1 avg
g2p_00000697-a-1 outliers⁺⁺
g2p_00000703-a-1 avg
g2p_00000703-a-1 outliers⁺⁺
g2p_00000706-a-1 avg
g2p_00000706-a-1 outliers⁺⁺
g2p_00000708-a-1 avg
g2p_00000708-a-1 outliers⁺⁺
g2p_00000710-a-1 avg
g2p_00000710-a-1 outliers⁺⁺
g2p_00000715-a-1 avg
g2p_00000715-a-1 outliers⁺⁺
g2p_00000736-a-1 avg
g2p_00000736-a-1 outliers⁺⁺
g2p_00000738-a-1 avg
g2p_00000738-a-1 outliers⁺⁺
g2p_00000739-a-1 avg
g2p_00000739-a-1 outliers⁺⁺
g2p_00000745-a-1 avg
g2p_00000745-a-1 outliers⁺⁺
g2p_00000746-a-1 avg
g2p_00000746-a-1 outliers⁺⁺
g2p_00000747-a-1 avg
g2p_00000747-a-1 outliers⁺⁺
g2p_00000748-a-1 avg
g2p_00000748-a-1 outliers⁺⁺
g2p_00000764-a-1 avg
g2p_00000764-a-1 outliers⁺⁺
g2p_00000780-a-1 avg
g2p_00000780-a-1 outliers⁺⁺
g2p_00000787-a-1 avg
g2p_00000787-a-1 outliers⁺⁺
g2p_00000803-a-1 avg
g2p_00000803-a-1 outliers⁺⁺
g2p_00000809-a-1 avg
g2p_00000809-a-1 outliers⁺⁺
g2p_00000810-a-1 avg
g2p_00000810-a-1 outliers⁺⁺
g2p_00000847-a-1 avg
g2p_00000847-a-1 outliers⁺⁺
g2p_00000858-a-1 avg
g2p_00000858-a-1 outliers⁺⁺
g2p_00000875-a-1 avg
g2p_00000875-a-1 outliers⁺⁺
g2p_00000878-a-1 avg
g2p_00000878-a-1 outliers⁺⁺
g2p_00000895-a-1 avg
g2p_00000895-a-1 outliers⁺⁺
g2p_00000899-a-1 avg
g2p_00000899-a-1 outliers⁺⁺
g2p_00000910-a-1 avg
g2p_00000910-a-1 outliers⁺⁺
g2p_00000911-a-1 avg
g2p_00000911-a-1 outliers⁺⁺
g2p_00000925-a-1 avg
g2p_00000925-a-1 outliers⁺⁺
g2p_00000926-a-1 avg
g2p_00000926-a-1 outliers⁺⁺
g2p_00000927-a-1 avg
g2p_00000927-a-1 outliers⁺⁺
g2p_00000928-a-1 avg
g2p_00000928-a-1 outliers⁺⁺
g2p_00000939-a-1 avg
g2p_00000939-a-1 outliers⁺⁺
g2p_00000940-a-1 avg
g2p_00000940-a-1 outliers⁺⁺
g2p_00000942-a-1 avg
g2p_00000942-a-1 outliers⁺⁺
g2p_00000959-a-1 avg
g2p_00000959-a-1 outliers⁺⁺
g2p_00000963-a-1 avg
g2p_00000963-a-1 outliers⁺⁺
g2p_00000966-a-1 avg
g2p_00000966-a-1 outliers⁺⁺
g2p_00000978-a-1 avg
g2p_00000978-a-1 outliers⁺⁺
g2p_00000990-a-1 avg
g2p_00000990-a-1 outliers⁺⁺
g2p_00000998-a-1 avg
g2p_00000998-a-1 outliers⁺⁺
g2p_00001002-a-1 avg
g2p_00001002-a-1 outliers⁺⁺
g2p_00001003-a-1 avg
g2p_00001003-a-1 outliers⁺⁺
g2p_00001007-a-1 avg
g2p_00001007-a-1 outliers⁺⁺
g2p_00001032-a-1 avg
g2p_00001032-a-1 outliers⁺⁺
g2p_00001033-a-1 avg
g2p_00001033-a-1 outliers⁺⁺
g2p_00001034-a-1 avg
g2p_00001034-a-1 outliers⁺⁺
g2p_00001050-a-1 avg
g2p_00001050-a-1 outliers⁺⁺
g2p_00001051-a-1 avg
g2p_00001051-a-1 outliers⁺⁺
g2p_00001053-a-1 avg
g2p_00001053-a-1 outliers⁺⁺
g2p_00001056-a-1 avg
g2p_00001056-a-1 outliers⁺⁺
g2p_00001062-a-1 avg
g2p_00001062-a-1 outliers⁺⁺
g2p_00001065-a-1 avg
g2p_00001065-a-1 outliers⁺⁺
g2p_00001077-a-1 avg
g2p_00001077-a-1 outliers⁺⁺
g2p_00001078-a-1 avg
g2p_00001078-a-1 outliers⁺⁺
g2p_00001082-a-1 avg
g2p_00001082-a-1 outliers⁺⁺
g2p_00001084-a-1 avg
g2p_00001084-a-1 outliers⁺⁺
g2p_00001087-a-1 avg
g2p_00001087-a-1 outliers⁺⁺
g2p_00001090-a-1 avg
g2p_00001090-a-1 outliers⁺⁺
g2p_00001102-a-1 avg

In [228]:
# Merge 1% dataset onto merged_df, with 1% Edgotype_class taking priority

# Add Edgotype_source to oneperc_df so it merges cleanly
oneperc_df['Edgotype_source'] = '1pct'

# Select relevant columns from oneperc_df
oneperc_cols = oneperc_df.columns.tolist()
# Identify columns that would conflict (already in merged_df)
shared_cols = [c for c in oneperc_cols if c in merged_df.columns]
additional_cols = ['clinvar_clnsig_clean',
    'dualipa_score',
    'dualipa_abun_change',
    'dualipa_abun_chg_dir',
    'dualipa_hit',
    'ppi_num_edges',
    'ppi_score',
    'ppi_hit',
    'Edgotype_class',
    'img_U2OS_cc_t_stat',
    'img_U2OS_cc_t_pval',
    'img_U2OS_cc_t_adj_pval',
    'img_U2OS_prot_abun_t_stat',
    'img_U2OS_prot_abun_t_pval',
    'img_U2OS_prot_abun_t_adj_pval',
    'img_Metadata_Bio_Batch',
    'imaging_score',
    'img_misloc_score',
    'img_pheno_hit',
    'img_misloc_hit',
    'img_pheno_hit_strict',
    'imaging_hit',
    'Edgotype_source'] # we want to keep those columns from oneperc_df

shared_cols = shared_cols + additional_cols
shared_cols = list(set(shared_cols))  # remove duplicates

print(f"Shared columns (will get _1pct suffix): {shared_cols}")

# Merge
full_df = merged_df.merge(
    oneperc_df[shared_cols],
    on='gene_variant',
    how='outer',
    suffixes=('_literature', '_1pct')
)

# Fill gene_symbol and aa_change for variants only in oneperc
full_df['gene_symbol'] = full_df['gene_symbol'].fillna(full_df['gene_variant'].str.rsplit('_', n=1).str[0])
full_df['aa_change_literature'] = full_df['aa_change_literature'].fillna(full_df['gene_variant'].str.rsplit('_', n=1).str[1])

# Priority: use 1% Edgotype_class if available, otherwise keep literature
full_df['Edgotype_class'] = full_df['Edgotype_class_1pct'].fillna(full_df['Edgotype_class_literature'])

# Update Edgotype_source: '1pct' if from 1%, otherwise keep literature source
full_df['Edgotype_source'] = np.where(
    full_df['Edgotype_class_1pct'].notna(),
    '1pct',
    full_df['Edgotype_source_literature']
)

# For variants that had both, note which were overwritten
overwritten = full_df[
    full_df['Edgotype_class_1pct'].notna() & 
    full_df['Edgotype_class_literature'].notna()
].copy()
print(f"\nVariants where 1% overwrote literature Edgotype_class: {len(overwritten)}")
if len(overwritten) > 0:
    changed = overwritten[overwritten['Edgotype_class_1pct'] != overwritten['Edgotype_class_literature']]
    same = overwritten[overwritten['Edgotype_class_1pct'] == overwritten['Edgotype_class_literature']]
    print(f"  Same classification: {len(same)}")
    print(f"  Different classification: {len(changed)}")
    if len(changed) > 0:
        print(changed[['gene_variant', 'Edgotype_class_1pct', 'Edgotype_class_literature', 'Edgotype_source_literature']].to_string(index=False))


# Build 'Source' column listing which datasets have data for each variant
oneperc_variant_set = set(oneperc_df['gene_variant'].dropna())

source_checks = {
    '1pct_PPI': 'ppi_score',
    '1pct_DualIPA': 'dualipa_score',
    '1pct_Imaging': 'imaging_score',
    'Sahni_PPI': 'Sahni_Category',
    'Sahni_Chaperone': 'Sahni_Chaperone_binding',
    'Lacoste_Imaging': 'Lacoste_Mislocalized',
    'Luck_PPI': 'Luck_pathogenecity',
    'Rolland_PPI': 'Rolland_category',
    'Fragoza_ExAC_PPI': 'Fragoza_ExAC_Mutation',
    'Fragoza_COSMIC_PPI': 'Fragoza_COSMIC_Mutation',
    'Fragoza_HGMD_PPI': 'Fragoza_HGMD_Mutation',
    'Fragoza_Abundance': 'Fragoza_Abundance_Status',
}

def get_sources(row):
    sources = []
    for dataset_name, col in source_checks.items():
        if col in full_df.columns and pd.notna(row.get(col)):
            sources.append(dataset_name)
    return '; '.join(sources) if sources else np.nan

full_df['Source'] = full_df.apply(get_sources, axis=1)

# Simplified source column: map detailed sources to dataset-level names
source_simple_map = {
    '1pct_PPI': '1pct',
    '1pct_DualIPA': '1pct',
    '1pct_Imaging': '1pct',
    'Sahni_PPI': 'Sahni',
    'Sahni_Chaperone': 'Sahni',
    'Lacoste_Imaging': 'Lacoste',
    'Luck_PPI': 'Luck',
    'Rolland_PPI': 'Rolland',
    'Fragoza_ExAC_PPI': 'Fragoza',
    'Fragoza_COSMIC_PPI': 'Fragoza',
    'Fragoza_HGMD_PPI': 'Fragoza',
    'Fragoza_Abundance': 'Fragoza',
}

def get_sources_simple(source_str):
    if pd.isna(source_str):
        return np.nan
    detailed = source_str.split('; ')
    simple = sorted(set(source_simple_map[s] for s in detailed if s in source_simple_map))
    return '; '.join(simple) if simple else np.nan

full_df['Source_Simple'] = full_df['Source'].apply(get_sources_simple)

print(f"\nSource_Simple breakdown:")
from collections import Counter
all_simple = [s for sources in full_df['Source_Simple'].dropna() for s in sources.split('; ')]
for name, count in Counter(all_simple).most_common():
    print(f"  {name}: {count}")


print(f"\nSource breakdown (individual datasets):")
from collections import Counter
all_sources = [s for sources in full_df['Source'].dropna() for s in sources.split('; ')]
for name, count in Counter(all_sources).most_common():
    print(f"  {name}: {count}")

print(f"\nVariants by number of sources:")
full_df['n_sources'] = full_df['Source'].apply(lambda x: len(x.split('; ')) if pd.notna(x) else 0)
print(full_df['n_sources'].value_counts().sort_index())


# Clean up: drop the split columns, keep unified ones
full_df.drop(columns=['Edgotype_class_1pct', 'Edgotype_class_literature', 
                       'Edgotype_source_literature', 'Edgotype_source_1pct'], inplace=True, errors='ignore')


# Rename aa_change_literature back to aa_change
if 'aa_change_1pct' in full_df.columns:
    full_df['aa_change'] = full_df['aa_change_literature'].fillna(full_df['aa_change_1pct'])
    full_df.drop(columns=['aa_change_literature', 'aa_change_1pct'], inplace=True, errors='ignore')
elif 'aa_change_literature' in full_df.columns:
    full_df.rename(columns={'aa_change_literature': 'aa_change'}, inplace=True)

print(f"\nFull merged table: {full_df.shape}")
print(f"Unique variants: {full_df.gene_variant.nunique()}")
print(f"Variants with Edgotype_class: {full_df.Edgotype_class.notna().sum()}")
print(f"\nEdgotype source breakdown:")
print(full_df.Edgotype_source.value_counts(dropna=False))
full_df

Shared columns (will get _1pct suffix): ['img_misloc_hit', 'img_U2OS_prot_abun_t_pval', 'dualipa_abun_chg_dir', 'img_U2OS_cc_t_adj_pval', 'img_U2OS_prot_abun_t_adj_pval', 'aa_change', 'img_U2OS_cc_t_stat', 'ppi_score', 'img_U2OS_cc_t_pval', 'imaging_score', 'img_pheno_hit', 'Edgotype_class', 'dualipa_hit', 'ppi_num_edges', 'imaging_hit', 'dualipa_score', 'ppi_hit', 'Edgotype_source', 'img_pheno_hit_strict', 'clinvar_clnsig_clean', 'img_misloc_score', 'gene_variant', 'img_U2OS_prot_abun_t_stat', 'img_Metadata_Bio_Batch', 'dualipa_abun_change']

Variants where 1% overwrote literature Edgotype_class: 39
  Same classification: 18
  Different classification: 21
    gene_variant Edgotype_class_1pct Edgotype_class_literature Edgotype_source_literature
  CLN6_Gly123Asp  Perturbed-degree-1                   Edgetic                       Luck
    EMD_Asp72Val             Edgetic           Quasi-wild-type                      Sahni
   EMD_Pro183Thr             Edgetic           Quasi-wild-type                      Sahni
    EMD_Ser54Phe             Edgetic           Quasi-wild-type                      Sahni
  GALE_Asp103Gly  Uncertain-degree-1        Perturbed-degree-1               Fragoza_HGMD
 HPRT1_Thr168Ile             Edgetic        Perturbed-degree-1               Fragoza_HGMD
 LITAF_Ala111Gly             Edgetic                Quasi-null                      Sahni
 LITAF_Gly112Ser     Quasi-wild-type                Quasi-null                      Sahni
   MVK_Asn301Thr  Perturbed-degree-1                   Edgetic               Fragoza_HGMD
NMNAT1_Glu257Lys     Quasi-wild-type      Unperturbed-degree-1               Fragoza_HGMD
NMNAT1_Leu153Val     Quasi-wild-type        Perturbed-degree-1               Fragoza_HGMD
 SMAD3_Arg279Lys           Uncertain      Unperturbed-degree-1               Fragoza_HGMD
 SMAD3_Arg287Trp     Quasi-wild-type      Unperturbed-degree-1               Fragoza_HGMD
 SMAD3_Glu239Lys          Quasi-null      Unperturbed-degree-1               Fragoza_HGMD
 SMAD3_Pro263Leu     Quasi-wild-type      Unperturbed-degree-1               Fragoza_HGMD
 SMAD3_Thr261Ile     Quasi-wild-type      Unperturbed-degree-1               Fragoza_HGMD
 TMEM43_Arg28Trp     Quasi-wild-type                   Edgetic                       Luck
TMEM43_Tyr371His             Edgetic           Quasi-wild-type                       Luck
   TPM1_Glu40Lys     Quasi-wild-type                   Edgetic                      Sahni
   TPM1_Val95Ala     Quasi-wild-type                   Edgetic                      Sahni
    VHL_Pro81Ser  Perturbed-degree-1      Unperturbed-degree-1               Fragoza_ExAC

Source_Simple breakdown:
  Sahni: 2462
  Lacoste: 2203
  Fragoza: 2010
  1pct: 1407
  Rolland: 115
  Luck: 20

Source breakdown (individual datasets):
  Sahni_Chaperone: 2394
  Lacoste_Imaging: 2203
  Fragoza_ExAC_PPI: 1676
  1pct_Imaging: 794
  1pct_DualIPA: 791
  Sahni_PPI: 527
  1pct_PPI: 502
  Fragoza_Abundance: 278
  Fragoza_HGMD_PPI: 204
  Fragoza_COSMIC_PPI: 162
  Rolland_PPI: 115
  Luck_PPI: 20

Variants by number of sources:
n_sources
1    4168
2    1745
3     404
4     109
5      44
6      17
7       2
8       3
Name: count, dtype: int64

Full merged table: (6492, 53)
Unique variants: 6491
Variants with Edgotype_class: 2863

Edgotype source breakdown:
Edgotype_source
NaN               3629
Fragoza_ExAC      1637
Sahni              512
1pct               402
Fragoza_COSMIC     155
Fragoza_HGMD       145
Luck                12
Name: count, dtype: int64

,gene_symbol,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,Luck_omim_ids,...,img_misloc_score,img_U2OS_prot_abun_t_stat,img_Metadata_Bio_Batch,dualipa_abun_change,Edgotype_class,Edgotype_source,Source,Source_Simple,n_sources,aa_change
0,A2M,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Lacoste_Imaging,Lacoste,1,Cys972Tyr
1,A4GALT,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Ala219Val
2,A4GALT,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Lacoste_Imaging,Lacoste,1,Ala272Val
3,A4GALT,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Cys96Tyr
4,A4GALT,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Met183Lys
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6487,ZSCAN22,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Ala321Val
6488,ZSCAN9,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Gln34Arg
6489,ZYX,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Arg489Trp
6490,ZYX,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Arg563Gln
6491,ZYX,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Unperturbed-degree-1,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,His223Leu

# Merging all clinical significance annotations into a unified column

In [229]:
# --- Unified clinical_significance for full_df ---

# Priority: 1pct clinvar > allele_col clinvar > ClinVar 2025-01 parquet > Sahni > Lacoste
# Luck/Rolland are NOT ClinVar-based, so we keep them as separate metadata but don't fold them in.

# Identify column names (may have suffixes from merges)
clinvar_1pct_col = 'clinvar_clnsig_clean_1pct' if 'clinvar_clnsig_clean_1pct' in full_df.columns else None
clinvar_allele_col = 'clinvar_clnsig_clean_literature' if 'clinvar_clnsig_clean_literature' in full_df.columns else None
clinvar_parquet_col = 'ClinVar_significance' if 'ClinVar_significance' in full_df.columns else None

# Build priority list (highest priority first)
priority_cols = []
priority_labels = []

if clinvar_1pct_col and clinvar_1pct_col in full_df.columns:
    priority_cols.append(clinvar_1pct_col)
    priority_labels.append('1pct_allele_col')

if clinvar_allele_col and clinvar_allele_col in full_df.columns:
    priority_cols.append(clinvar_allele_col)
    priority_labels.append('allele_col')

if clinvar_parquet_col and clinvar_parquet_col in full_df.columns:
    priority_cols.append(clinvar_parquet_col)
    priority_labels.append('ClinVar_2025_parquet')

# Sahni and Lacoste are older ClinVar snapshots — lowest priority fallback
if 'Sahni_clinical_significance' in full_df.columns:
    priority_cols.append('Sahni_clinical_significance')
    priority_labels.append('Sahni')

if 'Lacoste_ClinVar_class' in full_df.columns:
    priority_cols.append('Lacoste_ClinVar_class')
    priority_labels.append('Lacoste')

print("Priority order for clinical_significance:")
for i, (col, label) in enumerate(zip(priority_cols, priority_labels)):
    n_valid = full_df[col].notna().sum()
    print(f"  {i+1}. {label} ({col}): {n_valid} non-null")

# Cascade: take first non-NaN in priority order
full_df['clinvar_clinical_significance_unified'] = full_df[priority_cols].bfill(axis=1).iloc[:, 0]

# Track which source was used
def get_clinsig_source(row):
    for col, label in zip(priority_cols, priority_labels):
        if pd.notna(row.get(col)):
            return label
    return np.nan

full_df['clinvar_clinical_significance_source_unified'] = full_df.apply(get_clinsig_source, axis=1)

# --- Summary ---
print(f"\n=== Unified clinvar_clinical_significance_unified ===")
print(full_df['clinvar_clinical_significance_unified'].value_counts(dropna=False))

print(f"\n=== Source of clinvar_clinical_significance_unified ===")
print(full_df['clinvar_clinical_significance_source_unified'].value_counts(dropna=False))

# Cross-tab: significance by source
ct = pd.crosstab(
    full_df['clinvar_clinical_significance_unified'].fillna('No annotation'),
    full_df['clinvar_clinical_significance_source_unified'].fillna('None'),
    margins=True
)
print(f"\n--- Cross-tab: significance (rows) vs source (columns) ---")
print(ct.to_string())

# --- Check for conflicts between top-2 sources ---
if clinvar_1pct_col and clinvar_allele_col:
    both = full_df[full_df[clinvar_1pct_col].notna() & full_df[clinvar_allele_col].notna()]
    if len(both) > 0:
        concordant = (both[clinvar_1pct_col] == both[clinvar_allele_col]).sum()
        discordant = (both[clinvar_1pct_col] != both[clinvar_allele_col]).sum()
        print(f"\n1pct vs allele_col concordance: {concordant}/{len(both)} ({100*concordant/len(both):.1f}%)")
        if discordant > 0:
            disc = both[both[clinvar_1pct_col] != both[clinvar_allele_col]]
            print(f"  Discordant: {discordant}")
            print(pd.crosstab(disc[clinvar_1pct_col], disc[clinvar_allele_col]).to_string())

Priority order for clinical_significance:
  1. 1pct_allele_col (clinvar_clnsig_clean_1pct): 1407 non-null
  2. allele_col (clinvar_clnsig_clean_literature): 2677 non-null
  3. ClinVar_2025_parquet (ClinVar_significance): 2433 non-null
  4. Sahni (Sahni_clinical_significance): 2462 non-null
  5. Lacoste (Lacoste_ClinVar_class): 1341 non-null

=== Unified clinvar_clinical_significance_unified ===
clinvar_clinical_significance_unified
Pathogenic     1905
NaN            1729
Others          943
Benign          698
VUS             668
Conflicting     549
Name: count, dtype: int64

=== Source of clinvar_clinical_significance_unified ===
clinvar_clinical_significance_source_unified
allele_col              2426
NaN                     1729
1pct_allele_col         1407
ClinVar_2025_parquet     726
Lacoste                  204
Name: count, dtype: int64

--- Cross-tab: significance (rows) vs source (columns) ---
clinvar_clinical_significance_source_unified  1pct_allele_col  ClinVar_2025_parquet  Lacoste  None  allele_col   All
clinvar_clinical_significance_unified
Benign                                                    159                   261       17     0         261   698
Conflicting                                               238                    99        0     0         212   549
No annotation                                               0                     0        0  1729           0  1729
Others                                                    131                    23       11     0         778   943
Pathogenic                                                668                   152      136     0         949  1905
VUS                                                       211                   191       40     0         226   668
All                                                      1407                   726      204  1729        2426  6492

1pct vs allele_col concordance: 251/251 (100.0%)

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/366082364.py:42: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  full_df['clinvar_clinical_significance_unified'] = full_df[priority_cols].bfill(axis=1).iloc[:, 0]

In [230]:
for col in full_df.columns:
    if 'clinvar' in col or 'clinical' in col:
        print(col)

Sahni_clinical_significance
clinvar_clnsig_clean_literature
clinvar_clnsig_clean_1pct
clinvar_clinical_significance_unified
clinvar_clinical_significance_source_unified

In [231]:
full_df[['Sahni_clinical_significance',
'clinvar_clnsig_clean_literature','clinvar_clnsig_clean_1pct',
'clinvar_clinical_significance_unified',
'clinvar_clinical_significance_source_unified']]

,Sahni_clinical_significance,clinvar_clnsig_clean_literature,clinvar_clnsig_clean_1pct,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified
0,NaN,Benign,NaN,Benign,allele_col
1,VUS,VUS,NaN,VUS,allele_col
2,NaN,NaN,NaN,NaN,NaN
3,Others,Others,NaN,Others,allele_col
4,Others,Others,NaN,Others,allele_col
...,...,...,...,...,...
6487,NaN,NaN,NaN,NaN,NaN
6488,NaN,NaN,NaN,NaN,NaN
6489,NaN,NaN,NaN,NaN,NaN
6490,NaN,NaN,NaN,NaN,NaN
6491,NaN,NaN,NaN,NaN,NaN

# Additional checks

## Remove synonymous variants from final dataset

In [232]:
# 3. Synonymous variants (same 3-letter code at start and end)
def is_synonymous(aa_change):
    if pd.isna(aa_change):
        return False
    match = re.match(r'^([A-Z][a-z]{2})\d+([A-Z][a-z]{2})$', aa_change)
    if match:
        return match.group(1) == match.group(2)
    return False

synonymous_mask = full_df['aa_change'].apply(is_synonymous)
print(f"Synonymous variants: {synonymous_mask.sum()}")
if synonymous_mask.any():
    print(full_df.loc[synonymous_mask, ['gene_variant']].to_string(index=False))

# Remove synonymous variants from dataset
full_df = full_df[~synonymous_mask].copy()
print(f"After removing synonymous variants: {full_df.shape}, {full_df.gene_variant.nunique()} unique variants")

Synonymous variants: 41
      gene_variant
   ADIPOQ_Gly15Gly
    AKT1_Glu242Glu
     ANG_Gly110Gly
      ANG_Gly86Gly
   APBB3_Thr318Thr
     BCL10_Leu8Leu
     BTK_Val219Val
     C1QA_Gly70Gly
     C1QA_Gly92Gly
    CD22_Pro596Pro
     CFH_Ala307Ala
  CHRNA3_Tyr215Tyr
       CRP_Leu6Leu
    DRD2_Pro319Pro
      FAS_Thr58Thr
      FAS_Thr74Thr
    FCAR_Arg108Arg
    GJD2_Ser196Ser
     HRAS_His27His
   HSPB8_Thr194Thr
     IL18_Ser35Ser
    IL1B_Phe105Phe
  ISYNA1_Leu343Leu
    ITIH3_Pro36Pro
    KCNE3_Phe66Phe
    NR1H3_Ser54Ser
    NR1H3_Ser99Ser
   OLFM2_Ala226Ala
    OPTC_Phe162Phe
   PPARG_His449His
  SCARB1_Ala350Ala
SERPINA3_Leu241Leu
SERPINA3_Leu266Leu
 SLC22A12_His86His
     SPP1_Asp94Asp
   STK11_Leu183Leu
  TIMM44_Ala424Ala
   TIMP2_Ser101Ser
    TPH2_Pro312Pro
   TSSK4_Val179Val
   TSSK4_Val255Val
After removing synonymous variants: (6451, 55), 6450 unique variants

## Updated gene names

In [233]:
# Ran the full gene_symbol names into https://www.genenames.org/tools/multi-symbol-checker/

gene_check = pd.read_csv('../1_inputs/hgnc-symbol-check.csv')
gene_check

,Input,Match type,Approved symbol,Approved name,HGNC ID,Location
0,A2M,Approved symbol,A2M,alpha-2-macroglobulin,HGNC:7,12p13.31
1,A4GALT,Approved symbol,A4GALT,"alpha 1,4-galactosyltransferase (P1PK blood gr...",HGNC:18149,22q13.2
2,AAAS,Approved symbol,AAAS,aladin WD repeat nucleoporin,HGNC:13666,12q13.13
3,AANAT,Approved symbol,AANAT,aralkylamine N-acetyltransferase,HGNC:19,17q25.1
4,ABAT,Approved symbol,ABAT,4-aminobutyrate aminotransferase,HGNC:23,16p13.2
...,...,...,...,...,...,...
2044,ZNRD2,Approved symbol,ZNRD2,zinc ribbon domain containing 2,HGNC:11328,11q13.1
2045,ZSCAN16,Approved symbol,ZSCAN16,zinc finger and SCAN domain containing 16,HGNC:20813,6p22.1
2046,ZSCAN22,Approved symbol,ZSCAN22,zinc finger and SCAN domain containing 22,HGNC:4929,19q13.43
2047,ZSCAN9,Approved symbol,ZSCAN9,zinc finger and SCAN domain containing 9,HGNC:12984,6p22.1
2048,ZYX,Approved symbol,ZYX,zyxin,HGNC:13200,7q34

In [234]:
update_gene_symbol_dict = gene_check[gene_check['Match type'] == 'Previous symbol'].set_index('Input')['Approved symbol'].to_dict()
alias_dict = gene_check[gene_check['Match type'] == 'Alias symbol'].set_index('Input')['Approved symbol'].to_dict()

def update_gene_symbol(symbol):
    if pd.isna(symbol):
        return symbol
    return update_gene_symbol_dict.get(symbol, symbol)

full_df['gene_symbol_old'] = full_df['gene_symbol']
full_df['gene_symbol'] = full_df['gene_symbol'].apply(update_gene_symbol)
full_df['alias_symbol'] = full_df['gene_symbol_old'].map(alias_dict)
full_df['gene_variant'] = full_df['gene_symbol'] + '_' + full_df['aa_change']
full_df

,gene_symbol,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,Luck_omim_ids,...,Edgotype_class,Edgotype_source,Source,Source_Simple,n_sources,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,gene_symbol_old,alias_symbol
0,A2M,A2M_Cys972Tyr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Cys972Tyr,Benign,allele_col,A2M,NaN
1,A4GALT,A4GALT_Ala219Val,VUS,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Ala219Val,VUS,allele_col,A4GALT,NaN
2,A4GALT,A4GALT_Ala272Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Ala272Val,NaN,NaN,A4GALT,NaN
3,A4GALT,A4GALT_Cys96Tyr,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Cys96Tyr,Others,allele_col,A4GALT,NaN
4,A4GALT,A4GALT_Met183Lys,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Met183Lys,Others,allele_col,A4GALT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6487,ZSCAN22,ZSCAN22_Ala321Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Ala321Val,NaN,NaN,ZSCAN22,NaN
6488,ZSCAN9,ZSCAN9_Gln34Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unperturbed-degree-1,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Gln34Arg,NaN,NaN,ZSCAN9,NaN
6489,ZYX,ZYX_Arg489Trp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Arg489Trp,NaN,NaN,ZYX,NaN
6490,ZYX,ZYX_Arg563Gln,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Quasi-wild-type,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,Arg563Gln,NaN,NaN,ZYX,NaN
6491,ZYX,ZYX_His223Leu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unperturbed-degree-1,Fragoza_ExAC,Fragoza_ExAC_PPI,Fragoza,1,His223Leu,NaN,NaN,ZYX,NaN

In [235]:
# Some variants became duplicated after gene symbol update (e.g. because they were in a gene that got merged into another). Check for duplicates and merge them together.
duplicates = full_df[full_df.duplicated('gene_variant', keep=False)].copy()
print(f"Variants that became duplicated after gene symbol update: {len(duplicates)}")
if len(duplicates) > 0:
    print(duplicates[['gene_variant', 'gene_symbol_old', 'gene_symbol', 'alias_symbol', 'Source']].to_string(index=False))
    
    # For each duplicated gene_variant, merge rows by coalescing columns (first non-NaN)
    # and concatenating Source fields
    def merge_duplicate_rows(group):
        if len(group) == 1:
            return group.iloc[0]
        
        merged_row = {}
        for col in group.columns:
            if col == 'Source':
                # Combine all sources, deduplicate
                all_sources = []
                for val in group[col].dropna():
                    all_sources.extend(val.split('; '))
                unique_sources = list(dict.fromkeys(all_sources))  # preserve order, deduplicate
                merged_row[col] = '; '.join(unique_sources) if unique_sources else np.nan
            elif col == 'Source_Simple':
                # Combine all simple sources, deduplicate
                all_sources = []
                for val in group[col].dropna():
                    all_sources.extend(val.split('; '))
                unique_sources = sorted(set(all_sources))
                merged_row[col] = '; '.join(unique_sources) if unique_sources else np.nan
            elif col == 'n_sources':
                # Will recalculate after
                merged_row[col] = np.nan
            elif col == 'gene_symbol_old':
                # Keep all old symbols for traceability
                old_symbols = group[col].dropna().unique()
                merged_row[col] = '; '.join(old_symbols) if len(old_symbols) > 0 else np.nan
            elif col == 'alias_symbol':
                # Keep all alias symbols
                aliases = group[col].dropna().unique()
                merged_row[col] = '; '.join(aliases) if len(aliases) > 0 else np.nan
            else:
                # Coalesce: take first non-NaN value
                non_null = group[col].dropna()
                merged_row[col] = non_null.iloc[0] if len(non_null) > 0 else np.nan
        
        return pd.Series(merged_row)
    
    # Merge duplicate rows
    merged_duplicates = duplicates.groupby('gene_variant', sort=False).apply(merge_duplicate_rows).reset_index(drop=True)
    
    # Recalculate n_sources
    merged_duplicates['n_sources'] = merged_duplicates['Source'].apply(
        lambda x: len(x.split('; ')) if pd.notna(x) else 0
    )
    
    print(f"\nAfter merging duplicates: {len(merged_duplicates)} unique variants")
    print(merged_duplicates[['gene_variant', 'gene_symbol_old', 'gene_symbol', 'alias_symbol', 'Source']].to_string(index=False))
    
    # Remove all duplicate rows from full_df and add back the merged ones
    full_df_no_dups = full_df.drop_duplicates('gene_variant', keep=False)
    full_df = pd.concat([full_df_no_dups, merged_duplicates], ignore_index=True)
    
    # Recalculate n_sources for consistency
    full_df['n_sources'] = full_df['Source'].apply(
        lambda x: len(x.split('; ')) if pd.notna(x) else 0
    )
    
    print(f"\nFinal dataset after merging duplicates: {full_df.shape}, unique variants: {full_df.gene_variant.nunique()}")

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1679254819.py:48: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  merged_duplicates = duplicates.groupby('gene_variant', sort=False).apply(merge_duplicate_rows).reset_index(drop=True)

Variants that became duplicated after gene symbol update: 40
     gene_variant gene_symbol_old gene_symbol alias_symbol          Source
   ARSL_Gly245Arg            ARSE        ARSL          NaN Lacoste_Imaging
   ARSL_Gly317Arg            ARSE        ARSL          NaN Lacoste_Imaging
   ARSL_Pro578Ser            ARSE        ARSL          NaN Lacoste_Imaging
   ARSL_Gly245Arg            ARSL        ARSL          NaN Sahni_Chaperone
   ARSL_Gly317Arg            ARSL        ARSL          NaN Sahni_Chaperone
   ARSL_Pro578Ser            ARSL        ARSL          NaN Sahni_Chaperone
  CILK1_Arg272Gln           CILK1       CILK1          NaN Sahni_Chaperone
   UTP4_Arg565Trp          CIRH1A        UTP4          NaN Lacoste_Imaging
 CRIPTO_Pro125Leu          CRIPTO      CRIPTO          NaN Sahni_Chaperone
 CRIPTO_Val110Leu          CRIPTO      CRIPTO          NaN Sahni_Chaperone
   PJVK_Arg265Cys          DFNB59        PJVK          NaN Lacoste_Imaging
   PJVK_Gly292Arg          DFNB59        PJVK          NaN Lacoste_Imaging
   EGFR_Leu858Arg            EGFR        EGFR          NaN Lacoste_Imaging
   EGFR_Leu858Arg            EGFR        EGFR          NaN Lacoste_Imaging
   G6PC1_Arg83Cys           G6PC1       G6PC1          NaN Sahni_Chaperone
  G6PC1_Gly222Arg           G6PC1       G6PC1          NaN Sahni_Chaperone
  G6PC1_Pro113Leu           G6PC1       G6PC1          NaN Sahni_Chaperone
  G6PC1_Val338Phe           G6PC1       G6PC1          NaN Sahni_Chaperone
   G6PC1_Arg83Cys            G6PC       G6PC1          NaN Lacoste_Imaging
  G6PC1_Gly222Arg            G6PC       G6PC1          NaN Lacoste_Imaging
  G6PC1_Pro113Leu            G6PC       G6PC1          NaN Lacoste_Imaging
  G6PC1_Val338Phe            G6PC       G6PC1          NaN Lacoste_Imaging
  CILK1_Arg272Gln             ICK       CILK1          NaN Lacoste_Imaging
NECTIN1_Ser112Thr         NECTIN1     NECTIN1          NaN Sahni_Chaperone
NECTIN1_Thr131Ala         NECTIN1     NECTIN1          NaN Sahni_Chaperone
 NHERF1_Arg153Gln          NHERF1      NHERF1          NaN Sahni_Chaperone
 NHERF1_Leu110Val          NHERF1      NHERF1          NaN Sahni_Chaperone
   PJVK_Arg265Cys            PJVK        PJVK          NaN Sahni_Chaperone
   PJVK_Gly292Arg            PJVK        PJVK          NaN Sahni_Chaperone
NECTIN1_Ser112Thr           PVRL1     NECTIN1          NaN Lacoste_Imaging
NECTIN1_Thr131Ala           PVRL1     NECTIN1          NaN Lacoste_Imaging
 NHERF1_Arg153Gln        SLC9A3R1      NHERF1          NaN Lacoste_Imaging
 NHERF1_Leu110Val        SLC9A3R1      NHERF1          NaN Lacoste_Imaging
 CRIPTO_Pro125Leu           TDGF1      CRIPTO          NaN Lacoste_Imaging
 CRIPTO_Val110Leu           TDGF1      CRIPTO          NaN Lacoste_Imaging
   UTP4_Arg565Trp            UTP4        UTP4          NaN Sahni_Chaperone
  YARS1_Glu196Lys           YARS1       YARS1          NaN Sahni_Chaperone
   YARS1_Gly41Arg           YARS1       YARS1          NaN Sahni_Chaperone
  YARS1_Glu196Lys            YARS       YARS1          NaN Lacoste_Imaging
   YARS1_Gly41Arg            YARS       YARS1          NaN Lacoste_Imaging

After merging duplicates: 20 unique variants
     gene_variant  gene_symbol_old gene_symbol  alias_symbol                           Source
   ARSL_Gly245Arg       ARSE; ARSL        ARSL           NaN Lacoste_Imaging; Sahni_Chaperone
   ARSL_Gly317Arg       ARSE; ARSL        ARSL           NaN Lacoste_Imaging; Sahni_Chaperone
   ARSL_Pro578Ser       ARSE; ARSL        ARSL           NaN Lacoste_Imaging; Sahni_Chaperone
  CILK1_Arg272Gln       CILK1; ICK       CILK1           NaN Sahni_Chaperone; Lacoste_Imaging
   UTP4_Arg565Trp     CIRH1A; UTP4        UTP4           NaN Lacoste_Imaging; Sahni_Chaperone
 CRIPTO_Pro125Leu    CRIPTO; TDGF1      CRIPTO           NaN Sahni_Chaperone; Lacoste_Imaging
 CRIPTO_Val110Leu    CRIPTO; TDGF1      CRIPTO           NaN Sahni_Chaperone; Lacoste_Imaging
   PJVK_Arg265Cys     DFNB59; PJVK        PJVK           NaN Lacoste_Imaging; Sahni_Chaperone
   PJVK_Gly292Arg     DFNB59; PJVK        PJVK           NaN Lacoste_Imaging; Sahni_Chaperone
   EGFR_Leu858Arg             EGFR        EGFR           NaN                  Lacoste_Imaging
   G6PC1_Arg83Cys      G6PC1; G6PC       G6PC1           NaN Sahni_Chaperone; Lacoste_Imaging
  G6PC1_Gly222Arg      G6PC1; G6PC       G6PC1           NaN Sahni_Chaperone; Lacoste_Imaging
  G6PC1_Pro113Leu      G6PC1; G6PC       G6PC1           NaN Sahni_Chaperone; Lacoste_Imaging
  G6PC1_Val338Phe      G6PC1; G6PC       G6PC1           NaN Sahni_Chaperone; Lacoste_Imaging
NECTIN1_Ser112Thr   NECTIN1; PVRL1     NECTIN1           NaN Sahni_Chaperone; Lacoste_Imaging
NECTIN1_Thr131Ala   NECTIN1; PVRL1     NECTIN1           NaN Sahni_Chaperone; Lacoste_Imaging
 NHERF1_Arg153Gln NHERF1; SLC9A3R1      NHERF1           NaN Sahni_Chaperone; Lacoste_Imaging
 NHERF1_Leu110Val NHERF1; SLC9A3R1      NHERF1           NaN Sahni_Chaperone; Lacoste_Imaging
  YARS1_Glu196Lys      YARS1; YARS       YARS1           NaN Sahni_Chaperone; Lacoste_Imaging
   YARS1_Gly41Arg      YARS1; YARS       YARS1           NaN Sahni_Chaperone; Lacoste_Imaging

Final dataset after merging duplicates: (6431, 57), unique variants: 6431

In [237]:
for gene_var in full_df['gene_variant'].dropna().unique():
    print(gene_var)

A2M_Cys972Tyr
A4GALT_Ala219Val
A4GALT_Ala272Val
A4GALT_Cys96Tyr
A4GALT_Met183Lys
A4GALT_Ser100Leu
AAAS_Gln15Lys
AAAS_Leu381Arg
AAAS_Leu430Phe
AAAS_Ser263Pro
AANAT_Ala129Thr
AANAT_Thr3Met
ABAT_Arg220Lys
ABCC11_Gly180Arg
ABCD1_Arg389Gly
ABCD1_Arg518Gln
ABCF3_Arg340Trp
ABCF3_Arg510His
ABCG8_Ala632Val
ABCG8_Glu423Asp
ABCG8_Pro231Thr
ABHD16A_Arg184Leu
ABHD5_Glu260Lys
ABHD5_Glu7Lys
ABHD5_His82Arg
ABHD5_Ser115Gly
ABTB1_Arg386His
ACADM_Ala27Val
ACADM_Ala52Val
ACADM_Arg181Cys
ACADM_Arg206Cys
ACADM_Lys304Glu
ACADM_Lys329Glu
ACADM_Met249Val
ACADM_Met274Val
ACADSB_Glu354Lys
ACADSB_Glu387Lys
ACADSB_Leu255Phe
ACADSB_Thr115Ile
ACADSB_Thr148Ile
ACADSB_Tyr250Cys
ACADSB_Tyr283Cys
ACADS_Arg46Trp
ACADS_Gly274Ser
ACADS_Trp177Arg
ACAT1_Ala127Val
ACAT1_Ala132Gly
ACAT2_Gly161Ser
ACAT2_Ile254Thr
ACCS_Asp59Asn
ACCS_Ser393Leu
ACD_Arg113Gln
ACD_Val518Ala
ACSF2_Ala34Val
ACSF2_Gly19Trp
ACSF3_Ala17Pro
ACSF3_Ala197Thr
ACSF3_Arg10Trp
ACSF3_Arg471Trp
ACSF3_Arg558Trp
ACSF3_Asp236Asn
ACSF3_Asp457Asn
ACSF3_Glu359Lys
ACSF3_Gly119Asp
ACSF3_Gly225Arg
ACSF3_Ile200Met
ACSF3_Lys195Arg
ACSF3_Met198Arg
ACSF3_Met266Val
ACSF3_Pro243Leu
ACSF3_Pro285Leu
ACSF3_Ser431Tyr
ACSF3_Thr358Ile
ACSM3_Lys359Asn
ACSM3_Lys367Asn
ACTA2_Arg212Gln
ACTA2_Arg292Gly
ACTA2_Arg39His
ACTA2_Asn117Thr
ACTB_Arg183Trp
ACTB_Arg196Cys
ACTB_Asn12Asp
ACTB_Glu117Lys
ACTB_Glu364Gln
ACTB_Glu364Lys
ACTB_Leu65Val
ACTB_Ser265Ala
ACTC1_Arg314His
ACTC1_His90Tyr
ACTC1_Pro166Ala
ACTC1_Ser273Phe
ACTG1_Ile122Val
ACTG1_Pro264Leu
ACTG1_Thr89Ile
ACTN2_Ala119Thr
ACTN2_Asp475Asn
ACTN2_Gln349Leu
ACTN2_Gln9Arg
ACTN2_Glu583Ala
ACTN2_Glu628Gly
ACTN2_His775Tyr
ACTN2_Met604Val
ACTN2_Thr495Met
ACTN2_Val115Met
ACTN4_Lys255Glu
ACTN4_Ser262Pro
ACTN4_Thr259Ile
ACVR1B_Asp335Asn
ACVR1B_Glu412Asp
ACVR1_Arg206His
ACVR1_Arg375Pro
ACVR1_Gln207Glu
ACVR1_Gly328Arg
ACVR1_Gly356Asp
ACVR2B_Arg40His
ACVR2B_Val494Ile
ACVRL1_Arg374Trp
ACVRL1_Arg484Gln
ACVRL1_Asp330Asn
ACVRL1_Cys344Pro
ACVRL1_Glu206Gly
ACVRL1_Glu215Lys
ACVRL1_Glu224Lys
ACVRL1_Gly48Glu
ACVRL1_Leu337Pro
ACVRL1_Lys487Thr
ACVRL1_Met376Arg
ACVRL1_Pro449Leu
ACVRL1_Val380Gly
ACY1_Ala111Val
ACY1_Arg197Gln
ACY1_Arg197Trp
ACY1_Arg353Cys
ACY1_Arg378Gln
ACY1_Arg378Trp
ACY1_Arg386Cys
ACY1_Arg393His
ACY1_Asn179Ser
ACY1_Glu233Asp
ACY1_Glu381Asp
ACY1_Trp234Arg
ACY3_Arg8Gln
ADA_Arg101Gln
ADA_Gln199Pro
ADA_Lys80Arg
ADA_Pro297Gln
ADH1C_Ile350Val
ADIPOQ_Arg112Cys
ADIPOQ_Ile164Thr
ADIPOQ_Tyr111His
ADORA3_Ile248Leu
ADRB2_Ala119Asp
ADRM1_Ala324Val
ADRM1_Ala345Thr
ADRM1_Asp53Glu
ADRM1_Gly279Glu
ADRM1_Ile327Met
ADRM1_Lys390Thr
ADRM1_Met163Val
ADRM1_Thr240Asn
AFAP1L1_Leu406Pro
AFAP1L1_Ser98Asn
AGA_Gly302Arg
AGA_Gly60Asp
AGER_Gly82Ser
AGPAT2_Ala239Val
AGPAT2_Ala240Val
AGRP_Ala67Thr
AGTR1_Cys289Trp
AGTR1_Gly45Arg
AGTR1_Phe204Ser
AGTR1_Thr282Met
AGT_Arg342Gln
AGT_Arg375Gln
AGT_Leu10Phe
AGT_Leu43Phe
AGT_Thr174Met
AGT_Thr207Met
AGT_Tyr248Cys
AGT_Tyr281Cys
AGXT_Ala186Val
AGXT_Ala210Pro
AGXT_Ala248Ser
AGXT_Ala248Val
AGXT_Ala280Val
AGXT_Ala295Thr
AGXT_Ala383Asp
AGXT_Ala85Asp
AGXT_Arg111Gln
AGXT_Arg118Cys
AGXT_Arg118His
AGXT_Arg197Gln
AGXT_Arg233Cys
AGXT_Arg233His
AGXT_Arg233Leu
AGXT_Arg289Cys
AGXT_Arg289His
AGXT_Arg301Cys
AGXT_Arg360Gln
AGXT_Arg36Cys
AGXT_Arg36His
AGXT_Arg381Lys
AGXT_Asn22Ser
AGXT_Asp129His
AGXT_Asp183Asn
AGXT_Asp201Asn
AGXT_Asp243His
AGXT_Asp341Glu
AGXT_Cys173Tyr
AGXT_Cys178Tyr
AGXT_Cys253Arg
AGXT_Gln282His
AGXT_Glu274Asp
AGXT_Glu371Lys
AGXT_Glu59Lys
AGXT_Glu95Lys
AGXT_Gly116Arg
AGXT_Gly156Arg
AGXT_Gly161Arg
AGXT_Gly161Cys
AGXT_Gly161Ser
AGXT_Gly170Arg
AGXT_Gly199Ser
AGXT_Gly216Arg
AGXT_Gly349Ser
AGXT_Gly41Arg
AGXT_Gly41Glu
AGXT_Gly41Val
AGXT_Gly42Glu
AGXT_Gly47Arg
AGXT_Gly63Arg
AGXT_Gly82Arg
AGXT_Gly82Glu
AGXT_Ile202Asn
AGXT_Ile244Thr
AGXT_Ile279Thr
AGXT_Ile340Met
AGXT_Leu101Pro
AGXT_Leu153Val
AGXT_Leu166Pro
AGXT_Leu25Arg
AGXT_Leu269Pro
AGXT_Leu26Pro
AGXT_Leu284Pro
AGXT_Leu359Pro
AGXT_Leu384Pro
AGXT_Lys12Arg
AGXT_Met195Leu
AGXT_Met49Leu
AGXT_Phe152Ile
AGXT_Pro10Ala
AGXT_Pro11Arg
AGXT_Pro11His
AGXT_Pro11Leu
AGXT_Pro319Leu
AGXT_Ser187Phe
AGXT_Ser205Leu
AGXT_Ser205Pro
AGXT_Ser218Leu
AGXT_Ser221Pro
AGXT_Ser81Leu
AGXT_Thr70Asn
AGXT_Trp108Arg
AGXT_Trp108Cys
AGXT_Val162Met
AGXT_Val326Ile
AGXT_Val336Asp
AGXT_Val8Leu
AHCY_Ala89Val
AHCY_Arg49Cys
AHCY_Asp86Gly
AHCY_Ile92Val
AHCY_Tyr143Cys
AHSG_Thr248Met
AHSG_Thr256Ser
AIPL1_Ala313Ser
AIPL1_Arg270His
AIPL1_Arg302Leu
AIPL1_Cys239Arg
AIPL1_Gly262Ser
AIPL1_His82Tyr
AIPL1_Ile206Asn
AIPL1_Met79Thr
AIPL1_Pro376Ser
AIPL1_Thr114Ile
AIPL1_Val96Ile
AK2_Arg103Trp
AK2_Arg186Cys
AK2_Asp165Gly
AK8_Arg339Cys
AK8_Thr169Lys
AK8_Val227Ile
AKAP17A_Arg298Lys
AKAP17A_Arg675Cys
AKAP9_Asp204Asn
AKAP9_Gln148Arg
AKAP9_Thr155Asn
AKR1C3_His5Gln
AKR1C4_Leu311Val
AKR1D1_Arg261Cys
AKR1D1_Leu106Phe
AKR1D1_Pro133Arg
AKR1D1_Pro198Leu
AKR7A2_Ala142Thr
AKR7A3_Pro309Leu
AKT1_Arg370Cys
AKT1_Asp44Asn
AKT1_Gln79Lys
AKT1_Glu17Lys
AKT1_Glu267Gly
AKT1_Glu49Lys
AKT1_Leu153Pro
AKT1_Leu52Arg
AKT1_Phe35Leu
AKT1_Val201Ile
AKT2_Arg274His
AKTIP_Arg33Gln
ALAS2_Ala135Thr
ALAS2_Arg133His
ALAS2_Arg374Cys
ALAS2_Arg411Gln
ALAS2_Arg415Cys
ALAS2_Arg448Gln
ALAS2_Asp122Asn
ALAS2_Asp153Val
ALAS2_Cys358Tyr
ALAS2_Gly254Ser
ALAS2_Ile252Thr
ALAS2_Ile289Thr
ALAS2_Ile439Asn
ALAS2_Ile476Asn
ALAS2_Lys262Gln
ALAS2_Phe128Leu
ALAS2_Ser531Gly
ALAS2_Thr351Ser
ALAS2_Tyr549Phe
ALDH3A2_Pro121Leu
ALDH3A2_Ser415Asn
ALDH3A2_Tyr279Asn
ALDH4A1_Ser352Leu
ALDH6A1_Gly446Arg
ALDOA_Asp128Gly
ALDOA_Asp129Gly
ALDOA_Cys338Tyr
ALDOA_Cys339Tyr
ALDOA_Glu207Lys
ALDOB_Ala150Pro
ALDOB_Ala280Asp
ALDOB_Val222Phe
ALDOC_Asn312Ser
ALG12_Arg146Gln
ALG12_Arg311Cys
ALG12_Phe142Val
ALG12_Thr67Met
ALG3_Arg266Cys
ALG3_Gly118Asp
ALG3_Ile107Val
ALG3_Met157Lys
ALG6_Ala333Val
ALG6_Arg113His
ALG6_Gly227Glu
ALG8_Asn222Ser
ALG8_Gly275Asp
ALG8_Ile439Thr
ALG8_Thr47Pro
ALKBH3_Arg213Cys
ALKBH3_Asn226Ser
ALKBH3_Gly39Cys
ALKBH4_Arg239Cys
ALK_Arg1275Gln
ALK_Cys1196Met
ALK_Gly1202Arg
ALK_Phe1174Leu
ALK_Ser1206Tyr
ALK_Thr1151Met
ALOX15_Thr560Met
ALOX5_Glu254Lys
ALPL_Ala179Thr
ALPL_Ala377Val
AMACR_Leu107Pro
AMACR_Ser52Pro
AMHR2_Arg504Cys
AMHR2_Arg54Cys
AMHR2_Asp426Gly
AMHR2_Asp491His
AMHR2_Gly142Val
AMHR2_His282Gln
AMHR2_Val458Ala
AMMECR1_Arg207Gly
AMOT_Ala556Val
AMOT_Thr899Ala
AMPD2_Glu697Asp
AMPD3_Ala329Val
AMPD3_Pro594Leu
AMPD3_Trp459Arg
AMPH_Met376Ile
AMT_Arg223His
AMT_Arg320His
AMT_Asn145Ile
AMT_Asn48Ile
AMT_Gly172Asp
AMT_Gly269Asp
AMT_Val115Ala
AMT_Val212Ala
ANGPTL3_Arg288Gln
ANGPTL3_Asp41Asn
ANGPTL3_Leu164Phe
ANGPTL3_Tyr417Cys
ANGPTL4_Glu40Lys
ANGPTL4_Gly223Arg
ANGPTL4_Gly361Ser
ANGPTL4_Gly77Arg
ANG_Gln12Leu
ANG_Gln36Leu
ANG_Lys64Ile
ANG_Pro112Leu
ANG_Pro136Leu
ANKRD1_Thr116Met
ANKRD44_Arg80Trp
ANTXR2_Tyr381Cys
ANTXR2_Tyr45Cys
ANTXR2_Val386Phe
ANTXR2_Val394Ala
ANTXR2_Val50Phe
ANTXR2_Val58Ala
ANXA10_Met62Thr
ANXA10_Met71Leu
ANXA10_Phe234Ser
ANXA11_Arg230Cys
AOAH_Asp28Asn
AP2S1_Arg15Cys
AP2S1_Arg15His
AP4B1_Leu480Ser
APBB1IP_Asp134Asn
APEH_Phe378Ser
APEX1_Gln51His
APEX1_Glu126Asp
APEX1_Gly306Ala
APEX1_Leu104Arg
APIP_Gly111Ala
APIP_Met181Val
APOA1_Ala188Ser
APOA1_Ala199Pro
APOA1_Arg197Cys
APOA1_Arg34Leu
APOA1_Glu144Asp
APOA1_Leu84Arg
APOA1_Trp74Arg
APOA1_Val180Glu
APOC3_Asp45Asn
APOC3_Asp65Asn
APOC3_Gln38Lys
APOC3_Gln58Lys
APOC3_Thr74Ala
APOC3_Thr94Ala
APOC4_Leu96Arg
APOD_Phe36Val
APOD_Phe56Val
APOD_Thr158Lys
APOD_Thr178Lys
APOH_Cys306Gly
APOH_Cys325Gly
APOH_Trp316Ser
APOH_Trp335Ser
APPL1_Glu643Gln
APPL1_Glu67Gly
APPL1_Thr590Ile
APLP2_His205Arg
APLP2_Lys70Arg
APRT_Arg67Gln
APRT_Met136Thr
APRT_Val150Phe
APRT_Val84Met
APTX_Ala110Val
APTX_His140Arg
APTX_Val175Gly
AQP1_Asn192Lys
AQP1_Gln47Arg
AQP1_Pro38Leu
AQP2_Arg187His
AQP2_Glu258Lys
AQP2_Gly64Arg
AQP2_Thr126Met
AQP4_Asp184Glu
AQP4_Ile128Thr
AQP4_Met224Thr
AQP4_Met278Thr
ARFIP2_Arg138Cys
ARFIP2_Pro77Ala
ARG1_Asp128Gly
ARG1_Gly235Arg
ARG1_Ile11Thr
ARG1_Thr290Ser
ARHGEF10_Thr88Ile
ARHGEF39_Arg230Cys
ARHGEF39_Asp204Asn
ARHGEF3_Asn432Ser
ARHGEF9_Gly55Ala
ARIH2_Glu29Asp
ARL11_Cys148Arg
ARL13B_Arg200Cys
ARL16_Gly66Asp
ARL16_Ser10Arg
ARL2BP_Glu87Lys
ARL2BP_Met45Arg
ARL2_Arg139Cys
ARL6_Gly169Ala
ARL6_Leu170Trp
ARL6_Thr31Arg
ARL6_Thr31Met
ARMC1_Met83Thr
ARSA_Asn350Ser
ARSA_Tyr201Cys
ARSL_Arg12Ser
ARSI_Pro228Leu
ARSI_Val373Met
ART4_Asn265Asp
ART4_Gly108Val
ART4_Phe62Ser
ART4_Thr117Ile
ASAH1_Arg254Gly
ASAH1_Glu138Val
ASAH1_Pro362Arg
ASH2L_Arg592Cys
ASL_Arg12Gln
ASNS_Ala277Thr
ASNS_Ala6Glu
ASPA_Glu24Gly
ASPA_Glu285Ala
ASPA_Ile143Phe
ASPA_Met195Arg
ASPSCR1_Arg214Cys
ASS1_Gly14Ser
ASS1_Lys310Gln
ASS1_Val345Gly
ATCAY_Ser301Arg
ATF2_Ser456Leu
ATF4_Ala324Val
ATF4_Glu322Asp
ATF4_Pro258Ala
ATF4_Thr137Ser
ATF6_Ala145Pro
ATF6_Pro157Ser
ATG5_Lys58Met
ATM_Cys107Tyr
ATM_Leu43Pro
ATM_Ser49Cys
ATOSB_Ala178Thr
ATP2B4_Gly293Ser
ATP2B4_Val586Met
ATP5F1B_Ser25Pro
ATP6AP2_Arg157Cys
ATP6V0A4_Arg449His
ATP6V1B1_Arg465His
ATP6V1B1_Met174Arg
ATP6V1B1_Pro346Arg
ATPAF2_Glu241Gly
ATPAF2_Trp94Arg
AVPR2_Asn55Asp
AXIN2_Val539Met
B2M_Ala6Val
B2M_Asp54Asn
B2M_Tyr30His
B3GALNT1_Glu266Ala
B3GALNT1_Gly271Arg
B3GNT3_His328Arg
B4GALT7_Ala186Asp
B4GALT7_Arg270Cys
BAAT_Ala182Ser
BAAT_Arg201Pro
BAAT_Met76Val
BAAT_Val304Ala
BABAM1_Ala120Thr
BABAM2_Val250Ile
BAG3_Arg218Trp
BAG3_Arg258Trp
BAG3_Arg477His
BAG3_Leu462Pro
BAG3_Pro380Ser
BAG5_Ile279Leu
BAG6_Ser625Pro
BAK1_Arg169Gln
BAK1_Gln73Leu
BAK1_Gln98Glu
BAK1_Glu120Val
BAK1_Leu163Val
BAK1_Thr103Met
BANF1_Ala12Thr
BANK1_Ala353Thr
BANK1_Ala383Thr
BANK1_Arg31His
BANK1_Arg61His
BANP_Ala162Val
BANP_Pro348Ser
BAP1_Arg59Pro
BAP1_Arg718Gln
BAP1_Asn290Ser
BAP1_Cys91Gly
BAP1_Cys91Ser
BAP1_Glu31Lys
BAP1_Leu49Pro
BAP1_Pro12Thr
BAP1_Ser596Gly
BAP1_Thr423Lys
BAP1_Thr93Ala
BBS10_Cys25Trp
BBS10_Cys91Trp
BBS10_Leu348Ser
BBS10_Thr623Pro
BBS10_Val174Gly
BBS12_Gly540Val
BBS12_Ile346Thr
BBS12_Pro159Leu
BBS12_Thr501Met
BBS1_Arg160Gln
BBS1_Leu518Pro
BBS1_Met390Arg
BBS5_Arg207His
BBS5_Asn184Ser
BBS5_Gly72Ser
BBS7_His323Arg
BBS7_Ser556Arg
BBS7_Thr211Ile
BCAM_Arg175Gln
BCAM_Arg77His
BCAM_Ser447Leu
BCAM_Thr539Ala
BCAR3_Ala624Val
BCAR3_Asn733Ser
BCAR3_Phe6Tyr
BCAR3_Pro404Ser
BCAS2_Asn139Ser
BCHE_Gln518Leu
BCHE_Gln546Leu
BCHE_Leu330Ile
BCHE_Leu358Ile
BCHE_Tyr128Cys
BCHE_Tyr156Cys
BCKDHB_His156Arg
BCKDHB_His206Arg
BCL10_Ala5Ser
BCL2L1_Pro48Ser
BCO1_Ala379Val
BCO1_Thr170Met
BCS1L_Arg144Gln
BCS1L_Gln302Glu
BCS1L_Pro99Leu
BDH2_Glu29Asp
BDH2_Met109Thr
BDNF_Thr2Ile
BEST1_Arg158Gly
BEST1_Arg218Gly
BEST1_Arg32Cys
BEST1_Arg92Cys
BEST1_Leu480Phe
BEST1_Leu567Phe
BEST1_Tyr25His
BEST1_Tyr85His
BEX5_Glu74Asp
BFSP2_Ala407Asp
BFSP2_Arg339His
BHMT_Arg239Gln
BHMT_Gly199Ser
BHMT_Pro197Ser
BICDL2_Glu58Lys
BIK_Asp69Glu
BIRC2_Ala506Val
BIRC2_Leu9Arg
BIRC2_Lys516Glu
BIRC2_Tyr297Cys
BIRC2_Val77Leu
BIRC7_His164Arg
BLK_Ala71Thr
BLMH_Asn66Lys
BLMH_Glu381Ala
BLMH_Glu381Lys
BLMH_Ile248Thr
BLMH_Ile443Val
BLMH_Lys244Glu
BLZF1_Gln40Arg
BLZF1_His45Arg
BMI1_Cys18Tyr
BMP15_Arg61Gln
BMP15_Arg76Cys
BMP15_Asn196Lys
BMP15_Tyr235Cys
BMP4_Gly168Ala
BMP4_Ser367Thr
BMP4_Ser91Cys
BMP4_Thr225Ala
BMP7_Arg303Cys
BMPR1B_Arg486Gln
BMPR1B_Arg486Trp
BMPR1B_Ile200Lys
BMPR2_Arg491Gln
BOLL_Met270Ile
BOLL_Ser9Tyr
BOLL_Val78Ile
BPGM_Arg62Gln
BPGM_Arg90Cys
BRAF_Ala727Val
BRAF_Asp565Glu
BRAF_Asp594Val
BRAF_Gln257Arg
BRAF_Gln262Lys
BRAF_Glu501Lys
BRAF_Glu501Val
BRAF_Glu586Lys
BRAF_Gly464Val
BRAF_Gly466Ala
BRAF_Gly466Glu
BRAF_Gly466Val
BRAF_Gly469Ala
BRAF_Gly469Glu
BRAF_Gly596Arg
BRAF_Gly596Val
BRAF_Leu245Phe
BRAF_Leu485Phe
BRAF_Lys499Asn
BRAF_Lys601Glu
BRAF_Phe468Ser
BRAF_Phe595Leu
BRAF_Thr241Arg
BRAF_Val471Phe
BRAF_Val487Gly
BRAF_Val600Glu
BRAF_Val600Gly
BRCA1_Ala102Gly
BRCA1_Arg391Met
BRCA1_Arg595Gln
BRCA1_Arg71Gly
BRCA1_Arg71Lys
BRCA1_Asn132Lys
BRCA1_Asp67Tyr
BRCA1_Cys39Arg
BRCA1_Cys44Tyr
BRCA1_Cys61Gly
BRCA1_Cys64Ser
BRCA1_Cys64Tyr
BRCA1_Glu143Lys
BRCA1_Glu455Lys
BRCA1_Glu631Lys
BRCA1_Gly602Ala
BRCA1_Gly666Val
BRCA1_His239Arg
BRCA1_His299Tyr
BRCA1_His41Arg
BRCA1_Leu460Pro
BRCA1_Leu660Pro
BRCA1_Lys502Glu
BRCA1_Met548Ile
BRCA1_Met671Lys
BRCA1_Phe558Ser
BRCA1_Phe591Leu
BRCA1_Pro510Ser
BRCA1_Pro533Leu
BRCA1_Ser408Ile
BRCA1_Ser611Arg
BRCA1_Thr37Lys
BRCA1_Thr581Ala
BRCA1_Thr581Ile
BRCA1_Thr587Arg
BRCA1_Thr669Ser
BRCA1_Tyr179Cys
BRCA1_Val275Ile
BRCA1_Val632Ala
BRIP1_Arg848His
BRIP1_Gln255His
BRIP1_His587Arg
BRIP1_Leu195Pro
BRIP1_Pro47Ala
BRIP1_Ser520Thr
BRIP1_Val76Ile
BRME1_Asn576Ser
BRME1_Gln500Arg
BRME1_Gly267Arg
BRME1_Leu155Phe
BRMS1L_Ser7Gly
BSCL2_Asp20Glu
BSG_Glu92Lys
BSND_Arg8Trp
BSND_Gly284Asp
BSND_Gly47Arg
BSND_Val43Ile
BST1_Arg125His
BTC_Cys7Gly
BTC_Pro70Ser
BTD_Ala171Thr
BTD_Glu112Gln
BTD_Leu278Val
BTD_Trp487Arg
BTG1_Asn139Ser
BTK_Arg307Thr
BTK_Cys154Ser
BTK_Ile56Thr
BTK_Leu358Phe
BTK_Lys430Glu
BTK_Met509Ile
BTK_Pro565Leu
BTK_Tyr591Ser
BTK_Val64Phe
BTRC_Arg594His
BTRC_Ile439Val
BTRC_Leu8Met
BTRC_Pro592His
BTRC_Thr414Ala
BTRC_Thr601Ser
BUB1B_Arg36Gln
BUB1B_Arg727Cys
BUB1B_Asn1004Ser
BUB1B_Asn1032His
BUB1B_Leu1012Pro
BUB1B_Leu844Phe
BUB1B_Thr40Met
BUB1B_Tyr155Cys
BUB1B_Val618Ala
BUD13_Pro148Leu
C10orf88_Gly8Arg
C12orf50_Gln306Arg
C12orf50_Trp292Arg
C12orf50_Tyr334Cys
KNSTRN_Pro26Leu
KNSTRN_Pro26Ser
C19orf48P_Leu70Phe
C1QB_Gly15Asp
C1QB_Gly217Arg
C1QB_Gly244Arg
C1QB_Gly42Asp
C1QC_Gly34Arg
C1QC_Gly6Arg
C1S_Arg119His
C1S_Gly630Glu
C1orf174_Ala81Thr
C1orf174_Arg131Cys
C1orf174_Ser82Ala
C1orf174_Val195Met
MGME1_Pro102Ser
C22orf23_Met136Leu
C2_Cys111Tyr
C2_Cys131Tyr
C2_Glu298Asp
C2_Glu318Asp
C2_Gly444Arg
C2_Gly464Arg
C2_Ser189Phe
C2_Ser209Phe
C2_Val641Ala
C3orf62_Arg66Gly
C3orf62_Asn142Asp
C3orf62_Glu110Lys
C3orf62_Met203Ile
C3orf62_Val60Met
C4orf33_His166Arg
C5AR2_Ser323Ile
C8orf33_Gly25Arg
C9_Cys119Gly
C9_Cys528Tyr
CA1_Arg246His
CA1_Arg247His
CA1_His68Arg
CA4_Arg14Trp
CA4_Arg219Ser
CA4_Arg69His
CA8_Ser100Pro
CABP4_Arg124Cys
CABP4_Arg19Cys
CABP5_Arg44Gln
CABP5_Glu140Lys
CABP5_Gly73Ser
CABP5_Thr65Arg
CABP5_Val128Ala
CACNB4_Arg468Gln
CACNB4_Cys104Phe
CADM1_His246Asn
CADM1_Tyr251Ser
CALCOCO2_Glu222Lys
CALCOCO2_Pro389Ala
CALCOCO2_Thr255Ala
CALCOCO2_Thr273Ala
CALCOCO2_Val248Ala
CALR3_Arg73Gln
CALR3_Lys82Arg
CAMK2D_Arg469Cys
CAMK2D_Arg469His
CAMK2D_Asp167Glu
CAMK2D_Gly376Asp
CAPN13_Thr280Ala
CAPN3_Ala286Glu
CAPN3_Ala798Glu
CAPN3_Thr194Lys
CAPN3_Thr706Lys
CARD9_Arg173His
CARD9_Ser12Asn
CARD9_Val385Leu
CARTPT_Leu34Phe
CARTPT_Leu61Phe
CASK_Asp687Gly
CASP10_Leu285Phe
CASP10_Pro501Leu
CASP10_Tyr446Cys
CASP10_Val410Ile
CASP2_Arg155His
CASP2_Arg265Gly
CASP2_Glu388Lys
CASP2_Gly349Ser
CASP2_Val29Glu
CASP6_Ala109Thr
CASP6_Asn73Thr
CASP6_Ile270Thr
CASP6_Lys255Thr
CASP6_Phe31Leu
CASP6_Val275Phe
CASP9_Arg173His
CASP9_Arg178Cys
CASP9_Gln221Arg
CASP9_His237Pro
CASP9_Pro336Ser
CASP9_Thr366Asn
CAT_Arg354His
CAT_Asp54Glu
CAT_Glu67Asp
CAV3_Asp28Glu
CAV3_Gly56Ser
CAV3_Ser141Arg
CAV3_Thr78Met
CBFB_Arg151His
CBLB_Phe328Leu
CBLB_Ser622Thr
CBR1_Val88Ile
CBR3_Pro131Ser
CBR3_Val244Met
CBS_Ala114Val
CBS_Arg224Cys
CBS_Arg369Cys
CBS_Arg379Trp
CBS_Arg548Gln
CBS_Asp388Asn
CBS_Cys109Arg
CBS_Gly116Arg
CBS_Gly85Arg
CBS_Ile278Thr
CBS_Leu101Pro
CBS_Leu154Gln
CBS_Leu456Pro
CBS_Lys102Gln
CBS_Lys384Glu
CBS_Lys72Ile
CBS_Met391Ile
CBS_Pro422Leu
CBS_Pro427Leu
CBS_Pro49Leu
CCBE1_Gly136Arg
CCDC106_Ala54Thr
CCDC116_Cys519Arg
CCDC172_Asn145Lys
CCDC172_Ile10Val
CCDC172_Phe60Leu
CCDC185_Ser603Gly
CCDC33_Arg30Leu
CCDC33_Gly196Arg
CCDC33_Met25Val
CCDC33_Pro203Leu
CCDC33_Ser73Asn
CCDC42_Ala144Thr
CCDC42_Arg128His
CCDC60_Ile46Val
CCDC68_Asp151Gly
CCDC68_Leu100Val
CCDC68_Val249Ala
CCDC70_Arg73Gln
CCDC70_Met211Val
CCDC74A_Gly302Arg
CCDC92_Ser70Cys
CCER1_Glu293Lys
CCKBR_Glu288Lys
CCKBR_Val125Ile
CCL4_Ala16Thr
CCL4_Ala21Val
CCL4_Cys18Arg
CCM2_Leu198Arg
CCN6_Cys132Tyr
CCN6_Cys163Tyr
CCN6_Cys96Arg
CCN6_Ser352Pro
CCNB1IP1_Arg104His
CCNB1IP1_Asn212Asp
CCNB1IP1_Phe41Leu
CCNB1IP1_Thr187Ala
CCNB1IP1_Tyr106His
CCND1_Ala30Thr
CCND1_Arg260Cys
CCND1_Asp25Ala
CCND1_Glu162Lys
CCND1_Pro287Leu
CCND1_Ser166Tyr
CCND3_Ala266Val
CCND3_Glu253Asp
CCND3_Pro134Ser
CCND3_Ser259Ala
CCNDBP1_Ile277Thr
CCNG1_Glu167Lys
CCNH_Asn155Thr
CCT5_His147Arg
CD151_Arg171Cys
CD151_Arg178His
CD207_Ala300Pro
CD207_Ala55Val
CD207_Arg66Gln
CD207_Asn288Asp
CD207_Glu114Val
CD207_Trp264Arg
CD2BP2_Thr262Ile
CD36_Ile413Leu
CD36_Phe254Leu
CD36_Pro90Ser
CD36_Val137Ala
CD38_Arg140Trp
CD3E_Glu189Gln
CD40_Cys83Arg
CD40_Gly266Asp
CD40_Pro227Ala
CD40_Ser124Leu
CD44_Arg46Pro
CD44_Thr163Lys
CD55_Arg52Leu
CD55_Arg52Pro
CD55_Glu156Lys
CD55_Pro216Leu
CD70_Asp165Tyr
CD79B_Gly137Ser
CD96_Thr264Met
CD96_Thr280Met
CDA_Ala40Thr
CDA_Ala70Thr
CDA_Ala88Thr
CDA_Ala88Val
CDA_Arg68Trp
CDA_Pro37Thr
CDA_Pro61Leu
CDA_Val115Met
CDC26_Asn21Ser
CDC26_Glu37Gln
CDC26_Lys31Glu
CDC42EP4_Met102Val
CDC45_Gly150Glu
CDC73_Arg147Cys
CDC73_Arg156His
CDC73_Arg91Pro
CDC73_Leu64Pro
CDC73_Leu95Pro
CDC7_Gln106Arg
CDC7_Gln456His
CDC7_Ile99Leu
CDC7_Ile99Thr
CDC7_Lys416Thr
CDK4_Ala23Ser
CDK4_Arg209Cys
CDK4_Arg24Cys
CDK4_Arg24His
CDK4_Arg255Cys
CDK4_Arg255His
CDK4_Asn41Ser
CDK4_Gly43Glu
CDK4_Lys22Arg
CDK4_Ser267Pro
CDK4_Ser52Asn
CDK4_Val174Gly
CDK5R1_Ala108Val
CDK5R1_Leu302Ile
CDK5RAP3_Glu173Lys
CDK6_Asp110Asn
CDK6_Ser317Cys
CDKN1A_Arg156Trp
CDKN1A_Arg67Leu
CDKN1A_Arg83Trp
CDKN1A_Arg84Gln
CDKN1A_Asp149Gly
CDKN1A_Cys117Tyr
CDKN1A_Phe63Leu
CDKN1A_Ser31Arg
CDKN1B_Arg169Lys
CDKN1B_Asn173Ser
CDKN1B_Asp63Glu
CDKN1B_Cys29Phe
CDKN1B_Glu172Lys
CDKN1B_Glu39Gln
CDKN1B_Gly150Glu
CDKN1B_Ile119Thr
CDKN1B_Pro122Leu
CDKN1B_Pro155Arg
CDKN1B_Pro191His
CDKN1B_Pro95Ser
CDKN1B_Ser161Cys
CDKN1B_Ser7Cys
CDKN2C_Arg117Gln
CDKN2C_Arg133Gln
CDKN2C_Thr69Ala
CDKN2C_Val31Leu
CDKN2D_Ala121Ser
CDKN2D_Pro142Ser
CDKN2D_Pro67Leu
CDKN2D_Val94Met
CEP55_Ala244Pro
CEP55_Arg138Gln
CEP55_Arg348Lys
CEP55_Cys236Arg
CEP55_Glu321Lys
CEP55_His57Gln
CEP55_Leu59Phe
CEP55_Thr209Met
CEP72_Arg137Cys
CEP72_Gly406Arg
CEP72_Pro412Thr
CER1_Arg19Trp
CERKL_Arg106Ser
CERT1_Arg128His
CETN1_Met72Thr
CETP_Asp442Gly
CETP_Asp459Gly
CETP_Leu151Pro
CETP_Leu168Pro
CETP_Leu296Gln
CETP_Leu313Gln
CETP_Ser332Tyr
CETP_Ser349Tyr
CFB_Leu9His
CFB_Lys323Glu
CFB_Phe286Leu
CFC1_Ala145Thr
CFC1_Arg47Gln
CFC1_Arg78Trp
CFC1_Pro217Arg
CFHR5_Arg356His
CFHR5_Gly145Glu
CFHR5_Lys144Asn
CFHR5_Met514Arg
CFHR5_Phe192Leu
CFHR5_Pro46Ser
CFH_Arg127Leu
CFH_Arg78Gly
CFH_Gln400Lys
CFI_Ala240Gly
CFI_Gly162Asp
CFI_Ile340Thr
CFP_Arg100Trp
CFP_Arg319Cys
CFP_Arg346Cys
CFP_Arg73Trp
CFP_Gly250Ser
CFP_Met420Thr
CFP_Pro409Leu
CFP_Trp294Ser
CFP_Trp321Ser
CFP_Tyr414Asp
CGRRF1_Arg185Trp
CHD2_Glu287Gln
CHD2_Glu412Lys
CHD2_Pro195Leu
CHGA_Gly382Ser
CHGA_Pro388Leu
CHIT1_Ala442Val
CHIT1_Glu74Lys
CHIT1_Gly354Arg
CHMP2B_Asn143Ser
CHMP2B_Asp148Tyr
CHMP2B_Gln206His
CHMP4A_Gly153Arg
CHMP7_Arg228Cys
CHN1_Ala223Val
CHN1_Asp115Asn
CHN1_Glu313Lys
CHN1_Gly228Ser
CHN1_Ile126Met
CHN1_Leu20Phe
CHN1_Pro141Leu
CHN1_Pro252Gln
CHN1_Pro252Ser
CHN1_Tyr143His
CHRM2_Cys176Trp
CHRNA1_Arg209Leu
CHRNA1_Arg229Leu
CHRNA1_Gly153Ser
CHRNA1_Gly173Ser
CHRNA1_Gly74Cys
CHRNA1_Gly94Cys
CHRNA1_Val156Met
CHRNA1_Val176Met
CHRNA4_Leu258Val
CHRNA4_Leu290Val
CHRNA4_Ser248Phe
CHRNA4_Ser252Leu
CHRNA4_Ser280Phe
CHRNA4_Ser284Leu
CHRNA4_Thr261Ile
CHRNA4_Thr293Ile
CHRNB1_Leu262Met
CHRNB1_Leu285Met
CHRNB1_Val266Met
CHRNB1_Val289Met
CHRNB4_Arg136Trp
CHRNB4_Met467Val
CHRNB4_Thr91Ile
CHRND_Gln267Glu
CHRND_Gln288Glu
CHRND_Glu381Lys
CHRND_Glu402Lys
CHRND_Ile58Lys
CHRND_Ile79Lys
CHRND_Leu42Pro
CHRNG_Arg187Cys
CHRNG_Arg86Cys
CHRNG_Val107Gly
CHST6_His249Pro
CHST6_Tyr110Cys
CHST6_Tyr358Asp
CIAPIN1_Ala34Glu
CIDEA_Val115Phe
CIDEA_Val149Phe
CINP_Arg164His
CINP_Asp177Asn
CKM_Asp54Gly
CLCN2_Arg101Gln
CLCN2_Arg249Trp
CLCN2_Arg577Gln
CLCN2_Gly239Glu
CLCN2_Gly715Glu
CLCN5_Arg516Trp
CLCN5_Gly88Asp
CLCN5_Leu200Arg
CLCN5_Lys725Glu
CLCNKB_Ala61Asp
CLCNKB_Arg438His
CLCNKB_Pro124Leu
CLCNKB_Thr353Ser
CLCNKB_Thr481Ser
CLDN14_Gly101Arg
CLDN14_Val85Asp
CLDN16_Ala139Val
CLDN16_Arg216Cys
CLDN16_Met71Arg
CLDN16_Ser235Tyr
CLDN19_Arg200Gln
CLDN19_Gln57Glu
CLDN19_Gly20Asp
CLDN19_Leu90Pro
CLEC1A_Gly26Ala
CLEC1A_Pro272Ser
CLIC3_Met210Leu
CLN6_Ala12Thr
CLN6_Arg6Thr
CLN6_Gly123Asp
CLN6_Leu47Phe
CLN8_Ala30Pro
CLN8_Arg24Gly
CLN8_Gln256Glu
CLN8_Thr170Met
CLOCK_Gly235Glu
CLOCK_Leu395Ile
CLRN1_Asn48Lys
CLRN1_Cys40Gly
CLRN1_Ser105Pro
CLU_Gln381Pro
CLU_Gln433Pro
CNGA3_Arg563Cys
CNGA3_Cys191Tyr
CNGA3_Pro163Leu
CNGA3_Ser401Pro
CNOT3_Ser491Ala
CNOT7_Lys152Arg
CNST_Arg399Cys
CNST_Gln183Arg
COG2_Val589Ile
COG7_Gln749Lys
COL10A1_Cys591Arg
COL10A1_Gly18Arg
COL10A1_Gly18Glu
COL10A1_Gly595Arg
COL2A1_Arg57Cys
COL2A1_Thr164Met
COL2A1_Thr171Asn
COL2A1_Thr220Met
COL2A1_Thr229Pro
COL2A1_Tyr79Asn
COLQ_Asp342Glu
COMP_Ala171Thr
COMP_Arg718Pro
COMP_Asn386Asp
COMP_Asn555Lys
COMP_Asp271His
COMP_Asp319Val
COMP_Asp342Tyr
COMP_Asp408Asn
COMP_Asp511Glu
COMP_Asp605Asn

# Same variants different isoforms?

In [238]:
import re
from collections import defaultdict

# Parse aa_change into (ref_aa, position, alt_aa)
def parse_aa_change(aa_change):
    match = re.match(r'^([A-Z][a-z]{2})(\d+)([A-Z][a-z]{2})$', aa_change)
    if match:
        return match.group(1), int(match.group(2)), match.group(3)
    return None, None, None

# Group variants by gene
gene_variants = defaultdict(list)
for gv in full_df['gene_variant'].dropna().unique():
    parts = gv.rsplit('_', 1)
    if len(parts) == 2:
        gene, aa = parts
        ref, pos, alt = parse_aa_change(aa)
        if pos is not None:
            gene_variants[gene].append((ref, pos, alt, gv))

# For each gene, find pairs with same ref_aa and alt_aa but different positions
print("=== Potential isoform-offset duplicates ===\n")
isoform_duplicates = []

for gene, variants in sorted(gene_variants.items()):
    if len(variants) < 2:
        continue
    
    # Group by (ref_aa, alt_aa)
    aa_groups = defaultdict(list)
    for ref, pos, alt, gv in variants:
        aa_groups[(ref, alt)].append((pos, gv))
    
    for (ref, alt), positions in aa_groups.items():
        if len(positions) < 2:
            continue
        positions.sort()
        # Check all pairs for consistent offsets within this gene
        for i in range(len(positions)):
            for j in range(i+1, len(positions)):
                pos_i, gv_i = positions[i]
                pos_j, gv_j = positions[j]
                offset = pos_j - pos_i
                isoform_duplicates.append({
                    'gene': gene,
                    'variant_1': gv_i,
                    'variant_2': gv_j,
                    'offset': offset,
                    'ref_aa': ref,
                    'alt_aa': alt,
                })

dup_df = pd.DataFrame(isoform_duplicates)
print(f"Total potential isoform-offset duplicate pairs: {len(dup_df)}")

# Find genes with consistent offsets (multiple pairs with same offset)
if len(dup_df) > 0:
    consistent = dup_df.groupby(['gene', 'offset']).filter(lambda x: len(x) >= 2)
    consistent_summary = consistent.groupby(['gene', 'offset']).agg(
        n_pairs=('variant_1', 'count'),
        examples=('variant_1', lambda x: list(x)[:3])
    ).reset_index().sort_values('n_pairs', ascending=False)
    
    print(f"\nGenes with consistent offsets (≥2 pairs same offset):")
    print(f"{'Gene':<15} {'Offset':<8} {'Pairs':<6} Examples")
    print("-" * 80)
    for _, row in consistent_summary.iterrows():
        gene_rows = consistent[(consistent.gene == row.gene) & (consistent.offset == row.offset)]
        pairs_str = '; '.join([f"{r.variant_1} / {r.variant_2}" for _, r in gene_rows.head(3).iterrows()])
        print(f"{row.gene:<15} {row.offset:<8} {row.n_pairs:<6} {pairs_str}")
    
    print(f"\n⚠️  These {len(consistent_summary)} gene-offset groups likely represent the same variants ")
    print(f"   mapped to different transcript isoforms and should be deduplicated.")
    print(f"   Total variant pairs to resolve: {len(consistent)}")

=== Potential isoform-offset duplicates ===

Total potential isoform-offset duplicate pairs: 927

Genes with consistent offsets (≥2 pairs same offset):
Gene            Offset   Pairs  Examples
--------------------------------------------------------------------------------
ACADM           25       4      ACADM_Ala27Val / ACADM_Ala52Val; ACADM_Arg181Cys / ACADM_Arg206Cys; ACADM_Lys304Glu / ACADM_Lys329Glu
F9              46       4      F9_Cys124Tyr / F9_Cys170Tyr; F9_Cys361Arg / F9_Cys407Arg; F9_Glu27Lys / F9_Glu73Lys
DMD             3068     4      DMD_Ala353Val / DMD_Ala3421Val; DMD_Asp119Gly / DMD_Asp3187Gly; DMD_Asp267His / DMD_Asp3335His
GDAP1           68       4      GDAP1_Arg93His / GDAP1_Arg161His; GDAP1_Arg242Gln / GDAP1_Arg310Gln; GDAP1_Leu171Phe / GDAP1_Leu239Phe
SQSTM1          84       4      SQSTM1_Ala297Val / SQSTM1_Ala381Val; SQSTM1_Pro303Leu / SQSTM1_Pro387Leu; SQSTM1_Pro308Leu / SQSTM1_Pro392Leu
GBA1            39       4      GBA1_Arg257Gln / GBA1_Arg296Gln; GBA1_Leu185Phe / GBA1_Leu224Phe; GBA1_Leu444Pro / GBA1_Leu483Pro
FGG             26       4      FGG_Ala82Gly / FGG_Ala108Gly; FGG_Asp330Val / FGG_Asp356Val; FGG_Cys139Tyr / FGG_Cys165Tyr
C2              20       4      C2_Cys111Tyr / C2_Cys131Tyr; C2_Glu298Asp / C2_Glu318Asp; C2_Gly444Arg / C2_Gly464Arg
FGB             30       4      FGB_Ala335Thr / FGB_Ala365Thr; FGB_His67Leu / FGB_His97Leu; FGB_Leu172Gln / FGB_Leu202Gln
CCN6            18       4      CCN6_Cys114Tyr / CCN6_Cys132Tyr; CCN6_Cys145Tyr / CCN6_Cys163Tyr; CCN6_Cys78Arg / CCN6_Cys96Arg
CETP            17       4      CETP_Asp442Gly / CETP_Asp459Gly; CETP_Leu151Pro / CETP_Leu168Pro; CETP_Leu296Gln / CETP_Leu313Gln
HADHB           1        4      HADHB_Ala326Pro / HADHB_Ala327Pro; HADHB_Arg61His / HADHB_Arg62His; HADHB_His379Arg / HADHB_His380Arg
RLBP1           1        4      RLBP1_Arg150Gln / RLBP1_Arg151Gln; RLBP1_Gly145Asp / RLBP1_Gly146Asp; RLBP1_Ile200Thr / RLBP1_Ile201Thr
CHRNA1          20       4      CHRNA1_Arg209Leu / CHRNA1_Arg229Leu; CHRNA1_Gly153Ser / CHRNA1_Gly173Ser; CHRNA1_Gly74Cys / CHRNA1_Gly94Cys
CHRNA4          32       4      CHRNA4_Leu258Val / CHRNA4_Leu290Val; CHRNA4_Ser248Phe / CHRNA4_Ser280Phe; CHRNA4_Ser252Leu / CHRNA4_Ser284Leu
F11             18       4      F11_Gln29His / F11_Gln47His; F11_Leu342Pro / F11_Leu360Pro; F11_Phe283Leu / F11_Phe301Leu
F10             40       4      F10_Arg142Met / F10_Arg182Met; F10_Arg326Cys / F10_Arg366Cys; F10_Glu14Gly / F10_Glu54Gly
OTX2            8        4      OTX2_Arg89Gly / OTX2_Arg97Gly; OTX2_Asn225Ser / OTX2_Asn233Ser; OTX2_Pro133Thr / OTX2_Pro141Thr
CRYGD           1        4      CRYGD_Arg14Cys / CRYGD_Arg15Cys; CRYGD_Glu106Ala / CRYGD_Glu107Ala; CRYGD_Gly60Cys / CRYGD_Gly61Cys
SCN1B           33       4      SCN1B_Arg52Cys / SCN1B_Arg85Cys; SCN1B_Arg52His / SCN1B_Arg85His; SCN1B_Cys88Trp / SCN1B_Cys121Trp
AMT             97       4      AMT_Arg223His / AMT_Arg320His; AMT_Asn48Ile / AMT_Asn145Ile; AMT_Gly172Asp / AMT_Gly269Asp
DLD             35       4      DLD_Glu340Lys / DLD_Glu375Lys; DLD_Gly194Cys / DLD_Gly229Cys; DLD_Ile358Thr / DLD_Ile393Thr
PITX2           53       4      PITX2_Gly137Val / PITX2_Gly190Val; PITX2_Leu54Gln / PITX2_Leu107Gln; PITX2_Pro64Arg / PITX2_Pro117Arg
INS             24       4      INS_Arg31Cys / INS_Arg55Cys; INS_Gly60Arg / INS_Gly84Arg; INS_Gly66Cys / INS_Gly90Cys
MMACHC          57       4      MMACHC_Arg149Pro / MMACHC_Arg206Pro; MMACHC_His65Arg / MMACHC_His122Arg; MMACHC_Leu59Pro / MMACHC_Leu116Pro
TNFRSF13B       46       4      TNFRSF13B_Ala103Thr / TNFRSF13B_Ala149Thr; TNFRSF13B_Cys58Arg / TNFRSF13B_Cys104Arg; TNFRSF13B_Leu125Arg / TNFRSF13B_Leu171Arg
TK2             91       4      TK2_Arg143Lys / TK2_Arg234Lys; TK2_His72Asn / TK2_His163Asn; TK2_Leu166Pro / TK2_Leu257Pro
TIMP3           23       4      TIMP3_Gly167Cys / TIMP3_Gly190Cys; TIMP3_Ser170Cys / TIMP3_Ser193Cys; TIMP3_Ser181Cys / TIMP3_Ser204Cys
AGXT            115      4      AGXT_Arg118Cys / AGXT_Arg233Cys; AGXT_Arg118His / AGXT_Arg233His; AGXT_Gly41Arg / AGXT_Gly156Arg
KRT18           1        4      KRT18_Gln284Arg / KRT18_Gln285Arg; KRT18_Gly339Arg / KRT18_Gly340Arg; KRT18_His127Leu / KRT18_His128Leu
UBE3A           267      4      UBE3A_Arg239Cys / UBE3A_Arg506Cys; UBE3A_Ile62Thr / UBE3A_Ile329Thr; UBE3A_Ile537Lys / UBE3A_Ile804Lys
AGT             33       4      AGT_Arg342Gln / AGT_Arg375Gln; AGT_Leu10Phe / AGT_Leu43Phe; AGT_Thr174Met / AGT_Thr207Met
TBXAS1          68       4      TBXAS1_Arg345Gln / TBXAS1_Arg413Gln; TBXAS1_Leu15Pro / TBXAS1_Leu83Pro; TBXAS1_Lys190Glu / TBXAS1_Lys258Glu
IMPDH1          36       4      IMPDH1_Arg273Pro / IMPDH1_Arg309Pro; IMPDH1_Asp275Asn / IMPDH1_Asp311Asn; IMPDH1_His421Pro / IMPDH1_His457Pro
MITF            6        3      MITF_Asn204Lys / MITF_Asn210Lys; MITF_Ser244Pro / MITF_Ser250Pro; MITF_Ser292Pro / MITF_Ser298Pro
EPB42           30       3      EPB42_Ala112Thr / EPB42_Ala142Thr; EPB42_Arg280Gln / EPB42_Arg310Gln; EPB42_Arg287Cys / EPB42_Arg317Cys
PCCA            25       3      PCCA_Ala50Pro / PCCA_Ala75Pro; PCCA_Leu392Trp / PCCA_Leu417Trp; PCCA_Val335Gly / PCCA_Val360Gly
ELANE           29       3      ELANE_Ala32Val / ELANE_Ala61Val; ELANE_Cys122Ser / ELANE_Cys151Ser; ELANE_Gly181Val / ELANE_Gly210Val
NF2             83       3      NF2_Arg335Cys / NF2_Arg418Cys; NF2_Asn137Tyr / NF2_Asn220Tyr; NF2_Leu452Pro / NF2_Leu535Pro
PGK1            1        3      PGK1_Arg205Pro / PGK1_Arg206Pro; PGK1_Asp267Asn / PGK1_Asp268Asn; PGK1_Cys315Arg / PGK1_Cys316Arg
RGR             4        3      RGR_Ala234Thr / RGR_Ala238Thr; RGR_His152Asn / RGR_His156Asn; RGR_Val132Leu / RGR_Val136Leu
LIPC            22       3      LIPC_Asn193Ser / LIPC_Asn215Ser; LIPC_Leu334Phe / LIPC_Leu356Phe; LIPC_Thr383Met / LIPC_Thr405Met
KRT8            204      3      KRT8_Arg137His / KRT8_Arg341His; KRT8_Lys260Asn / KRT8_Lys464Asn; KRT8_Val176Ile / KRT8_Val380Ile
GNMT            1        3      GNMT_Asn140Ser / GNMT_Asn141Ser; GNMT_His176Asn / GNMT_His177Asn; GNMT_Leu49Pro / GNMT_Leu50Pro
PRODH           108      3      PRODH_Arg77Trp / PRODH_Arg185Trp; PRODH_Asp318Asn / PRODH_Asp426Asn; PRODH_Leu181Met / PRODH_Leu289Met
PROC            42       3      PROC_Gln290Leu / PROC_Gln332Leu; PROC_Gly72Arg / PROC_Gly114Arg; PROC_His134Asn / PROC_His176Asn
PPARG           28       3      PPARG_Asp396Asn / PPARG_Asp424Asn; PPARG_Pro85Gln / PPARG_Pro113Gln; PPARG_Val290Met / PPARG_Val318Met
IHH             118      3      IHH_Glu13Lys / IHH_Glu131Lys; IHH_Thr36Ile / IHH_Thr154Ile; IHH_Val72Ala / IHH_Val190Ala
GK              6        3      GK_Asp440Val / GK_Asp446Val; GK_Cys256Arg / GK_Cys262Arg; GK_Thr278Met / GK_Thr284Met
ACADSB          33       3      ACADSB_Glu354Lys / ACADSB_Glu387Lys; ACADSB_Thr115Ile / ACADSB_Thr148Ile; ACADSB_Tyr250Cys / ACADSB_Tyr283Cys
SERPINA3        25       3      SERPINA3_Leu53Pro / SERPINA3_Leu78Pro; SERPINA3_Met389Val / SERPINA3_Met414Val; SERPINA3_Pro227Ala / SERPINA3_Pro252Ala
SERPINA10       21       3      SERPINA10_Gln363Arg / SERPINA10_Gln384Arg; SERPINA10_Phe124Leu / SERPINA10_Phe145Leu; SERPINA10_Ser122Tyr / SERPINA10_Ser143Tyr
BEST1           60       3      BEST1_Arg158Gly / BEST1_Arg218Gly; BEST1_Arg32Cys / BEST1_Arg92Cys; BEST1_Tyr25His / BEST1_Tyr85His
TULP1           53       3      TULP1_Arg367Pro / TULP1_Arg420Pro; TULP1_Arg429Trp / TULP1_Arg482Trp; TULP1_Phe329Ser / TULP1_Phe382Ser
TTR             20       3      TTR_Arg103Ser / TTR_Arg123Ser; TTR_Ile73Val / TTR_Ile93Val; TTR_Val30Met / TTR_Val50Met
TPH2            6        3      TPH2_Arg303Trp / TPH2_Arg309Trp; TPH2_Arg441His / TPH2_Arg447His; TPH2_Pro206Ser / TPH2_Pro212Ser
AGXT            75       3      AGXT_Gly41Arg / AGXT_Gly116Arg; AGXT_Leu26Pro / AGXT_Leu101Pro; AGXT_Leu284Pro / AGXT_Leu359Pro
ALAS2           37       3      ALAS2_Arg411Gln / ALAS2_Arg448Gln; ALAS2_Ile252Thr / ALAS2_Ile289Thr; ALAS2_Ile439Asn / ALAS2_Ile476Asn
D2HGDH          301      3      D2HGDH_Asn138Asp / D2HGDH_Asn439Asp; D2HGDH_Asp74Tyr / D2HGDH_Asp375Tyr; D2HGDH_Val143Ala / D2HGDH_Val444Ala
ANTXR2          336      3      ANTXR2_Tyr45Cys / ANTXR2_Tyr381Cys; ANTXR2_Val50Phe / ANTXR2_Val386Phe; ANTXR2_Val58Ala / ANTXR2_Val394Ala
APOC3           20       3      APOC3_Asp45Asn / APOC3_Asp65Asn; APOC3_Gln38Lys / APOC3_Gln58Lys; APOC3_Thr74Ala / APOC3_Thr94Ala
STS             22       3      STS_Arg432Cys / STS_Arg454Cys; STS_Ser319Leu / STS_Ser341Leu; STS_Trp350Arg / STS_Trp372Arg
BCHE            28       3      BCHE_Gln518Leu / BCHE_Gln546Leu; BCHE_Leu330Ile / BCHE_Leu358Ile; BCHE_Tyr128Cys / BCHE_Tyr156Cys
NR1I2           55       3      NR1I2_Arg67Gln / NR1I2_Arg122Gln; NR1I2_Arg43Cys / NR1I2_Arg98Cys; NR1I2_Gln103Lys / NR1I2_Gln158Lys
SOD1            1        3      SOD1_Gly37Arg / SOD1_Gly38Arg; SOD1_Gly41Ser / SOD1_Gly42Ser; SOD1_Leu126Ser / SOD1_Leu127Ser
CHRND           21       3      CHRND_Gln267Glu / CHRND_Gln288Glu; CHRND_Glu381Lys / CHRND_Glu402Lys; CHRND_Ile58Lys / CHRND_Ile79Lys
SERPINC1        32       3      SERPINC1_Arg47Cys / SERPINC1_Arg79Cys; SERPINC1_Leu126Pro / SERPINC1_Leu158Pro; SERPINC1_Pro16His / SERPINC1_Pro48His
CFP             27       3      CFP_Arg73Trp / CFP_Arg100Trp; CFP_Arg319Cys / CFP_Arg346Cys; CFP_Trp294Ser / CFP_Trp321Ser
TFAP2A          6        2      TFAP2A_Arg248Trp / TFAP2A_Arg254Trp; TFAP2A_Gly256Glu / TFAP2A_Gly262Glu
PANK2           326      2      PANK2_Gly85Arg / PANK2_Gly411Arg; PANK2_Phe114Leu / PANK2_Phe440Leu
VCP             218      2      VCP_Ala221Ser / VCP_Ala439Ser; VCP_Thr44Ala / VCP_Thr262Ala
TRAF1           2        2      TRAF1_Arg226Cys / TRAF1_Arg228Cys; TRAF1_Arg226His / TRAF1_Arg228His
TP63            39       2      TP63_Asp312Asn / TP63_Asp351Asn; TP63_Ile510Thr / TP63_Ile549Thr
SHBG            29       2      SHBG_Asp327Asn / SHBG_Asp356Asn; SHBG_Pro156Leu / SHBG_Pro185Leu
TIMP3           11       2      TIMP3_Ser170Cys / TIMP3_Ser181Cys; TIMP3_Ser193Cys / TIMP3_Ser204Cys
PIK3R1          270      2      PIK3R1_Arg139Gln / PIK3R1_Arg409Gln; PIK3R1_Met56Ile / PIK3R1_Met326Ile
TAFAZZIN        69       2      TAFAZZIN_Gly128Val / TAFAZZIN_Gly197Val; TAFAZZIN_Leu141Arg / TAFAZZIN_Leu210Arg
SQSTM1          5        2      SQSTM1_Pro303Leu / SQSTM1_Pro308Leu; SQSTM1_Pro387Leu / SQSTM1_Pro392Leu
STXBP1          145      2      STXBP1_Arg406Leu / STXBP1_Arg551Leu; STXBP1_Pro335Leu / STXBP1_Pro480Leu
SMAD3           25       2      SMAD3_Arg243Cys / SMAD3_Arg268Cys; SMAD3_Arg243His / SMAD3_Arg268His
PLP1            1        2      PLP1_Leu86Pro / PLP1_Leu87Pro; PLP1_Pro14Leu / PLP1_Pro15Leu
STXBP1          127      2      STXBP1_Gly417Asp / STXBP1_Gly544Asp; STXBP1_Pro335Leu / STXBP1_Pro462Leu
PLP1            34       2      PLP1_Ala213Glu / PLP1_Ala247Glu; PLP1_Trp128Leu / PLP1_Trp162Leu
PTCH1           66       2      PTCH1_Gly44Arg / PTCH1_Gly110Arg; PTCH1_Thr164Pro / PTCH1_Thr230Pro
SMAD3           130      2      SMAD3_Arg243His / SMAD3_Arg373His; SMAD3_Pro263Leu / SMAD3_Pro393Leu
PROZ            40       2      PROZ_Glu30Gln / PROZ_Glu70Gln; PROZ_Glu30Lys / PROZ_Glu70Lys
PLTP            52       2      PLTP_Arg183Trp / PLTP_Arg235Trp; PLTP_Arg424Gln / PLTP_Arg476Gln
SMPD1           2        2      SMPD1_Asp49Val / SMPD1_Asp51Val; SMPD1_Pro330Arg / SMPD1_Pro332Arg
STXBP1          114      2      STXBP1_Arg292Cys / STXBP1_Arg406Cys; STXBP1_Arg292His / STXBP1_Arg406His
GFAP            5        2      GFAP_Glu205Lys / GFAP_Glu210Lys; GFAP_Leu352Pro / GFAP_Leu357Pro
NR1I3           4        2      NR1I3_His246Arg / NR1I3_His250Arg; NR1I3_Leu308Pro / NR1I3_Leu312Pro
AGXT            171      2      AGXT_Arg118Cys / AGXT_Arg289Cys; AGXT_Arg118His / AGXT_Arg289His
BANK1           30       2      BANK1_Ala353Thr / BANK1_Ala383Thr; BANK1_Arg31His / BANK1_Arg61His
APOH            19       2      APOH_Cys306Gly / APOH_Cys325Gly; APOH_Trp316Ser / APOH_Trp335Ser
APOD            20       2      APOD_Phe36Val / APOD_Phe56Val; APOD_Thr158Lys / APOD_Thr178Lys
ANG             24       2      ANG_Gln12Leu / ANG_Gln36Leu; ANG_Pro112Leu / ANG_Pro136Leu
ALDOA           1        2      ALDOA_Asp128Gly / ALDOA_Asp129Gly; ALDOA_Cys338Tyr / ALDOA_Cys339Tyr
AGXT            258      2      AGXT_Leu26Pro / AGXT_Leu284Pro; AGXT_Leu101Pro / AGXT_Leu359Pro
AGXT            253      2      AGXT_Arg36Cys / AGXT_Arg289Cys; AGXT_Arg36His / AGXT_Arg289His
AGXT            197      2      AGXT_Arg36Cys / AGXT_Arg233Cys; AGXT_Arg36His / AGXT_Arg233His
AGXT            183      2      AGXT_Arg118Cys / AGXT_Arg301Cys; AGXT_Leu101Pro / AGXT_Leu284Pro
AGXT            114      2      AGXT_Asp129His / AGXT_Asp243His; AGXT_Gly47Arg / AGXT_Gly161Arg
NIPA1           75       2      NIPA1_Ala25Thr / NIPA1_Ala100Thr; NIPA1_Gly31Arg / NIPA1_Gly106Arg
AGXT            100      2      AGXT_Gly116Arg / AGXT_Gly216Arg; AGXT_Leu284Pro / AGXT_Leu384Pro
AGXT            82       2      AGXT_Arg36Cys / AGXT_Arg118Cys; AGXT_Arg36His / AGXT_Arg118His
AGXT            56       2      AGXT_Arg233Cys / AGXT_Arg289Cys; AGXT_Arg233His / AGXT_Arg289His
AGXT            41       2      AGXT_Gly41Arg / AGXT_Gly82Arg; AGXT_Gly41Glu / AGXT_Gly82Glu
AGXT            40       2      AGXT_Gly116Arg / AGXT_Gly156Arg; AGXT_Gly42Glu / AGXT_Gly82Glu
AGXT            35       2      AGXT_Gly47Arg / AGXT_Gly82Arg; AGXT_Ile244Thr / AGXT_Ile279Thr
AGXT            16       2      AGXT_Gly47Arg / AGXT_Gly63Arg; AGXT_Ser205Pro / AGXT_Ser221Pro
AGXT            5        2      AGXT_Cys173Tyr / AGXT_Cys178Tyr; AGXT_Gly156Arg / AGXT_Gly161Arg
ACY1            181      2      ACY1_Arg197Gln / ACY1_Arg378Gln; ACY1_Arg197Trp / ACY1_Arg378Trp
BRAF            3        2      BRAF_Gly466Ala / BRAF_Gly469Ala; BRAF_Gly466Glu / BRAF_Gly469Glu
C1QB            27       2      C1QB_Gly15Asp / C1QB_Gly42Asp; C1QB_Gly217Arg / C1QB_Gly244Arg
CAPN3           512      2      CAPN3_Ala286Glu / CAPN3_Ala798Glu; CAPN3_Thr194Lys / CAPN3_Thr706Lys
CCN6            31       2      CCN6_Cys114Tyr / CCN6_Cys145Tyr; CCN6_Cys132Tyr / CCN6_Cys163Tyr
MMACHC          77       2      MMACHC_Leu59Pro / MMACHC_Leu136Pro; MMACHC_Leu116Pro / MMACHC_Leu193Pro
MITF            48       2      MITF_Ser244Pro / MITF_Ser292Pro; MITF_Ser250Pro / MITF_Ser298Pro
INSL3           24       2      INSL3_Arg78Cys / INSL3_Arg102Cys; INSL3_Arg81His / INSL3_Arg105His
HNF4A           9        2      HNF4A_Arg324His / HNF4A_Arg333His; HNF4A_Cys93Trp / HNF4A_Cys102Trp
HBB             1        2      HBB_Ala115Asp / HBB_Ala116Asp; HBB_Leu32Pro / HBB_Leu33Pro
HADHA           36       2      HADHA_Glu474Gln / HADHA_Glu510Gln; HADHA_Val246Asp / HADHA_Val282Asp
GFAP            3        2      GFAP_Glu207Lys / GFAP_Glu210Lys; GFAP_Glu371Gly / GFAP_Glu374Gly
GCNT2           2        2      GCNT2_Arg383His / GCNT2_Arg385His; GCNT2_Gly348Glu / GCNT2_Gly350Glu
GC              16       2      GC_Asp416Glu / GC_Asp432Glu; GC_Thr420Lys / GC_Thr436Lys
FSHB            18       2      FSHB_Cys82Arg / FSHB_Cys100Arg; FSHB_Cys51Gly / FSHB_Cys69Gly
FGFR2           115      2      FGFR2_Ser152Phe / FGFR2_Ser267Phe; FGFR2_Tyr213Cys / FGFR2_Tyr328Cys
FAS             16       2      FAS_Glu256Gly / FAS_Glu272Gly; FAS_His95Pro / FAS_His111Pro
F9              85       2      F9_Arg294Gln / F9_Arg379Gln; F9_Gly357Arg / F9_Gly442Arg
F12             296      2      F12_Cys275Ser / F12_Cys571Ser; F12_Trp190Cys / F12_Trp486Cys
DCX             108      2      DCX_Arg78His / DCX_Arg186His; DCX_Arg78Leu / DCX_Arg186Leu
DCX             10       2      DCX_Arg186Cys / DCX_Arg196Cys; DCX_Arg186His / DCX_Arg196His
CLCN2           476      2      CLCN2_Arg101Gln / CLCN2_Arg577Gln; CLCN2_Gly239Glu / CLCN2_Gly715Glu
CHRNB1          23       2      CHRNB1_Leu262Met / CHRNB1_Leu285Met; CHRNB1_Val266Met / CHRNB1_Val289Met
CDK4            231      2      CDK4_Arg24Cys / CDK4_Arg255Cys; CDK4_Arg24His / CDK4_Arg255His
ZFP57           20       2      ZFP57_Arg228His / ZFP57_Arg248His; ZFP57_His257Asn / ZFP57_His277Asn

⚠️  These 136 gene-offset groups likely represent the same variants
   mapped to different transcript isoforms and should be deduplicated.
   Total variant pairs to resolve: 374

In [239]:
full_df[full_df.gene_symbol == 'TAFAZZIN']

,gene_symbol,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,Luck_omim_ids,...,Edgotype_class,Edgotype_source,Source,Source_Simple,n_sources,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,gene_symbol_old,alias_symbol
5582,TAFAZZIN,TAFAZZIN_Arg69Cys,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Arg69Cys,Pathogenic,allele_col,TAFAZZIN,NaN
5583,TAFAZZIN,TAFAZZIN_Gly128Val,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Gly128Val,Others,allele_col,TAFAZZIN,NaN
5584,TAFAZZIN,TAFAZZIN_Gly210Arg,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Gly210Arg,Pathogenic,allele_col,TAFAZZIN,NaN
5585,TAFAZZIN,TAFAZZIN_Leu141Arg,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Leu141Arg,Others,allele_col,TAFAZZIN,NaN
5608,TAFAZZIN,TAFAZZIN_Arg94Cys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Arg94Cys,Pathogenic,Lacoste,TAZ,WWTR1
5609,TAFAZZIN,TAFAZZIN_Gly197Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Gly197Val,NaN,NaN,TAZ,WWTR1
5610,TAFAZZIN,TAFAZZIN_Gly240Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Gly240Arg,Pathogenic,Lacoste,TAZ,WWTR1
5611,TAFAZZIN,TAFAZZIN_Leu210Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Leu210Arg,NaN,NaN,TAZ,WWTR1

In [240]:
# TAFAZIN 69 in sahni and allele_col, but 94 in Lacoste and 96 in ClinVar aaaaaaaaaaaaaaaaa

In [241]:
allele_col[allele_col.symbol == 'TAFAZZIN']

,symbol,aa_change,gene_variant,spdi,nt_change,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,...,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant,am_pathogenicity
411,TAFAZZIN,Arg69Cys,TAFAZZIN_Arg69Cys,NC_000023.11:154413247:C:T,205C>T,23,154413248,C,T,X,...,>90,<10,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9913
412,TAFAZZIN,Gly128Val,TAFAZZIN_Gly128Val,NC_000023.11:154420037:G:T,383G>T,23,154420038,G,T,X,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False,0.9988
413,TAFAZZIN,Leu141Arg,TAFAZZIN_Leu141Arg,NC_000023.11:154420076:T:G,422T>G,23,154420077,T,G,X,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False,0.9970
414,TAFAZZIN,Gly210Arg,TAFAZZIN_Gly210Arg,NC_000023.11:154420675:G:A,628G>A,23,154420676,G,A,X,...,NaN,NaN,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9949
6483,TAFAZZIN,Arg69Ser,TAFAZZIN_Arg69Ser,NC_000023.11:154413247:C:A,205C>A,23,154413248,C,A,X,...,>90,<10,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9995
6484,TAFAZZIN,Ser85Pro,TAFAZZIN_Ser85Pro,NC_000023.11:154413524:T:C,253T>C,23,154413525,T,C,X,...,>90,<10,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9926
6485,TAFAZZIN,Cys93Arg,TAFAZZIN_Cys93Arg,NC_000023.11:154413548:T:C,277T>C,23,154413549,T,C,X,...,>90,<10,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9980
6486,TAFAZZIN,Gly128Arg,TAFAZZIN_Gly128Arg,NC_000023.11:154420036:G:A,382G>A,23,154420037,G,A,X,...,NaN,NaN,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9992
6487,TAFAZZIN,Gly128Glu,TAFAZZIN_Gly128Glu,NC_000023.11:154420037:G:A,383G>A,23,154420038,G,A,X,...,NaN,NaN,302060,x-linked recessive,OMIM,NaN,0,BARTH SYNDROME,False,0.9994
6488,TAFAZZIN,Gly210Arg,TAFAZZIN_Gly210Arg,NC_000023.11:154420675:G:C,628G>C,23,154420676,G,C,X,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False,0.9949

In [242]:
# For each consistent offset pair, show which datasets each variant comes from
if len(consistent) > 0:
    print(f"{'Gene':<15} {'Offset':<8} {'Variant_1':<30} {'Source_1':<40} {'Variant_2':<30} {'Source_2':<40}")
    print("-" * 170)
    
    source_lookup = full_df.set_index('gene_variant')['Source'].to_dict()
    source_simple_lookup = full_df.set_index('gene_variant')['Source_Simple'].to_dict()
    
    for _, row in consistent.sort_values(['gene', 'offset']).iterrows():
        src1 = source_simple_lookup.get(row['variant_1'], 'N/A')
        src2 = source_simple_lookup.get(row['variant_2'], 'N/A')
        print(f"{row['gene']:<15} {row['offset']:<8} {row['variant_1']:<30} {str(src1):<40} {row['variant_2']:<30} {str(src2):<40}")

    # Summary: how often do the two sides of a pair come from the same vs different datasets?
    print("\n\n=== Source pattern summary ===\n")
    
    pair_sources = []
    for _, row in consistent.iterrows():
        src1 = source_simple_lookup.get(row['variant_1'], None)
        src2 = source_simple_lookup.get(row['variant_2'], None)
        
        # Check if they share any dataset
        if pd.notna(src1) and pd.notna(src2):
            set1 = set(src1.split('; '))
            set2 = set(src2.split('; '))
            shared = set1 & set2
            pattern = 'same_dataset' if shared else 'different_datasets'
        else:
            pattern = 'missing_source'
        
        pair_sources.append({
            'gene': row['gene'],
            'offset': row['offset'],
            'variant_1': row['variant_1'],
            'variant_2': row['variant_2'],
            'source_1': src1,
            'source_2': src2,
            'pattern': pattern,
        })
    
    pair_src_df = pd.DataFrame(pair_sources)
    
    print("Pattern counts:")
    print(pair_src_df['pattern'].value_counts())
    
    print("\n--- Pairs from DIFFERENT datasets (cross-dataset isoform mismatch) ---")
    diff_ds = pair_src_df[pair_src_df.pattern == 'different_datasets']
    if len(diff_ds) > 0:
        # Show source combination frequencies
        diff_ds['source_combo'] = diff_ds.apply(
            lambda r: ' ↔ '.join(sorted([str(r.source_1), str(r.source_2)])), axis=1
        )
        print(f"\nSource combination frequencies:")
        print(diff_ds['source_combo'].value_counts().to_string())
        print(f"\nExamples:")
        print(diff_ds[['gene', 'offset', 'variant_1', 'source_1', 'variant_2', 'source_2']].head(20).to_string(index=False))
    
    print("\n--- Pairs from SAME dataset (within-dataset isoform inconsistency) ---")
    same_ds = pair_src_df[pair_src_df.pattern == 'same_dataset']
    if len(same_ds) > 0:
        print(f"\n{len(same_ds)} pairs")
        print(same_ds[['gene', 'offset', 'variant_1', 'source_1', 'variant_2', 'source_2']].head(20).to_string(index=False))

Gene            Offset   Variant_1                      Source_1                                 Variant_2                      Source_2
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ACADM           25       ACADM_Ala27Val                 Lacoste                                  ACADM_Ala52Val                 Sahni
ACADM           25       ACADM_Arg181Cys                Lacoste                                  ACADM_Arg206Cys                Sahni
ACADM           25       ACADM_Lys304Glu                Lacoste                                  ACADM_Lys329Glu                Sahni
ACADM           25       ACADM_Met249Val                Lacoste                                  ACADM_Met274Val                Sahni
ACADSB          33       ACADSB_Glu354Lys               Lacoste                                  ACADSB_Glu387Lys               Sahni
ACADSB          33       ACADSB_Thr115Ile               Lacoste                                  ACADSB_Thr148Ile               Sahni
ACADSB          33       ACADSB_Tyr250Cys               Lacoste                                  ACADSB_Tyr283Cys               Sahni
ACY1            181      ACY1_Arg197Gln                 Fragoza                                  ACY1_Arg378Gln                 Fragoza
ACY1            181      ACY1_Arg197Trp                 Fragoza; Sahni                           ACY1_Arg378Trp                 Fragoza
AGT             33       AGT_Arg342Gln                  Lacoste                                  AGT_Arg375Gln                  Sahni
AGT             33       AGT_Leu10Phe                   Lacoste                                  AGT_Leu43Phe                   Sahni
AGT             33       AGT_Thr174Met                  Lacoste                                  AGT_Thr207Met                  Sahni
AGT             33       AGT_Tyr248Cys                  Lacoste                                  AGT_Tyr281Cys                  Sahni
AGXT            5        AGXT_Cys173Tyr                 1pct                                     AGXT_Cys178Tyr                 1pct
AGXT            5        AGXT_Gly156Arg                 1pct                                     AGXT_Gly161Arg                 1pct
AGXT            16       AGXT_Gly47Arg                  1pct                                     AGXT_Gly63Arg                  1pct
AGXT            16       AGXT_Ser205Pro                 1pct                                     AGXT_Ser221Pro                 1pct
AGXT            35       AGXT_Gly47Arg                  1pct                                     AGXT_Gly82Arg                  1pct
AGXT            35       AGXT_Ile244Thr                 1pct                                     AGXT_Ile279Thr                 1pct
AGXT            40       AGXT_Gly116Arg                 1pct                                     AGXT_Gly156Arg                 1pct
AGXT            40       AGXT_Gly42Glu                  1pct                                     AGXT_Gly82Glu                  1pct
AGXT            41       AGXT_Gly41Arg                  1pct                                     AGXT_Gly82Arg                  1pct
AGXT            41       AGXT_Gly41Glu                  1pct                                     AGXT_Gly82Glu                  1pct
AGXT            56       AGXT_Arg233Cys                 1pct                                     AGXT_Arg289Cys                 1pct
AGXT            56       AGXT_Arg233His                 1pct                                     AGXT_Arg289His                 1pct
AGXT            75       AGXT_Gly41Arg                  1pct                                     AGXT_Gly116Arg                 1pct
AGXT            75       AGXT_Leu26Pro                  1pct                                     AGXT_Leu101Pro                 1pct
AGXT            75       AGXT_Leu284Pro                 1pct                                     AGXT_Leu359Pro                 1pct
AGXT            82       AGXT_Arg36Cys                  1pct                                     AGXT_Arg118Cys                 1pct
AGXT            82       AGXT_Arg36His                  1pct                                     AGXT_Arg118His                 1pct
AGXT            100      AGXT_Gly116Arg                 1pct                                     AGXT_Gly216Arg                 1pct
AGXT            100      AGXT_Leu284Pro                 1pct                                     AGXT_Leu384Pro                 1pct
AGXT            114      AGXT_Asp129His                 1pct                                     AGXT_Asp243His                 1pct
AGXT            114      AGXT_Gly47Arg                  1pct                                     AGXT_Gly161Arg                 1pct
AGXT            115      AGXT_Arg118Cys                 1pct                                     AGXT_Arg233Cys                 1pct
AGXT            115      AGXT_Arg118His                 1pct                                     AGXT_Arg233His                 1pct
AGXT            115      AGXT_Gly41Arg                  1pct                                     AGXT_Gly156Arg                 1pct
AGXT            115      AGXT_Leu269Pro                 1pct                                     AGXT_Leu384Pro                 1pct
AGXT            171      AGXT_Arg118Cys                 1pct                                     AGXT_Arg289Cys                 1pct
AGXT            171      AGXT_Arg118His                 1pct                                     AGXT_Arg289His                 1pct
AGXT            183      AGXT_Arg118Cys                 1pct                                     AGXT_Arg301Cys                 1pct
AGXT            183      AGXT_Leu101Pro                 1pct                                     AGXT_Leu284Pro                 1pct
AGXT            197      AGXT_Arg36Cys                  1pct                                     AGXT_Arg233Cys                 1pct
AGXT            197      AGXT_Arg36His                  1pct                                     AGXT_Arg233His                 1pct
AGXT            253      AGXT_Arg36Cys                  1pct                                     AGXT_Arg289Cys                 1pct
AGXT            253      AGXT_Arg36His                  1pct                                     AGXT_Arg289His                 1pct
AGXT            258      AGXT_Leu26Pro                  1pct                                     AGXT_Leu284Pro                 1pct
AGXT            258      AGXT_Leu101Pro                 1pct                                     AGXT_Leu359Pro                 1pct
ALAS2           37       ALAS2_Arg411Gln                Sahni                                    ALAS2_Arg448Gln                Lacoste
ALAS2           37       ALAS2_Ile252Thr                Sahni                                    ALAS2_Ile289Thr                Lacoste
ALAS2           37       ALAS2_Ile439Asn                1pct; Sahni                              ALAS2_Ile476Asn                Lacoste
ALDOA           1        ALDOA_Asp128Gly                Lacoste                                  ALDOA_Asp129Gly                Sahni
ALDOA           1        ALDOA_Cys338Tyr                Lacoste                                  ALDOA_Cys339Tyr                Sahni
AMT             97       AMT_Arg223His                  Sahni                                    AMT_Arg320His                  Lacoste
AMT             97       AMT_Asn48Ile                   Sahni                                    AMT_Asn145Ile                  Lacoste
AMT             97       AMT_Gly172Asp                  Sahni                                    AMT_Gly269Asp                  Lacoste
AMT             97       AMT_Val115Ala                  Sahni                                    AMT_Val212Ala                  Lacoste
ANG             24       ANG_Gln12Leu                   Lacoste                                  ANG_Gln36Leu                   Sahni
ANG             24       ANG_Pro112Leu                  Lacoste                                  ANG_Pro136Leu                  Sahni
ANTXR2          336      ANTXR2_Tyr45Cys                Sahni                                    ANTXR2_Tyr381Cys               Lacoste
ANTXR2          336      ANTXR2_Val50Phe                Sahni                                    ANTXR2_Val386Phe               Lacoste
ANTXR2          336      ANTXR2_Val58Ala                Sahni                                    ANTXR2_Val394Ala               Lacoste
APOC3           20       APOC3_Asp45Asn                 Lacoste                                  APOC3_Asp65Asn                 Sahni
APOC3           20       APOC3_Gln38Lys                 Lacoste                                  APOC3_Gln58Lys                 Sahni
APOC3           20       APOC3_Thr74Ala                 Lacoste                                  APOC3_Thr94Ala                 Sahni
APOD            20       APOD_Phe36Val                  Lacoste                                  APOD_Phe56Val                  Sahni
APOD            20       APOD_Thr158Lys                 Lacoste                                  APOD_Thr178Lys                 Sahni
APOH            19       APOH_Cys306Gly                 Lacoste                                  APOH_Cys325Gly                 Sahni
APOH            19       APOH_Trp316Ser                 Lacoste                                  APOH_Trp335Ser                 Sahni
BANK1           30       BANK1_Ala353Thr                Sahni                                    BANK1_Ala383Thr                Lacoste
BANK1           30       BANK1_Arg31His                 Sahni                                    BANK1_Arg61His                 Lacoste
BCHE            28       BCHE_Gln518Leu                 Lacoste                                  BCHE_Gln546Leu                 Sahni
BCHE            28       BCHE_Leu330Ile                 Lacoste                                  BCHE_Leu358Ile                 Sahni
BCHE            28       BCHE_Tyr128Cys                 Lacoste                                  BCHE_Tyr156Cys                 Sahni
BEST1           60       BEST1_Arg158Gly                Sahni                                    BEST1_Arg218Gly                Lacoste
BEST1           60       BEST1_Arg32Cys                 Sahni                                    BEST1_Arg92Cys                 Lacoste
BEST1           60       BEST1_Tyr25His                 Sahni                                    BEST1_Tyr85His                 Lacoste
BRAF            3        BRAF_Gly466Ala                 Lacoste                                  BRAF_Gly469Ala                 Lacoste
BRAF            3        BRAF_Gly466Glu                 Lacoste                                  BRAF_Gly469Glu                 1pct; Lacoste
C1QB            27       C1QB_Gly15Asp                  Lacoste                                  C1QB_Gly42Asp                  Sahni
C1QB            27       C1QB_Gly217Arg                 Lacoste                                  C1QB_Gly244Arg                 Sahni
C2              20       C2_Cys111Tyr                   Lacoste                                  C2_Cys131Tyr                   Sahni
C2              20       C2_Glu298Asp                   Lacoste                                  C2_Glu318Asp                   Sahni
C2              20       C2_Gly444Arg                   Lacoste                                  C2_Gly464Arg                   Sahni
C2              20       C2_Ser189Phe                   Lacoste                                  C2_Ser209Phe                   Sahni
CAPN3           512      CAPN3_Ala286Glu                Sahni                                    CAPN3_Ala798Glu                Lacoste
CAPN3           512      CAPN3_Thr194Lys                Sahni                                    CAPN3_Thr706Lys                Lacoste
CCN6            18       CCN6_Cys114Tyr                 Lacoste                                  CCN6_Cys132Tyr                 Sahni
CCN6            18       CCN6_Cys145Tyr                 Lacoste                                  CCN6_Cys163Tyr                 Sahni
CCN6            18       CCN6_Cys78Arg                  Lacoste                                  CCN6_Cys96Arg                  Sahni
CCN6            18       CCN6_Ser334Pro                 Lacoste                                  CCN6_Ser352Pro                 Sahni
CCN6            31       CCN6_Cys114Tyr                 Lacoste                                  CCN6_Cys145Tyr                 Lacoste
CCN6            31       CCN6_Cys132Tyr                 Sahni                                    CCN6_Cys163Tyr                 Sahni
CDK4            231      CDK4_Arg24Cys                  Sahni                                    CDK4_Arg255Cys                 Fragoza
CDK4            231      CDK4_Arg24His                  Fragoza; Sahni                           CDK4_Arg255His                 Fragoza
CETP            17       CETP_Asp442Gly                 Lacoste                                  CETP_Asp459Gly                 Sahni
CETP            17       CETP_Leu151Pro                 Lacoste                                  CETP_Leu168Pro                 Sahni
CETP            17       CETP_Leu296Gln                 Lacoste                                  CETP_Leu313Gln                 Sahni
CETP            17       CETP_Ser332Tyr                 Lacoste                                  CETP_Ser349Tyr                 Sahni
CFP             27       CFP_Arg73Trp                   Lacoste                                  CFP_Arg100Trp                  1pct; Sahni
CFP             27       CFP_Arg319Cys                  Lacoste                                  CFP_Arg346Cys                  1pct; Sahni
CFP             27       CFP_Trp294Ser                  Lacoste                                  CFP_Trp321Ser                  1pct; Sahni
CHRNA1          20       CHRNA1_Arg209Leu               Lacoste                                  CHRNA1_Arg229Leu               Sahni
CHRNA1          20       CHRNA1_Gly153Ser               Lacoste                                  CHRNA1_Gly173Ser               Sahni
CHRNA1          20       CHRNA1_Gly74Cys                Lacoste                                  CHRNA1_Gly94Cys                Sahni
CHRNA1          20       CHRNA1_Val156Met               Lacoste                                  CHRNA1_Val176Met               Sahni
CHRNA4          32       CHRNA4_Leu258Val               Lacoste                                  CHRNA4_Leu290Val               Sahni
CHRNA4          32       CHRNA4_Ser248Phe               Lacoste                                  CHRNA4_Ser280Phe               Sahni
CHRNA4          32       CHRNA4_Ser252Leu               Lacoste                                  CHRNA4_Ser284Leu               Sahni
CHRNA4          32       CHRNA4_Thr261Ile               Lacoste                                  CHRNA4_Thr293Ile               Sahni
CHRNB1          23       CHRNB1_Leu262Met               Lacoste                                  CHRNB1_Leu285Met               Sahni
CHRNB1          23       CHRNB1_Val266Met               Lacoste                                  CHRNB1_Val289Met               Sahni
CHRND           21       CHRND_Gln267Glu                Lacoste                                  CHRND_Gln288Glu                Sahni
CHRND           21       CHRND_Glu381Lys                Lacoste                                  CHRND_Glu402Lys                Sahni
CHRND           21       CHRND_Ile58Lys                 Lacoste                                  CHRND_Ile79Lys                 Sahni
CLCN2           476      CLCN2_Arg101Gln                Sahni                                    CLCN2_Arg577Gln                Lacoste
CLCN2           476      CLCN2_Gly239Glu                Sahni                                    CLCN2_Gly715Glu                Lacoste
CRYGD           1        CRYGD_Arg14Cys                 Lacoste                                  CRYGD_Arg15Cys                 Sahni
CRYGD           1        CRYGD_Glu106Ala                Lacoste                                  CRYGD_Glu107Ala                Sahni
CRYGD           1        CRYGD_Gly60Cys                 Lacoste                                  CRYGD_Gly61Cys                 Sahni
CRYGD           1        CRYGD_Pro23Thr                 Lacoste                                  CRYGD_Pro24Thr                 Sahni
D2HGDH          301      D2HGDH_Asn138Asp               Sahni                                    D2HGDH_Asn439Asp               Lacoste
D2HGDH          301      D2HGDH_Asp74Tyr                Sahni                                    D2HGDH_Asp375Tyr               Lacoste
D2HGDH          301      D2HGDH_Val143Ala               Sahni                                    D2HGDH_Val444Ala               Lacoste
DCX             10       DCX_Arg186Cys                  1pct                                     DCX_Arg196Cys                  1pct
DCX             10       DCX_Arg186His                  1pct                                     DCX_Arg196His                  1pct
DCX             108      DCX_Arg78His                   1pct                                     DCX_Arg186His                  1pct
DCX             108      DCX_Arg78Leu                   1pct                                     DCX_Arg186Leu                  1pct
DLD             35       DLD_Glu340Lys                  Lacoste                                  DLD_Glu375Lys                  Sahni
DLD             35       DLD_Gly194Cys                  Lacoste                                  DLD_Gly229Cys                  Sahni
DLD             35       DLD_Ile358Thr                  Lacoste                                  DLD_Ile393Thr                  Sahni
DLD             35       DLD_Lys37Glu                   Lacoste                                  DLD_Lys72Glu                   Sahni
DMD             3068     DMD_Ala353Val                  Sahni                                    DMD_Ala3421Val                 Lacoste
DMD             3068     DMD_Asp119Gly                  Sahni                                    DMD_Asp3187Gly                 Lacoste
DMD             3068     DMD_Asp267His                  Sahni                                    DMD_Asp3335His                 Lacoste
DMD             3068     DMD_Cys139Arg                  Sahni                                    DMD_Cys3207Arg                 Lacoste
ELANE           29       ELANE_Ala32Val                 Lacoste                                  ELANE_Ala61Val                 Sahni
ELANE           29       ELANE_Cys122Ser                Lacoste                                  ELANE_Cys151Ser                Sahni
ELANE           29       ELANE_Gly181Val                Lacoste                                  ELANE_Gly210Val                Sahni
EPB42           30       EPB42_Ala112Thr                Sahni                                    EPB42_Ala142Thr                Lacoste
EPB42           30       EPB42_Arg280Gln                Sahni                                    EPB42_Arg310Gln                Lacoste
EPB42           30       EPB42_Arg287Cys                Sahni                                    EPB42_Arg317Cys                Lacoste
F10             40       F10_Arg142Met                  Lacoste                                  F10_Arg182Met                  Sahni
F10             40       F10_Arg326Cys                  Lacoste                                  F10_Arg366Cys                  Sahni
F10             40       F10_Glu14Gly                   Lacoste                                  F10_Glu54Gly                   Sahni
F10             40       F10_Val342Ala                  Lacoste                                  F10_Val382Ala                  Sahni

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_70048/1232042155.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diff_ds['source_combo'] = diff_ds.apply(

In [243]:
# === Merge cross-dataset isoform duplicates (Sahni aa_change is canonical) ===

full_bu = full_df.copy()  # backup before merging

# Step 1: Identify cross-dataset pairs only (different_datasets pattern)
cross_dataset_pairs = pair_src_df[pair_src_df.pattern == 'different_datasets'].copy()
print(f"Cross-dataset isoform duplicate pairs to merge: {len(cross_dataset_pairs)}")
print(f"\nSource combo breakdown:")
cross_dataset_pairs['source_combo'] = cross_dataset_pairs.apply(
    lambda r: ' ↔ '.join(sorted([str(r.source_1), str(r.source_2)])), axis=1
)
print(cross_dataset_pairs['source_combo'].value_counts().to_string())

# Step 2: For each pair, determine which variant to keep (Sahni-side) and which to fold in
# Priority: variant from 1pct/Sahni keeps its gene_variant; Lacoste/Fragoza/other folds in

source_priority = ['1pct', 'Sahni', 'Rolland', 'Luck', 'Fragoza', 'Lacoste']

def get_priority(source_str):
    """Lower number = higher priority (keep this variant's aa numbering)."""
    if pd.isna(source_str):
        return 999
    sources = source_str.split('; ')
    best = 999
    for s in sources:
        if s in source_priority:
            best = min(best, source_priority.index(s))
    return best

# Build merge plan: for each pair, keep_variant (canonical) absorbs drop_variant
merge_plan = []
for _, row in cross_dataset_pairs.iterrows():
    pri1 = get_priority(row['source_1'])
    pri2 = get_priority(row['source_2'])
    
    if pri1 <= pri2:
        keep_variant = row['variant_1']
        drop_variant = row['variant_2']
    else:
        keep_variant = row['variant_2']
        drop_variant = row['variant_1']
    
    merge_plan.append({
        'gene': row['gene'],
        'offset': row['offset'],
        'keep_variant': keep_variant,
        'drop_variant': drop_variant,
        'keep_source': row['source_1'] if pri1 <= pri2 else row['source_2'],
        'drop_source': row['source_2'] if pri1 <= pri2 else row['source_1'],
    })

merge_plan_df = pd.DataFrame(merge_plan)
print(f"\nMerge plan: {len(merge_plan_df)} pairs")
print(f"  Variants to drop (fold into canonical): {merge_plan_df['drop_variant'].nunique()}")
print(f"\nKeep → Drop direction:")
print(merge_plan_df.groupby(['keep_source', 'drop_source']).size().to_string())

# Step 3: For each drop_variant, fold its data columns into the keep_variant row
# Columns that come from Lacoste (the main "drop" source):
lacoste_cols = ['Lacoste_ClinVar_class', 'Lacoste_Phenotype_annotation', 
                'Lacoste_dbSNP_ID', 'Lacoste_Uniprot', 'Lacoste_Mislocalized', 
                'Lacoste_Impact_score']

# Build a mapping: drop_variant -> keep_variant
drop_to_keep = dict(zip(merge_plan_df['drop_variant'], merge_plan_df['keep_variant']))

# For each drop_variant, transfer non-NaN values to the keep_variant row
full_df_indexed = full_df.set_index('gene_variant')

transferred = 0
for drop_var, keep_var in drop_to_keep.items():
    if drop_var not in full_df_indexed.index or keep_var not in full_df_indexed.index:
        continue
    
    drop_row = full_df_indexed.loc[drop_var]
    
    # Transfer all columns where keep_variant is NaN but drop_variant has data
    for col in full_df_indexed.columns:
        if col in ['gene_symbol', 'aa_change', 'gene_variant', 'gene_symbol_old', 'alias_symbol']:
            continue  # Don't overwrite identity columns
        
        # Handle potential duplicate index (shouldn't happen after dedup, but be safe)
        keep_val = full_df_indexed.at[keep_var, col] if keep_var in full_df_indexed.index else np.nan
        drop_val = drop_row[col] if not isinstance(drop_row, pd.DataFrame) else drop_row.iloc[0][col]
        
        if pd.isna(keep_val) and pd.notna(drop_val):
            full_df_indexed.at[keep_var, col] = drop_val
            transferred += 1
    
    # Update Source columns for keep_variant
    keep_source = full_df_indexed.at[keep_var, 'Source']
    drop_source = drop_row['Source'] if not isinstance(drop_row, pd.DataFrame) else drop_row.iloc[0]['Source']
    
    if pd.notna(drop_source):
        if pd.notna(keep_source):
            all_sources = keep_source.split('; ') + drop_source.split('; ')
            unique_sources = list(dict.fromkeys(all_sources))
            full_df_indexed.at[keep_var, 'Source'] = '; '.join(unique_sources)
        else:
            full_df_indexed.at[keep_var, 'Source'] = drop_source

print(f"\nTransferred {transferred} non-NaN values from drop variants to keep variants")

# Step 4: Remove the drop_variants from the dataset
variants_to_drop = set(drop_to_keep.keys())
n_before = len(full_df_indexed)
full_df = full_df_indexed.drop(index=list(variants_to_drop & set(full_df_indexed.index)), errors='ignore').reset_index()
n_after = len(full_df)
print(f"\nRemoved {n_before - n_after} isoform-duplicate rows")

# Step 5: Recalculate Source_Simple and n_sources
full_df['Source_Simple'] = full_df['Source'].apply(get_sources_simple)
full_df['n_sources'] = full_df['Source'].apply(lambda x: len(x.split('; ')) if pd.notna(x) else 0)

print(f"\nFinal dataset after isoform deduplication: {full_df.shape}")
print(f"Unique variants: {full_df.gene_variant.nunique()}")

# Step 6: Show what was merged (for verification)
print(f"\n=== Merged isoform pairs (showing transferred Lacoste data) ===")
merged_variants = set(drop_to_keep.values())
verify_df = full_df[full_df.gene_variant.isin(merged_variants)]
verify_cols = ['gene_variant', 'Source_Simple'] + [c for c in lacoste_cols if c in full_df.columns]
print(verify_df[verify_cols].to_string(index=False))

# Step 7: Log the mapping for traceability
print(f"\n=== Isoform mapping log (drop → keep) ===")
print(f"{'Drop variant (alt isoform)':<35} {'Keep variant (canonical)':<35} {'Drop source':<15} {'Keep source':<15}")
print("-" * 105)
for _, row in merge_plan_df.iterrows():
    print(f"{row['drop_variant']:<35} {row['keep_variant']:<35} {row['drop_source']:<15} {row['keep_source']:<15}")

Cross-dataset isoform duplicate pairs to merge: 302

Source combo breakdown:
source_combo
Lacoste ↔ Sahni             285
1pct; Sahni ↔ Lacoste         9
Lacoste ↔ Rolland; Sahni      4
Fragoza; Sahni ↔ Lacoste      3
Fragoza ↔ Sahni               1

Merge plan: 302 pairs
  Variants to drop (fold into canonical): 302

Keep → Drop direction:
keep_source     drop_source
1pct; Sahni     Lacoste          9
Fragoza; Sahni  Lacoste          3
Rolland; Sahni  Lacoste          4
Sahni           Fragoza          1
                Lacoste        285

Transferred 1581 non-NaN values from drop variants to keep variants

Removed 302 isoform-duplicate rows

Final dataset after isoform deduplication: (6129, 57)
Unique variants: 6129

=== Merged isoform pairs (showing transferred Lacoste data) ===
       gene_variant           Source_Simple Lacoste_ClinVar_class                                     Lacoste_Phenotype_annotation Lacoste_dbSNP_ID Lacoste_Uniprot  Lacoste_Mislocalized  Lacoste_Impact_score
     ACADM_Ala52Val          Lacoste; Sahni                   NaN                   Medium chain acyl CoA dehydrogenase deficiency              NaN          P11310                   0.0              0.120104
    ACADM_Arg206Cys          Lacoste; Sahni            Pathogenic                   Medium chain acyl CoA dehydrogenase deficiency              NaN          P11310                   0.0                   NaN
    ACADM_Lys329Glu          Lacoste; Sahni                   VUS                   Medium chain acyl CoA dehydrogenase deficiency       rs77931234          P11310                   0.0              0.072675
    ACADM_Met274Val          Lacoste; Sahni                   NaN                   Medium chain acyl CoA dehydrogenase deficiency              NaN          P11310                   0.0              0.099586
   ACADSB_Glu387Lys          Lacoste; Sahni                   VUS                     2-Methylbutyryl-CoA dehydrogenase deficiency      rs188094280          P45954                   0.0                   NaN
   ACADSB_Thr148Ile          Lacoste; Sahni                   VUS                     2-Methylbutyryl-CoA dehydrogenase deficiency       rs58639322          P45954                   0.0                   NaN
   ACADSB_Tyr283Cys          Lacoste; Sahni                   VUS                     2-Methylbutyryl-CoA dehydrogenase deficiency      rs201035053          P45954                   0.0              0.082419
      AGT_Arg375Gln          Lacoste; Sahni            Pathogenic                                         Renal tubular dysgenesis       rs74315283          P01019                   0.0              0.315075
       AGT_Leu43Phe          Lacoste; Sahni                   VUS                                                     Preeclampsia       rs41271499          P01019                   0.0              0.253351
      AGT_Thr207Met          Lacoste; Sahni                Benign                                   Hypertension, association with           rs4762          P01019                   0.0              0.228641
      AGT_Tyr281Cys          Lacoste; Sahni                   VUS                                                     Hypertension       rs56073403          P01019                   0.0              0.401458
    ALAS2_Arg411Gln          Lacoste; Sahni                   NaN                                            Sideroblastic anaemia              NaN          P22557                   0.0              0.183719
    ALAS2_Ile252Thr          Lacoste; Sahni                   NaN                                            Sideroblastic anaemia              NaN          P22557                   0.0              0.190913
    ALAS2_Ile439Asn    1pct; Lacoste; Sahni            Pathogenic                                            Sideroblastic anaemia      rs137852299          P22557                   0.0              0.234583
    ALDOA_Asp129Gly          Lacoste; Sahni            Pathogenic                                            Aldolase A deficiency      rs121909533          P04075                   0.0              0.031162
    ALDOA_Cys339Tyr          Lacoste; Sahni                   NaN                                            Aldolase A deficiency              NaN          P04075                   0.0              0.010624
      AMT_Arg223His          Lacoste; Sahni            Pathogenic                                    Hyperglycinaemia, non-ketotic      rs121964985          P48728                   0.0              0.086822
       AMT_Asn48Ile          Lacoste; Sahni            Pathogenic                                    Hyperglycinaemia, non-ketotic              NaN          P48728                   0.0              0.080302
      AMT_Gly172Asp          Lacoste; Sahni            Pathogenic                                    Hyperglycinaemia, non-ketotic      rs121964981          P48728                   0.0              0.048847
      AMT_Val115Ala          Lacoste; Sahni                   VUS                                    Hyperglycinaemia, non-ketotic      rs201141125          P48728                   0.0              0.127006
       ANG_Gln36Leu          Lacoste; Sahni            Pathogenic                                    Amyotrophic lateral sclerosis      rs121909535          P03950                   1.0              0.418067
      ANG_Pro136Leu          Lacoste; Sahni            Pathogenic                                    Amyotrophic lateral sclerosis      rs121909543          P03950                   1.0              0.315162
    ANTXR2_Tyr45Cys          Lacoste; Sahni            Pathogenic                                   Fibromatosis, juvenile hyaline      rs137852901          P58335                   0.0                   NaN
    ANTXR2_Val50Phe          Lacoste; Sahni                   NaN                                   Fibromatosis, juvenile hyaline              NaN          P58335                   0.0                   NaN
    ANTXR2_Val58Ala          Lacoste; Sahni                   NaN                                   Fibromatosis, juvenile hyaline              NaN          P58335                   0.0              0.421934
     APOC3_Asp65Asn          Lacoste; Sahni                   VUS                                        Apolipoprotein C3 variant      rs149707394          P02656                   0.0                   NaN
     APOC3_Gln58Lys          Lacoste; Sahni                   NaN                                            Hypertriglyceridaemia              NaN          P02656                   0.0              0.475225
     APOC3_Thr94Ala          Lacoste; Sahni            Pathogenic                                     Apolipoprotein C3 deficiency      rs121918381          P02656                   0.0              0.047289
      APOD_Phe56Val          Lacoste; Sahni                   NaN                 Decr. HDL3-C and apoA-I level in females, assoc.      rs144811342          P05090                   0.0                   NaN
     APOD_Thr178Lys          Lacoste; Sahni                   NaN                   Incr. triglyceride level in males, association           rs5955          P05090                   0.0                   NaN
     APOH_Cys325Gly          Lacoste; Sahni                   NaN                    Apolipoprotein H deficiency, association with        rs1801689          P02749                   1.0                   NaN
     APOH_Trp335Ser          Lacoste; Sahni                   NaN                    Apolipoprotein H deficiency, association with        rs1801690          P02749                   0.0                   NaN
    BANK1_Ala353Thr          Lacoste; Sahni                   NaN               Systemic lupus erythematosus, prot. against, assoc        rs3733197          Q8NDB2                   0.0                   NaN
     BANK1_Arg31His          Lacoste; Sahni                   VUS               Systemic lupus erythematosus, prot. against, assoc       rs10516487          Q8NDB2                   0.0                   NaN
     BCHE_Gln546Leu          Lacoste; Sahni                   NaN                                 Butyrylcholinesterase deficiency              NaN          P06276                   0.0              0.593967
     BCHE_Leu358Ile          Lacoste; Sahni                   VUS                                    Butyrylcholinesterase variant      rs121918557          P06276                   0.0              0.075932
     BCHE_Tyr156Cys          Lacoste; Sahni            Pathogenic                                 Butyrylcholinesterase deficiency      rs121918558          P06276                   0.0              0.133861
    BEST1_Arg158Gly          Lacoste; Sahni            Pathogenic                                           Best macular dystrophy              NaN          O76090                   0.0                   NaN
     BEST1_Arg32Cys          Lacoste; Sahni            Pathogenic                                           Best macular dystrophy              NaN          O76090                   0.0                   NaN
     BEST1_Tyr25His          Lacoste; Sahni            Pathogenic                                           Best macular dystrophy       rs28940274          O76090                   0.0                   NaN
     C1QB_Gly244Arg          Lacoste; Sahni            Pathogenic                                           C1Q deficiency, type B       rs34813378          P02746                   0.0                   NaN
      C1QB_Gly42Asp          Lacoste; Sahni                   NaN                                           C1Q deficiency, type B              NaN          P02746                   0.0                   NaN
       C2_Cys131Tyr          Lacoste; Sahni                   NaN                                         Complement C2 deficiency              NaN          P06681                   0.0              0.191701
       C2_Glu318Asp          Lacoste; Sahni                Benign                                         Complement C2 deficiency        rs9332739          P06681                   0.0              0.421352
       C2_Gly464Arg          Lacoste; Sahni                   NaN                                         Complement C2 deficiency      rs151340617          P06681                   0.0              0.192420
       C2_Ser209Phe          Lacoste; Sahni            Pathogenic                                         Complement C2 deficiency       rs28934590          P06681                   0.0              0.264873
    CAPN3_Ala286Glu          Lacoste; Sahni            Pathogenic                               Muscular dystrophy, limb girdle 2A      rs149095128          P20807                   0.0              0.036273
    CAPN3_Thr194Lys          Lacoste; Sahni                   NaN                                  Muscular dystrophy, limb girdle              NaN          P20807                   1.0              0.031461
     CCN6_Cys132Tyr          Lacoste; Sahni                   NaN                          Pseudorheumatoid dysplasia, progressive              NaN             NaN                   0.0              0.288128
     CCN6_Cys163Tyr          Lacoste; Sahni            Pathogenic                          Pseudorheumatoid dysplasia, progressive      rs121908899             NaN                   0.0                   NaN
      CCN6_Cys96Arg          Lacoste; Sahni            Pathogenic                          Pseudorheumatoid dysplasia, progressive      rs121908902             NaN                   0.0              0.301070
     CCN6_Ser352Pro          Lacoste; Sahni            Pathogenic               Spondyloepiphyseal dysplasia tarda and arthropathy      rs121908903             NaN                   0.0              0.088167
      CDK4_Arg24Cys          Fragoza; Sahni                   NaN                                                              NaN              NaN             NaN                   NaN                   NaN
     CETP_Asp459Gly          Lacoste; Sahni                   VUS                    Cholesterol ester transfer protein deficiency        rs2303790          P11597                   0.0                   NaN
     CETP_Leu168Pro          Lacoste; Sahni                   NaN                                       Hyperalphalipoproteinaemia              NaN          P11597                   0.0                   NaN
     CETP_Leu313Gln          Lacoste; Sahni                   NaN                   Higher HDL cholesterol level, association with              NaN          P11597                   0.0                   NaN
     CETP_Ser349Tyr          Lacoste; Sahni                Benign                               Reduced activity, association with              NaN          P11597                   0.0                   NaN
      CFP_Arg100Trp    1pct; Lacoste; Sahni            Pathogenic                                             Properdin deficiency      rs132630259          P27918                   0.0              0.147094
      CFP_Arg346Cys    1pct; Lacoste; Sahni                   NaN                                             Properdin deficiency              NaN          P27918                   1.0              0.501622
      CFP_Trp321Ser    1pct; Lacoste; Sahni                   NaN                                             Properdin deficiency              NaN          P27918                   1.0              0.433512
   CHRNA1_Arg229Leu          Lacoste; Sahni            Pathogenic                     Fetal akinesia deformation sequence disorder      rs137852809          P02708                   0.0              0.157807
   CHRNA1_Gly173Ser          Lacoste; Sahni            Pathogenic                                 Slow channel myasthenic syndrome      rs137852801          P02708                   0.0              0.328765
    CHRNA1_Gly94Cys          Lacoste; Sahni                   VUS                                   Congenital myasthenic syndrome      rs199470444          P02708                   0.0              0.284193
   CHRNA1_Val176Met          Lacoste; Sahni                   VUS                                 Slow channel myasthenic syndrome      rs137852799          P02708                   0.0              0.162392
   CHRNA4_Leu290Val          Lacoste; Sahni                   VUS                                 Epilepsy, nocturnal frontal lobe              NaN          P43681                   0.0              0.406388
   CHRNA4_Ser280Phe          Lacoste; Sahni            Pathogenic                                 Epilepsy, nocturnal frontal lobe      rs121909580          P43681                   0.0              0.543059
   CHRNA4_Ser284Leu          Lacoste; Sahni            Pathogenic                                 Epilepsy, nocturnal frontal lobe       rs28931591          P43681                   0.0              0.283612
   CHRNA4_Thr293Ile          Lacoste; Sahni            Pathogenic                                 Epilepsy, nocturnal frontal lobe      rs281865066          P43681                   0.0              0.323463
   CHRNB1_Leu285Met          Lacoste; Sahni            Pathogenic                                 Slow channel myasthenic syndrome      rs137852811          P11230                   0.0              0.081084
   CHRNB1_Val289Met          Lacoste; Sahni            Pathogenic                                 Slow channel myasthenic syndrome      rs137852810          P11230                   0.0              0.101857
    CHRND_Gln288Glu          Lacoste; Sahni                   VUS                                 Slow channel myasthenic syndrome       rs41265127          Q07001                   0.0              0.280884
    CHRND_Glu402Lys          Lacoste; Sahni                   VUS                                   Congenital myasthenic syndrome      rs145955590          Q07001                   0.0              0.217090
     CHRND_Ile79Lys          Lacoste; Sahni            Pathogenic                                   Congenital myasthenic syndrome      rs121909509          Q07001                   0.0                   NaN
    CLCN2_Arg101Gln          Lacoste; Sahni                   VUS                                 Idiopathic epilepsy, generalised      rs137852682          P51788                   0.0                   NaN
    CLCN2_Gly239Glu          Lacoste; Sahni                   VUS                                 Idiopathic epilepsy, generalised      rs137852681          P51788                   0.0              0.484141
     CRYGD_Arg15Cys          Lacoste; Sahni            Pathogenic                          Punctate cataract, juvenile progressive      rs121909595          P07320                   1.0              0.273768
    CRYGD_Glu107Ala          Lacoste; Sahni                   NaN                                                         Cataract              NaN          P07320                   1.0              0.261986
     CRYGD_Gly61Cys          Lacoste; Sahni                   VUS                                                         Cataract      rs150857132          P07320                   0.0              0.167602
     CRYGD_Pro24Thr          Lacoste; Sahni            Pathogenic                                                         Cataract       rs28931605          P07320                   0.0              0.300418
   D2HGDH_Asn138Asp          Lacoste; Sahni            Pathogenic                                     D-2-hydroxyglutaric aciduria      rs121434362          Q8N465                   0.0              0.572175
    D2HGDH_Asp74Tyr          Lacoste; Sahni            Pathogenic                                     D-2-hydroxyglutaric aciduria      rs267606759          Q8N465                   0.0              0.199081
   D2HGDH_Val143Ala          Lacoste; Sahni            Pathogenic                                     D-2-hydroxyglutaric aciduria      rs121434360          Q8N465                   0.0              0.267525
      DLD_Glu375Lys          Lacoste; Sahni            Pathogenic                        Dihydrolipoamide dehydrogenase deficiency      rs121964992          P09622                   0.0                   NaN
      DLD_Gly229Cys          Lacoste; Sahni            Pathogenic                        Dihydrolipoamide dehydrogenase deficiency      rs121964990          P09622                   0.0              0.049547
      DLD_Ile393Thr          Lacoste; Sahni            Pathogenic                        Dihydrolipoamide dehydrogenase deficiency      rs121964991          P09622                   0.0                   NaN
       DLD_Lys72Glu          Lacoste; Sahni            Pathogenic                        Dihydrolipoamide dehydrogenase deficiency      rs121964987          P09622                   0.0              0.053241
      DMD_Ala353Val          Lacoste; Sahni                   VUS                                     Muscular dystrophy, Duchenne      rs104894791          P11532                   0.0              0.095345
      DMD_Asp119Gly          Lacoste; Sahni            Pathogenic                                     Muscular dystrophy, Duchenne              NaN          P11532                   1.0              0.092163
      DMD_Asp267His          Lacoste; Sahni                   NaN                                     Muscular dystrophy, Duchenne              NaN          P11532                   0.0              0.557738
      DMD_Cys139Arg          Lacoste; Sahni            Pathogenic                                     Muscular dystrophy, Duchenne              NaN          P11532                   1.0              0.520182
     ELANE_Ala61Val          Lacoste; Sahni            Pathogenic                                             Neutropaenia, cyclic      rs137854447          P08246                   1.0              0.302275

In [256]:
gene_to_test = 'TAFAZZIN'

In [258]:
full_bu[full_bu.gene_symbol == gene_to_test]

,gene_symbol,gene_variant,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,Luck_omim_ids,...,Edgotype_class,Edgotype_source,Source,Source_Simple,n_sources,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,gene_symbol_old,alias_symbol
5582,TAFAZZIN,TAFAZZIN_Arg69Cys,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Arg69Cys,Pathogenic,allele_col,TAFAZZIN,NaN
5583,TAFAZZIN,TAFAZZIN_Gly128Val,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Gly128Val,Others,allele_col,TAFAZZIN,NaN
5584,TAFAZZIN,TAFAZZIN_Gly210Arg,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Gly210Arg,Pathogenic,allele_col,TAFAZZIN,NaN
5585,TAFAZZIN,TAFAZZIN_Leu141Arg,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Leu141Arg,Others,allele_col,TAFAZZIN,NaN
5608,TAFAZZIN,TAFAZZIN_Arg94Cys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Arg94Cys,Pathogenic,Lacoste,TAZ,WWTR1
5609,TAFAZZIN,TAFAZZIN_Gly197Val,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Gly197Val,NaN,NaN,TAZ,WWTR1
5610,TAFAZZIN,TAFAZZIN_Gly240Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Gly240Arg,Pathogenic,Lacoste,TAZ,WWTR1
5611,TAFAZZIN,TAFAZZIN_Leu210Arg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Leu210Arg,NaN,NaN,TAZ,WWTR1

In [259]:
full_df[full_df.gene_symbol == gene_to_test]

,gene_variant,gene_symbol,Sahni_clinical_significance,Sahni_Category,Sahni_Chaperone_binding,Rolland_category,Rolland_Phenotype,Luck_assay_id,Luck_pathogenecity,Luck_omim_ids,...,Edgotype_class,Edgotype_source,Source,Source_Simple,n_sources,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,gene_symbol_old,alias_symbol
5323,TAFAZZIN_Arg69Cys,TAFAZZIN,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Arg69Cys,Pathogenic,allele_col,TAFAZZIN,NaN
5324,TAFAZZIN_Gly128Val,TAFAZZIN,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Gly128Val,Others,allele_col,TAFAZZIN,NaN
5325,TAFAZZIN_Gly210Arg,TAFAZZIN,Pathogenic,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone,Sahni,1,Gly210Arg,Pathogenic,allele_col,TAFAZZIN,NaN
5326,TAFAZZIN_Leu141Arg,TAFAZZIN,Others,NaN,Y,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Sahni_Chaperone; Lacoste_Imaging,Lacoste; Sahni,2,Leu141Arg,Others,allele_col,TAFAZZIN,NaN
5349,TAFAZZIN_Arg94Cys,TAFAZZIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Arg94Cys,Pathogenic,Lacoste,TAZ,WWTR1
5350,TAFAZZIN_Gly240Arg,TAFAZZIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Lacoste_Imaging,Lacoste,1,Gly240Arg,Pathogenic,Lacoste,TAZ,WWTR1

In [ ]:
pair_src_df.to_csv('../3_outputs/Merging_datasets_offset_variants_for_Tong.csv', index=False)

In [ ]:
full_bu[full_bu.gene_symbol == 'TAFAZZIN'][['gene_variant', 'Source_Simple']].to_csv('../3_outputs/Merging_datasets_TAFAZZIN_variants.csv', index=False)

In [260]:
# This approach removes pairs of dubious variants where there are multiple pairs with the same offset in the same gene. 
# This means that it's missing if only a single pair is present and if the offset changes in the gene 
# TAFAZZIN is an example of the latter, see above, 4 variants seem to be duplicates but only two are fixed because they share the same offset.

# Merging Abundance and Imaging data

In [270]:
# === Unify Imaging and Abundance hits across datasets ===

# -------------------------------------------------------
# 1. IMAGING HIT UNIFIED
# -------------------------------------------------------

# Audit values
print("=== Imaging columns audit ===")
print(f"\nimaging_hit (1pct):")
print(full_df['imaging_hit'].value_counts(dropna=False))
print(f"\nLacoste_Mislocalized:")
print(full_df['Lacoste_Mislocalized'].value_counts(dropna=False))

# Harmonize Lacoste_Mislocalized (1.0/0.0 float) to True/False
full_df['_lacoste_imaging_hit'] = full_df['Lacoste_Mislocalized'].map({1.0: True, 0.0: False})

# Check concordance for overlapping variants
img_both = full_df[full_df['imaging_hit'].notna() & full_df['_lacoste_imaging_hit'].notna()].copy()
print(f"\n=== Imaging concordance (variants with both 1pct and Lacoste) ===")
print(f"Variants with both: {len(img_both)}")

if len(img_both) > 0:
    img_both['_img_concordant'] = img_both['imaging_hit'] == img_both['_lacoste_imaging_hit']
    concordant = img_both['_img_concordant'].sum()
    discordant = (~img_both['_img_concordant']).sum()
    print(f"  Concordant: {concordant} ({100*concordant/len(img_both):.1f}%)")
    print(f"  Discordant: {discordant} ({100*discordant/len(img_both):.1f}%)")
    
    if discordant > 0:
        ct = pd.crosstab(
            img_both['imaging_hit'].map({True: '1pct_True', False: '1pct_False'}),
            img_both['_lacoste_imaging_hit'].map({True: 'Lacoste_True', False: 'Lacoste_False'}),
            margins=True
        )
        print(f"\n  Cross-tab:")
        print(ct.to_string())
        
        disc = img_both[~img_both['_img_concordant']]
        print(f"\n  Discordant variants:")
        print(disc[['gene_variant', 'imaging_hit', 'Lacoste_Mislocalized', 'Source_Simple']].to_string(index=False))

# Build unified column: 1pct > Lacoste
full_df['imaging_hit_unified'] = full_df['imaging_hit'].where(
    full_df['imaging_hit'].notna(),
    full_df['_lacoste_imaging_hit']
)

# Track source
def get_imaging_source(row):
    if pd.notna(row['imaging_hit']):
        return '1pct'
    elif pd.notna(row['_lacoste_imaging_hit']):
        return 'Lacoste'
    return np.nan

full_df['imaging_hit_unified_source'] = full_df.apply(get_imaging_source, axis=1)

# Flag discordance
def get_imaging_discordance(row):
    if pd.notna(row['imaging_hit']) and pd.notna(row['_lacoste_imaging_hit']):
        if row['imaging_hit'] != row['_lacoste_imaging_hit']:
            return True
        else:
            return False
    return np.nan

full_df['imaging_hit_discordant'] = full_df.apply(get_imaging_discordance, axis=1)

# Clean up temp column
full_df.drop(columns=['_lacoste_imaging_hit'], inplace=True)

print(f"\n=== imaging_hit_unified ===")
print(full_df['imaging_hit_unified'].value_counts(dropna=False))
print(f"\n  Source breakdown:")
print(full_df['imaging_hit_unified_source'].value_counts(dropna=False))
print(f"\n  Discordant flags:")
print(full_df['imaging_hit_discordant'].value_counts(dropna=False))


# -------------------------------------------------------
# 2. ABUNDANCE HIT UNIFIED
# -------------------------------------------------------

print("\n\n" + "=" * 60)
print("=== Abundance columns audit ===")
print(f"\ndualipa_hit (1pct):")
print(full_df['dualipa_hit'].value_counts(dropna=False))
print(f"\nSahni_Chaperone_binding:")
print(full_df['Sahni_Chaperone_binding'].value_counts(dropna=False))
print(f"\nFragoza_Abundance_Status:")
print(full_df['Fragoza_Abundance_Status'].value_counts(dropna=False))

# Harmonize Sahni_Chaperone_binding: Y (binds chaperone = unstable) -> True, N -> False
full_df['_sahni_abun_hit'] = full_df['Sahni_Chaperone_binding'].map({'Y': True, 'N': False})

# Harmonize Fragoza_Abundance_Status: unstable/partially_unstable -> True, stable -> False
full_df['_fragoza_abun_hit'] = full_df['Fragoza_Abundance_Status'].map({
    'unstable': True,
    'partially_unstable': True,
    'stable': False,
})

# Check pairwise concordance
abun_sources = {
    '1pct': 'dualipa_hit',
    'Sahni': '_sahni_abun_hit',
    'Fragoza': '_fragoza_abun_hit',
}

print(f"\n=== Abundance concordance (pairwise) ===")
for (name_a, col_a), (name_b, col_b) in combinations(abun_sources.items(), 2):
    both = full_df[full_df[col_a].notna() & full_df[col_b].notna()].copy()
    if len(both) == 0:
        print(f"\n{name_a} ∩ {name_b}: no overlap")
        continue
    
    both['_concordant'] = both[col_a] == both[col_b]
    concordant = both['_concordant'].sum()
    discordant = (~both['_concordant']).sum()
    
    print(f"\n{name_a} ∩ {name_b}: {len(both)} overlapping variants")
    print(f"  Concordant: {concordant} ({100*concordant/len(both):.1f}%)")
    print(f"  Discordant: {discordant} ({100*discordant/len(both):.1f}%)")
    
    if discordant > 0:
        ct = pd.crosstab(
            both[col_a].map({True: f'{name_a}_True', False: f'{name_a}_False'}),
            both[col_b].map({True: f'{name_b}_True', False: f'{name_b}_False'}),
            margins=True
        )
        print(f"  Cross-tab:")
        print(ct.to_string())
        
        disc = both[~both['_concordant']]
        print(f"\n  Discordant variants:")
        show_cols = ['gene_variant', col_a, col_b, 'Source_Simple']
        # Also show original columns for context
        extra_cols = ['Sahni_Chaperone_binding', 'Fragoza_Abundance_Status', 'dualipa_hit']
        show_cols += [c for c in extra_cols if c not in show_cols and c in full_df.columns]
        print(disc[show_cols].to_string(index=False))

# Build unified column: 1pct > Sahni > Fragoza
full_df['abundance_hit_unified'] = (
    full_df['dualipa_hit']
    .where(full_df['dualipa_hit'].notna(), full_df['_sahni_abun_hit'])
    .where(full_df['dualipa_hit'].notna() | full_df['_sahni_abun_hit'].notna(), full_df['_fragoza_abun_hit'])
)

# Track source
def get_abundance_source(row):
    if pd.notna(row['dualipa_hit']):
        return '1pct'
    elif pd.notna(row['_sahni_abun_hit']):
        return 'Sahni'
    elif pd.notna(row['_fragoza_abun_hit']):
        return 'Fragoza'
    return np.nan

full_df['abundance_hit_unified_source'] = full_df.apply(get_abundance_source, axis=1)

# Flag discordance: check if ANY pair of available sources disagree
def get_abundance_discordance(row):
    values = {}
    if pd.notna(row['dualipa_hit']):
        values['1pct'] = row['dualipa_hit']
    if pd.notna(row['_sahni_abun_hit']):
        values['Sahni'] = row['_sahni_abun_hit']
    if pd.notna(row['_fragoza_abun_hit']):
        values['Fragoza'] = row['_fragoza_abun_hit']
    
    if len(values) < 2:
        return np.nan  # Can't assess discordance with <2 sources
    
    unique_vals = set(values.values())
    return len(unique_vals) > 1  # True if discordant

full_df['abundance_hit_discordant'] = full_df.apply(get_abundance_discordance, axis=1)

# Clean up temp columns
full_df.drop(columns=['_sahni_abun_hit', '_fragoza_abun_hit'], inplace=True)

print(f"\n=== abundance_hit_unified ===")
print(full_df['abundance_hit_unified'].value_counts(dropna=False))
print(f"\n  Source breakdown:")
print(full_df['abundance_hit_unified_source'].value_counts(dropna=False))
print(f"\n  Discordant flags:")
print(full_df['abundance_hit_discordant'].value_counts(dropna=False))

# -------------------------------------------------------
# 3. SUMMARY
# -------------------------------------------------------
print("\n\n" + "=" * 60)
print("=== UNIFIED COLUMNS SUMMARY ===")
print(f"\nTotal variants: {len(full_df)}")
print(f"  With imaging_hit_unified:   {full_df['imaging_hit_unified'].notna().sum()}")
print(f"    of which discordant:      {(full_df['imaging_hit_discordant'] == True).sum()}")
print(f"  With abundance_hit_unified: {full_df['abundance_hit_unified'].notna().sum()}")
print(f"    of which discordant:      {(full_df['abundance_hit_discordant'] == True).sum()}")

=== Imaging columns audit ===

imaging_hit (1pct):
imaging_hit
NaN      5335
False     673
True      121
Name: count, dtype: int64

Lacoste_Mislocalized:
Lacoste_Mislocalized
NaN    3959
0.0    1925
1.0     245
Name: count, dtype: int64

=== Imaging concordance (variants with both 1pct and Lacoste) ===
Variants with both: 60
  Concordant: 44 (73.3%)
  Discordant: 16 (26.7%)

  Cross-tab:
_lacoste_imaging_hit  Lacoste_False  Lacoste_True  All
imaging_hit
1pct_False                       39             4   43
1pct_True                        12             5   17
All                              51             9   60

  Discordant variants:
    gene_variant imaging_hit  Lacoste_Mislocalized                          Source_Simple
  AIPL1_Met79Thr        True                   0.0                   1pct; Lacoste; Sahni
  FBP1_Gly260Arg        True                   0.0 1pct; Fragoza; Lacoste; Rolland; Sahni
 FOXP3_Leu242Pro        True                   0.0                   1pct; Lacoste; Sahni
   MLH1_Ser44Phe        True                   0.0                   1pct; Lacoste; Sahni
  PNPO_Arg116Gln        True                   0.0                   1pct; Lacoste; Sahni
   PNPO_Arg95Cys        True                   0.0                   1pct; Lacoste; Sahni
   PNPO_Arg95His        True                   0.0                   1pct; Lacoste; Sahni
   RP2_Leu253Arg        True                   0.0                   1pct; Lacoste; Sahni
 RPS19_Arg101His       False                   1.0                          1pct; Lacoste
  RPS19_Arg62Trp       False                   1.0                          1pct; Lacoste
 RPS19_Gly127Glu       False                   1.0                          1pct; Lacoste
  RPS19_Val15Phe       False                   1.0                          1pct; Lacoste
SFTPA2_Gly231Val        True                   0.0                   1pct; Lacoste; Sahni
SFTPA2_Phe198Ser        True                   0.0                   1pct; Lacoste; Sahni
   TAT_Arg119Trp        True                   0.0          1pct; Fragoza; Lacoste; Sahni
   TAT_Leu273Pro        True                   0.0          1pct; Fragoza; Lacoste; Sahni

=== imaging_hit_unified ===
imaging_hit_unified
NaN      3225
False    2547
True      357
Name: count, dtype: int64

  Source breakdown:
imaging_hit_unified_source
NaN        3225
Lacoste    2110
1pct        794
Name: count, dtype: int64

  Discordant flags:
imaging_hit_discordant
NaN      6069
False      44
True       16
Name: count, dtype: int64


============================================================
=== Abundance columns audit ===

dualipa_hit (1pct):
dualipa_hit
NaN      5338
False     525
True      266
Name: count, dtype: int64

Sahni_Chaperone_binding:
Sahni_Chaperone_binding
NaN    3765
N      1832
Y       532
Name: count, dtype: int64

Fragoza_Abundance_Status:
Fragoza_Abundance_Status
NaN                   5851
stable                 214
partially_unstable      55
unstable                 9
Name: count, dtype: int64

=== Abundance concordance (pairwise) ===

1pct ∩ Sahni: 146 overlapping variants
  Concordant: 101 (69.2%)
  Discordant: 45 (30.8%)
  Cross-tab:
_sahni_abun_hit  Sahni_False  Sahni_True  All
dualipa_hit
1pct_False                78          22  100
1pct_True                 23          23   46
All                      101          45  146

  Discordant variants:
     gene_variant dualipa_hit _sahni_abun_hit                          Source_Simple Sahni_Chaperone_binding Fragoza_Abundance_Status
   AGXT_Arg233Leu        True           False                            1pct; Sahni                       N                      NaN
  ALAS2_Ile439Asn       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
 CDKN1A_Asp149Gly       False            True                            1pct; Sahni                       Y                      NaN
  CDKN1A_Ser31Arg       False            True                   1pct; Fragoza; Sahni                       Y                   stable
   CHN1_Ala223Val        True           False                            1pct; Sahni                       N                      NaN
   CHN1_Gly228Ser        True           False                            1pct; Sahni                       N                      NaN
   CHN1_Pro252Gln        True           False                            1pct; Sahni                       N                      NaN
   CRYAB_Arg56Trp        True           False                   1pct; Lacoste; Sahni                       N                      NaN
   EFHC1_Pro77Thr        True           False          1pct; Lacoste; Rolland; Sahni                       N                      NaN
   FBP1_Asn213Lys        True           False          1pct; Fragoza; Rolland; Sahni                       N                      NaN
    FXN_Arg165Cys        True           False                   1pct; Lacoste; Sahni                       N                      NaN
    GAMT_Trp20Ser        True           False                            1pct; Sahni                       N                      NaN
   GFAP_Arg258Pro       False            True          1pct; Lacoste; Rolland; Sahni                       Y                      NaN
   GFAP_Asp295Asn        True           False          1pct; Lacoste; Rolland; Sahni                       N                      NaN
   GFAP_Glu207Gln        True           False                   1pct; Lacoste; Sahni                       N                      NaN
   GFAP_Glu374Gly        True           False          1pct; Lacoste; Rolland; Sahni                       N                      NaN
   KRT2_Asn186Lys        True           False          1pct; Lacoste; Rolland; Sahni                       N                      NaN
   KRT2_Gln181Pro        True           False                   1pct; Lacoste; Sahni                       N                      NaN
   KRT2_Gly219Asp        True           False          1pct; Lacoste; Rolland; Sahni                       N                      NaN
   MCEE_Arg143His        True           False 1pct; Fragoza; Lacoste; Rolland; Sahni                       N                      NaN
   MID1_Cys266Arg        True           False                   1pct; Lacoste; Sahni                       N                      NaN
   MID1_Lys370Glu        True           False                   1pct; Lacoste; Sahni                       N                      NaN
   MID1_Pro151Leu        True           False                   1pct; Lacoste; Sahni                       N                      NaN
    MVK_Asn205Asp       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
    MVK_Asn301Thr        True           False          1pct; Fragoza; Lacoste; Sahni                       N                      NaN
 NEUROG3_Arg93Leu        True           False                            1pct; Sahni                       N                      NaN
  NR0B1_Arg267Pro       False            True                            1pct; Sahni                       Y                      NaN
   PHYH_Ile199Phe       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
  PITX2_Leu107Gln       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
  PITX2_Pro117Arg       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
   PKP2_Ser140Phe       False            True          1pct; Lacoste; Rolland; Sahni                       Y                      NaN
   PMP22_Leu80Pro        True           False                   1pct; Lacoste; Sahni                       N                      NaN
PRKAR1A_Ala213Asp       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
 PRKAR1A_Arg74Cys       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
 RAD51D_Glu233Gly       False            True                   1pct; Rolland; Sahni                       Y                      NaN
    RP2_Arg282Trp       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
  SFTPC_Cys189Gly        True           False                   1pct; Lacoste; Sahni                       N                      NaN
SMARCB1_Asn279Lys       False            True                            1pct; Sahni                       Y                      NaN
   STAR_Ala218Val       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
   STAR_Glu169Lys       False            True                            1pct; Sahni                       Y                      NaN
   STAR_Met144Arg       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
   STAR_Met225Thr       False            True                            1pct; Sahni                       Y                      NaN
     TH_Cys328Phe       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
     TH_Gln381Lys       False            True                   1pct; Lacoste; Sahni                       Y                      NaN
     TH_Thr245Pro       False            True                   1pct; Lacoste; Sahni                       Y                      NaN

1pct ∩ Fragoza: 3 overlapping variants
  Concordant: 3 (100.0%)
  Discordant: 0 (0.0%)

Sahni ∩ Fragoza: 4 overlapping variants
  Concordant: 3 (75.0%)
  Discordant: 1 (25.0%)
  Cross-tab:
_fragoza_abun_hit  Fragoza_False  All
_sahni_abun_hit
Sahni_False                    3    3
Sahni_True                     1    1
All                            4    4

  Discordant variants:
   gene_variant _sahni_abun_hit _fragoza_abun_hit        Source_Simple Sahni_Chaperone_binding Fragoza_Abundance_Status dualipa_hit
CDKN1A_Ser31Arg            True             False 1pct; Fragoza; Sahni                       Y                   stable       False

=== abundance_hit_unified ===
abundance_hit_unified
NaN      2846
False    2466
True      817
Name: count, dtype: int64

  Source breakdown:
abundance_hit_unified_source
NaN        2846
Sahni      2218
1pct        791
Fragoza     274
Name: count, dtype: int64

  Discordant flags:
abundance_hit_discordant
NaN      5982
False     102
True       45
Name: count, dtype: int64


============================================================
=== UNIFIED COLUMNS SUMMARY ===

Total variants: 6129
  With imaging_hit_unified:   2904
    of which discordant:      16
  With abundance_hit_unified: 3283
    of which discordant:      45

In [286]:
full_df = full_df[['gene_variant', 'gene_symbol', 'aa_change', 
       'clinvar_clinical_significance_unified', 'clinvar_clinical_significance_source_unified',
       'Edgotype_class', 'Edgotype_source',
       'imaging_hit_unified', 'imaging_hit_unified_source',
       'imaging_hit_discordant', 
       'abundance_hit_unified', 'abundance_hit_unified_source', 'abundance_hit_discordant',
       'Source', 'Source_Simple', 'n_sources',
       'Sahni_clinical_significance',
       'Sahni_Category', 'Sahni_Chaperone_binding', 
       'Rolland_category', 'Rolland_Phenotype', 
       'Luck_assay_id', 'Luck_pathogenecity', 'Luck_omim_ids', 
       'Lacoste_ClinVar_class',
       'Lacoste_Phenotype_annotation', 'Lacoste_dbSNP_ID', 'Lacoste_Uniprot',
       'Lacoste_Mislocalized', 'Lacoste_Impact_score', 'Fragoza_ExAC_dbSNP_id',
       'Fragoza_ExAC_Mutation', 'Fragoza_ExAC_AF_all',
       'Fragoza_COSMIC_dbSNP_id', 'Fragoza_COSMIC_Mutation',
       'Fragoza_HGMD_Mutation', 'Fragoza_Abundance_HGVS_cDNA',
       'Fragoza_Abundance_Status', 'ClinVar_significance',
       'clinvar_clnsig_clean_literature', 'img_misloc_hit',
       'img_U2OS_prot_abun_t_pval', 'dualipa_abun_chg_dir',
       'img_U2OS_cc_t_adj_pval', 'img_U2OS_prot_abun_t_adj_pval',
       'img_U2OS_cc_t_stat', 'ppi_score', 'img_U2OS_cc_t_pval',
       'imaging_score', 'img_pheno_hit', 'dualipa_hit', 'ppi_num_edges',
       'imaging_hit', 'dualipa_score', 'ppi_hit', 'img_pheno_hit_strict',
       'clinvar_clnsig_clean_1pct', 'img_misloc_score',
       'img_U2OS_prot_abun_t_stat', 'img_Metadata_Bio_Batch',
       'dualipa_abun_change',  
       'gene_symbol_old',
       'alias_symbol'
       ]]

full_df

,gene_variant,gene_symbol,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,Edgotype_class,Edgotype_source,imaging_hit_unified,imaging_hit_unified_source,imaging_hit_discordant,...,dualipa_score,ppi_hit,img_pheno_hit_strict,clinvar_clnsig_clean_1pct,img_misloc_score,img_U2OS_prot_abun_t_stat,img_Metadata_Bio_Batch,dualipa_abun_change,gene_symbol_old,alias_symbol
0,A2M_Cys972Tyr,A2M,Cys972Tyr,Benign,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A2M,NaN
1,A4GALT_Ala219Val,A4GALT,Ala219Val,VUS,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A4GALT,NaN
2,A4GALT_Ala272Val,A4GALT,Ala272Val,NaN,NaN,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A4GALT,NaN
3,A4GALT_Cys96Tyr,A4GALT,Cys96Tyr,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A4GALT,NaN
4,A4GALT_Met183Lys,A4GALT,Met183Lys,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A4GALT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6124,NECTIN1_Thr131Ala,NECTIN1,Thr131Ala,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NECTIN1; PVRL1,NaN
6125,NHERF1_Arg153Gln,NHERF1,Arg153Gln,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHERF1; SLC9A3R1,NaN
6126,NHERF1_Leu110Val,NHERF1,Leu110Val,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NHERF1; SLC9A3R1,NaN
6127,YARS1_Glu196Lys,YARS1,Glu196Lys,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YARS1; YARS,NaN
6128,YARS1_Gly41Arg,YARS1,Gly41Arg,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YARS1; YARS,NaN

In [287]:
# save final full merged table
full_df.to_csv('../3_outputs/Unified_1pct_Sahni_Rolland_Luck_Lacoste_Fragoza_260213.csv', index=False)

# Add additional columns from allele_col

In [295]:
# Identify which allele_col columns are NOT already in full_df (to avoid redundancy)
existing_cols = set(full_df.columns)
allele_col_new_cols = [c for c in allele_col_dedup.columns if c not in existing_cols or c == 'gene_variant']

print(f"Columns from allele_col to add: {len(allele_col_new_cols) - 1}")  # -1 for gene_variant
print(allele_col_new_cols)

full_df_annotated = full_df.merge(
    allele_col_dedup[allele_col_new_cols],
    on='gene_variant',
    how='left',
)

print(f"full_df: {full_df.shape} → full_df_annotated: {full_df_annotated.shape}")
assert len(full_df_annotated) == len(full_df), f"Row count changed! {len(full_df)} → {len(full_df_annotated)} — duplicates in allele_col_dedup?"

full_df_annotated

Columns from allele_col to add: 1013

,gene_variant,gene_symbol,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,Edgotype_class,Edgotype_source,imaging_hit_unified,imaging_hit_unified_source,imaging_hit_discordant,...,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant,am_pathogenicity
0,A2M_Cys972Tyr,A2M,Cys972Tyr,Benign,allele_col,NaN,NaN,False,Lacoste,NaN,...,70-90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9488
1,A4GALT_Ala219Val,A4GALT,Ala219Val,VUS,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9612
2,A4GALT_Ala272Val,A4GALT,Ala272Val,NaN,NaN,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT_Cys96Tyr,A4GALT,Cys96Tyr,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9898
4,A4GALT_Met183Lys,A4GALT,Met183Lys,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.8767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6124,NECTIN1_Thr131Ala,NECTIN1,Thr131Ala,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,Rare genetic developmental defect during embry...,2.0,NaN,False,0.0604
6125,NHERF1_Arg153Gln,NHERF1,Arg153Gln,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,70-90,10-90,612287,autosomal dominant,OMIM,NaN,0.0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False,0.5088
6126,NHERF1_Leu110Val,NHERF1,Leu110Val,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,50-70,10-90,612287,autosomal dominant,OMIM,NaN,0.0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False,0.0954
6127,YARS1_Glu196Lys,YARS1,Glu196Lys,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,10-90,608323;619418,multiple,OMIM,NaN,0.0,"CHARCOT-MARIE-TOOTH DISEASE, DOMINANT INTERMED...",False,0.7318
6128,YARS1_Gly41Arg,YARS1,Gly41Arg,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,10-90,608323,autosomal dominant,OMIM,NaN,0.0,"CHARCOT-MARIE-TOOTH DISEASE, DOMINANT INTERMED...",False,0.9982

In [310]:
# Step 1: First merge on current gene_variant (as before)
existing_cols = set(full_df.columns)
allele_col_new_cols = [c for c in allele_col_dedup.columns if c not in existing_cols or c == 'gene_variant']

print(f"Columns from allele_col to add: {len(allele_col_new_cols) - 1}")
print(allele_col_new_cols)

full_df_annotated = full_df.merge(
    allele_col_dedup[allele_col_new_cols],
    on='gene_variant',
    how='left',
)

n_missing_before = full_df_annotated[allele_col_new_cols[2]].isna().sum()  # pick first non-key col
print(f"\nAfter primary merge: {n_missing_before} variants without allele_col annotation")

# Step 2: For rows still missing annotations, try matching via old gene symbol
missing_mask = full_df_annotated[allele_col_new_cols[2]].isna()
has_old_symbol = full_df_annotated['gene_symbol_old'].notna()
backfill_mask = missing_mask & has_old_symbol

print(f"Variants to attempt backfill with gene_symbol_old: {backfill_mask.sum()}")

if backfill_mask.sum() > 0:
    # Build temp gene_variant using old symbol
    full_df_annotated['_gene_variant_old'] = (
        full_df_annotated['gene_symbol_old'].str.split('; ').str[0] + '_' + full_df_annotated['aa_change']
    )
    
    # Merge allele_col on old gene_variant
    allele_col_for_backfill = allele_col_dedup[allele_col_new_cols].rename(
        columns={'gene_variant': '_gene_variant_old'}
    )
    
    backfill_df = full_df_annotated.loc[backfill_mask, ['_gene_variant_old']].merge(
        allele_col_for_backfill,
        on='_gene_variant_old',
        how='left',
    )
    
    # Fill in the missing values
    n_backfilled = 0
    for col in allele_col_new_cols:
        if col == 'gene_variant':
            continue
        if col in backfill_df.columns:
            new_vals = backfill_df[col].values
            old_vals = full_df_annotated.loc[backfill_mask, col].values
            fill_mask = pd.isna(old_vals) & pd.notna(new_vals)
            if fill_mask.any():
                full_df_annotated.loc[backfill_mask, col] = np.where(
                    pd.isna(full_df_annotated.loc[backfill_mask, col]),
                    backfill_df[col].values,
                    full_df_annotated.loc[backfill_mask, col]
                )
                n_backfilled += fill_mask.sum()
    
    # Clean up temp column
    full_df_annotated.drop(columns=['_gene_variant_old'], inplace=True)
    
    n_missing_after = full_df_annotated[allele_col_new_cols[2]].isna().sum()
    n_rescued = n_missing_before - n_missing_after
    print(f"Rescued {n_rescued} variants via gene_symbol_old backfill")
    print(f"Still missing: {n_missing_after}")

# Final check
print(f"\nfull_df: {full_df.shape} → full_df_annotated: {full_df_annotated.shape}")
assert len(full_df_annotated) == len(full_df), f"Row count changed!"

# Show remaining unannotated variants by source
still_missing = full_df_annotated[full_df_annotated[allele_col_new_cols[2]].isna()]
print(f"\nRemaining unannotated by Source_Simple:")
print(still_missing['Source_Simple'].value_counts(dropna=False))

full_df_annotated

Columns from allele_col to add: 1013

,gene_variant,gene_symbol,aa_change,clinvar_clinical_significance_unified,clinvar_clinical_significance_source_unified,Edgotype_class,Edgotype_source,imaging_hit_unified,imaging_hit_unified_source,imaging_hit_discordant,...,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant,am_pathogenicity
0,A2M_Cys972Tyr,A2M,Cys972Tyr,Benign,allele_col,NaN,NaN,False,Lacoste,NaN,...,70-90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9488
1,A4GALT_Ala219Val,A4GALT,Ala219Val,VUS,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9612
2,A4GALT_Ala272Val,A4GALT,Ala272Val,NaN,NaN,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A4GALT_Cys96Tyr,A4GALT,Cys96Tyr,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,0.9898
4,A4GALT_Met183Lys,A4GALT,Met183Lys,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,<10,NaN,NaN,NaN,NaN,0.0,NaN,False,0.8767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6124,NECTIN1_Thr131Ala,NECTIN1,Thr131Ala,Others,allele_col,NaN,NaN,False,Lacoste,NaN,...,NaN,NaN,NaN,NaN,NaN,Rare genetic developmental defect during embry...,2.0,NaN,False,0.0604
6125,NHERF1_Arg153Gln,NHERF1,Arg153Gln,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,70-90,10-90,612287,autosomal dominant,OMIM,NaN,0.0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False,0.5088
6126,NHERF1_Leu110Val,NHERF1,Leu110Val,Conflicting,allele_col,NaN,NaN,False,Lacoste,NaN,...,50-70,10-90,612287,autosomal dominant,OMIM,NaN,0.0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False,0.0954
6127,YARS1_Glu196Lys,YARS1,Glu196Lys,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,10-90,608323;619418,multiple,OMIM,NaN,0.0,"CHARCOT-MARIE-TOOTH DISEASE, DOMINANT INTERMED...",False,0.7318
6128,YARS1_Gly41Arg,YARS1,Gly41Arg,Pathogenic,allele_col,NaN,NaN,False,Lacoste,NaN,...,>90,10-90,608323,autosomal dominant,OMIM,NaN,0.0,"CHARCOT-MARIE-TOOTH DISEASE, DOMINANT INTERMED...",False,0.9982

In [313]:
full_df_annotated.to_csv('../3_outputs/Unified_1pct_Sahni_Rolland_Luck_Lacoste_Fragoza_260217_annotated.csv', index=False)

In [312]:
full_df_annotated[full_df_annotated.nt_change.isna()].Source_Simple.value_counts(dropna=False)

Source_Simple
Fragoza             1835
Lacoste              484
Fragoza; Lacoste       4
Name: count, dtype: int64