In [41]:
import sys
sys.path.insert(1, "scripts/")

import extract_plddt_scores as get_plddt
import calculate_rsa_scores as get_rsa

In [ ]:
pdb_file = "/home/shenrunx/igvf/varchamp/2025_laval_submitted/4_compare_AI_scores/1_inputs/raw_data/UP000005640_9606_HUMAN_v4/AF-X6R8D5-F1-model_v4.pdb.gz"

# Step 3: Extract pLDDT Scores
def extract_plddt(pdb_file):
    """Parse AlphaFold output for per-residue pLDDT scores from a .gz PDB file"""
    with gzip.open(pdb_file, 'rt') as f:
        pdb_content = f.read()
    parser = PDBParser()
    structure = parser.get_structure("AF", StringIO(pdb_content))
    return [(residue.get_id()[1], residue.get_resname(), residue["CA"].bfactor) for residue in structure.get_residues()]

plddt_scores = extract_plddt(pdb_file=pdb_file)
plddt_scores[:10]

[(1, 'MET', 43.9),
 (2, 'GLY', 47.84),
 (3, 'ARG', 53.25),
 (4, 'LYS', 47.35),
 (5, 'GLU', 58.27),
 (6, 'HIS', 42.5),
 (7, 'GLU', 45.51),
 (8, 'SER', 52.87),
 (9, 'PRO', 45.72),
 (10, 'SER', 50.8)]

In [ ]:
parquet_dir = "../3_outputs/processed_data/plddt_scores"
parquet_files = [f"{parquet_dir}/{par_f}" for par_f in os.listdir(parquet_dir)]
parquet_files

# 1. Get all scores for a specific protein
df = get_plddt.query_plddt(parquet_files, pdb_ids=["AF-X6R8D5-F1-model_v4"])

                    pdb_id chain_id  residue_num residue_name  plddt
0    AF-X6R8D5-F1-model_v4        A            1          MET  43.90
1    AF-X6R8D5-F1-model_v4        A            2          GLY  47.84
2    AF-X6R8D5-F1-model_v4        A            3          ARG  53.25
3    AF-X6R8D5-F1-model_v4        A            4          LYS  47.35
4    AF-X6R8D5-F1-model_v4        A            5          GLU  58.27
..                     ...      ...          ...          ...    ...
122  AF-X6R8D5-F1-model_v4        A          123          VAL  83.56
123  AF-X6R8D5-F1-model_v4        A          124          LEU  81.48
124  AF-X6R8D5-F1-model_v4        A          125          TRP  80.66
125  AF-X6R8D5-F1-model_v4        A          126          ARG  79.65
126  AF-X6R8D5-F1-model_v4        A          127          SER  70.53

[127 rows x 5 columns]

In [65]:
parquet_files = [par_f for par_f in glob.glob("../3_outputs/processed_data/rsa_scores")]
parquet_files

pdb1 = "AF-X6R8D5-F1-model_v4"
# pdb1 = "AF-Q5VUB5-F1-model_v4"

df_6lzg = get_rsa.get_structure_rsa(parquet_files, pdb1)
print(f"Retrieved {len(df_6lzg)} residues for {pdb1}")
df_6lzg

# 2. Get RSA for a specific residue
# rsa = get_rsa.get_residue_rsa(parquet_files, pdb1, "A", 124)
# rsa = get_rsa.get_residue_rsa(parquet_files, pdb1, "A", 124)
# print(f"RSA for {pdb1} chain A residue 42: {rsa}%")

# # 3. Advanced query - all residues with RSA > 50%
# all_data = get_rsa.query_rsa_data(parquet_files)
# exposed_residues = all_data[all_data['rsa'] > 50.0]
# print(f"Found {len(exposed_residues)} exposed residues (RSA > 50%)")

Retrieved 127 residues for AF-X6R8D5-F1-model_v4

                    pdb_id chain_id  residue_num residue_name       rsa
0    AF-X6R8D5-F1-model_v4        A            1          MET  1.000000
1    AF-X6R8D5-F1-model_v4        A            2          GLY  0.845238
2    AF-X6R8D5-F1-model_v4        A            3          ARG  1.000000
3    AF-X6R8D5-F1-model_v4        A            4          LYS  0.839024
4    AF-X6R8D5-F1-model_v4        A            5          GLU  1.000000
..                     ...      ...          ...          ...       ...
122  AF-X6R8D5-F1-model_v4        A          123          VAL  0.739437
123  AF-X6R8D5-F1-model_v4        A          124          LEU  0.676829
124  AF-X6R8D5-F1-model_v4        A          125          TRP  0.744493
125  AF-X6R8D5-F1-model_v4        A          126          ARG  0.814516
126  AF-X6R8D5-F1-model_v4        A          127          SER  1.000000

[127 rows x 5 columns]