# Processing gnomAD and ClinVar data

In [1]:
import os
import subprocess
import polars as pl
import pandas as pd
import re

# Set strict error handling
def run_command(cmd):
    result = subprocess.run(cmd, shell=True, check=True, text=True)
    return result

## 1. ClinVar

ClinVar variants released on 2024-03-01 and the data is accessed on March 13, 2025

### Clean up ClinVar annotations

For merging the ClinVar with the VarChAMP variants more easily

In [2]:
dest_path = "../1_inputs/raw_inputs/clinvar/variant_summary.txt.gz"
## Define the new processed and cleaned clinvar file
processed_clinvar_parq = "../3_outputs/processed_data/clinvar/clinvar_processed.parquet"

In [4]:
# ## Read CSV with Polars (auto-decompresses .gz)
# clinvar = pl.read_csv(dest_path, separator='\t', infer_schema_length=1000000)

# ## Process data with Polars expressions
# clinvar = (
#     clinvar
#     .filter(pl.col("Assembly") == "GRCh38")
#     .with_columns(
#         pl.col("Name")
#         # Split the string on '.', '(' or ')'
#         .map_elements(lambda s: re.split(r"[.\(\)]", s), pl.List(pl.String))
#         .alias("Name_listed")
#     )
# )
# clinvar = clinvar.with_columns(
#     pl.col("Name_listed").list.get(0).alias("NM"),
#     pl.col("Name_listed").list.get(1).alias("version"), 
#     pl.col("Name_listed").list.get(2).alias("gene"),
#     pl.col("Name_listed").list.get(3).alias("c"),
#     pl.col("Name_listed").list.get(4).alias("clinvar_nt_change"),
#     pl.col("Name_listed").list.get(5).alias("p"),
#     pl.col("Name_listed").list.get(6).alias("clinvar_aa_change")
# ).with_columns(
#         SPDI=pl.col("ChromosomeAccession") + ":" + 
#             pl.col("PositionVCF").cast(str) + ":" +
#             pl.col("ReferenceAlleleVCF") + ":" +
#             pl.col("AlternateAlleleVCF"),
#         RefSeq_mRNA=pl.col("NM") + "." + pl.col("version"),
#         StarStatus=pl.when(pl.col("ReviewStatus").str.contains(r'single|conflicting'))
#             .then(1)
#             .when(pl.col("ReviewStatus").str.contains('multiple'))
#             .then(2)
#             .when(pl.col("ReviewStatus").str.contains('expert'))
#             .then(3)
#             .when(pl.col("ReviewStatus").str.contains('practice'))
#             .then(4)
#             .otherwise(None)
# )

In [4]:
## Create the mapping expression with precise logic for a cleaner ClinVar Annotation
clinvar_mapping = (
    # First check for Conflicting interpretations (highest priority)
    pl.when(
        pl.col("ClinicalSignificance").str.to_lowercase().str.contains("conflicting")
    )
    .then(pl.lit("3_Conflicting"))
    
    # Then check for Uncertain significance (VUS)
    .when(pl.col("ClinicalSignificance").str.to_lowercase().str.contains("uncertain"))
    .then(pl.lit("4_VUS"))
    
    # # Special case for strings containing both "Uncertain significance" and "Pathogenic"
    # .when(
    #     pl.col("clinvar_clnsig").str.to_lowercase().str.contains("uncertain") &
    #     pl.col("clinvar_clnsig").str.to_lowercase().str.contains("pathogenic")
    # )
    # .then(pl.lit("4_VUS"))  # The dictionary says to classify this as VUS
    
    # Check for Pathogenic
    .when(pl.col("ClinicalSignificance").str.to_lowercase().str.contains("pathogenic"))
    .then(pl.lit("1_Pathogenic"))
    
    # Check for Benign
    .when(pl.col("ClinicalSignificance").str.to_lowercase().str.contains("benign"))
    .then(pl.lit("2_Benign"))
    
    # Everything else goes to Others
    .otherwise(pl.lit("5_Others"))
)

# Apply the mapping to create a new column
clinvar = clinvar.with_columns(clinvar_clnsig_clean=clinvar_mapping)

# Create a dataframe with unique mappings to check accuracy
unique_mappings = clinvar.select(
    pl.col("ClinicalSignificance"),
    pl.col("clinvar_clnsig_clean")
).unique()

# Sort by original value for easier verification
unique_mappings = unique_mappings.sort("ClinicalSignificance")

# Print each mapping to verify accuracy
print("Original Value -> Mapped Value")
print("-" * 50)
for row in unique_mappings.rows():
    print(f"{row[0]} -> {row[1]}")

Original Value -> Mapped Value
--------------------------------------------------
- -> 5_Others
Affects -> 5_Others
Affects; risk factor -> 5_Others
Benign -> 2_Benign
Benign/Likely benign -> 2_Benign
Benign/Likely benign; association -> 2_Benign
Benign/Likely benign; drug response -> 2_Benign
Benign/Likely benign; drug response; other -> 2_Benign
Benign/Likely benign; other -> 2_Benign
Benign/Likely benign; other; risk factor -> 2_Benign
Benign/Likely benign; risk factor -> 2_Benign
Benign; Affects -> 2_Benign
Benign; Affects; association; other -> 2_Benign
Benign; association -> 2_Benign
Benign; confers sensitivity -> 2_Benign
Benign; drug response -> 2_Benign
Benign; other -> 2_Benign
Benign; protective -> 2_Benign
Benign; risk factor -> 2_Benign
Conflicting classifications of pathogenicity -> 3_Conflicting
Conflicting classifications of pathogenicity; Affects -> 3_Conflicting
Conflicting classifications of pathogenicity; association -> 3_Conflicting
Conflicting classifications of pathogenicity; association; risk factor -> 3_Conflicting
Conflicting classifications of pathogenicity; drug response -> 3_Conflicting
Conflicting classifications of pathogenicity; drug response; other -> 3_Conflicting
Conflicting classifications of pathogenicity; other -> 3_Conflicting
Conflicting classifications of pathogenicity; other; risk factor -> 3_Conflicting
Conflicting classifications of pathogenicity; protective -> 3_Conflicting
Conflicting classifications of pathogenicity; risk factor -> 3_Conflicting
Likely benign -> 2_Benign
Likely benign; Affects; association -> 2_Benign
Likely benign; association -> 2_Benign
Likely benign; drug response -> 2_Benign
Likely benign; drug response; other -> 2_Benign
Likely benign; other -> 2_Benign
Likely benign; protective -> 2_Benign
Likely benign; risk factor -> 2_Benign
Likely pathogenic -> 1_Pathogenic
Likely pathogenic, low penetrance -> 1_Pathogenic
Likely pathogenic/Likely risk allele -> 1_Pathogenic
Likely pathogenic; Affects -> 1_Pathogenic
Likely pathogenic; association -> 1_Pathogenic
Likely pathogenic; drug response -> 1_Pathogenic
Likely pathogenic; other -> 1_Pathogenic
Likely pathogenic; risk factor -> 1_Pathogenic
Likely risk allele -> 5_Others
Pathogenic -> 1_Pathogenic
Pathogenic, low penetrance -> 1_Pathogenic
Pathogenic/Likely pathogenic -> 1_Pathogenic
Pathogenic/Likely pathogenic/Likely risk allele -> 1_Pathogenic
Pathogenic/Likely pathogenic/Pathogenic, low penetrance -> 1_Pathogenic
Pathogenic/Likely pathogenic/Pathogenic, low penetrance; other -> 1_Pathogenic
Pathogenic/Likely pathogenic/Pathogenic, low penetrance; risk factor -> 1_Pathogenic
Pathogenic/Likely pathogenic; association -> 1_Pathogenic
Pathogenic/Likely pathogenic; other -> 1_Pathogenic
Pathogenic/Likely pathogenic; risk factor -> 1_Pathogenic
Pathogenic/Likely risk allele -> 1_Pathogenic
Pathogenic/Likely risk allele; risk factor -> 1_Pathogenic
Pathogenic/Pathogenic, low penetrance; other -> 1_Pathogenic
Pathogenic/Pathogenic, low penetrance; other; risk factor -> 1_Pathogenic
Pathogenic; Affects -> 1_Pathogenic
Pathogenic; association -> 1_Pathogenic
Pathogenic; association; protective -> 1_Pathogenic
Pathogenic; confers sensitivity -> 1_Pathogenic
Pathogenic; drug response -> 1_Pathogenic
Pathogenic; other -> 1_Pathogenic
Pathogenic; protective -> 1_Pathogenic
Pathogenic; risk factor -> 1_Pathogenic
Uncertain risk allele -> 4_VUS
Uncertain risk allele; risk factor -> 4_VUS
Uncertain significance -> 4_VUS
Uncertain significance/Uncertain risk allele -> 4_VUS
Uncertain significance; Affects -> 4_VUS
Uncertain significance; Pathogenic/Likely pathogenic -> 4_VUS
Uncertain significance; association -> 4_VUS
Uncertain significance; drug response -> 4_VUS
Uncertain significance; other -> 4_VUS
Uncertain significance; risk factor -> 4_VUS
association -> 5_Others
association not found -> 5_Others
association; drug response; risk factor -> 5_Others
association; risk factor -> 5_Others
confers sensitivity -> 5_Others
confers sensitivity; other -> 5_Others
conflicting data from submitters -> 3_Conflicting
drug response -> 5_Others
drug response; other -> 5_Others
drug response; risk factor -> 5_Others
no classification for the single variant -> 5_Others
no classifications from unflagged records -> 5_Others
not provided -> 5_Others
other -> 5_Others
other; risk factor -> 5_Others
protective -> 5_Others
protective; risk factor -> 5_Others
risk factor -> 5_Others

In [5]:
# ## Make sure we only drop columns that actually exist
# columns_to_drop = [col for col in ['NM', 'version', 'gene', 'c', 'p', 'ReferenceAllele', 'AlternateAllele', 'Name_listed'] 
#                   if col in clinvar.columns]
# if columns_to_drop:
#     clinvar = clinvar.drop(columns_to_drop)

# # Now cast to categorical
# clinvar = clinvar.with_columns(
#     pl.col(["Assembly", "ClinicalSignificance", "ReviewStatus", "clinvar_clnsig_clean"]).cast(pl.Categorical)
# )

# # Write to Parquet with ZSTD compression
# clinvar.write_parquet(processed_clinvar_parq, 
#                      compression="zstd", 
#                      statistics=True)

## 2. Merge clinvar and gnomad to varchamp alleles

### 2.1 Loading varchamp alleles

In [70]:
## get unique info for genes in polars
gene_info = pl.scan_csv(f"../1_inputs/VarChamp_Consolidated_allele_collection.tsv", separator="\t", infer_schema_length=100000) #[gene_cols]
gene_info = gene_info.with_columns([
    # Fix: Use concat_str for string concatenation
    pl.concat_str([pl.lit("chr"), pl.col("chr")]).alias("chrom"),
    # Fix: Get the last character of the first part (before ">")
    pl.col("nt_change").str.split(">").list.get(0).str.slice(-1).alias("ref"),
    # Fix: Get the entire second part (after ">") - slice(0) gets from start to end
    pl.col("nt_change").str.split(">").list.get(-1).alias("alt")
]).with_columns([
    # Fix: Use concat_str for the varid string concatenation
    pl.concat_str([
        pl.col("chr"),
        pl.lit("-"),
        pl.col("chr_pos_38").cast(pl.String),
        pl.lit("-"),
        pl.col("ref"),
        pl.lit("-"),
        pl.col("alt")
    ]).alias("varid")
])

gene_info.collect()

shape: (8_488, 21)
┌────────┬──────────┬───────────┬───────────┬───┬───────┬─────┬─────┬─────────────────┐
│ orf_id ┆ symbol   ┆ nt_change ┆ aa_change ┆ … ┆ chrom ┆ ref ┆ alt ┆ varid           │
│ ---    ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---   ┆ --- ┆ --- ┆ ---             │
│ i64    ┆ str      ┆ str       ┆ str       ┆   ┆ str   ┆ str ┆ str ┆ str             │
╞════════╪══════════╪═══════════╪═══════════╪═══╪═══════╪═════╪═════╪═════════════════╡
│ 2      ┆ GBA      ┆ 160G>C    ┆ Val54Leu  ┆ … ┆ chr1  ┆ G   ┆ C   ┆ 1-155240033-G-C │
│ 2      ┆ GBA      ┆ 670C>T    ┆ Leu224Phe ┆ … ┆ chr1  ┆ C   ┆ T   ┆ 1-155238225-C-T │
│ 2      ┆ GBA      ┆ 887G>A    ┆ Arg296Gln ┆ … ┆ chr1  ┆ G   ┆ A   ┆ 1-155237453-G-A │
│ 2      ┆ GBA      ┆ 1448T>C   ┆ Leu483Pro ┆ … ┆ chr1  ┆ T   ┆ C   ┆ 1-155235252-T-C │
│ 25     ┆ SLC9A3R1 ┆ 328C>G    ┆ Leu110Val ┆ … ┆ chr17 ┆ C   ┆ G   ┆ 17-74749174-C-G │
│ …      ┆ …        ┆ …         ┆ …         ┆ … ┆ …     ┆ …   ┆ …   ┆ …               │
│ 8999   ┆ TTR      ┆ 355G>A    ┆ Asp119Asn ┆ … ┆ chr18 ┆ G   ┆ A   ┆ 18-31598586-G-A │
│ 7323   ┆ PMP22    ┆ 152A>G    ┆ His51Arg  ┆ … ┆ chr17 ┆ A   ┆ G   ┆ 17-15259120-A-G │
│ 2651   ┆ CLN6     ┆ 89G>C     ┆ Gly30Ala  ┆ … ┆ chr15 ┆ G   ┆ C   ┆ 15-68218645-G-C │
│ 7323   ┆ PMP22    ┆ 403G>A    ┆ Ala135Thr ┆ … ┆ chr17 ┆ G   ┆ A   ┆ 17-15230997-G-A │
│ 7215   ┆ NR0B1    ┆ 376G>A    ┆ Val126Met ┆ … ┆ chrX  ┆ G   ┆ A   ┆ X-30308988-G-A  │
└────────┴──────────┴───────────┴───────────┴───┴───────┴─────┴─────┴─────────────────┘

### 2.2 Merge with ClinVar

In [71]:
processed_clinvar_parq = "../3_outputs/processed_data/clinvar/clinvar_processed.parquet"
gene_info_clinvar_parq = "../3_outputs/varchamp_consolidated_alleles_clinvar_annot.parquet"
gene_info_clinvar_tsv = "../3_outputs/varchamp_consolidated_alleles_clinvar_annot.tsv"

clinvar = pl.scan_parquet(processed_clinvar_parq)
clinvar.collect().head()

gene_info_clinvar = gene_info.join(
                        clinvar,
                        left_on="spdi",
                        right_on="SPDI",
                        how="left"
                    )
gene_info_clinvar = gene_info_clinvar.collect()

# gene_info_clinvar.write_parquet(gene_info_clinvar_parq, compression="zstd")
# gene_info_clinvar.write_csv(gene_info_clinvar_tsv, separator="\t")

In [72]:
clinvar.collect().shape

(3390885, 47)

#### Report the number of alleles missing ClinVar annotations

In [73]:
gene_info_clinvar = pl.scan_parquet(gene_info_clinvar_parq)
gene_info_clinvar.filter((~pl.col("spdi").is_null())&(pl.col("#AlleleID").is_null())).collect()

shape: (936, 67)
┌────────┬────────┬───────────┬───────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ orf_id ┆ symbol ┆ nt_change ┆ aa_change ┆ … ┆ clinvar_aa_ ┆ RefSeq_mRN ┆ StarStatus ┆ clinvar_cl │
│ ---    ┆ ---    ┆ ---       ┆ ---       ┆   ┆ change      ┆ A          ┆ ---        ┆ nsig_clean │
│ i64    ┆ str    ┆ str       ┆ str       ┆   ┆ ---         ┆ ---        ┆ i32        ┆ ---        │
│        ┆        ┆           ┆           ┆   ┆ str         ┆ str        ┆            ┆ cat        │
╞════════╪════════╪═══════════╪═══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2      ┆ GBA    ┆ 160G>C    ┆ Val54Leu  ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 2      ┆ GBA    ┆ 670C>T    ┆ Leu224Phe ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 167    ┆ ACTA2  ┆ 874A>G    ┆ Arg292Gly ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 187    ┆ FOXA3  ┆ 271G>A    ┆ Gly91Arg  ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 286    ┆ ABHD5  ┆ 245A>G    ┆ His82Arg  ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ …      ┆ …      ┆ …         ┆ …         ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 4765   ┆ ITGB2  ┆ 769C>T    ┆ Arg257Trp ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 4765   ┆ ITGB2  ┆ 905C>T    ┆ Pro302Leu ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 4765   ┆ ITGB2  ┆ 1670G>C   ┆ Cys557Ser ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 9316   ┆ RPGR   ┆ 460G>C    ┆ Ala154Pro ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 10732  ┆ BBS5   ┆ 158C>T    ┆ Thr53Ile  ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
└────────┴────────┴───────────┴───────────┴───┴─────────────┴────────────┴────────────┴────────────┘

Check why missing, and it seems like some alleles just weren't collected by ClinVar yet

In [74]:
gene_info_clinvar.filter(pl.col("symbol")=="GBA").sort(by="clinvar_aa_change").collect()

shape: (27, 67)
┌────────┬────────┬───────────┬───────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ orf_id ┆ symbol ┆ nt_change ┆ aa_change ┆ … ┆ clinvar_aa_ ┆ RefSeq_mRN ┆ StarStatus ┆ clinvar_cl │
│ ---    ┆ ---    ┆ ---       ┆ ---       ┆   ┆ change      ┆ A          ┆ ---        ┆ nsig_clean │
│ i64    ┆ str    ┆ str       ┆ str       ┆   ┆ ---         ┆ ---        ┆ i32        ┆ ---        │
│        ┆        ┆           ┆           ┆   ┆ str         ┆ str        ┆            ┆ cat        │
╞════════╪════════╪═══════════╪═══════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 2      ┆ GBA    ┆ 160G>C    ┆ Val54Leu  ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 2      ┆ GBA    ┆ 670C>T    ┆ Leu224Phe ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 2      ┆ GBA    ┆ 1483G>C   ┆ Ala495Pro ┆ … ┆ Ala495Pro   ┆ NM_000157. ┆ 1          ┆ 3_Conflict │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ing        │
│ 2      ┆ GBA    ┆ 476G>A    ┆ Arg159Gln ┆ … ┆ Arg159Gln   ┆ NM_000157. ┆ 2          ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
│ 2      ┆ GBA    ┆ 605G>A    ┆ Arg202Gln ┆ … ┆ Arg202Gln   ┆ NM_000157. ┆ 1          ┆ 3_Conflict │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ing        │
│ …      ┆ …      ┆ …         ┆ …         ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 2      ┆ GBA    ┆ 870C>A    ┆ Phe290Leu ┆ … ┆ Phe290Leu   ┆ NM_000157. ┆ null       ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
│ 2      ┆ GBA    ┆ 983C>T    ┆ Pro328Leu ┆ … ┆ Pro328Leu   ┆ NM_000157. ┆ null       ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
│ 2      ┆ GBA    ┆ 1085C>T   ┆ Thr362Ile ┆ … ┆ Thr362Ile   ┆ NM_000157. ┆ 2          ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
│ 2      ┆ GBA    ┆ 667T>C    ┆ Trp223Arg ┆ … ┆ Trp223Arg   ┆ NM_000157. ┆ 2          ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
│ 2      ┆ GBA    ┆ 1240G>T   ┆ Val414Leu ┆ … ┆ Val414Leu   ┆ NM_000157. ┆ 2          ┆ 1_Pathogen │
│        ┆        ┆           ┆           ┆   ┆             ┆ 4          ┆            ┆ ic         │
└────────┴────────┴───────────┴───────────┴───┴─────────────┴────────────┴────────────┴────────────┘

### 2.3 Merge with gnomad

##### Sort out all the vcf files and all their position coordinates for looking up varchamp-related variants

In [18]:
## Generate all the position coordinates for varchamp-related variants for quicker look-up

## Define some constants
VCF_DIR = "../1_inputs/raw_inputs/gnomad"
CHROMOSOMES = [str(c) for c in list(range(1, 23))] + ['X', 'Y']

# VARIANT_LIST = f"../3_outputs/processed_data/gnomad_allele_frequencies/gnomad_variants_list.txt"
# gene_info_pd[["chrom","chr_pos_38","ref","alt"]].to_csv(VARIANT_LIST, sep="\t", header=False, index=False)

In [19]:
# # !conda install bcftools -c conda-forge -y ## install bcftools if you didn't

# OUTPUT_DIR = f"../3_outputs/processed_data/gnomad_allele_frequencies"
# os.makedirs(OUTPUT_DIR, exist_ok=True)

# # Process chromosomes
# for chrom in CHROMOSOMES:
#     vcf_file = f"{VCF_DIR}/gnomad.exomes.v4.1.sites.chr{chrom}.vcf.bgz"
#     csi_file = f"{vcf_file}.csi"
#     output_file = f"{OUTPUT_DIR}/chr{chrom}_allele_frequencies.txt"
    
#     if os.path.exists(vcf_file):
#         print(f"Processing chromosome {chrom}...")
        
#         if not os.path.exists(csi_file):
#             print(f"Indexing {vcf_file}")
#             run_command(f"bcftools index --threads 4 {vcf_file}")
        
#         print(f"Extracting frequencies for {chrom}")
#         view_cmd = f"bcftools view -R {VARIANT_LIST} {vcf_file}"
#         query_cmd = "bcftools query -f '%CHROM\\t%POS\\t%REF\\t%ALT\\t%AF\\n'"
        
#         with open(output_file, 'w') as f:
#             p1 = subprocess.Popen(view_cmd.split(), stdout=subprocess.PIPE)
#             p2 = subprocess.Popen(query_cmd.split(), stdin=p1.stdout, stdout=f)
#             p1.stdout.close()
#             p2.communicate()
            
#         print(f"Saved to {output_file}")
#     else:
#         print(f"Skipping chromosome {chrom} - file not found")

# print("Processing completed")

#### Merge the gnomad AF files from chromosomes

In [26]:
allele_freq_dfs = []
for chrom in CHROMOSOMES:
    try:
        allele_freq = pl.read_csv(f"../3_outputs/processed_data/gnomad_allele_frequencies/chr{chrom}_allele_frequencies.txt",
                                separator="\t", has_header=False, 
                                new_columns=["chr","chr_pos_38","ref","alt","allele_freq"])
        allele_freq = allele_freq.with_columns(
            pl.col("chr").str.replace(r"\'", "").str.replace(r"\'", "").str.replace("chr", "")
        ).drop_nulls()
        # allele_freq = allele_freq.filter(~pl.all_horizontal(pl.all().is_null()))
        # print(allele_freq)
        allele_freq_dfs.append(allele_freq)
    except:
        continue

allele_freq_all = pl.concat(allele_freq_dfs)
allele_freq_gnomad = allele_freq_all.with_columns(
    pl.concat_str([pl.col("chr"),
                   pl.lit('-'),
                   pl.col("chr_pos_38").cast(pl.String),
                   pl.lit('-'),
                   pl.col("ref"),
                   pl.lit('-'),
                   pl.col("alt")
                   ]).alias("varid"),
    pl.col("allele_freq").alias("gnomad_af")
).drop(pl.col("allele_freq"))#.to_pandas()

allele_freq_gnomad

shape: (9_713, 6)
┌─────┬────────────┬─────┬─────┬─────────────────┬───────────┐
│ chr ┆ chr_pos_38 ┆ ref ┆ alt ┆ varid           ┆ gnomad_af │
│ --- ┆ ---        ┆ --- ┆ --- ┆ ---             ┆ ---       │
│ str ┆ i64        ┆ str ┆ str ┆ str             ┆ f64       │
╞═════╪════════════╪═════╪═════╪═════════════════╪═══════════╡
│ 1   ┆ 2028259    ┆ C   ┆ A   ┆ 1-2028259-C-A   ┆ 6.8500e-7 │
│ 1   ┆ 2028259    ┆ C   ┆ T   ┆ 1-2028259-C-T   ┆ 0.001409  │
│ 1   ┆ 2028260    ┆ G   ┆ A   ┆ 1-2028260-G-A   ┆ 0.0217404 │
│ 1   ┆ 5907193    ┆ CG  ┆ C   ┆ 1-5907193-CG-C  ┆ 0.0       │
│ 1   ┆ 5907194    ┆ G   ┆ A   ┆ 1-5907194-G-A   ┆ 0.000013  │
│ …   ┆ …          ┆ …   ┆ …   ┆ …               ┆ …         │
│ X   ┆ 154863124  ┆ C   ┆ T   ┆ X-154863124-C-T ┆ 0.000011  │
│ X   ┆ 154863125  ┆ G   ┆ A   ┆ X-154863125-G-A ┆ 0.000004  │
│ X   ┆ 154863151  ┆ C   ┆ T   ┆ X-154863151-C-T ┆ 0.000004  │
│ X   ┆ 155280059  ┆ G   ┆ C   ┆ X-155280059-G-C ┆ 0.000116  │
│ X   ┆ 155280059  ┆ G   ┆ T   ┆ X-155280059-G-T ┆ 9.2858e-7 │
└─────┴────────────┴─────┴─────┴─────────────────┴───────────┘

### Merge the gnomad AF to VarChAMP alleles

In [67]:
gene_info_gnomad = gene_info.join(allele_freq_gnomad.lazy(),
                                  on="varid",
                                  how="left")

# gene_info_gnomad.to_csv("../3_outputs/varchamp_consolidated_alleles_gnomad_annot.tsv", sep="\t", index=False)

In [69]:
# gene_info_gnomad.collect()

### Merge the ClinVar info AND gnomad AF BOTH to VarChAMP alleles

In [79]:
gene_info_clinvar_gnomad = gene_info_clinvar.join(
    allele_freq_gnomad.select(pl.col(["varid","gnomad_af"])).lazy(),
    on="varid",how="left").collect()

gene_info_clinvar_gnomad.write_csv("../3_outputs/varchamp_consolidated_alleles_clinvar_gnomad.tsv", separator="\t")

## 4. Add Sequence Confirmation

In [99]:
## More stuff to be added

In [81]:
valid_sequence_confirmation_class = [1., 2., 7., 99.]

In [88]:
[col for col in gene_info.columns if col not in seq_confirm_res_df.columns]

<ipython-input-88-278c6c8e5a23>:1: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  [col for col in gene_info.columns if col not in seq_confirm_res_df.columns]

['chr',
 'chr_pos_38',
 'mutation_id_rc4',
 'mutation_id_cegs2',
 'mutation_id_edgotyping3',
 'entry_plate',
 'entry_well',
 'sequence',
 'chrom',
 'ref',
 'alt',
 'varid']

In [92]:
seq_confirm_res_df = pl.read_csv(f"../1_inputs/seq_confirmation_results/VarChampSeqConfirmationResult.tsv", separator="\t", infer_schema_length=10000)
seq_confirm_res_df = seq_confirm_res_df.drop_nulls(
    subset="entry_sequence_confirmation_class"
).rename(
    {"orf_id_wt": "orf_id",
     "mutation_id_old": "mut_id"}
)
seq_confirm_res_df

shape: (8_710, 33)
┌────────┬────────────┬───────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ symbol ┆ ensembl_ge ┆ orf_id    ┆ mut_id ┆ … ┆ dualip_seq ┆ dualip_seq ┆ mislocaliz ┆ mislocaliz │
│ ---    ┆ ne_id      ┆ ---       ┆ ---    ┆   ┆ uenced     ┆ uence_conf ┆ ation_sequ ┆ ation_sequ │
│ str    ┆ ---        ┆ i64       ┆ i64    ┆   ┆ ---        ┆ irmation_c ┆ enced      ┆ ence_confi │
│        ┆ str        ┆           ┆        ┆   ┆ i64        ┆ …          ┆ ---        ┆ …          │
│        ┆            ┆           ┆        ┆   ┆            ┆ ---        ┆ i64        ┆ ---        │
│        ┆            ┆           ┆        ┆   ┆            ┆ str        ┆            ┆ str        │
╞════════╪════════════╪═══════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 6      ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 73     ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 113    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 231    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 213510 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ …      ┆ …          ┆ …         ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ CTNNB1 ┆ ENSG000001 ┆ 100070227 ┆ 212487 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 68036      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ TBX19  ┆ ENSG000001 ┆ 100070258 ┆ 212488 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 43178      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ TBX19  ┆ ENSG000001 ┆ 100070258 ┆ 212489 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 43178      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GDF2   ┆ ENSG000002 ┆ 100070273 ┆ 212491 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 63761      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GDF2   ┆ ENSG000002 ┆ 100070273 ┆ 212492 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 63761      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
└────────┴────────────┴───────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [98]:
seq_confirm_res_df.filter(
    (pl.col("entry_sequence_confirmation_class")=="1")
    & (pl.col("entry_sequence_confirmation_class")!=pl.col("dualip_sequence_confirmation_class"))
    
)

shape: (5_816, 33)
┌────────┬────────────┬───────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ symbol ┆ ensembl_ge ┆ orf_id    ┆ mut_id ┆ … ┆ dualip_seq ┆ dualip_seq ┆ mislocaliz ┆ mislocaliz │
│ ---    ┆ ne_id      ┆ ---       ┆ ---    ┆   ┆ uenced     ┆ uence_conf ┆ ation_sequ ┆ ation_sequ │
│ str    ┆ ---        ┆ i64       ┆ i64    ┆   ┆ ---        ┆ irmation_c ┆ enced      ┆ ence_confi │
│        ┆ str        ┆           ┆        ┆   ┆ i64        ┆ …          ┆ ---        ┆ …          │
│        ┆            ┆           ┆        ┆   ┆            ┆ ---        ┆ i64        ┆ ---        │
│        ┆            ┆           ┆        ┆   ┆            ┆ str        ┆            ┆ str        │
╞════════╪════════════╪═══════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 6      ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 73     ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 113    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 231    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 213510 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ …      ┆ …          ┆ …         ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ SRY    ┆ ENSG000001 ┆ 100070152 ┆ 229149 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 84895      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ SRY    ┆ ENSG000001 ┆ 100070152 ┆ 229151 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 84895      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ SRY    ┆ ENSG000001 ┆ 100070152 ┆ 229152 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 84895      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ CTNNB1 ┆ ENSG000001 ┆ 100070227 ┆ 212487 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 68036      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ TBX19  ┆ ENSG000001 ┆ 100070258 ┆ 212489 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 43178      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
└────────┴────────────┴───────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [82]:
gene_info_clinvar_gnomad = pl.read_csv("../3_outputs/varchamp_consolidated_alleles_clinvar_gnomad.tsv", separator="\t", infer_schema_length=10000)
seq_confirm_res_df = pl.read_csv(f"../1_inputs/seq_confirmation_results/VarChampSeqConfirmationResult.tsv", separator="\t", infer_schema_length=10000)
seq_confirm_res_df = seq_confirm_res_df.drop_nulls(
    subset="entry_sequence_confirmation_class"
).rename(
    {"orf_id_wt": "orf_id",
     "mutation_id_old": "mut_id"}
)
display(seq_confirm_res_df)
# print("seq_confirm_res_df unique ccsb_mutation_id", len(seq_confirm_res_df.dropna(subset="entry_sequence_confirmation_class")["ccsb_mutation_id"].unique()))

gene_info_clinvar_gnomad_sc = seq_confirm_res_df.join(
        gene_info_clinvar_gnomad, 
        on=["spdi"],
        suffix="_old"
)#.drop_nulls(subset="entry_sequence_confirmation_class")

gene_info_clinvar_gnomad_sc = gene_info_clinvar_gnomad_sc.drop(
    [col for col in gene_info_clinvar_gnomad_sc.columns if col.endswith("_old")]
).with_columns(
    pl.when(pl.col("entry_sequence_confirmation_class") == "NULL")
    .then(pl.lit(None))
    .otherwise(pl.col("entry_sequence_confirmation_class"))
    .alias("entry_sequence_confirmation_class")
).with_columns(
    pl.col("entry_sequence_confirmation_class").cast(pl.Float32).alias("entry_sequence_confirmation_class")
)

gene_info_clinvar_gnomad_sc = gene_info_clinvar_gnomad_sc.filter(pl.col("entry_sequence_confirmation_class").is_in(valid_sequence_confirmation_class))
gene_info_clinvar_gnomad_sc.write_csv("../3_outputs/varchamp_consolidated_alleles_clinvar_gnomad_sequence_confirmed.tsv", separator="\t")

shape: (8_710, 33)
┌────────┬────────────┬───────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ symbol ┆ ensembl_ge ┆ orf_id    ┆ mut_id ┆ … ┆ dualip_seq ┆ dualip_seq ┆ mislocaliz ┆ mislocaliz │
│ ---    ┆ ne_id      ┆ ---       ┆ ---    ┆   ┆ uenced     ┆ uence_conf ┆ ation_sequ ┆ ation_sequ │
│ str    ┆ ---        ┆ i64       ┆ i64    ┆   ┆ ---        ┆ irmation_c ┆ enced      ┆ ence_confi │
│        ┆ str        ┆           ┆        ┆   ┆ i64        ┆ …          ┆ ---        ┆ …          │
│        ┆            ┆           ┆        ┆   ┆            ┆ ---        ┆ i64        ┆ ---        │
│        ┆            ┆           ┆        ┆   ┆            ┆ str        ┆            ┆ str        │
╞════════╪════════════╪═══════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 6      ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 73     ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 113    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 231    ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GBA1   ┆ ENSG000001 ┆ 2         ┆ 213510 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 77628      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ …      ┆ …          ┆ …         ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ CTNNB1 ┆ ENSG000001 ┆ 100070227 ┆ 212487 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 68036      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ TBX19  ┆ ENSG000001 ┆ 100070258 ┆ 212488 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 43178      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ TBX19  ┆ ENSG000001 ┆ 100070258 ┆ 212489 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 43178      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GDF2   ┆ ENSG000002 ┆ 100070273 ┆ 212491 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 63761      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
│ GDF2   ┆ ENSG000002 ┆ 100070273 ┆ 212492 ┆ … ┆ 0          ┆ NULL       ┆ 0          ┆ NULL       │
│        ┆ 63761      ┆           ┆        ┆   ┆            ┆            ┆            ┆            │
└────────┴────────────┴───────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [83]:
gene_info_clinvar_gnomad_sc

shape: (7_545, 92)
┌────────┬─────────────┬───────────┬────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ symbol ┆ ensembl_gen ┆ orf_id    ┆ mut_id ┆ … ┆ RefSeq_mRN ┆ StarStatus ┆ clinvar_cl ┆ gnomad_af │
│ ---    ┆ e_id        ┆ ---       ┆ ---    ┆   ┆ A          ┆ ---        ┆ nsig_clean ┆ ---       │
│ str    ┆ ---         ┆ i64       ┆ i64    ┆   ┆ ---        ┆ i64        ┆ ---        ┆ f64       │
│        ┆ str         ┆           ┆        ┆   ┆ str        ┆            ┆ str        ┆           │
╞════════╪═════════════╪═══════════╪════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ GBA1   ┆ ENSG0000017 ┆ 2         ┆ 6      ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆ 7628        ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ GBA1   ┆ ENSG0000017 ┆ 2         ┆ 73     ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│        ┆ 7628        ┆           ┆        ┆   ┆            ┆            ┆            ┆           │
│ GBA1   ┆ ENSG0000017 ┆ 2         ┆ 113    ┆ … ┆ NM_000157. ┆ 2          ┆ 1_Pathogen ┆ null      │
│        ┆ 7628        ┆           ┆        ┆   ┆ 4          ┆            ┆ ic         ┆           │
│ GBA1   ┆ ENSG0000017 ┆ 2         ┆ 231    ┆ … ┆ NM_000157. ┆ 2          ┆ 1_Pathogen ┆ null      │
│        ┆ 7628        ┆           ┆        ┆   ┆ 4          ┆            ┆ ic         ┆           │
│ GBA1   ┆ ENSG0000017 ┆ 2         ┆ 213510 ┆ … ┆ NM_000157. ┆ 2          ┆ 1_Pathogen ┆ null      │
│        ┆ 7628        ┆           ┆        ┆   ┆ 4          ┆            ┆ ic         ┆           │
│ …      ┆ …           ┆ …         ┆ …      ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ SRY    ┆ ENSG0000018 ┆ 100070152 ┆ 229151 ┆ … ┆ NM_003140. ┆ null       ┆ 1_Pathogen ┆ null      │
│        ┆ 4895        ┆           ┆        ┆   ┆ 3          ┆            ┆ ic         ┆           │
│ SRY    ┆ ENSG0000018 ┆ 100070152 ┆ 229152 ┆ … ┆ NM_003140. ┆ null       ┆ 1_Pathogen ┆ null      │
│        ┆ 4895        ┆           ┆        ┆   ┆ 3          ┆            ┆ ic         ┆           │
│ CTNNB1 ┆ ENSG0000016 ┆ 100070227 ┆ 212487 ┆ … ┆ NM_001904. ┆ 2          ┆ 2_Benign   ┆ 0.001253  │
│        ┆ 8036        ┆           ┆        ┆   ┆ 4          ┆            ┆            ┆           │
│ TBX19  ┆ ENSG0000014 ┆ 100070258 ┆ 212488 ┆ … ┆ NM_005149. ┆ null       ┆ 1_Pathogen ┆ 0.000007  │
│        ┆ 3178        ┆           ┆        ┆   ┆ 3          ┆            ┆ ic         ┆           │
│ TBX19  ┆ ENSG0000014 ┆ 100070258 ┆ 212489 ┆ … ┆ NM_005149. ┆ null       ┆ 1_Pathogen ┆ 6.8405e-7 │
│        ┆ 3178        ┆           ┆        ┆   ┆ 3          ┆            ┆ ic         ┆           │
└────────┴─────────────┴───────────┴────────┴───┴────────────┴────────────┴────────────┴───────────┘