# Map SpliceAI predictions

In [1]:
import pandas as pd
import polars as pl

In [2]:
inputs_dir = "../1_inputs"
outputs_dir = "../3_outputs"

In [3]:
splice_df = pd.read_csv(f"{inputs_dir}/ccsb_mutations_with_spliceai_scores.tsv", sep="\t", low_memory=False)
splice_df

,mutation_id,orf_id,nt_change,aa_change,cloned,ensembl_protein_id,orf_class,aa_change_hgvs,nt_change_cnt,cloned_project,...,DS_AL,DS_DG,DS_DL,DP_AG,DP_AL,DP_DG,DP_DL,any_DS_above_0.2,any_DS_above_0.5,any_DS_above_0.8
0,CCSBVarC000001,2,160G>C,Val54Leu,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Val54Leu,1,pre_varchamp,...,0.00,0.0,0.0,44.0,7.0,-24.0,1.0,False,False,False
1,CCSBVarC000002,2,670C>T,Leu224Phe,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Leu224Phe,1,pre_varchamp,...,0.00,0.0,0.0,-6.0,22.0,2.0,-17.0,False,False,False
2,CCSBVarC000003,2,887G>A,Arg296Gln,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Arg296Gln,1,pre_varchamp,...,0.00,0.0,0.0,-24.0,28.0,3.0,-23.0,False,False,False
3,CCSBVarC000004,2,1448T>C,Leu483Pro,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Leu483Pro,1,pre_varchamp,...,0.00,0.0,0.0,43.0,34.0,-43.0,-48.0,False,False,False
4,CCSBVarC000005,25,328C>G,Leu110Val,1,ENSP00000262613.5,class1m,ENSP00000262613.5:p.Leu110Val,1,pre_varchamp,...,0.00,0.0,0.0,-12.0,30.0,-1.0,13.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38601,CCSBVarC039842,1460,2671A>G,Ser891Gly,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Ser891Gly,1,varchamp_pign,...,0.01,0.0,0.8,-6.0,30.0,-39.0,-1.0,True,True,False
38602,CCSBVarC039843,1460,2699C>G,Ser900Cys,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Ser900Cys,1,varchamp_pign,...,0.01,0.0,0.0,20.0,26.0,3.0,0.0,False,False,False
38603,CCSBVarC039844,1460,2701A>G,Met901Val,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Met901Val,1,varchamp_pign,...,0.00,0.0,0.0,28.0,-39.0,5.0,28.0,False,False,False
38604,CCSBVarC039845,1460,2750C>T,Thr917Met,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Thr917Met,1,varchamp_pign,...,0.00,0.0,0.0,10.0,-13.0,-42.0,-17.0,False,False,False
38605,CCSBVarC039846,1460,2770G>A,Gly924Ser,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Gly924Ser,1,varchamp_pign,...,0.00,0.0,0.0,-2.0,30.0,3.0,-22.0,False,False,False

In [4]:
allele_col = pl.read_parquet(f"{outputs_dir}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI.parquet").to_pandas()
allele_col

,symbol,aa_change,gene_variant,spdi,nt_change,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,...,plddt_f32,rsa_f32,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names
0,GBA1,Val54Leu,GBA1_Val54Leu,NC_000001.11:155240033:C:G,160G>C,1,155240033,C,G,1,...,NaN,NaN,NaN,NaN,None,None,None,None,0,None
1,GBA1,Leu224Phe,GBA1_Leu224Phe,NC_000001.11:155238225:G:A,670C>T,1,155238225,G,A,1,...,NaN,NaN,NaN,NaN,None,None,None,None,0,None
2,GBA1,Arg296Gln,GBA1_Arg296Gln,NC_000001.11:155237453:C:T,887G>A,1,155237453,C,T,1,...,98.910004,22.580645,>90,10-90,608013;230800;230900;231000;230800;231005;168600,multiple,OMIM,None,0,"GAUCHER DISEASE, PERINATAL LETHAL; GAUCHER DIS..."
3,GBA1,Leu483Pro,GBA1_Leu483Pro,NC_000001.11:155235252:A:G,1448T>C,1,155235252,A,G,1,...,98.389999,9.756097,>90,<10,230900;230800;231000;168600;608013;230900;2310...,multiple,OMIM,None,0,"GAUCHER DISEASE, TYPE II; GAUCHER DISEASE, TYP..."
4,NHERF1,Leu110Val,NHERF1_Leu110Val,NC_000017.11:74749174:C:G,328C>G,17,74749174,C,G,17,...,52.570000,47.560974,50-70,10-90,612287,autosomal dominant,OMIM,None,0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9618,BRIP1,Thr266Lys,BRIP1_Thr266Lys,NC_000017.11:61808588:G:T,797C>A,17,61808588,G,T,17,...,93.019997,1.408451,>90,<10,167000,somatic mutation,OMIM,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER
9619,BRIP1,Ser520Thr,BRIP1_Ser520Thr,NC_000017.11:61784339:C:G,1559G>C,17,61784339,C,G,17,...,86.389999,25.384617,70-90,10-90,None,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,None
9620,BRIP1,Leu537His,BRIP1_Leu537His,NC_000017.11:61784288:A:T,1610T>A,17,61784288,A,T,17,...,94.150002,0.000000,>90,<10,167000,None,None,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER
9621,BRIP1,His587Arg,BRIP1_His587Arg,NC_000017.11:61780874:T:C,1760A>G,17,61780874,T,C,17,...,90.540001,17.934782,>90,10-90,114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,BREAST CANCER
9622,BRIP1,Arg848His,BRIP1_Arg848His,NC_000017.11:61693462:C:T,2543G>A,17,61693462,C,T,17,...,92.540001,13.709678,>90,10-90,609054;114480;609054;609054;114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,"FANCONI ANEMIA, COMPLEMENTATION GROUP J; BREAS..."

In [5]:
# Create a mapping DataFrame with just the columns we need
splice_mapping = splice_df[['orf_id', 'nt_change', 'any_DS_above_0.2']].rename(
    columns={'any_DS_above_0.2': 'splicing_variant'}
)

# Merge onto allele_col
allele_col = allele_col.merge(
    splice_mapping,
    on=['orf_id', 'nt_change'],
    how='left'
)

# Fill NaN values with False (variants not found in splice_df)
allele_col['splicing_variant'] = allele_col['splicing_variant'].fillna(False)

print(f"Total variants in allele_col: {len(allele_col)}")
print(f"Splicing variants (any_DS > 0.2): {allele_col['splicing_variant'].sum()}")

allele_col.drop(columns=["seq", "seq_aa"]).to_csv(f"{outputs_dir}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI_SpliceAI.tsv", sep="\t", index=False)
allele_col

Total variants in allele_col: 9712
Splicing variants (any_DS > 0.2): 392

,symbol,aa_change,gene_variant,spdi,nt_change,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,...,rsa_f32,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant
0,GBA1,Val54Leu,GBA1_Val54Leu,NC_000001.11:155240033:C:G,160G>C,1,155240033,C,G,1,...,NaN,NaN,NaN,None,None,None,None,0,None,False
1,GBA1,Leu224Phe,GBA1_Leu224Phe,NC_000001.11:155238225:G:A,670C>T,1,155238225,G,A,1,...,NaN,NaN,NaN,None,None,None,None,0,None,False
2,GBA1,Arg296Gln,GBA1_Arg296Gln,NC_000001.11:155237453:C:T,887G>A,1,155237453,C,T,1,...,22.580645,>90,10-90,608013;230800;230900;231000;230800;231005;168600,multiple,OMIM,None,0,"GAUCHER DISEASE, PERINATAL LETHAL; GAUCHER DIS...",False
3,GBA1,Leu483Pro,GBA1_Leu483Pro,NC_000001.11:155235252:A:G,1448T>C,1,155235252,A,G,1,...,9.756097,>90,<10,230900;230800;231000;168600;608013;230900;2310...,multiple,OMIM,None,0,"GAUCHER DISEASE, TYPE II; GAUCHER DISEASE, TYP...",False
4,NHERF1,Leu110Val,NHERF1_Leu110Val,NC_000017.11:74749174:C:G,328C>G,17,74749174,C,G,17,...,47.560974,50-70,10-90,612287,autosomal dominant,OMIM,None,0,"NEPHROLITHIASIS/OSTEOPOROSIS, HYPOPHOSPHATEMIC, 2",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9707,BRIP1,Thr266Lys,BRIP1_Thr266Lys,NC_000017.11:61808588:G:T,797C>A,17,61808588,G,T,17,...,1.408451,>90,<10,167000,somatic mutation,OMIM,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER,False
9708,BRIP1,Ser520Thr,BRIP1_Ser520Thr,NC_000017.11:61784339:C:G,1559G>C,17,61784339,C,G,17,...,25.384617,70-90,10-90,None,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,None,False
9709,BRIP1,Leu537His,BRIP1_Leu537His,NC_000017.11:61784288:A:T,1610T>A,17,61784288,A,T,17,...,0.000000,>90,<10,167000,None,None,Rare genetic renal disease; Rare genetic devel...,7,OVARIAN CANCER,False
9710,BRIP1,His587Arg,BRIP1_His587Arg,NC_000017.11:61780874:T:C,1760A>G,17,61780874,T,C,17,...,17.934782,>90,10-90,114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,BREAST CANCER,False
9711,BRIP1,Arg848His,BRIP1_Arg848His,NC_000017.11:61693462:C:T,2543G>A,17,61693462,C,T,17,...,13.709678,>90,10-90,609054;114480;609054;609054;114480,autosomal dominant,OMIM,Rare genetic renal disease; Rare genetic devel...,7,"FANCONI ANEMIA, COMPLEMENTATION GROUP J; BREAS...",True