In [7]:
import pandas as pd

In [8]:
inputs_dir = "../1_inputs"
outputs_dir = "../3_outputs"

In [9]:
splice_df = pd.read_csv(f"{inputs_dir}/ccsb_mutations_with_spliceai_scores.tsv", sep="\t")
splice_df

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_15642/1560664950.py:1: DtypeWarning: Columns (27,29,31,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  splice_df = pd.read_csv(f"{inputs_dir}/ccsb_mutations_with_spliceai_scores.tsv", sep="\t")

,mutation_id,orf_id,nt_change,aa_change,cloned,ensembl_protein_id,orf_class,aa_change_hgvs,nt_change_cnt,cloned_project,...,DS_AL,DS_DG,DS_DL,DP_AG,DP_AL,DP_DG,DP_DL,any_DS_above_0.2,any_DS_above_0.5,any_DS_above_0.8
0,CCSBVarC000001,2,160G>C,Val54Leu,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Val54Leu,1,pre_varchamp,...,0.00,0.0,0.0,44.0,7.0,-24.0,1.0,False,False,False
1,CCSBVarC000002,2,670C>T,Leu224Phe,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Leu224Phe,1,pre_varchamp,...,0.00,0.0,0.0,-6.0,22.0,2.0,-17.0,False,False,False
2,CCSBVarC000003,2,887G>A,Arg296Gln,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Arg296Gln,1,pre_varchamp,...,0.00,0.0,0.0,-24.0,28.0,3.0,-23.0,False,False,False
3,CCSBVarC000004,2,1448T>C,Leu483Pro,1,ENSP00000357357.3,class1m,ENSP00000357357.3:p.Leu483Pro,1,pre_varchamp,...,0.00,0.0,0.0,43.0,34.0,-43.0,-48.0,False,False,False
4,CCSBVarC000005,25,328C>G,Leu110Val,1,ENSP00000262613.5,class1m,ENSP00000262613.5:p.Leu110Val,1,pre_varchamp,...,0.00,0.0,0.0,-12.0,30.0,-1.0,13.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38601,CCSBVarC039842,1460,2671A>G,Ser891Gly,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Ser891Gly,1,varchamp_pign,...,0.01,0.0,0.8,-6.0,30.0,-39.0,-1.0,True,True,False
38602,CCSBVarC039843,1460,2699C>G,Ser900Cys,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Ser900Cys,1,varchamp_pign,...,0.01,0.0,0.0,20.0,26.0,3.0,0.0,False,False,False
38603,CCSBVarC039844,1460,2701A>G,Met901Val,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Met901Val,1,varchamp_pign,...,0.00,0.0,0.0,28.0,-39.0,5.0,28.0,False,False,False
38604,CCSBVarC039845,1460,2750C>T,Thr917Met,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Thr917Met,1,varchamp_pign,...,0.00,0.0,0.0,10.0,-13.0,-42.0,-17.0,False,False,False
38605,CCSBVarC039846,1460,2770G>A,Gly924Ser,1,ENSP00000492233.1,class3m,ENSP00000492233.1:p.Gly924Ser,1,varchamp_pign,...,0.00,0.0,0.0,-2.0,30.0,3.0,-22.0,False,False,False

In [10]:
allele_col = pd.read_csv(f"{outputs_dir}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI.tsv", sep="\t")
allele_col

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_15642/2910183168.py:1: DtypeWarning: Columns (1,5,19,20,102,104,134,137,140,155,156,157,159,160,162,164,188,189,191,192,194,195,198,209,212,216,217,218,219,229,230,240,241,242,247,248,253,254,257,258,479,481,483,485,487,489,499,501,503,505,507,509,515,517,521,523,527,529,531,535,543,553,555,557,563,565,567,569,571,579,581,583,585,593,595,647,649,651,653,655,657,659,663,667,699,701,703,713,715,717,725,727,729,731,733,735,737,755,823,845,851,875,877,879,881,883,889,893,905,907,909,911,913,915,917,919,921,933,934,940,942,943,944,947,948,950,951,955,963,964,965,973,974,975,979,985,993,995,997) have mixed types. Specify dtype option on import or set low_memory=False.
  allele_col = pd.read_csv(f"{outputs_dir}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI.tsv", sep="\t")

,symbol,ensembl_gene_id,orf_id,mut_id,ccsb_mutation_id,ccsb_allele_id,spdi,nt_change,aa_change,seq,...,plddt_f32,rsa_f32,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names
0,GBA1,ENSG00000177628,2,6,CCSBVarC000001,ALE0000584,NC_000001.11:155240033:C:G,160G>C,Val54Leu,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
1,GBA1,ENSG00000177628,2,73,CCSBVarC000002,ALE00000002,NC_000001.11:155238225:G:A,670C>T,Leu224Phe,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
2,GBA1,ENSG00000177628,2,113,CCSBVarC000003,ALE00000003,NC_000001.11:155237453:C:T,887G>A,Arg296Gln,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,98.91,22.580645,>90,10-90,608013;230800;230900;231000;230800;231005;168600,multiple,OMIM,NaN,0,"GAUCHER DISEASE, PERINATAL LETHAL; GAUCHER DIS..."
3,GBA1,ENSG00000177628,2,231,CCSBVarC000004,ALE00000004,NC_000001.11:155235252:A:G,1448T>C,Leu483Pro,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,98.39,9.756097,>90,<10,230900;230800;231000;168600;608013;230900;2310...,multiple,OMIM,NaN,0,"GAUCHER DISEASE, TYPE II; GAUCHER DISEASE, TYP..."
4,GBA1,ENSG00000177628,2,213510,CCSBVarC003869,ALE00003869,NC_000001.11:155239934:G:A,259C>T,Arg87Trp,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,98.35,5.241935,>90,<10,230800;127750;168600,multiple,OMIM,NaN,0,"GAUCHER DISEASE, TYPE I; DEMENTIA, LEWY BODY; ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9594,ZC4H2,NaN,4320,0,CCSBVarC009188,NaN,NC_000023.11:64921845:A:T,197T>A,Leu66His,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,93.30,50.000000,>90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME
9595,ZC4H2,NaN,4320,0,CCSBVarC009191,NaN,NC_000023.11:64917865:C:T,593G>A,Arg198Gln,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,88.17,44.354840,70-90,10-90,314580;301041,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME; WIEACKER-WOLFF SYNDRO...
9596,ZC4H2,NaN,4320,0,CCSBVarC009194,NaN,NC_000023.11:64976325:C:T,53G>A,Arg18Lys,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,97.95,70.564514,>90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME
9597,ZC4H2,NaN,4320,0,CCSBVarC009197,NaN,NC_000023.11:64917821:G:A,637C>T,Arg213Trp,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,70.32,83.870964,70-90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME
9598,ZC4H2,NaN,4320,0,CCSBVarC009207,NaN,NC_000023.11:64917827:G:A,631C>T,Arg211Trp,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,78.85,80.645164,70-90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME

In [11]:
# Create a mapping DataFrame with just the columns we need
splice_mapping = splice_df[['orf_id', 'nt_change', 'any_DS_above_0.2']].rename(
    columns={'any_DS_above_0.2': 'splicing_variant'}
)

# Merge onto allele_col
allele_col = allele_col.merge(
    splice_mapping,
    on=['orf_id', 'nt_change'],
    how='left'
)

# Fill NaN values with False (variants not found in splice_df)
allele_col['splicing_variant'] = allele_col['splicing_variant'].fillna(False)

print(f"Total variants in allele_col: {len(allele_col)}")
print(f"Splicing variants (any_DS > 0.2): {allele_col['splicing_variant'].sum()}")

allele_col.to_csv(f"{outputs_dir}/VarChAMP_Allele_Collection_1Perc_ClinVar_dbNSFP_pLDDT_RSA_G2P_OMIM_MOI_SpliceAI.tsv", sep="\t", index=False)
allele_col

/var/folders/ng/d7mydbq105b1ndpt60np34jh0000gn/T/ipykernel_15642/551275527.py:14: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  allele_col['splicing_variant'] = allele_col['splicing_variant'].fillna(False)

Total variants in allele_col: 9688
Splicing variants (any_DS > 0.2): 392

,symbol,ensembl_gene_id,orf_id,mut_id,ccsb_mutation_id,ccsb_allele_id,spdi,nt_change,aa_change,seq,...,rsa_f32,pLDDT_Category,RSA_Category,OMIM_IDs,inheritance_pattern,inheritance_source,disease_modules,disease_module_count,OMIM_disease_names,splicing_variant
0,GBA1,ENSG00000177628,2,6,CCSBVarC000001,ALE0000584,NC_000001.11:155240033:C:G,160G>C,Val54Leu,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False
1,GBA1,ENSG00000177628,2,73,CCSBVarC000002,ALE00000002,NC_000001.11:155238225:G:A,670C>T,Leu224Phe,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,False
2,GBA1,ENSG00000177628,2,113,CCSBVarC000003,ALE00000003,NC_000001.11:155237453:C:T,887G>A,Arg296Gln,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,22.580645,>90,10-90,608013;230800;230900;231000;230800;231005;168600,multiple,OMIM,NaN,0,"GAUCHER DISEASE, PERINATAL LETHAL; GAUCHER DIS...",False
3,GBA1,ENSG00000177628,2,231,CCSBVarC000004,ALE00000004,NC_000001.11:155235252:A:G,1448T>C,Leu483Pro,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,9.756097,>90,<10,230900;230800;231000;168600;608013;230900;2310...,multiple,OMIM,NaN,0,"GAUCHER DISEASE, TYPE II; GAUCHER DISEASE, TYP...",False
4,GBA1,ENSG00000177628,2,213510,CCSBVarC003869,ALE00003869,NC_000001.11:155239934:G:A,259C>T,Arg87Trp,ATGGAGTTTTCAAGTCCTTCCAGAGAGGAATGTCCCAAGCCTTTGA...,...,5.241935,>90,<10,230800;127750;168600,multiple,OMIM,NaN,0,"GAUCHER DISEASE, TYPE I; DEMENTIA, LEWY BODY; ...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9683,ZC4H2,NaN,4320,0,CCSBVarC009188,NaN,NC_000023.11:64921845:A:T,197T>A,Leu66His,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,50.000000,>90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME,False
9684,ZC4H2,NaN,4320,0,CCSBVarC009191,NaN,NC_000023.11:64917865:C:T,593G>A,Arg198Gln,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,44.354840,70-90,10-90,314580;301041,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME; WIEACKER-WOLFF SYNDRO...,False
9685,ZC4H2,NaN,4320,0,CCSBVarC009194,NaN,NC_000023.11:64976325:C:T,53G>A,Arg18Lys,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,70.564514,>90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME,False
9686,ZC4H2,NaN,4320,0,CCSBVarC009197,NaN,NC_000023.11:64917821:G:A,637C>T,Arg213Trp,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,83.870964,70-90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME,False
9687,ZC4H2,NaN,4320,0,CCSBVarC009207,NaN,NC_000023.11:64917827:G:A,631C>T,Arg211Trp,ATGGCAGATGAGCAAGAAATCATGTGCAAATTGGAAAGCATTAAAG...,...,80.645164,70-90,10-90,314580,x-linked recessive,OMIM,Rare genetic developmental defect during embry...,2,WIEACKER-WOLFF SYNDROME,False