In [1]:
import pandas as pd

In [4]:
seq_file = '../../1_allele_collection/3_outputs/VarChampSeqConfirmationResult_final_call.tsv'

seq_df = pd.read_csv(seq_file, sep='\t')

seq_df = seq_df[seq_df.symbol == 'MVK']

seq_df

,symbol,ensembl_gene_id,orf_id,mut_id,ccsb_mutation_id,ccsb_allele_id,spdi,nt_change,aa_change,collection,...,chr_num,nuc_loc,ref_allele,alt_allele,Chrom,entry_seq_final,db_seq_final,n2h_seq_final,dualip_seq_final,mislocalization_seq_final
78,MVK,ENSG00000110921,281,1,CCSBVarC007113,ALE00007111,NC_000012.12:109574836:T:C,14T>C,Val5Ala,Edgotyping3,...,12,109574836,T,C,12,Y,N,Y,Y,Y
79,MVK,ENSG00000110921,281,3,CCSBVarC007114,ALE00007112,NC_000012.12:109574881:A:C,59A>C,His20Pro,Edgotyping3,...,12,109574881,A,C,12,Y,Y,Y,Y,Y
80,MVK,ENSG00000110921,281,4,CCSBVarC007115,ALE00007113,NC_000012.12:109576041:T:C,122T>C,Leu41Pro,Edgotyping3,...,12,109576041,T,C,12,Y,N,Y,Y,Y
81,MVK,ENSG00000110921,281,5,CCSBVarC007116,ALE00007114,NC_000012.12:109576074:G:A,155G>A,Ser52Asn,Edgotyping3,...,12,109576074,G,A,12,Y,Y,Y,Y,N
82,MVK,ENSG00000110921,281,6,CCSBVarC007117,ALE00007115,NC_000012.12:109579813:G:A,238G>A,Val80Ile,Edgotyping3,...,12,109579813,G,A,12,Y,N,N,Y,Y
83,MVK,ENSG00000110921,281,7,CCSBVarC007118,ALE00007116,NC_000012.12:109579877:G:A,302G>A,Cys101Tyr,Edgotyping3,...,12,109579877,G,A,12,Y,Y,Y,Y,Y
84,MVK,ENSG00000110921,281,8,CCSBVarC007119,ALE00007117,NC_000012.12:109579892:G:A,317G>A,Arg106His,Edgotyping3,...,12,109579892,G,A,12,Y,N,Y,Y,Y
85,MVK,ENSG00000110921,281,10,CCSBVarC007120,ALE00007118,NC_000012.12:109579921:T:C,346T>C,Tyr116His,Edgotyping3,...,12,109579921,T,C,12,N,N,Y,Y,N
86,MVK,ENSG00000110921,281,11,CCSBVarC004836,ALE00004836,NC_000012.12:109581465:G:A,442G>A,Ala148Thr,Edgotyping3,...,12,109581465,G,A,12,Y,Y,N,Y,N
87,MVK,ENSG00000110921,281,12,CCSBVarC007121,ALE00007119,NC_000012.12:109581517:C:T,494C>T,Pro165Leu,Edgotyping3,...,12,109581517,C,T,12,Y,N,Y,N,Y
88,MVK,ENSG00000110921,281,13,CCSBVarC000027,ALE00000027,NC_000012.12:109581523:C:T,500C>T,Pro167Leu,Edgotyping3,...,12,109581523,C,T,12,Y,Y,N,N,Y
89,MVK,ENSG00000110921,281,14,CCSBVarC007122,ALE00007120,NC_000012.12:109586092:C:T,598C>T,Pro200Ser,Edgotyping3,...,12,109586092,C,T,12,Y,N,Y,Y,Y
90,MVK,ENSG00000110921,281,16,CCSBVarC007123,ALE00007121,NC_000012.12:109586102:T:C,608T>C,Val203Ala,Edgotyping3,...,12,109586102,T,C,12,Y,N,N,Y,N
91,MVK,ENSG00000110921,281,17,CCSBVarC007124,ALE00007122,NC_000012.12:109590802:A:T,709A>T,Thr237Ser,Edgotyping3,...,12,109590802,A,T,12,Y,Y,N,N,N
92,MVK,ENSG00000110921,281,18,CCSBVarC007125,ALE00007123,NC_000012.12:109590857:T:C,764T>C,Leu255Pro,Edgotyping3,...,12,109590857,T,C,12,Y,Y,Y,Y,Y
93,MVK,ENSG00000110921,281,19,CCSBVarC007126,ALE00007124,NC_000012.12:109591274:A:G,802A>G,Ile268Val,Edgotyping3,...,12,109591274,A,G,12,Y,Y,Y,Y,Y
94,MVK,ENSG00000110921,281,20,CCSBVarC007127,ALE00007125,NC_000012.12:109591275:T:C,803T>C,Ile268Thr,Edgotyping3,...,12,109591275,T,C,12,Y,N,Y,Y,N
95,MVK,ENSG00000110921,281,21,CCSBVarC007128,ALE00007126,NC_000012.12:109591304:G:A,832G>A,Val278Met,Edgotyping3,...,12,109591304,G,A,12,Y,Y,Y,Y,Y
96,MVK,ENSG00000110921,281,22,CCSBVarC007129,ALE00007127,NC_000012.12:109591329:C:T,857C>T,Pro286Leu,Edgotyping3,...,12,109591329,C,T,12,N,N,N,N,N
97,MVK,ENSG00000110921,281,23,CCSBVarC000029,ALE00000029,NC_000012.12:109595044:A:C,902A>C,Asn301Thr,Edgotyping3,...,12,109595044,A,C,12,Y,Y,Y,Y,N
98,MVK,ENSG00000110921,281,24,CCSBVarC007130,ALE00007128,NC_000012.12:109595070:G:A,928G>A,Val310Met,Edgotyping3,...,12,109595070,G,A,12,Y,N,N,N,N
99,MVK,ENSG00000110921,281,26,CCSBVarC007131,ALE00007129,NC_000012.12:109596480:T:C,1094T>C,Phe365Ser,Edgotyping3,...,12,109596480,T,C,12,Y,Y,N,Y,N
100,MVK,ENSG00000110921,281,27,CCSBVarC007132,ALE00007130,NC_000012.12:109596515:G:A,1129G>A,Val377Ile,Edgotyping3,...,12,109596515,G,A,12,N,N,N,N,N
101,MVK,ENSG00000110921,281,28,CCSBVarC007133,ALE00007131,NC_000012.12:109596542:G:A,1156G>A,Asp386Asn,Edgotyping3,...,12,109596542,G,A,12,Y,N,Y,N,Y
102,MVK,ENSG00000110921,281,29,CCSBVarC007134,ALE00007132,NC_000012.12:109596549:G:A,1163G>A,Arg388Gln,Edgotyping3,...,12,109596549,G,A,12,Y,N,Y,N,Y
103,MVK,ENSG00000110921,281,727,CCSBVarC000026,ALE00000026,NC_000012.12:109574882:T:A,60T>A,His20Gln,RC4,...,12,109574882,T,A,12,Y,Y,Y,N,Y
104,MVK,ENSG00000110921,281,739,CCSBVarC000027,ALE00000027,NC_000012.12:109581523:C:T,500C>T,Pro167Leu,RC4,...,12,109581523,C,T,12,Y,Y,N,Y,N
105,MVK,ENSG00000110921,281,744,CCSBVarC000028,ALE00000028,NC_000012.12:109586107:A:G,613A>G,Asn205Asp,RC4,...,12,109586107,A,G,12,Y,Y,Y,Y,Y
106,MVK,ENSG00000110921,281,763,CCSBVarC000029,ALE00000029,NC_000012.12:109595044:A:C,902A>C,Asn301Thr,RC4,...,12,109595044,A,C,12,Y,Y,N,Y,N
107,MVK,ENSG00000110921,281,200087,CCSBVarC004834,ALE00004834,NC_000012.12:109579932:C:G,357C>G,Ile119Met,CEGS2,...,12,109579932,C,G,12,Y,Y,Y,Y,Y
108,MVK,ENSG00000110921,281,200088,CCSBVarC004835,ALE00004835,NC_000012.12:109581427:C:T,404C>T,Ser135Leu,CEGS2,...,12,109581427,C,T,12,Y,Y,N,Y,N
109,MVK,ENSG00000110921,281,200089,CCSBVarC004836,ALE00004836,NC_000012.12:109581465:G:A,442G>A,Ala148Thr,CEGS2,...,12,109581465,G,A,12,Y,Y,N,Y,N
110,MVK,ENSG00000110921,281,200091,CCSBVarC004837,ALE00004837,NC_000012.12:109586119:A:G,625A>G,Thr209Ala,CEGS2,...,12,109586119,A,G,12,Y,Y,Y,Y,Y
111,MVK,ENSG00000110921,281,200092,CCSBVarC004838,ALE00004838,NC_000012.12:109586754:G:C,632G>C,Gly211Ala,CEGS2,...,12,109586754,G,C,12,Y,Y,Y,Y,N
112,MVK,ENSG00000110921,281,200093,CCSBVarC004841,ALE00004841,NC_000012.12:109590841:G:A,748G>A,Val250Ile,CEGS2,...,12,109590841,G,A,12,Y,Y,N,Y,Y
113,MVK,ENSG00000110921,281,200094,CCSBVarC004839,ALE00004839,NC_000012.12:109590794:T:C,701T>C,Leu234Pro,CEGS2,...,12,109590794,T,C,12,N,N,N,N,N
114,MVK,ENSG00000110921,281,200095,CCSBVarC004840,ALE00004840,NC_000012.12:109590821:C:T,728C>T,Thr243Ile,CEGS2,...,12,109590821,C,T,12,Y,Y,Y,Y,Y
115,MVK,ENSG00000110921,281,200096,CCSBVarC004843,ALE00004843,NC_000012.12:109591301:C:T,829C>T,Arg277Cys,CEGS2,...,12,109591301,C,T,12,Y,Y,N,Y,N
116,MVK,ENSG00000110921,281,200097,CCSBVarC004844,ALE00004844,NC_000012.12:109591335:C:T,863C>T,Pro288Leu,CEGS2,...,12,109591335,C,T,12,Y,Y,Y,Y,Y
117,MVK,ENSG00000110921,281,200098,CCSBVarC004845,ALE00004845,NC_000012.12:109591349:G:A,877G>A,Val293Met,CEGS2,...,12,109591349,G,A,12,Y,Y,Y,Y,N
118,MVK,ENSG00000110921,281,200099,CCSBVarC004842,ALE00004842,NC_000012.12:109591266:T:C,794T>C,Leu265Pro,CEGS2,...,12,109591266,T,C,12,Y,Y,N,Y,Y
119,MVK,ENSG00000110921,281,200100,CCSBVarC004847,ALE00004847,NC_000012.12:109595128:G:A,986G>A,Ser329Asn,CEGS2,...,12,109595128,G,A,12,Y,Y,Y,Y,Y
120,MVK,ENSG00000110921,281,200101,CCSBVarC004846,ALE00004846,NC_000012.12:109595107:C:G,965C>G,Thr322Ser,CEGS2,...,12,109595107,C,G,12,Y,Y,N,Y,N
121,MVK,ENSG00000110921,281,200102,CCSBVarC004848,ALE00004848,NC_000012.12:109595148:G:A,1006G>A,Gly336Ser,CEGS2,...,12,109595148,G,A,12,Y,N,N,N,N
122,MVK,ENSG00000110921,281,200103,CCSBVarC004850,ALE00004850,NC_000012.12:109596518:T:C,1132T>C,Ser378Pro,CEGS2,...,12,109596518,T,C,12,N,Y,N,Y,N
123,MVK,ENSG00000110921,281,200104,CCSBVarC004849,ALE00004849,NC_000012.12:109596486:G:C,1100G>C,Cys367Ser,CEGS2,...,12,109596486,G,C,12,Y,Y,N,Y,N

In [11]:
seq_cols = [col for col in seq_df.columns if 'seq' in col.lower()]

seq_df[seq_df.columns[:9].tolist() + seq_cols]

,symbol,ensembl_gene_id,orf_id,mut_id,ccsb_mutation_id,ccsb_allele_id,spdi,nt_change,aa_change,entry_seq_pool,...,dualip_sequence_confirmation_class,dualip_ref_sequence_confirmation_class,mislocalization_sequenced,mislocalization_sequence_confirmation_class,mislocalization_ref_sequence_confirmation_class,entry_seq_final,db_seq_final,n2h_seq_final,dualip_seq_final,mislocalization_seq_final
78,MVK,ENSG00000110921,281,1,CCSBVarC007113,ALE00007111,NC_000012.12:109574836:T:C,14T>C,Val5Ala,2.0,...,1.0,1.0,1,1.0,1.0,Y,N,Y,Y,Y
79,MVK,ENSG00000110921,281,3,CCSBVarC007114,ALE00007112,NC_000012.12:109574881:A:C,59A>C,His20Pro,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
80,MVK,ENSG00000110921,281,4,CCSBVarC007115,ALE00007113,NC_000012.12:109576041:T:C,122T>C,Leu41Pro,2.0,...,1.0,1.0,1,1.0,1.0,Y,N,Y,Y,Y
81,MVK,ENSG00000110921,281,5,CCSBVarC007116,ALE00007114,NC_000012.12:109576074:G:A,155G>A,Ser52Asn,2.0,...,1.0,1.0,1,3.0,1.0,Y,Y,Y,Y,N
82,MVK,ENSG00000110921,281,6,CCSBVarC007117,ALE00007115,NC_000012.12:109579813:G:A,238G>A,Val80Ile,2.0,...,1.0,1.0,1,1.0,1.0,Y,N,N,Y,Y
83,MVK,ENSG00000110921,281,7,CCSBVarC007118,ALE00007116,NC_000012.12:109579877:G:A,302G>A,Cys101Tyr,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
84,MVK,ENSG00000110921,281,8,CCSBVarC007119,ALE00007117,NC_000012.12:109579892:G:A,317G>A,Arg106His,2.0,...,1.0,1.0,1,1.0,1.0,Y,N,Y,Y,Y
85,MVK,ENSG00000110921,281,10,CCSBVarC007120,ALE00007118,NC_000012.12:109579921:T:C,346T>C,Tyr116His,2.0,...,1.0,1.0,1,3.0,1.0,N,N,Y,Y,N
86,MVK,ENSG00000110921,281,11,CCSBVarC004836,ALE00004836,NC_000012.12:109581465:G:A,442G>A,Ala148Thr,2.0,...,1.0,1.0,1,3.0,1.0,Y,Y,N,Y,N
87,MVK,ENSG00000110921,281,12,CCSBVarC007121,ALE00007119,NC_000012.12:109581517:C:T,494C>T,Pro165Leu,2.0,...,3.0,1.0,1,1.0,1.0,Y,N,Y,N,Y
88,MVK,ENSG00000110921,281,13,CCSBVarC000027,ALE00000027,NC_000012.12:109581523:C:T,500C>T,Pro167Leu,NaN,...,5.0,1.0,1,1.0,1.0,Y,Y,N,N,Y
89,MVK,ENSG00000110921,281,14,CCSBVarC007122,ALE00007120,NC_000012.12:109586092:C:T,598C>T,Pro200Ser,2.0,...,1.0,1.0,1,1.0,1.0,Y,N,Y,Y,Y
90,MVK,ENSG00000110921,281,16,CCSBVarC007123,ALE00007121,NC_000012.12:109586102:T:C,608T>C,Val203Ala,2.0,...,1.0,1.0,0,NaN,NaN,Y,N,N,Y,N
91,MVK,ENSG00000110921,281,17,CCSBVarC007124,ALE00007122,NC_000012.12:109590802:A:T,709A>T,Thr237Ser,2.0,...,5.0,1.0,0,NaN,NaN,Y,Y,N,N,N
92,MVK,ENSG00000110921,281,18,CCSBVarC007125,ALE00007123,NC_000012.12:109590857:T:C,764T>C,Leu255Pro,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
93,MVK,ENSG00000110921,281,19,CCSBVarC007126,ALE00007124,NC_000012.12:109591274:A:G,802A>G,Ile268Val,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
94,MVK,ENSG00000110921,281,20,CCSBVarC007127,ALE00007125,NC_000012.12:109591275:T:C,803T>C,Ile268Thr,2.0,...,1.0,1.0,1,3.0,1.0,Y,N,Y,Y,N
95,MVK,ENSG00000110921,281,21,CCSBVarC007128,ALE00007126,NC_000012.12:109591304:G:A,832G>A,Val278Met,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
96,MVK,ENSG00000110921,281,22,CCSBVarC007129,ALE00007127,NC_000012.12:109591329:C:T,857C>T,Pro286Leu,2.0,...,5.0,1.0,1,3.0,1.0,N,N,N,N,N
97,MVK,ENSG00000110921,281,23,CCSBVarC000029,ALE00000029,NC_000012.12:109595044:A:C,902A>C,Asn301Thr,NaN,...,1.0,1.0,1,3.0,1.0,Y,Y,Y,Y,N
98,MVK,ENSG00000110921,281,24,CCSBVarC007130,ALE00007128,NC_000012.12:109595070:G:A,928G>A,Val310Met,2.0,...,3.0,1.0,0,NaN,NaN,Y,N,N,N,N
99,MVK,ENSG00000110921,281,26,CCSBVarC007131,ALE00007129,NC_000012.12:109596480:T:C,1094T>C,Phe365Ser,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
100,MVK,ENSG00000110921,281,27,CCSBVarC007132,ALE00007130,NC_000012.12:109596515:G:A,1129G>A,Val377Ile,2.0,...,5.0,1.0,1,5.0,1.0,N,N,N,N,N
101,MVK,ENSG00000110921,281,28,CCSBVarC007133,ALE00007131,NC_000012.12:109596542:G:A,1156G>A,Asp386Asn,2.0,...,5.0,1.0,1,1.0,1.0,Y,N,Y,N,Y
102,MVK,ENSG00000110921,281,29,CCSBVarC007134,ALE00007132,NC_000012.12:109596549:G:A,1163G>A,Arg388Gln,2.0,...,5.0,1.0,1,1.0,1.0,Y,N,Y,N,Y
103,MVK,ENSG00000110921,281,727,CCSBVarC000026,ALE00000026,NC_000012.12:109574882:T:A,60T>A,His20Gln,2.0,...,5.0,1.0,1,1.0,1.0,Y,Y,Y,N,Y
104,MVK,ENSG00000110921,281,739,CCSBVarC000027,ALE00000027,NC_000012.12:109581523:C:T,500C>T,Pro167Leu,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
105,MVK,ENSG00000110921,281,744,CCSBVarC000028,ALE00000028,NC_000012.12:109586107:A:G,613A>G,Asn205Asp,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
106,MVK,ENSG00000110921,281,763,CCSBVarC000029,ALE00000029,NC_000012.12:109595044:A:C,902A>C,Asn301Thr,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
107,MVK,ENSG00000110921,281,200087,CCSBVarC004834,ALE00004834,NC_000012.12:109579932:C:G,357C>G,Ile119Met,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
108,MVK,ENSG00000110921,281,200088,CCSBVarC004835,ALE00004835,NC_000012.12:109581427:C:T,404C>T,Ser135Leu,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
109,MVK,ENSG00000110921,281,200089,CCSBVarC004836,ALE00004836,NC_000012.12:109581465:G:A,442G>A,Ala148Thr,NaN,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
110,MVK,ENSG00000110921,281,200091,CCSBVarC004837,ALE00004837,NC_000012.12:109586119:A:G,625A>G,Thr209Ala,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
111,MVK,ENSG00000110921,281,200092,CCSBVarC004838,ALE00004838,NC_000012.12:109586754:G:C,632G>C,Gly211Ala,2.0,...,1.0,1.0,1,3.0,1.0,Y,Y,Y,Y,N
112,MVK,ENSG00000110921,281,200093,CCSBVarC004841,ALE00004841,NC_000012.12:109590841:G:A,748G>A,Val250Ile,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,N,Y,Y
113,MVK,ENSG00000110921,281,200094,CCSBVarC004839,ALE00004839,NC_000012.12:109590794:T:C,701T>C,Leu234Pro,2.0,...,5.0,1.0,0,NaN,NaN,N,N,N,N,N
114,MVK,ENSG00000110921,281,200095,CCSBVarC004840,ALE00004840,NC_000012.12:109590821:C:T,728C>T,Thr243Ile,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
115,MVK,ENSG00000110921,281,200096,CCSBVarC004843,ALE00004843,NC_000012.12:109591301:C:T,829C>T,Arg277Cys,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
116,MVK,ENSG00000110921,281,200097,CCSBVarC004844,ALE00004844,NC_000012.12:109591335:C:T,863C>T,Pro288Leu,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
117,MVK,ENSG00000110921,281,200098,CCSBVarC004845,ALE00004845,NC_000012.12:109591349:G:A,877G>A,Val293Met,2.0,...,1.0,1.0,1,6.0,1.0,Y,Y,Y,Y,N
118,MVK,ENSG00000110921,281,200099,CCSBVarC004842,ALE00004842,NC_000012.12:109591266:T:C,794T>C,Leu265Pro,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,N,Y,Y
119,MVK,ENSG00000110921,281,200100,CCSBVarC004847,ALE00004847,NC_000012.12:109595128:G:A,986G>A,Ser329Asn,2.0,...,1.0,1.0,1,1.0,1.0,Y,Y,Y,Y,Y
120,MVK,ENSG00000110921,281,200101,CCSBVarC004846,ALE00004846,NC_000012.12:109595107:C:G,965C>G,Thr322Ser,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N
121,MVK,ENSG00000110921,281,200102,CCSBVarC004848,ALE00004848,NC_000012.12:109595148:G:A,1006G>A,Gly336Ser,2.0,...,5.0,1.0,0,NaN,NaN,Y,N,N,N,N
122,MVK,ENSG00000110921,281,200103,CCSBVarC004850,ALE00004850,NC_000012.12:109596518:T:C,1132T>C,Ser378Pro,2.0,...,1.0,1.0,0,NaN,NaN,N,Y,N,Y,N
123,MVK,ENSG00000110921,281,200104,CCSBVarC004849,ALE00004849,NC_000012.12:109596486:G:C,1100G>C,Cys367Ser,2.0,...,1.0,1.0,0,NaN,NaN,Y,Y,N,Y,N

In [ ]:
# code	description
# 1	perfectly validated
# 2	partially validated, >= 50% coverage
# 3	wild type
# 4	partial wild type, >= 50% coverage
# 5	target and off-target mutation, >= 50% coverage
# 6	off-target mutation, >= 50% coverage
# 7	truncated, < 50% coverage
# 99	no reads

# Sequencing QC Report

Generate summary statistics for why MVK variants were dropped during sequencing confirmation across different assay formats.

In [14]:
# Define assay columns to analyze
assay_cols = {
    'entry': ['entry_sequenced', 'entry_sequence_confirmation_class', 'entry_seq_final'],
    'db': ['db_sequenced', 'db_sequence_confirmation_class', 'db_seq_final'],
    'dualip': ['dualip_sequenced', 'dualip_sequence_confirmation_class', 'dualip_seq_final'],
    'mislocalization': ['mislocalization_sequenced', 'mislocalization_sequence_confirmation_class', 'mislocalization_seq_final']
}

# Generate report for each assay
reports = {}

for assay_name, cols in assay_cols.items():
    seq_col, class_col, final_col = cols
    
    # Check if columns exist in the dataframe
    if not all(col in seq_df.columns for col in cols):
        print(f"Skipping {assay_name}: columns not found")
        continue
    
    # Filter to variants only (mut_id > 0)
    assay_df = seq_df[seq_df.mut_id > 0].copy()
    
    # Overall stats
    total_variants = len(assay_df)
    sequenced = assay_df[seq_col].notna().sum()
    sequenced_pct = (sequenced / total_variants * 100) if total_variants > 0 else 0
    
    # Final call breakdown
    final_Y = (assay_df[final_col] == 'Y').sum()
    final_N = (assay_df[final_col] == 'N').sum()
    
    # Sequence confirmation class breakdown (for sequenced variants)
    seq_variants = assay_df[assay_df[seq_col].notna()]
    class_counts = seq_variants[class_col].value_counts().to_dict()
    
    # Reasons for final=False (N or M)
    failed = assay_df[assay_df[final_col].isin(['N', 'M'])]
    failed_class_counts = failed[class_col].value_counts().to_dict()
    
    reports[assay_name] = {
        'total_variants': total_variants,
        'sequenced': sequenced,
        'sequenced_pct': sequenced_pct,
        'final_Y': final_Y,
        'final_N': final_N,
        'pass_rate': (final_Y / sequenced * 100) if sequenced > 0 else 0,
        'all_class_counts': class_counts,
        'failed_class_counts': failed_class_counts
    }

# Print formatted reports
for assay_name, report in reports.items():
    print(f"\n{'='*60}")
    print(f"SEQUENCING QC REPORT: {assay_name.upper()}")
    print(f"{'='*60}")
    print(f"\nOverall Statistics:")
    print(f"  Total MVK variants: {report['total_variants']}")
    print(f"  Sequenced: {report['sequenced']} ({report['sequenced_pct']:.1f}%)")
    print(f"\nFinal Call Breakdown:")
    print(f"  Y (Pass): {report['final_Y']} ({report['pass_rate']:.1f}% of sequenced)")
    print(f"  N (Fail): {report['final_N']}")
    print(f"\nSequence Confirmation Classes (All Sequenced Variants):")
    for class_type, count in sorted(report['all_class_counts'].items()):
        print(f"  {class_type}: {count}")
    print(f"\nReasons for Failure (N or M only):")
    if report['failed_class_counts']:
        for class_type, count in sorted(report['failed_class_counts'].items()):
            print(f"  {class_type}: {count}")
    else:
        print("  All variants passed!")

print(f"\n{'='*60}\n")

============================================================
SEQUENCING QC REPORT: ENTRY
============================================================

Overall Statistics:
  Total MVK variants: 46
  Sequenced: 46 (100.0%)

Final Call Breakdown:
  Y (Pass): 41 (89.1% of sequenced)
  N (Fail): 5

Sequence Confirmation Classes (All Sequenced Variants):
  1.0: 37
  2.0: 1
  5.0: 2
  6.0: 3

Reasons for Failure (N or M only):
  5.0: 2
  6.0: 3

============================================================
SEQUENCING QC REPORT: DB
============================================================

Overall Statistics:
  Total MVK variants: 46
  Sequenced: 46 (100.0%)

Final Call Breakdown:
  Y (Pass): 30 (65.2% of sequenced)
  N (Fail): 16

Sequence Confirmation Classes (All Sequenced Variants):
  1.0: 28
  2.0: 2
  5.0: 14
  6.0: 1
  7.0: 1

Reasons for Failure (N or M only):
  5.0: 14
  6.0: 1
  7.0: 1

============================================================
SEQUENCING QC REPORT: DUALIP
============================================================

Overall Statistics:
  Total MVK variants: 46
  Sequenced: 46 (100.0%)

Final Call Breakdown:
  Y (Pass): 35 (76.1% of sequenced)
  N (Fail): 11

Sequence Confirmation Classes (All Sequenced Variants):
  1.0: 35
  3.0: 2
  5.0: 9

Reasons for Failure (N or M only):
  3.0: 2
  5.0: 9

============================================================
SEQUENCING QC REPORT: MISLOCALIZATION
============================================================

Overall Statistics:
  Total MVK variants: 46
  Sequenced: 46 (100.0%)

Final Call Breakdown:
  Y (Pass): 23 (50.0% of sequenced)
  N (Fail): 23

Sequence Confirmation Classes (All Sequenced Variants):
  1.0: 23
  3.0: 7
  5.0: 1
  6.0: 1

Reasons for Failure (N or M only):
  3.0: 7
  5.0: 1
  6.0: 1

============================================================

## Detailed Failure Analysis

List specific variants that failed sequencing QC for each assay.

In [15]:
# Show specific variants that failed for each assay
display_cols = ['aa_change', 'mut_id']

for assay_name, cols in assay_cols.items():
    seq_col, class_col, final_col = cols
    
    if not all(col in seq_df.columns for col in cols):
        continue
    
    print(f"\n{'='*60}")
    print(f"FAILED VARIANTS: {assay_name.upper()}")
    print(f"{'='*60}\n")
    
    # Get failed variants
    failed = seq_df[(seq_df.mut_id > 0) & (seq_df[final_col].isin(['N', 'M']))].copy()
    
    if len(failed) == 0:
        print("No variants failed!\n")
        continue
    
    # Display by failure reason
    for class_type in failed[class_col].unique():
        if pd.notna(class_type):
            variants_in_class = failed[failed[class_col] == class_type]
            print(f"{class_type} ({len(variants_in_class)} variants):")
            for _, row in variants_in_class.iterrows():
                print(f"  - {row['aa_change']} (mut_id: {row['mut_id']}, final: {row[final_col]})")
            print()

============================================================
FAILED VARIANTS: ENTRY
============================================================

6.0 (3 variants):
  - Tyr116His (mut_id: 10, final: N)
  - Leu234Pro (mut_id: 200094, final: N)
  - Ser378Pro (mut_id: 200103, final: N)

5.0 (2 variants):
  - Pro286Leu (mut_id: 22, final: N)
  - Val377Ile (mut_id: 27, final: N)


============================================================
FAILED VARIANTS: DB
============================================================

5.0 (14 variants):
  - Val5Ala (mut_id: 1, final: N)
  - Leu41Pro (mut_id: 4, final: N)
  - Val80Ile (mut_id: 6, final: N)
  - Arg106His (mut_id: 8, final: N)
  - Tyr116His (mut_id: 10, final: N)
  - Pro165Leu (mut_id: 12, final: N)
  - Pro200Ser (mut_id: 14, final: N)
  - Val203Ala (mut_id: 16, final: N)
  - Ile268Thr (mut_id: 20, final: N)
  - Pro286Leu (mut_id: 22, final: N)
  - Val310Met (mut_id: 24, final: N)
  - Val377Ile (mut_id: 27, final: N)
  - Asp386Asn (mut_id: 28, final: N)
  - Arg388Gln (mut_id: 29, final: N)

7.0 (1 variants):
  - Leu234Pro (mut_id: 200094, final: N)

6.0 (1 variants):
  - Gly336Ser (mut_id: 200102, final: N)


============================================================
FAILED VARIANTS: DUALIP
============================================================

3.0 (2 variants):
  - Pro165Leu (mut_id: 12, final: N)
  - Val310Met (mut_id: 24, final: N)

5.0 (9 variants):
  - Pro167Leu (mut_id: 13, final: N)
  - Thr237Ser (mut_id: 17, final: N)
  - Pro286Leu (mut_id: 22, final: N)
  - Val377Ile (mut_id: 27, final: N)
  - Asp386Asn (mut_id: 28, final: N)
  - Arg388Gln (mut_id: 29, final: N)
  - His20Gln (mut_id: 727, final: N)
  - Leu234Pro (mut_id: 200094, final: N)
  - Gly336Ser (mut_id: 200102, final: N)


============================================================
FAILED VARIANTS: MISLOCALIZATION
============================================================

3.0 (7 variants):
  - Ser52Asn (mut_id: 5, final: N)
  - Tyr116His (mut_id: 10, final: N)
  - Ala148Thr (mut_id: 11, final: N)
  - Ile268Thr (mut_id: 20, final: N)
  - Pro286Leu (mut_id: 22, final: N)
  - Asn301Thr (mut_id: 23, final: N)
  - Gly211Ala (mut_id: 200092, final: N)

5.0 (1 variants):
  - Val377Ile (mut_id: 27, final: N)

6.0 (1 variants):
  - Val293Met (mut_id: 200098, final: N)

## Global Sequencing QC Report

Variants must pass sequencing confirmation in **all 4 assays** (entry, db, dualipa, mislocalization) to be considered validated.

In [16]:
# Global sequencing validation requiring all 4 assays to pass
variants_df = seq_df[seq_df.mut_id > 0].copy()

# Check if all 4 seq_final columns are 'Y'
all_assays = ['entry_seq_final', 'db_seq_final', 'dualip_seq_final', 'mislocalization_seq_final']

# Create a pass/fail for each assay
for assay in all_assays:
    variants_df[f'{assay}_pass'] = variants_df[assay] == 'Y'

# Global validation requires ALL 4 to be 'Y'
variants_df['global_seq_validated'] = (
    (variants_df['entry_seq_final'] == 'Y') &
    (variants_df['db_seq_final'] == 'Y') &
    (variants_df['dualip_seq_final'] == 'Y') &
    (variants_df['mislocalization_seq_final'] == 'Y')
)

# Summary statistics
total_variants = len(variants_df)
globally_validated = variants_df['global_seq_validated'].sum()
validation_rate = (globally_validated / total_variants * 100) if total_variants > 0 else 0

print(f"\n{'='*60}")
print(f"GLOBAL SEQUENCING QC REPORT (ALL 4 ASSAYS MUST PASS)")
print(f"{'='*60}\n")
print(f"Total MVK variants: {total_variants}")
print(f"Globally validated (all 4 assays pass): {globally_validated} ({validation_rate:.1f}%)")
print(f"Failed at least one assay: {total_variants - globally_validated} ({100-validation_rate:.1f}%)\n")

# Breakdown by number of assays passed
pass_counts = variants_df[['entry_seq_final_pass', 'db_seq_final_pass', 
                            'dualip_seq_final_pass', 'mislocalization_seq_final_pass']].sum(axis=1)
print("Distribution by number of assays passed:")
for i in range(5):
    count = (pass_counts == i).sum()
    pct = (count / total_variants * 100) if total_variants > 0 else 0
    print(f"  {i}/4 assays passed: {count} ({pct:.1f}%)")

print(f"\n{'='*60}\n")

# Show which specific assays failed for variants that didn't pass all 4
failed_global = variants_df[~variants_df['global_seq_validated']].copy()

if len(failed_global) > 0:
    print(f"\nVariants failing at least one assay ({len(failed_global)} total):\n")
    
    for _, row in failed_global.iterrows():
        failed_assays = []
        for assay in ['entry', 'db', 'dualip', 'mislocalization']:
            if row[f'{assay}_seq_final'] != 'Y':
                failed_assays.append(f"{assay} ({row[f'{assay}_seq_final']})")
        
        print(f"  {row['aa_change']} (mut_id: {row['mut_id']}):")
        print(f"    Failed: {', '.join(failed_assays)}")
else:
    print("\nAll variants passed all 4 assays!")

============================================================
GLOBAL SEQUENCING QC REPORT (ALL 4 ASSAYS MUST PASS)
============================================================

Total MVK variants: 46
Globally validated (all 4 assays pass): 13 (28.3%)
Failed at least one assay: 33 (71.7%)

Distribution by number of assays passed:
  0/4 assays passed: 3 (6.5%)
  1/4 assays passed: 3 (6.5%)
  2/4 assays passed: 7 (15.2%)
  3/4 assays passed: 20 (43.5%)
  4/4 assays passed: 13 (28.3%)

============================================================


Variants failing at least one assay (33 total):

  Val5Ala (mut_id: 1):
    Failed: db (N)
  Leu41Pro (mut_id: 4):
    Failed: db (N)
  Ser52Asn (mut_id: 5):
    Failed: mislocalization (N)
  Val80Ile (mut_id: 6):
    Failed: db (N)
  Arg106His (mut_id: 8):
    Failed: db (N)
  Tyr116His (mut_id: 10):
    Failed: entry (N), db (N), mislocalization (N)
  Ala148Thr (mut_id: 11):
    Failed: mislocalization (N)
  Pro165Leu (mut_id: 12):
    Failed: db (N), dualip (N)
  Pro167Leu (mut_id: 13):
    Failed: dualip (N)
  Pro200Ser (mut_id: 14):
    Failed: db (N)
  Val203Ala (mut_id: 16):
    Failed: db (N), mislocalization (N)
  Thr237Ser (mut_id: 17):
    Failed: dualip (N), mislocalization (N)
  Ile268Thr (mut_id: 20):
    Failed: db (N), mislocalization (N)
  Pro286Leu (mut_id: 22):
    Failed: entry (N), db (N), dualip (N), mislocalization (N)
  Asn301Thr (mut_id: 23):
    Failed: mislocalization (N)
  Val310Met (mut_id: 24):
    Failed: db (N), dualip (N), mislocalization (N)
  Phe365Ser (mut_id: 26):
    Failed: mislocalization (N)
  Val377Ile (mut_id: 27):
    Failed: entry (N), db (N), dualip (N), mislocalization (N)
  Asp386Asn (mut_id: 28):
    Failed: db (N), dualip (N)
  Arg388Gln (mut_id: 29):
    Failed: db (N), dualip (N)
  His20Gln (mut_id: 727):
    Failed: dualip (N)
  Pro167Leu (mut_id: 739):
    Failed: mislocalization (N)
  Asn301Thr (mut_id: 763):
    Failed: mislocalization (N)
  Ser135Leu (mut_id: 200088):
    Failed: mislocalization (N)
  Ala148Thr (mut_id: 200089):
    Failed: mislocalization (N)
  Gly211Ala (mut_id: 200092):
    Failed: mislocalization (N)
  Leu234Pro (mut_id: 200094):
    Failed: entry (N), db (N), dualip (N), mislocalization (N)
  Arg277Cys (mut_id: 200096):
    Failed: mislocalization (N)
  Val293Met (mut_id: 200098):
    Failed: mislocalization (N)
  Thr322Ser (mut_id: 200101):
    Failed: mislocalization (N)
  Gly336Ser (mut_id: 200102):
    Failed: db (N), dualip (N), mislocalization (N)
  Ser378Pro (mut_id: 200103):
    Failed: entry (N), mislocalization (N)
  Cys367Ser (mut_id: 200104):
    Failed: mislocalization (N)

In [17]:
# Global sequencing validation requiring all 4 assays to pass
variants_df = seq_df[seq_df.mut_id > 0].copy()

# Check if all 4 seq_final columns are 'Y'
all_assays = ['entry_seq_final', 'db_seq_final', 'dualip_seq_final', 'mislocalization_seq_final']

# Global validation requires ALL 4 to be 'Y'
variants_df['global_seq_validated'] = (
    (variants_df['entry_seq_final'] == 'Y') &
    (variants_df['db_seq_final'] == 'Y') &
    (variants_df['dualip_seq_final'] == 'Y') &
    (variants_df['mislocalization_seq_final'] == 'Y')
)

# Create comprehensive table
table_data = []

for _, row in variants_df.iterrows():
    # Get failure information for each assay
    entry_status = row['entry_seq_final']
    entry_class = row['entry_sequence_confirmation_class'] if entry_status != 'Y' else '-'
    
    db_status = row['db_seq_final']
    db_class = row['db_sequence_confirmation_class'] if db_status != 'Y' else '-'
    
    dualip_status = row['dualip_seq_final']
    dualip_class = row['dualip_sequence_confirmation_class'] if dualip_status != 'Y' else '-'
    
    misloc_status = row['mislocalization_seq_final']
    misloc_class = row['mislocalization_sequence_confirmation_class'] if misloc_status != 'Y' else '-'
    
    table_data.append({
        'Variant': row['aa_change'],
        'mut_id': row['mut_id'],
        'Global Status': 'PASS' if row['global_seq_validated'] else 'FAIL',
        'Entry': entry_status,
        'Entry Class': entry_class,
        'DB': db_status,
        'DB Class': db_class,
        'DualIP': dualip_status,
        'DualIP Class': dualip_class,
        'Misloc': misloc_status,
        'Misloc Class': misloc_class
    })

# Create DataFrame
result_df = pd.DataFrame(table_data)

# Sort: PASS first, then FAIL
result_df = result_df.sort_values(by=['Global Status', 'Variant'], ascending=[False, True])

# Print summary
total_variants = len(result_df)
passed = (result_df['Global Status'] == 'PASS').sum()
failed = (result_df['Global Status'] == 'FAIL').sum()

print(f"\n{'='*100}")
print(f"COMPLETE MVK SEQUENCING QC TABLE")
print(f"{'='*100}\n")
print(f"Total variants: {total_variants}")
print(f"Passed all 4 assays: {passed} ({passed/total_variants*100:.1f}%)")
print(f"Failed at least one assay: {failed} ({failed/total_variants*100:.1f}%)\n")
print(f"{'='*100}\n")

# Display the table
print(result_df.to_string(index=False))

print(f"\n{'='*100}")
print("\nLEGEND:")
print("Status: Y = Pass, N = Fail, M = Manual review needed")
print("\nSequence Confirmation Classes:")
print("  1 = perfectly validated")
print("  2 = partially validated, >= 50% coverage")
print("  3 = wild type")
print("  4 = partial wild type, >= 50% coverage")
print("  5 = target and off-target mutation, >= 50% coverage")
print("  6 = off-target mutation, >= 50% coverage")
print("  7 = truncated, < 50% coverage")
print("  99 = no reads")
print(f"{'='*100}\n")

# Optionally save to file
# result_df.to_csv(output_folder / 'MVK_sequencing_QC_complete.tsv', sep='\t', index=False)
# print(f"Table saved to: {output_folder / 'MVK_sequencing_QC_complete.tsv'}")

====================================================================================================
COMPLETE MVK SEQUENCING QC TABLE
====================================================================================================

Total variants: 46
Passed all 4 assays: 13 (28.3%)
Failed at least one assay: 33 (71.7%)

====================================================================================================

  Variant  mut_id Global Status Entry Entry Class DB DB Class DualIP DualIP Class Misloc Misloc Class
Asn205Asp     744          PASS     Y           -  Y        -      Y            -      Y            -
Cys101Tyr       7          PASS     Y           -  Y        -      Y            -      Y            -
 His20Pro       3          PASS     Y           -  Y        -      Y            -      Y            -
Ile119Met  200087          PASS     Y           -  Y        -      Y            -      Y            -
Ile268Val      19          PASS     Y           -  Y        -      Y            -      Y            -
Leu255Pro      18          PASS     Y           -  Y        -      Y            -      Y            -
Leu265Pro  200099          PASS     Y           -  Y        -      Y            -      Y            -
Pro288Leu  200097          PASS     Y           -  Y        -      Y            -      Y            -
Ser329Asn  200100          PASS     Y           -  Y        -      Y            -      Y            -
Thr209Ala  200091          PASS     Y           -  Y        -      Y            -      Y            -
Thr243Ile  200095          PASS     Y           -  Y        -      Y            -      Y            -
Val250Ile  200093          PASS     Y           -  Y        -      Y            -      Y            -
Val278Met      21          PASS     Y           -  Y        -      Y            -      Y            -
Ala148Thr      11          FAIL     Y           -  Y        -      Y            -      N          3.0
Ala148Thr  200089          FAIL     Y           -  Y        -      Y            -      N          NaN
Arg106His       8          FAIL     Y           -  N      5.0      Y            -      Y            -
Arg277Cys  200096          FAIL     Y           -  Y        -      Y            -      N          NaN
Arg388Gln      29          FAIL     Y           -  N      5.0      N          5.0      Y            -
Asn301Thr      23          FAIL     Y           -  Y        -      Y            -      N          3.0
Asn301Thr     763          FAIL     Y           -  Y        -      Y            -      N          NaN
Asp386Asn      28          FAIL     Y           -  N      5.0      N          5.0      Y            -
Cys367Ser  200104          FAIL     Y           -  Y        -      Y            -      N          NaN
Gly211Ala  200092          FAIL     Y           -  Y        -      Y            -      N          3.0
Gly336Ser  200102          FAIL     Y           -  N      6.0      N          5.0      N          NaN
 His20Gln     727          FAIL     Y           -  Y        -      N          5.0      Y            -
Ile268Thr      20          FAIL     Y           -  N      5.0      Y            -      N          3.0
Leu234Pro  200094          FAIL     N         6.0  N      7.0      N          5.0      N          NaN
 Leu41Pro       4          FAIL     Y           -  N      5.0      Y            -      Y            -
Phe365Ser      26          FAIL     Y           -  Y        -      Y            -      N          NaN
Pro165Leu      12          FAIL     Y           -  N      5.0      N          3.0      Y            -
Pro167Leu      13          FAIL     Y           -  Y        -      N          5.0      Y            -
Pro167Leu     739          FAIL     Y           -  Y        -      Y            -      N          NaN
Pro200Ser      14          FAIL     Y           -  N      5.0      Y            -      Y            -
Pro286Leu      22          FAIL     N         5.0  N      5.0      N          5.0      N          3.0
Ser135Leu  200088          FAIL     Y           -  Y        -      Y            -      N          NaN
Ser378Pro  200103          FAIL     N         6.0  Y        -      Y            -      N          NaN
 Ser52Asn       5          FAIL     Y           -  Y        -      Y            -      N          3.0
Thr237Ser      17          FAIL     Y           -  Y        -      N          5.0      N          NaN
Thr322Ser  200101          FAIL     Y           -  Y        -      Y            -      N          NaN
Tyr116His      10          FAIL     N         6.0  N      5.0      Y            -      N          3.0
Val203Ala      16          FAIL     Y           -  N      5.0      Y            -      N          NaN
Val293Met  200098          FAIL     Y           -  Y        -      Y            -      N          6.0
Val310Met      24          FAIL     Y           -  N      5.0      N          3.0      N          NaN
Val377Ile      27          FAIL     N         5.0  N      5.0      N          5.0      N          5.0
  Val5Ala       1          FAIL     Y           -  N      5.0      Y            -      Y            -
 Val80Ile       6          FAIL     Y           -  N      5.0      Y            -      Y            -

====================================================================================================

LEGEND:
Status: Y = Pass, N = Fail, M = Manual review needed

Sequence Confirmation Classes:
  1 = perfectly validated
  2 = partially validated, >= 50% coverage
  3 = wild type
  4 = partial wild type, >= 50% coverage
  5 = target and off-target mutation, >= 50% coverage
  6 = off-target mutation, >= 50% coverage
  7 = truncated, < 50% coverage
  99 = no reads
====================================================================================================

In [20]:
result_df

,Variant,mut_id,Global Status,Entry,Entry Class,DB,DB Class,DualIP,DualIP Class,Misloc,Misloc Class
27,Asn205Asp,744,PASS,Y,-,Y,-,Y,-,Y,-
5,Cys101Tyr,7,PASS,Y,-,Y,-,Y,-,Y,-
1,His20Pro,3,PASS,Y,-,Y,-,Y,-,Y,-
29,Ile119Met,200087,PASS,Y,-,Y,-,Y,-,Y,-
15,Ile268Val,19,PASS,Y,-,Y,-,Y,-,Y,-
14,Leu255Pro,18,PASS,Y,-,Y,-,Y,-,Y,-
40,Leu265Pro,200099,PASS,Y,-,Y,-,Y,-,Y,-
38,Pro288Leu,200097,PASS,Y,-,Y,-,Y,-,Y,-
41,Ser329Asn,200100,PASS,Y,-,Y,-,Y,-,Y,-
32,Thr209Ala,200091,PASS,Y,-,Y,-,Y,-,Y,-
36,Thr243Ile,200095,PASS,Y,-,Y,-,Y,-,Y,-
34,Val250Ile,200093,PASS,Y,-,Y,-,Y,-,Y,-
17,Val278Met,21,PASS,Y,-,Y,-,Y,-,Y,-
8,Ala148Thr,11,FAIL,Y,-,Y,-,Y,-,N,3.0
31,Ala148Thr,200089,FAIL,Y,-,Y,-,Y,-,N,NaN
6,Arg106His,8,FAIL,Y,-,N,5.0,Y,-,Y,-
37,Arg277Cys,200096,FAIL,Y,-,Y,-,Y,-,N,NaN
24,Arg388Gln,29,FAIL,Y,-,N,5.0,N,5.0,Y,-
19,Asn301Thr,23,FAIL,Y,-,Y,-,Y,-,N,3.0
28,Asn301Thr,763,FAIL,Y,-,Y,-,Y,-,N,NaN
23,Asp386Asn,28,FAIL,Y,-,N,5.0,N,5.0,Y,-
45,Cys367Ser,200104,FAIL,Y,-,Y,-,Y,-,N,NaN
33,Gly211Ala,200092,FAIL,Y,-,Y,-,Y,-,N,3.0
43,Gly336Ser,200102,FAIL,Y,-,N,6.0,N,5.0,N,NaN
25,His20Gln,727,FAIL,Y,-,Y,-,N,5.0,Y,-
16,Ile268Thr,20,FAIL,Y,-,N,5.0,Y,-,N,3.0
35,Leu234Pro,200094,FAIL,N,6.0,N,7.0,N,5.0,N,NaN
2,Leu41Pro,4,FAIL,Y,-,N,5.0,Y,-,Y,-
21,Phe365Ser,26,FAIL,Y,-,Y,-,Y,-,N,NaN
9,Pro165Leu,12,FAIL,Y,-,N,5.0,N,3.0,Y,-
10,Pro167Leu,13,FAIL,Y,-,Y,-,N,5.0,Y,-
26,Pro167Leu,739,FAIL,Y,-,Y,-,Y,-,N,NaN
11,Pro200Ser,14,FAIL,Y,-,N,5.0,Y,-,Y,-
18,Pro286Leu,22,FAIL,N,5.0,N,5.0,N,5.0,N,3.0
30,Ser135Leu,200088,FAIL,Y,-,Y,-,Y,-,N,NaN
44,Ser378Pro,200103,FAIL,N,6.0,Y,-,Y,-,N,NaN
3,Ser52Asn,5,FAIL,Y,-,Y,-,Y,-,N,3.0
13,Thr237Ser,17,FAIL,Y,-,Y,-,N,5.0,N,NaN
42,Thr322Ser,200101,FAIL,Y,-,Y,-,Y,-,N,NaN
7,Tyr116His,10,FAIL,N,6.0,N,5.0,Y,-,N,3.0
12,Val203Ala,16,FAIL,Y,-,N,5.0,Y,-,N,NaN
39,Val293Met,200098,FAIL,Y,-,Y,-,Y,-,N,6.0
20,Val310Met,24,FAIL,Y,-,N,5.0,N,3.0,N,NaN
22,Val377Ile,27,FAIL,N,5.0,N,5.0,N,5.0,N,5.0
0,Val5Ala,1,FAIL,Y,-,N,5.0,Y,-,Y,-
4,Val80Ile,6,FAIL,Y,-,N,5.0,Y,-,Y,-

In [21]:
result_df.columns

Index(['Variant', 'mut_id', 'Global Status', 'Entry', 'Entry Class', 'DB',
       'DB Class', 'DualIP', 'DualIP Class', 'Misloc', 'Misloc Class'],
      dtype='object')

In [27]:
# Get value counts for each column
for col in ['Entry', 'Entry Class', 'DB', 'DB Class', 'DualIP', 'DualIP Class', 'Misloc', 'Misloc Class']:
    print(f"\n{col}:")
    print(result_df[col].value_counts(dropna=False, normalize=True))

Entry:
Entry
Y    0.891304
N    0.108696
Name: proportion, dtype: float64

Entry Class:
Entry Class
-      0.891304
6.0    0.065217
5.0    0.043478
Name: proportion, dtype: float64

DB:
DB
Y    0.652174
N    0.347826
Name: proportion, dtype: float64

DB Class:
DB Class
-      0.652174
5.0    0.304348
6.0    0.021739
7.0    0.021739
Name: proportion, dtype: float64

DualIP:
DualIP
Y    0.76087
N    0.23913
Name: proportion, dtype: float64

DualIP Class:
DualIP Class
-      0.760870
5.0    0.195652
3.0    0.043478
Name: proportion, dtype: float64

Misloc:
Misloc
Y    0.5
N    0.5
Name: proportion, dtype: float64

Misloc Class:
Misloc Class
-      0.500000
NaN    0.304348
3.0    0.152174
6.0    0.021739
5.0    0.021739
Name: proportion, dtype: float64